### ISSUE TITLE
[Helm] Heartbeat fails if custom CA is used by Auth but not by Operator

### ISSUE THREAD

**Issue by KeenanLawrence** [gravitational/teleport#20478] opened 2023-01-20 15:10 UTC
**Expected behavior:**
The pod reaches a healthy state when a custom CA is used

**Current behavior:**
Teleport pod enters a degraded state, with one of the two containers unhealthy

**Bug details:**
- Teleport version
11.2.2
- Recreation steps
Deploy the Helm chart with an existing CA secret
- Debug logs
```WARN [PROC:1]    Teleport process has exited with error. error:[
ERROR REPORT:
Original Error: *trace.ConnectionProblemError listener is closed
Stack Trace:
	github.com/gravitational/teleport/lib/srv/alpnproxy/listener.go:84 github.com/gravitational/teleport/lib/srv/alpnproxy.(*ListenerMuxWrapper).Accept
	google.golang.org/grpc@v1.50.1/server.go:823 google.golang.org/grpc.(*Server).Serve
	github.com/gravitational/teleport/lib/service/service.go:3937 github.com/gravitational/teleport/lib/service.(*TeleportProcess).initProxyEndpoint.func13
	github.com/gravitational/teleport/lib/service/supervisor.go:539 github.com/gravitational/teleport/lib/service.(*LocalService).Serve
	github.com/gravitational/teleport/lib/service/supervisor.go:276 github.com/gravitational/teleport/lib/service.(*LocalSupervisor).serve.func1
	runtime/asm_amd64.s:1594 runtime.goexit
User Message: listener is closed] pid:7.1 service:proxy.grpc service/supervisor.go:281
INFO [KUBERNETE] Exited. pid:7.1 service/kubernetes.go:297
INFO [AUTH:1]    Exited. pid:7.1 service/service.go:1812
WARN [AUTH:1]    TLS server exited with error: http: Server closed. pid:7.1 service/service.go:1698
INFO [PROXY:SER] Shutting down gracefully. pid:7.1 service/service.go:4018
```

**Comment by hugoShaka** [comment] 2023-01-24 22:45
Hello @KeenanLawrence 

I tried to reproduce and [found a v12 bug](https://github.com/gravitational/teleport/pull/20641) (helm failing to create the deployment) but have not faced the symptoms you mentioned.

AFAIK the operator should not need to trust the proxy certs nor the custom CA as it is creating two teleport clients:
- one over a unix socket
- one on the loopback interface on port 3025 (the certs served there are the Teleport CA ones, the custom CA you're passing is only used by the proxy service on port 3080/443) 

My reproduction steps are
```bash
set -euxo pipefail

NAMESPACE=teleport
TELEPORT_REPO_PATH=/home/shaka/work/teleport/examples/chart/teleport-cluster

# generate a CA
openssl genrsa -out ca.key.pem 2048
openssl req -new -x509 -key ca.key.pem -out ca.cert.pem -subj "/C=US/ST=Utah/L=Lehi/O=Your Company, Inc./OU=IT/CN=example.com"
# generate a keypair and sign it
openssl genrsa -out proxy.key.pem 2048
openssl req -new -key proxy.key.pem -out proxy.key.csr -subj "/C=US/ST=Utah/L=Lehi/O=Your Company, Inc./OU=IT/CN=teleport.example.com"
openssl x509 -req -in proxy.key.csr -CA ca.cert.pem -CAkey ca.key.pem -CAcreateserial -out proxy.cert.pem
# create fullchain
cat proxy.cert.pem ca.cert.pem > proxy.fullchain.pem

# create secrets containing CA
kubectl create namespace "$NAMESPACE" || true
kubectl delete -n "$NAMESPACE" secret my-tls-secret || true
kubectl delete -n "$NAMESPACE" secret my-root-ca || true
kubectl -n "$NAMESPACE" create secret tls my-tls-secret --cert=proxy.fullchain.pem --key=proxy.key.pem
kubectl -n "$NAMESPACE" create secret generic my-root-ca --from-file=ca.pem=ca.cert.pem

# helm install -n teleport teleport-repro teleport/teleport-cluster --version=12.0.0-alpha.1 --set clusterName=teleport.example.com --set tls.existingSecretName=my-tls-secret --set tls.existingCASecretName=my-root-ca --set operator.enabled=true
helm install -n "$NAMESPACE" teleport-repro "$TELEPORT_REPO_PATH" --set teleportVersionOverride=12.0.0-alpha.1 --set clusterName=teleport.example.com --set tls.existingSecretName=my-tls-secret --set tls.existingCASecretName=my-root-ca --set operator.enabled=true

# don't forget to cleanly uninstall the Helm chart to avoid CRD leforvers
```

Can you provide:
- the full operator logs (`kubectl logs ... -c operator`)
- the values and helm command you used to deploy
- the full teleport server logs (`kubectl logs ... -c teleport`)

**Comment by hugoShaka** [comment] 2024-04-24 21:50
Closing as the operator does not run in the auth pod since v15.

**Closed by hugoShaka** 2024-04-24 21:50 UTC
Labels: bug, helm
