### ISSUE TITLE
DB access and App access do not work when per session MFA is enabled

### ISSUE THREAD

**Issue by jon-can** [gravitational/teleport#8466] opened 2021-10-04 18:40 UTC
### Description

**What happened**:
If a user has per session MFA enabled in their Teleport role then they will be unable to access databases and applications via Teleport, even if their role allows them to access applications and databases.
**What you expected to happen**:
Users should still be able to access applications and databases.

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Enable per session MFA in a role
2. Log in as a user who has the per session MFA enabled role
3. Attempt to access an application or a database
4. Application Access returns "Not Found"
5. Database Access returns "psql: error: access to resource requires MFA".

### Server Details
- Teleport version (run `teleport version`): 7.1.0
- Server OS (e.g. from `/etc/os-release`): Ubuntu 20.04.1
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): AWS

### Client Details
- Tsh version (`tsh version`): 7.1.0
- Computer OS (e.g. Linux, macOS, Windows): macOS
- Browser version (for UI-related issues): Chrome and Firefox
- Installed via (e.g. apt, yum, brew, website download): website download

### Teleport Role Example
```kind: role
metadata:
  id: 1633371671295695232
  name: devrole
spec:
  allow:
    app_labels:
      type: kube
    db_labels:
      env: dev
    db_names:
    - '{{internal.db_names}}'
    - '*'
    db_users:
    - '{{internal.db_users}}'
    - '*'
    kubernetes_groups:
    - devs
    kubernetes_labels:
      environment: staging
    logins:
    - ubuntu
    node_labels:
      environment: development
    rules:
    - resources:
      - role
      verbs:
      - list
      - read
    - resources:
      - trusted_cluster
      verbs:
      - list
      - read
    - resources:
      - access_request
      verbs:
      - list
      - read
      - update
      - delete
  deny: {}
  options:
    cert_format: standard
    enhanced_recording:
    - command
    - network
    forward_agent: true
    max_session_ttl: 1h0m0s
    port_forwarding: false
    require_session_mfa: true
version: v3
```

### Debug Logs
Please include or attach debug logs, when appropriate. Obfuscate sensitive information!
- Start Teleport with --debug flag (`teleport --debug`)
- Run tsh with --debug flag (`tsh --debug`)

```Oct 04 18:28:20 ip-172-31-25-182 teleport[2759897]: 2021-10-04T18:28:20Z DEBU [WEB]       Creating application web session for kube-ui.demotest.gravitational.io in aws-west. web/apps.go:148
Oct 04 18:28:20 ip-172-31-25-182 teleport[2759897]: 2021-10-04T18:28:20Z DEBU [KEYGEN]    generated user key for [ubuntu none] with expiry on (1633374845) 2021-10-04 19:14:05.000560489 +0000 UTC native/native.go:256
Oct 04 18:28:20 ip-172-31-25-182 teleport[2759897]: 2021-10-04T18:28:20Z INFO [CA]        Generating TLS certificate {0x556b168 0xc0022e4810 1.3.9999.2.6=#0c012a,1.3.9999.2.5=#0c012a,1.3.9999.1.7=#13086177732d77657374,1.3.9999.1.5=#13086177732d77657374,1.3.9999.1.6=#13216b7562652d75692e64656d6f746573742e6772617669746174696f6e616c2e696f,1.3.9999.1.4=#132430633135613136662d356636622d343261332d613761642d303238386565383761363931,1.3.9999.1.3=#13096a63616e6164612d31,1.3.9999.1.2=#130464657673,CN=jcanada01@gmail.com,OU=usage:apps,O=devrole+O=contractor,POSTALCODE={\"aud\":[\"Kp7hYeYBOgJeo7IhVZtWBy0kUFE7xCFN\"]\,\"awsRole\":[\"arn:aws:iam::126027368216:role/auth0-developer\,arn:aws:iam::126027368216:saml-provider/auth0\"]\,\"awsRoleSession\":[\"jcanada01\"]\,\"clientID\":[\"Kp7hYeYBOgJeo7IhVZtWBy0kUFE7xCFN\"]\,\"created_at\":[\"2020-02-14T19:00:33.841Z\"]\,\"devlogin\":[\"developer\"]\,\"email\":[\"jcanada01@gmail.com\"]\,\"family_name\":[\"Canada\"]\,\"given_name\":[\"Jonathon\"]\,\"iss\":[\"https://gravitational.auth0.com/\"]\,\"locale\":[\"en\"]\,\"login\":[\"jonathon.canada\"]\,\"name\":[\"Jonathon Canada\"]\,\"nickname\":[\"jcanada01\"]\,\"picture\":[\"https://lh3.googleusercontent.com/a/AATXAJzoqrUPUFvczPObT-AEzNy2os-id_hJZi_5ePXh=s96-c\"]\,\"roles\":[\"gravitational/devc\"\,\"gravitational/dev-admin-role\"]\,\"sub\":[\"google-oauth2|117555337256929184745\"]\,\"unixaccountname\":[\"ec2-user\"]\,\"updated_at\":[\"2021-10-04T18:13:56.567Z\"]\,\"user_id\":[\"google-oauth2|117555337256929184745\"]},STREET=aws-west,L=ubuntu+L=none,ST=devs 2021-10-04 19:14:05.004176126 +0000 UTC []}. common_name:jcanada01@gmail.com dns_names:[] locality:[ubuntu none] not_after:2021-10-04 19:14:05.004176126 +0000 UTC org:[devrole contractor] org_unit:[usage:apps] tlsca/ca.go:637
Oct 04 18:28:20 ip-172-31-25-182 teleport[2759897]: 2021-10-04T18:28:20Z DEBU [AUTH]      Generated application web session for jcanada01@gmail.com with TTL 45m44.074407714s. auth/sessions.go:104
Oct 04 18:28:21 ip-172-31-25-182 teleport[2759897]: 2021-10-04T18:28:21Z INFO [AUDIT]     app.session.start addr.remote:70.181.210.118:61243 cluster_name:aws-westcode:T2007I ei:0 event:app.session.start namespace:default public_addr:kube-ui.demotest.gravitational.io server_id:d99f1fcb-bc9b-4573-8b38-f826ab8f1c48 sid:0c15a16f-5f6b-42a3-a7ad-0288ee87a691 time:2021-10-04T18:28:21.209Z uid:d02a109c-eb5b-4328-8b1f-cc99613236b8 user:jcanada01@gmail.com events/emitter.go:324
Oct 04 18:28:21 ip-172-31-25-182 teleport[2759897]: 2021-10-04T18:28:21Z INFO [AUDIT]     app.session.start addr.remote:70.181.210.118:61243 cluster_name:aws-westcode:T2007I ei:0 event:app.session.start namespace:default public_addr:kube-ui.demotest.gravitational.io server_id:d99f1fcb-bc9b-4573-8b38-f826ab8f1c48 sid:0c15a16f-5f6b-42a3-a7ad-0288ee87a691 time:2021-10-04T18:28:21.209Z uid:d02a109c-eb5b-4328-8b1f-cc99613236b8 user:jcanada01@gmail.com events/emitter.go:324
Oct 04 18:28:21 ip-172-31-25-182 teleport[2759897]: 2021-10-04T18:28:21Z DEBU [PROXY:SER] Dialing from: "@web-proxy" to: "@local-node". trace.fields:map[cluster:aws-west] reversetunnel/localsite.go:185
Oct 04 18:28:21 ip-172-31-25-182 teleport[2759897]: 2021-10-04T18:28:21Z DEBU [PROXY:SER] Tunnel dialing to ac7b7c38-dac6-4c9b-9cc7-0e13b3bffff9.aws-west. trace.fields:map[cluster:aws-west] reversetunnel/localsite.go:269
Oct 04 18:28:21 ip-172-31-25-182 teleport[2759897]: 2021-10-04T18:28:21Z DEBU [PROXY:SER] Connecting to 18.237.28.68:50074 through tunnel. trace.fields:map[cluster:aws-west] reversetunnel/localsite.go:459
Oct 04 18:28:21 ip-172-31-25-182 teleport[2759897]: 2021-10-04T18:28:21Z DEBU [PROXY:SER] Succeeded dialing from: "@web-proxy" to: "@local-node". trace.fields:map[cluster:aws-west] reversetunnel/localsite.go:191
Oct 04 18:28:21 ip-172-31-25-182 teleport[2759897]: 2021-10-04T18:28:21Z INFO [APP:WEB]   Round trip: GET /, code: 404, duration: 14.679947ms tls:version: 304, tls:resume:true, tls:csuite:1301, tls:server:kube-ui.demotest.gravitational.io forward/fwd.go:185
```

```Oct 04 18:37:40 ip-172-31-25-182 teleport[2759897]: 2021-10-04T18:37:40Z DEBU [MX:PROXY:] Detected Postgres client connection. protocol:5 multiplexer/multiplexer.go:251
Oct 04 18:37:40 ip-172-31-25-182 teleport[2759897]: 2021-10-04T18:37:40Z DEBU [DB:PROXY]  Accepted Postgres connection from 70.181.210.118:62032. db/proxyserver.go:256
Oct 04 18:37:40 ip-172-31-25-182 teleport[2759897]: 2021-10-04T18:37:40Z DEBU [DB:PROXY]  Received startup message: &pgproto3.SSLRequest{}. postgres/proxy.go:97
Oct 04 18:37:40 ip-172-31-25-182 teleport[2759897]: 2021-10-04T18:37:40Z DEBU [AUTH]      ClientCertPool -> cert(aws-east issued by aws-east:6297901547767151252122985717266166720) auth/middleware.go:590
Oct 04 18:37:40 ip-172-31-25-182 teleport[2759897]: 2021-10-04T18:37:40Z DEBU [AUTH]      ClientCertPool -> cert(aws-west issued by aws-west:122932108803982799327912107690831020675) auth/middleware.go:590
Oct 04 18:37:40 ip-172-31-25-182 teleport[2759897]: 2021-10-04T18:37:40Z DEBU [AUTH]      ClientCertPool -> cert(aws-west issued by aws-west:156191204548917725019236077938065176078) auth/middleware.go:590
Oct 04 18:37:40 ip-172-31-25-182 teleport[2759897]: 2021-10-04T18:37:40Z DEBU [DB:PROXY]  Received startup message: &pgproto3.StartupMessage{ProtocolVersion:0x30000, Parameters:map[string]string{"application_name":"psql", "client_encoding":"UTF8", "database":"postgres", "user":"dbadmin"}}. postgres/proxy.go:97
Oct 04 18:37:40 ip-172-31-25-182 teleport[2759897]: 2021-10-04T18:37:40Z DEBU [DB:PROXY]  Available database servers on aws-west: [DatabaseServer(Name=dev-db, Type=rds, Version=7.0.2, Labels=map[env:dev], HostID=e92ee419-b7ca-4d33-9942-54d9f8d610c8) DatabaseServer(Name=prod-db, Type=rds, Version=7.0.2, Labels=map[env:prod],HostID=e92ee419-b7ca-4d33-9942-54d9f8d610c8)]. db/proxyserver.go:503
Oct 04 18:37:40 ip-172-31-25-182 teleport[2759897]: 2021-10-04T18:37:40Z DEBU [DB:PROXY]  Dialing to DatabaseServer(Name=dev-db, Type=rds, Version=7.0.2, Labels=map[env:dev], HostID=e92ee419-b7ca-4d33-9942-54d9f8d610c8). db/proxyserver.go:300
Oct 04 18:37:40 ip-172-31-25-182 teleport[2759897]: 2021-10-04T18:37:40Z DEBU [AUTH]      Signing database CSR for cluster aws-west. auth/db.go:86
Oct 04 18:37:40 ip-172-31-25-182 teleport[2759897]: 2021-10-04T18:37:40Z INFO [CA]        Generating TLS certificate {0x556b168 0xc00200bb80 1.3.9999.2.2=#1308706f737467726573,1.3.9999.2.1=#13066465762d6462,1.3.9999.1.7=#13086177732d77657374,1.3.9999.1.3=#13096a63616e6164612d31,1.3.9999.1.2=#130464657673,CN=jcanada01@gmail.com,OU=usage:db,O=devrole+O=contractor,POSTALCODE={\"aud\":[\"Kp7hYeYBOgJeo7IhVZtWBy0kUFE7xCFN\"]\,\"awsRole\":[\"arn:aws:iam::126027368216:role/auth0-developer\,arn:aws:iam::126027368216:saml-provider/auth0\"]\,\"awsRoleSession\":[\"jcanada01\"]\,\"clientID\":[\"Kp7hYeYBOgJeo7IhVZtWBy0kUFE7xCFN\"]\,\"created_at\":[\"2020-02-14T19:00:33.841Z\"]\,\"devlogin\":[\"developer\"]\,\"email\":[\"jcanada01@gmail.com\"]\,\"family_name\":[\"Canada\"]\,\"given_name\":[\"Jonathon\"]\,\"iss\":[\"https://gravitational.auth0.com/\"]\,\"locale\":[\"en\"]\,\"login\":[\"jonathon.canada\"]\,\"name\":[\"Jonathon Canada\"]\,\"nickname\":[\"jcanada01\"]\,\"picture\":[\"https://lh3.googleusercontent.com/a/AATXAJzoqrUPUFvczPObT-AEzNy2os-id_hJZi_5ePXh=s96-c\"]\,\"roles\":[\"gravitational/devc\"\,\"gravitational/dev-admin-role\"]\,\"sub\":[\"google-oauth2|117555337256929184745\"]\,\"unixaccountname\":[\"ec2-user\"]\,\"updated_at\":[\"2021-10-04T18:17:09.688Z\"]\,\"user_id\":[\"google-oauth2|117555337256929184745\"]},STREET=aws-west,L=none+L=ubuntu,ST=devs 2021-10-04 19:37:40.695235695 +0000 UTC []}. common_name:jcanada01@gmail.com dns_names:[] locality:[none ubuntu] not_after:2021-10-04 19:37:40.695235695 +0000 UTC org:[devrole contractor] org_unit:[usage:db] tlsca/ca.go:637
Oct 04 18:37:40 ip-172-31-25-182 teleport[2759897]: 2021-10-04T18:37:40Z DEBU [PROXY:SER] Dialing from: "@db-proxy" to: "@local-node". trace.fields:map[cluster:aws-west] reversetunnel/localsite.go:185
Oct 04 18:37:40 ip-172-31-25-182 teleport[2759897]: 2021-10-04T18:37:40Z DEBU [PROXY:SER] Tunnel dialing to e92ee419-b7ca-4d33-9942-54d9f8d610c8.aws-west. trace.fields:map[cluster:aws-west] reversetunnel/localsite.go:269
Oct 04 18:37:40 ip-172-31-25-182 teleport[2759897]: 2021-10-04T18:37:40Z DEBU [PROXY:SER] Connecting to 54.193.83.6:59658 through tunnel. trace.fields:map[cluster:aws-west] reversetunnel/localsite.go:459
Oct 04 18:37:40 ip-172-31-25-182 teleport[2759897]: 2021-10-04T18:37:40Z DEBU [PROXY:SER] Succeeded dialing from: "@db-proxy" to: "@local-node". trace.fields:map[cluster:aws-west] reversetunnel/localsite.go:191
Oct 04 18:37:40 ip-172-31-25-182 teleport[2759897]: 2021-10-04T18:37:40Z DEBU [DB:PROXY]  Stop proxying from client to service. db/proxyserver.go:361
Oct 04 18:37:40 ip-172-31-25-182 teleport[2759897]: 2021-10-04T18:37:40Z DEBU [DB:PROXY]  Stop proxying from service to client. db/proxyserver.go:368
Oct 04 18:37:40 ip-172-31-25-182 teleport[2759897]: 2021-10-04T18:37:40Z INFO [AUDIT]     db.session.start cluster_name:aws-west code:TDB00W db_name:postgres db_protocol:postgres db_service:dev-db db_uri:jc-postgres-instance-1.c0m0dsney9i9.us-west-1.rds.amazonaws.com:5432 db_user:dbadmin ei:0 error:[access to resource requires MFA] event:db.session.start message:access to resource requires MFA namespace:default server_id:e92ee419-b7ca-4d33-9942-54d9f8d610c8 sid:c8a6bd49-bb0b-471e-be20-071accf74942 success:false time:2021-10-04T18:37:40.891Z uid:7dadc1f6-eaea-400f-9f1a-52217a3d378e user:jcanada01@gmail.com events/emitter.go:324
Oct 04 18:37:41 ip-172-31-25-182 teleport[2759897]: 2021-10-04T18:37:41Z DEBU [AUTH:GRPC] CreateAuditStream connection from e92ee419-b7ca-4d33-9942-54d9f8d610c8.aws-west. auth/grpcserver.go:139
Oct 04 18:37:41 ip-172-31-25-182 teleport[2759897]: 2021-10-04T18:37:41Z DEBU [AUTH:GRPC] Created stream: <nil>. auth/grpcserver.go:182
Oct 04 18:37:41 ip-172-31-25-182 teleport[2759897]: 2021-10-04T18:37:41Z INFO [AUDIT]     session.upload cluster_name:aws-west code:T2005I ei:2.147483647e+09 event:session.upload sid:c8a6bd49-bb0b-471e-be20-071accf74942 time:2021-10-04T18:37:41.963Z url:file:///var/lib/teleport/log/records/multi/c8a6bd49-bb0b-471e-be20-071accf74942 events/emitter.go:324
Oct 04 18:37:41 ip-172-31-25-182 teleport[2759897]: 2021-10-04T18:37:41Z DEBU [AUTH:GRPC] Completed stream: <nil>. auth/grpcserver.go:228
Oct 04 18:37:41 ip-172-31-25-182 teleport[2759897]: 2021-10-04T18:37:41Z WARN [AUTH:GRPC] Failed to flush close the stream. error:[
Oct 04 18:37:41 ip-172-31-25-182 teleport[2759897]: ERROR REPORT:
Oct 04 18:37:41 ip-172-31-25-182 teleport[2759897]: Original Error: *trace.ConnectionProblemError emitter has been closed
Oct 04 18:37:41 ip-172-31-25-182 teleport[2759897]: Stack Trace:
Oct 04 18:37:41 ip-172-31-25-182 teleport[2759897]:         /go/src/github.com/gravitational/teleport/lib/events/stream.go:423 github.com/gravitational/teleport/lib/events.(*ProtoStream).Close
Oct 04 18:37:41 ip-172-31-25-182 teleport[2759897]:         /go/src/github.com/gravitational/teleport/lib/events/emitter.go:454 github.com/gravitational/teleport/lib/events.(*CheckingStream).Close
Oct 04 18:37:41 ip-172-31-25-182 teleport[2759897]:         /go/src/github.com/gravitational/teleport/lib/auth/auth_with_roles.go:1979 github.com/gravitational/teleport/lib/auth.(*streamWithRoles).Close
Oct 04 18:37:41 ip-172-31-25-182 teleport[2759897]:         /go/src/github.com/gravitational/teleport/lib/auth/grpcserver.go:157 github.com/gravitational/teleport/lib/auth.(*GRPCServer).CreateAuditStream.func2
Oct 04 18:37:41 ip-172-31-25-182 teleport[2759897]:         /go/src/github.com/gravitational/teleport/lib/auth/grpcserver.go:232 github.com/gravitational/teleport/lib/auth.(*GRPCServer).CreateAuditStream
Oct 04 18:37:41 ip-172-31-25-182 teleport[2759897]:         /go/src/github.com/gravitational/teleport/vendor/github.com/gravitational/teleport/api/client/proto/authservice.pb.go:9893 github.com/gravitational/teleport/api/client/proto._AuthService_CreateAuditStream_Handler
Oct 04 18:37:41 ip-172-31-25-182 teleport[2759897]:         /go/src/github.com/gravitational/teleport/lib/auth/middleware.go:385 github.com/gravitational/teleport/lib/auth.(*Middleware).StreamInterceptor
Oct 04 18:37:41 ip-172-31-25-182 teleport[2759897]:         /go/src/github.com/gravitational/teleport/lib/auth/grpcserver.go:2974 github.com/gravitational/teleport/lib/auth.grpcErrorConvertStreamInterceptor.func1
Oct 04 18:37:41 ip-172-31-25-182 teleport[2759897]:         /go/src/github.com/gravitational/teleport/vendor/google.golang.org/grpc/server.go:1336 google.golang.org/grpc.(*Server).processStreamingRPC
Oct 04 18:37:41 ip-172-31-25-182 teleport[2759897]:         /go/src/github.com/gravitational/teleport/vendor/google.golang.org/grpc/server.go:1409 google.golang.org/grpc.(*Server).handleStream
Oct 04 18:37:41 ip-172-31-25-182 teleport[2759897]:         /go/src/github.com/gravitational/teleport/vendor/google.golang.org/grpc/server.go:746 google.golang.org/grpc.(*Server).serveStreams.func1.1
Oct 04 18:37:41 ip-172-31-25-182 teleport[2759897]:         /opt/go/src/runtime/asm_amd64.s:1371 runtime.goexit
Oct 04 18:37:41 ip-172-31-25-182 teleport[2759897]: User Message: emitter has been closed] auth/grpcserver.go:158

**Comment by webvictim** [comment] 2022-04-20 19:43
I just got hit with this one too and spent some time figuring it out. All you see in the web browser is "Not found" even though it seems like everything is absolutely fine.

Digging into logs does offer a little assistance, but the useful message is at `DEBUG` level:

```
Apr 20 18:55:13 ip-172-31-30-140 teleport[746628]: 2022-04-20T18:55:13Z DEBU [RBAC]      Access to app "jenkins" denied, role "access" requires per-session MFA services/role.go:1845
Apr 20 18:55:13 ip-172-31-30-140 teleport[746628]: 2022-04-20T18:55:13Z WARN [APP:SERVI] Failed to serve request: not found. app/server.go:575
```

**Comment by russjones** [comment] 2022-06-23 16:47
@jon-can Just to be clear, is the issue here that if one role within your role set requires per-session MFA it's requires for all access even if you have a role that allows you to access it without per-session MFA?

**Comment by zmb3** [comment] 2022-08-12 18:50
Closing as duplicate of #6172

**Closed by zmb3** 2022-08-12 18:50 UTC
Labels: bug, feature-request, mfa
