### ISSUE TITLE
X11 Forwarding support for Recording Proxy

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#1791] opened 2018-03-19 18:22 UTC
**Problem**

The SSH protocol supports X11 forwarding for a session by issuing a `x11-req` request within a `session` channel. However, when using Teleport with the recording proxy `x11-req` request types are not supported: https://github.com/gravitational/teleport/blob/v2.5.2/lib/srv/forward/sshserver.go#L621-L650

**Proposed Solution**

Add support for handling `x11-req` requests to the recording proxy.

**Workarounds**

When using Teleport in normal mode, the proxy simply establishes a TCP connection to the destination host and all communication occurs between the client and the target node. If the target node is a OpenSSH node, X11 forwarding will work.

**Comment by russjones** [comment] 2019-04-15 17:40
Some useful reading links:

- https://tools.ietf.org/html/rfc4254#section-6.3
- https://en.wikipedia.org/wiki/X_Window_authorization
- https://nnc3.com/mags/Networking2/ssh/ch09_03.htm

**Comment by benarent** [comment] 2020-05-21 16:08
Duplicate of https://github.com/gravitational/teleport/issues/3401

**Closed by benarent** 2020-05-21 16:08 UTC
