### ISSUE TITLE
Mark Servers with old software in the list

### ISSUE THREAD

**Issue by jryberg** [gravitational/teleport#19323] opened 2022-12-13 08:15 UTC
What would you like Teleport to do?
When I login to the UI there is a message telling me "Some Agents within this Cluster are running an older version of Teleport. Please consider upgrading them." It would be extremely helpful to see what version each client are running so we can make better decisions of what client that needs to be updated. Some clients is hard to manage centrally so we can't rely on for example Ansible or salt. 

What problem does this solve?
Easier to update clients

If a workaround exists, please include it.

**Comment by zmb3** [comment] 2022-12-13 16:26
Duplicate of #17488

**Closed by zmb3** 2022-12-13 16:26 UTC
Labels: feature-request
