### ISSUE TITLE
TTL: never does not work for cache policy

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#1116] opened 2017-07-02 17:40 UTC
Version: 2.2.3

When using `never` get this error:
```bash
cache.ttl invalid duration: never, accepted format '10h'
```

**Comment by kontsevoy** [comment] 2017-07-06 00:14
what's `cache.ttl` and "cache policy"? if this is something Telekube needs, it shouldn't be exposed to regular users.

**Comment by klizhentas** [comment] 2017-07-06 22:08
@kontsevoy it's all documented here:

https://github.com/gravitational/teleport/pull/853#issue-215907945

**Comment by kontsevoy** [comment] 2017-07-07 00:22
nevermind then

**Comment by kontsevoy** [comment] 2018-02-05 21:32
@klizhentas @russjones is this something trivial? seems so, adding to the cleanup milestone we're in the middle of.

**Comment by russjones** [comment] 2018-02-15 22:29
Tried to reproduce and couldn't, turns out it was fixed in https://github.com/gravitational/teleport/pull/1117.

**Closed by russjones** 2018-02-15 22:29 UTC
