### ISSUE TITLE
`TestCreateLock` flakiness

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#24005] opened 2023-04-03 16:40 UTC
This test times out in CI pretty often.

Example run: https://github.com/gravitational/teleport/actions/runs/4598953595/jobs/8123712141.

**Comment by zmb3** [comment] 2023-04-03 18:49
There are lots of goroutines stuck in `google.golang.org/grpc.(*ccBalancerWrapper).watcher`, which seems related to https://github.com/grpc/grpc-go/issues/5321 (we probably aren't properly closing a client somewhere).

**Comment by zmb3** [comment] 2023-04-03 18:52
I think this is actually a duplicate of #19372 and not specific to `TestCreateLock`.

**Closed** 2023-04-06 15:05 UTC
Labels: flaky tests
