### ISSUE TITLE
Initialize Teleport and exit

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#1241] opened 2017-08-31 01:33 UTC
## Problem

To install Teleport on a server at the moment you have to do the following.

1. Add the provisioning token to `teleport.yaml` or pass it on the command line.
1. Start Teleport and wait for `/var/lib/teleport` to be initialized.
1. Shut down Teleport.
1. Remove the token from either `teleport.yaml` or command line.
1. Star Teleport.

While not difficult to script, it is a bit cumbersome.

## Proposed Solution

Teleport should support an "initialize mode" where the token can be passed in using a environment variable or read in from a file on disk. Teleport would read in the provisioning token, initialize `/var/lib/teleport` and quit.

Then Teleport can be started without the token as it normally would.

**Comment by kontsevoy** [comment] 2017-08-31 01:38
note to self: lets talk to a user who requested this feature. need more context

**Comment by klizhentas** [comment] 2018-01-04 20:19
Use SSM parameter store ticket, dupe of #1546

**Closed by klizhentas** 2018-01-04 20:19 UTC
Labels: feature request
