### ISSUE TITLE
Error occurred whilst watching CA rotations for Machine ID 

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#15545] opened 2022-08-16 03:40 UTC
Expected behavior:
I'm seeing a lot of log spam  with tbot & Teleport v10.1.2 git:v10.1.2-0-g5bc7caf go1.18.3. This is before I've completed a CA rotation.

```
Cluster  teleport-10-ent.asteroid.earth
Version  10.1.2
host CA  never updated
user CA  never updated
db CA    never updated
jwt CA   never updated
CA pin   sha256:f58ecc4fa58aee350cd5156f6292198898172f81a1eadcdb351c81cb56d926ef
```

Current behavior:
```
Aug 16 00:49:00 ip-10-0-0-193 systemd[1]: Started MachineID Service.
Aug 16 00:49:01 ip-10-0-0-193 tbot[1485]: WARN [TBOT]      CLI parameters are overriding onboarding config from /etc/tbot.yaml config/config.go:335
Aug 16 00:49:01 ip-10-0-0-193 tbot[1485]: INFO [TBOT]      Attempting to generate new identity from token tbot/renew.go:454
Aug 16 00:49:01 ip-10-0-0-193 tbot[1485]: INFO [AUTH]      Attempting registration via proxy server. auth/register.go:185
Aug 16 00:49:01 ip-10-0-0-193 tbot[1485]: INFO [AUTH]      Successfully registered via proxy server. auth/register.go:192
Aug 16 00:49:01 ip-10-0-0-193 tbot[1485]: INFO [TBOT]      Successfully generated new bot identity, valid: after=2022-08-16T00:48:01Z, before=2022-08-16T01:49:01Z>
Aug 16 00:49:01 ip-10-0-0-193 tbot[1485]: INFO [TBOT]      Beginning renewal loop: ttl=1h0m0s interval=20m0s tbot/renew.go:653
Aug 16 00:49:01 ip-10-0-0-193 tbot[1485]: INFO [TBOT]      Started watching for CA rotations tbot/ca_rotation.go:154
Aug 16 00:49:02 ip-10-0-0-193 tbot[1485]: INFO [TBOT]      Attempting to generate new identity from token tbot/renew.go:454
Aug 16 00:49:02 ip-10-0-0-193 tbot[1485]: INFO [AUTH]      Attempting registration via proxy server. auth/register.go:185
Aug 16 00:49:02 ip-10-0-0-193 tbot[1485]: INFO [AUTH]      Successfully registered via proxy server. auth/register.go:192
Aug 16 00:49:02 ip-10-0-0-193 tbot[1485]: INFO [TBOT]      Successfully renewed bot certificates, valid: after=2022-08-16T00:48:01Z, before=2022-08-16T01:49:01Z, >
Aug 16 00:49:02 ip-10-0-0-193 tbot[1485]: ERRO [TBOT]      Error occurred whilst watching CA rotations, retrying in 1.897970462s. error:[
Aug 16 00:49:02 ip-10-0-0-193 tbot[1485]: ERROR REPORT:
Aug 16 00:49:02 ip-10-0-0-193 tbot[1485]: Original Error: *status.Error rpc error: code = Canceled desc = grpc: the client connection is closing
Aug 16 00:49:02 ip-10-0-0-193 tbot[1485]: Stack Trace:
Aug 16 00:49:02 ip-10-0-0-193 tbot[1485]:         /go/src/github.com/gravitational/teleport/api/client/streamwatcher.go:87 github.com/gravitational/teleport/api/c>
Aug 16 00:49:02 ip-10-0-0-193 tbot[1485]:         /opt/go/src/runtime/asm_amd64.s:1571 runtime.goexit
Aug 16 00:49:02 ip-10-0-0-193 tbot[1485]: User Message: rpc error: code = Canceled desc = grpc: the client connection is closing] tbot/ca_rotation.go:117
Aug 16 00:49:02 ip-10-0-0-193 tbot[1485]: INFO [TBOT]      Successfully renewed impersonated certificates for directory /home/ubuntu/machine-id, valid: after=2022>
Aug 16 00:49:02 ip-10-0-0-193 tbot[1485]: INFO [TBOT]      Persisted new certificates to disk. Next renewal in approximately 20m0s tbot/renew.go:642
Aug 16 00:49:04 ip-10-0-0-193 tbot[1485]: INFO [TBOT]      Started watching for CA rotations tbot/ca_rotation.go:154
Aug 16 01:09:02 ip-10-0-0-193 tbot[1485]: INFO [TBOT]      Attempting to generate new identity from token tbot/renew.go:454
Aug 16 01:09:02 ip-10-0-0-193 tbot[1485]: INFO [AUTH]      Attempting registration via proxy server. auth/register.go:185
Aug 16 01:09:02 ip-10-0-0-193 tbot[1485]: INFO [AUTH]      Successfully registered via proxy server. auth/register.go:192
Aug 16 01:09:02 ip-10-0-0-193 tbot[1485]: INFO [TBOT]      Successfully renewed bot certificates, valid: after=2022-08-16T00:48:02Z, before=2022-08-16T01:49:02Z, >
Aug 16 01:09:02 ip-10-0-0-193 tbot[1485]: ERRO [TBOT]      Error occurred whilst watching CA rotations, retrying in 1.664147659s. error:[
Aug 16 01:09:02 ip-10-0-0-193 tbot[1485]: ERROR REPORT:
Aug 16 01:09:02 ip-10-0-0-193 tbot[1485]: Original Error: *status.Error rpc error: code = Canceled desc = grpc: the client connection is closing
Aug 16 01:09:02 ip-10-0-0-193 tbot[1485]: Stack Trace:
Aug 16 01:09:02 ip-10-0-0-193 tbot[1485]:         /go/src/github.com/gravitational/teleport/api/client/streamwatcher.go:87 github.com/gravitational/teleport/api/c>
Aug 16 01:09:02 ip-10-0-0-193 tbot[1485]:         /opt/go/src/runtime/asm_amd64.s:1571 runtime.goexit
Aug 16 01:09:02 ip-10-0-0-193 tbot[1485]: User Message: rpc error: code = Canceled desc = grpc: the client connection is closing] tbot/ca_rotation.go:117
Aug 16 01:09:02 ip-10-0-0-193 tbot[1485]: INFO [TBOT]      Successfully renewed impersonated certificates for directory /home/ubuntu/machine-id, valid: after=2022>
Aug 16 01:09:02 ip-10-0-0-193 tbot[1485]: INFO [TBOT]      Persisted new certificates to disk. Next renewal in approximately 20m0s tbot/renew.go:642
Aug 16 01:09:04 ip-10-0-0-193 tbot[1485]: INFO [TBOT]      Started watching for CA rotations tbot/ca_rotation.go:154
Aug 16 01:29:02 ip-10-0-0-193 tbot[1485]: INFO [TBOT]      Attempting to generate new identity from token tbot/renew.go:454
Aug 16 01:29:02 ip-10-0-0-193 tbot[1485]: INFO [AUTH]      Attempting registration via proxy server. auth/register.go:185
Aug 16 01:29:02 ip-10-0-0-193 tbot[1485]: INFO [AUTH]      Successfully registered via proxy server. auth/register.go:192
Aug 16 01:29:02 ip-10-0-0-193 tbot[1485]: INFO [TBOT]      Successfully renewed bot certificates, valid: after=2022-08-16T01:08:02Z, before=2022-08-16T02:09:02Z, >
Aug 16 01:29:02 ip-10-0-0-193 tbot[1485]: ERRO [TBOT]      Error occurred whilst watching CA rotations, retrying in 1.296823825s. error:[
Aug 16 01:29:02 ip-10-0-0-193 tbot[1485]: ERROR REPORT:
Aug 16 01:29:02 ip-10-0-0-193 tbot[1485]: Original Error: *status.Error rpc error: code = Canceled desc = grpc: the client connection is closing
Aug 16 01:29:02 ip-10-0-0-193 tbot[1485]: Stack Trace:
Aug 16 01:29:02 ip-10-0-0-193 tbot[1485]:         /go/src/github.com/gravitational/teleport/api/client/streamwatcher.go:87 github.com/gravitational/teleport/api/c>
Aug 16 01:29:02 ip-10-0-0-193 tbot[1485]:         /opt/go/src/runtime/asm_amd64.s:1571 runtime.goexit
Aug 16 01:29:02 ip-10-0-0-193 tbot[1485]: User Message: rpc error: code = Canceled desc = grpc: the client connection is closing] tbot/ca_rotation.go:117
Aug 16 01:29:02 ip-10-0-0-193 tbot[1485]: INFO [TBOT]      Successfully renewed impersonated certificates for directory /home/ubuntu/machine-id, valid: after=2022>
Aug 16 01:29:02 ip-10-0-0-193 tbot[1485]: INFO [TBOT]      Persisted new certificates to disk. Next renewal in approximately 20m0s tbot/renew.go:642
Aug 16 01:29:04 ip-10-0-0-193 tbot[1485]: INFO [TBOT]      Started watching for CA rotations tbot/ca_rotation.go:154
Aug 16 01:49:02 ip-10-0-0-193 tbot[1485]: INFO [TBOT]      Attempting to generate new identity from token tbot/renew.go:454
Aug 16 01:49:02 ip-10-0-0-193 tbot[1485]: INFO [AUTH]      Attempting registration via proxy server. auth/register.go:185
Aug 16 01:49:02 ip-10-0-0-193 tbot[1485]: INFO [AUTH]      Successfully registered via proxy server. auth/register.go:192
Aug 16 01:49:02 ip-10-0-0-193 tbot[1485]: INFO [TBOT]      Successfully renewed bot certificates, valid: after=2022-08-16T01:28:02Z, before=2022-08-16T02:29:02Z, >
Aug 16 01:49:02 ip-10-0-0-193 tbot[1485]: ERRO [TBOT]      Error occurred whilst watching CA rotations, retrying in 1.927945402s. error:[
Aug 16 01:49:02 ip-10-0-0-193 tbot[1485]: ERROR REPORT:
Aug 16 01:49:02 ip-10-0-0-193 tbot[1485]: Original Error: *status.Error rpc error: code = Canceled desc = grpc: the client connection is closing
Aug 16 01:49:02 ip-10-0-0-193 tbot[1485]: Stack Trace:
Aug 16 01:49:02 ip-10-0-0-193 tbot[1485]:         /go/src/github.com/gravitational/teleport/api/client/streamwatcher.go:87 github.com/gravitational/teleport/api/c>
Aug 16 01:49:02 ip-10-0-0-193 tbot[1485]:         /opt/go/src/runtime/asm_amd64.s:1571 runtime.goexit
Aug 16 01:49:02 ip-10-0-0-193 tbot[1485]: User Message: rpc error: code = Canceled desc = grpc: the client connection is closing] tbot/ca_rotation.go:117
Aug 16 01:49:02 ip-10-0-0-193 tbot[1485]: INFO [TBOT]      Successfully renewed impersonated certificates for directory /home/ubuntu/machine-id, valid: after=2022>
Aug 16 01:49:02 ip-10-0-0-193 tbot[1485]: INFO [TBOT]      Persisted new certificates to disk. Next renewal in approximately 20m0s tbot/renew.go:642
Aug 16 01:49:04 ip-10-0-0-193 tbot[1485]: INFO [TBOT]      Started watching for CA rotations tbot/ca_rotation.go:154
```

Bug details:
- Teleport version
- Recreation steps
- Debug logs

**Comment by strideynet** [comment] 2022-08-16 09:04
Duplicate of https://github.com/gravitational/teleport/issues/14753

**Closed by strideynet** 2022-08-16 09:04 UTC
Labels: bug, machine-id
