### ISSUE TITLE
Require Reason option for Access Requests

### ISSUE THREAD

**Issue by Erick-Reyes** [gravitational/teleport#11504] opened 2022-03-28 14:51 UTC
### What
What would you like Teleport to do differently?
Customer is asking for the following: 
Right now, when you raise an access request; the reason field is optional (screenshot). We would like to mandate reasons input for all access requests but no such option is available currently. 
### How
How would you implement this?
They would like to add this option to the UI, probably some code modifications.

  options:
    # the `request_access` field can be set to 'always' or 'reason' to tell
    # tsh or the web UI to always create an access request on login. If it is
    # set to 'reason', the user will be required to indicate *why* they are
    # generating the access request.
    request_access: reason
    # the `request_prompt` field can be used to tell the user what should
    # be supplied in the request reason field.
    request_prompt: Please provide your ticket ID

### Why
Why do you need this?
If there is a setting for admin to toggle between enabling reasons mandatory/optional that will be useful for their case use. 

### Workaround
If a workaround exists, please include it.
Currently, we have the options.request_access flag for roles in doc: 
https://goteleport.com/docs/ver/8.0/enterprise/workflow/#example-setup

However, this will not work for the customer's use case since that enforces all reasons mandatory when initial login whereby they only need to mandate during the access request stage.

Additionally, they are asking if we can change the UI text in the access request text box from `Describe your request... (optional)` to something like `Describe your request.. (mandatory)`? In the meantime, while we work on this feature request. 

Please let me know if we need any additional information. 
<img width="578" alt="Request-Role" src="https://user-images.githubusercontent.com/96448492/160425134-ab14d354-27b3-473e-8be8-72c5768f3eb4.png">

**Comment by zmb3** [comment] 2022-06-16 20:56
Can their reviewers just refuse to approve access requests without a valid reason?

There's nothing hard about requiring a reason, but if we do that, users can just enter 'x' or some other value that's not actually a reason, and we haven't really improved the situation in any way.

In other words - the decision as to whether the provided reason (if any) is justification enough to provide access is a decision that's best made by approvers, not by Teleport.

**Comment by zmb3** [comment] 2022-06-25 13:44
Closing as duplicate of #7499.

**Closed by zmb3** 2022-06-25 13:44 UTC
Labels: feature-request, access-requests
