### ISSUE TITLE
Add UI capability to download session recordings

### ISSUE THREAD

**Issue by Erick-Reyes** [gravitational/teleport#19585] opened 2022-12-21 19:14 UTC
What would you like Teleport to do?
Add UI capability to download session recordings 
e.g. 
desktop session recordings 

What problem does this solve?
Allow users to be able to view sessions offline for internal purposes as currently, our cloud-hosted customers don't have access to our S3 bucket to be able to download the session recordings. 
e.g. specifically to play back desktop session recordings without the teleport UI 

If a workaround exists, please include it.
No current workaround as we can't do `tsh play` for desktop session recordings.

**Comment by zmb3** [comment] 2022-12-21 19:16
Sessions can't be viewed outside of Teleport, so what value would downloading them provide?

**Comment by zmb3** [comment] 2022-12-24 23:20
Duplicate of #4087

**Closed** 2022-12-24 23:20 UTC
Labels: feature-request, ui, audit-log, desktop-access, c-bd
