### ISSUE TITLE
Remove nodes quicker to avoid connection failed. 

### ISSUE THREAD

**Issue by moisesmejia1200** [gravitational/teleport#21888] opened 2023-02-15 18:40 UTC
**What would you like Teleport to do?**
When the teleport agent daemon on a node is stopped normally (for example, on shutdown), it should deregister itself from the system so that it no longer appears in the Servers, Applications or other lists immediately.

**What problem does this solve?**
Currently, if you attempt to run an SSH command across multiple hosts using label matching if any of the hosts fail to connect all subsequent hosts in the match list fail to run the command. In an environment where hosts are created and destroyed relatively rapidly (a volatile AWS autoscaling group for example), this is a problem, as at any given time it is likely that at least one of the instances matching the label will be offline, but not yet deregistered. This makes using Teleport SSH for automation over such a cluster basically useless.

If the terminated instances were immediately deregistered from Teleport when their agent was stopped, as part of the shutdown process, the host match list would more reliably contain only online hosts.

Also, let's say you do a full instance replacement on a scaling group with 4 instances. For some period, currently, 8 instances will appear in the servers list, only half of which actually exist. If you quickly want to connect to one of the new instances, it's a 50/50 chance you'll get one, or get a connection failure.

Related note: You might also consider changing the behavior of the SSH command so that a single instance connection failure doesn't stop the command from running on all the other hosts.

**If a workaround exists, please include it.**

We have shared tctl rm node/<resource-id> to remove nodes.

**Comment by webvictim** [comment] 2023-06-02 19:37
You can work around this by setting the following configuration parameter on your Teleport auth service and restarting:

```yaml
auth_service:
  routing_strategy: most_recent
```

This will make Teleport always choose the node with the most recent heartbeats in the event of multiple nodes matching the hostname and should reduce errors in connection.

**Comment by Pesticles** [comment] 2023-08-07 21:47
This would solve so many issues I have.

This should definitely be the default behaviour; if the service is stopped it should immediately be deregistered, what is the point of leaving the node record behind?

**Comment by zmb3** [comment] 2023-09-11 23:36
Closing as duplicate of #3479

**Closed by zmb3** 2023-09-11 23:36 UTC
Labels: feature-request, ssh, c-sm
