### ISSUE TITLE
Long-Lasting Role Assignment through JIT Workflow

### ISSUE THREAD

**Issue by nick-at-teleport** [gravitational/teleport#16889] opened 2022-09-30 15:04 UTC
What would you like Teleport to do?

Currently users are granted a certificate through JIT workflows per session that they are working. For some teams it would be ideal if Teleport could assign a role to a user for a specified duration (ie several weeks - months) without them having to change permissions through their IDP

What problem does this solve?

For some teams that are working on a project for a month-long time frame it is cumbersome to request access daily. The admins for these organizations don't want to have to approve access daily, and changing the group for the user in the SAML/OIDC mapping could leave the door open for privilege creep if they forget to go back and change permissions when access is no longer needed after project completion. 

If a workaround exists, please include it.

Only known workaround to have the role expire after a long project is to set the certificate to expire after the access is no longer needed. In the example where a user needs access for a month this means creating a certificate that has a long ttl.

**Comment by zmb3** [comment] 2022-09-30 17:08
Possible duplicate of any of these?
- https://github.com/gravitational/teleport/issues/4820
- https://github.com/gravitational/teleport/issues/14040
- https://github.com/gravitational/teleport/issues/4820

**Comment by nick-at-teleport** [comment] 2022-09-30 19:22
This would probably align closely with https://github.com/gravitational/teleport/issues/4820

**Comment by zmb3** [comment] 2022-09-30 22:05
Ok, thanks for confirming. In order to keep things manageable I'll close this in favor of 14040.

**Closed by zmb3** 2022-09-30 22:05 UTC
Labels: feature-request, access-requests
