### ISSUE TITLE
Windows Teleport Connect v16.4.0 file upload fails with error "source path is empty" 

### ISSUE THREAD

**Issue by TeleLos** [gravitational/teleport#46889] opened 2024-09-24 19:09 UTC
Expected behavior:
With correct permissions in place, a user should be able to successfully upload a file to a Linux node resource. 

Current behavior:
Attempt to upload a file results in error "source path is empty". The same procedure works if performed via the Teleport UI. 

[24-09-24 11:31:21] [tshd] info: receive teleport.lib.teleterm.v1.TerminalService ReportUsageEvent {}
[24-09-24 11:31:21] [tshd] error: receive teleport.lib.teleterm.v1.TerminalService TransferFile RpcError: source path is empty

Bug details:
- Teleport Connect Version 16.4.0 (Windows Installer), Teleport Cluster 16.3.0 and 16.4.0, Teleport agent 16.3.0 and 16.4.0
- Recreation steps 
   1.    log in as root user
   2.    file uploaded to destination ~/
   3.    drag and drop a file for find or use the browse button option

**Comment by mohamadfhatir** [comment] 2024-09-26 07:05
Im experience same issue on Mac Installation 16.2.1 and 16.4.2, it says source path is empty
also happen on my teleport webui, error message : Bad request, failed to parse error message.

Teleport cluster : 16.4.0

**Comment by gzdunek** [comment] 2024-09-30 14:48
I can confirm the issue. It happens, because in [Electron 32 a non-standard `File.path` was removed](https://github.com/electron/electron/pull/42053). To fix the problem, we need to read the file to path with `webUtils.getPathForFile` instead of reading it from `File.path`. 
Too bad that `File.path` was not completely removed from the Electron (I mean types), we would have got a TS compilation error. Instead, the application crashes silently 💀.

>also happen on my teleport webui, error message : Bad request, failed to parse error message.

This problem seems unrelated. I just tested the upload and download in Web UI (16.4.2) and couldn't reproduce it. 
If it happens again, please open a separate issue (I'm going to close this one with a PR to Connect).

**Closed** 2024-10-01 09:04 UTC
Labels: bug, regression, teleport-connect, c-eld
