### ISSUE TITLE
Support an Organizational ARN when creating a Teleport AWS joining token 

### ISSUE THREAD

**Issue by TeleLos** [gravitational/teleport#25422] opened 2023-05-01 18:29 UTC
What would you like Teleport to do?
When creating an teleport token of type join_method:iam, one must specify all aws_accounts which apply via the spec.allow settings. It would be more efficient to use an org arn instead. Especially when the hundreds of aws_accounts apply. 

What problem does this solve?
This would make creating an IAM join token more efficient. 

If a workaround exists, please include it.
Input all the individual aws_accounts into the token spec.allow block.

**Comment by r0mant** [comment] 2023-05-05 15:43
Duplicate of https://github.com/gravitational/teleport/issues/22675.

**Closed by r0mant** 2023-05-05 15:43 UTC
Labels: feature-request, aws, c-na
