### ISSUE TITLE
Standardize number of digits in timestamp

### ISSUE THREAD

**Issue by Aharic** [gravitational/teleport#14089] opened 2022-07-04 21:07 UTC
What would you like Teleport to do?

Standardized number of digits in event timestamps to make parsing easier.

What problem does this solve?

When Teleport emits timestamps, it does not always use 3 digits after the decimal / radix point, making parsing more difficult:

```
2022-03-03T23:59:01.662Z      sso.user1.last@example.com/user.login/<none>
2022-02-07T22:20:15.961Z      sso.user2.last@example.com/exec/<none>
2022-04-11T21:22:43.51Z       sso.user2.last@example.com/user.login/<none>
2022-02-03T21:37:30.019Z      sso.user3.last@example.com/exec/<none>
2022-04-13T23:02:10.111Z      sso.user4.last@example.com/user.login/<none>
2022-02-28T22:44:52.37Z       sso.user5.last@example.com/exec/<none>
2022-04-08T00:08:28.929Z      sso.user5.last@example.com/user.login/<none>
2022-01-07T04:59:32.009Z      user6.last@example.com/user.login/<none>
```

**Comment by zmb3** [comment] 2022-08-11 15:57
This looks to be a duplicate of #3590.

**Closed by zmb3** 2022-08-11 15:57 UTC
Labels: feature-request, audit-log
