### ISSUE TITLE
Dynamic Labels Not Working for Application Access

### ISSUE THREAD

**Issue by thetuber** [gravitational/teleport#15830] opened 2022-08-25 03:57 UTC
Expected behavior:

A user that is able to access an application that has a static label, should be able to still do so when the label is a dynamic label.

Current behavior:

While static label access still works, with a dynamic label, the browser often displays the message: "Not found". The application is still visible, but clicking the "launch" button often gives the error message.

Bug details:
- Teleport version

9.1.2

- Recreation steps

Install a webserver on the teleport client and have it listen on port 8000.
Copy the file `msp` to `/etc` on the teleport client.

Use the `server.yaml` and `client.yaml` config files for teleport.
Start teleport on both nodes.
On the server, create a role and user using the `role.xml` and `user.xml` files. Reset the password for user `testuser`.
Log in to the Teleport web ui as `testuser`. Go to the `application access` tab, and click the `launch` button.
Sometimes it works, sometimes you get the error message `Not found`

- Debug logs

In the logs, these are the following ips:

server public ip: 1.1.1.1
server private ip: 3.3.3.3
client public ip: 2.2.2.2
client private ip: 4.4.4.4

[teleport.zip](https://github.com/gravitational/teleport/files/9421219/teleport.zip)

**Comment by GavinFrazar** [comment] 2023-07-11 01:36
Closing because I can't reproduce this

**Closed by GavinFrazar** 2023-07-11 01:36 UTC
Labels: bug, application-access
