### ISSUE TITLE
Support DeployService when using only private subnets with NAT gw

### ISSUE THREAD

**Issue by marcoandredinis** [gravitational/teleport#40522] opened 2024-04-12 14:25 UTC
Expected behavior:
When deploying the DatabaseService, part of the Discover/Enroll RDSs, Teleport creates an ECS Service per VPC.
Each of those services will proxy database connections that exist in that VPC.
Each ECS Service receives all the database subnets that were found.

When [creating the ECS Service](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_CreateService.html) we set its network configuration to assign a public ip address so that we get Internet connectivity.
https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_AwsVpcConfiguration.html#ECS-Type-AwsVpcConfiguration-assignPublicIp
This is recommended here:
https://docs.aws.amazon.com/AmazonECS/latest/bestpracticesguide/networking-outbound.html#networking-public-subnet

However, when all the subnets are private, we must not set the `AssignPublicIP` to true.
This is described here https://docs.aws.amazon.com/AmazonECS/latest/bestpracticesguide/networking-outbound.html#networking-private-subnet

For this option to work, users must configure the NAT gateway.

**Comment by GavinFrazar** [comment] 2024-08-26 19:21
Closing because I can't reproduce an issue.

I am able to deploy into private subnets (route to a NAT gateway) without issues as-is.

**Closed by GavinFrazar** 2024-08-26 19:21 UTC
Labels: bug, aws, discover
