### ISSUE TITLE
Improve GUI wrapper

### ISSUE THREAD

**Issue by moisesmejia1200** [gravitational/teleport#22480] opened 2023-03-01 16:15 UTC
**What would you like Teleport to do?** 

The customer would like better wrapping/editing of users in web GUI. Currently, if a user has many roles already attached, it is hard to figure out where the cursor is or where you are supposed to enter the role to add.

**What problem does this solve?** 

The customer mentioned this would make it easier to add roles to users when done via web GUI

**If a workaround exists, please include it.** 

 At the moment, the workaround is thru cli

<img width="627" alt="Screenshot 2023-03-01 at 10 14 44 AM" src="https://user-images.githubusercontent.com/103964432/222197838-4082a915-172e-4351-8d46-d1e64aebf53f.png">

**Comment by zmb3** [comment] 2023-03-01 16:27
This is a duplicate of #20757 and is fixed by #21212.

**Closed by zmb3** 2023-03-01 16:27 UTC
Labels: feature-request
