### ISSUE TITLE
Unable to create auth_connectors with access role ( in the UI ) 

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#7667] opened 2021-07-23 16:53 UTC
### Description

**What happened**:

While testing SSO providers as part of https://github.com/gravitational/teleport/issues/7572 , I was unable to add auth connectors without editing the default role. It looks like we are missing 'auth_connector' from the role. 

This works with the CLI but it's not shown on the UI. 

**What you expected to happen**:

### Reproduction Steps

```diff
vagrant@teleport:~$ sudo tctl get role/editor
kind: role
metadata:
  description: Edit cluster configuration
  id: 1627058601902614706
  name: editor
spec:
  allow:
    app_labels:
      '*': '*'
    db_labels:
      '*': '*'
    kubernetes_labels:
      '*': '*'
    rules:
    - resources:
      - user
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - role
      verbs:
      - list
      - create
      - read
      - update
      - delete
+    - resources:
+       - auth_connector
+      verbs: 
+      - list
+      - create
+      - read
+      - update
+      - delete
    - resources:
      - oidc
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - saml
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - github
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - cluster_auth_preference
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - cluster_config
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - trusted_cluster
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - remote_cluster
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - token
      verbs:
      - list
      - create
      - read
      - update
      - delete
  deny: {}
  options:
    cert_format: standard
    enhanced_recording:
    - command
    - network
    forward_agent: true
    max_session_ttl: 30h0m0s
    port_forwarding: true
version: v3
```

### Server Details
- Teleport version (run `teleport version`): 7.0.0.beta.3

**Comment by webvictim** [comment] 2021-08-11 14:30
Just hit this myself with `7.0.0`. Looks like a regression because this was possible with older versions.

**Comment by webvictim** [comment] 2021-08-11 16:15
I tested with 6.2.8 and this doesn't appear to be a regression from there: it may just have been an oversight from the RBAC changes in 6.0. Either way, it should be fixed so it works the same as Enterprise (i.e. out of the box)

**Comment by zmb3** [comment] 2023-02-19 14:59
The editor role has read/write on auth connectors, so this must have been fixed at some point.

**Closed by zmb3** 2023-02-19 14:59 UTC
Labels: bug, ux, sso, rbac, regression
