### ISSUE TITLE
Add light mode for the Teleport UI

### ISSUE THREAD

**Issue by Erick-Reyes** [gravitational/teleport#19367] opened 2022-12-14 17:00 UTC
What would you like Teleport to do?
Add an option for light mode for the Teleport UI, currently, only a dark color scheme exists. 

What problem does this solve?
It helps customers with optical limitations, as the dark mode can make it difficult to interact with the GUI. In addition, adding this feature to the Teleport UI will enhance the user experience.  

If a workaround exists, please include it.
No workaround as there is no light mode.

**Comment by zmb3** [comment] 2022-12-14 21:46
Duplicate of #15234

**Closed by zmb3** 2022-12-14 21:46 UTC
Labels: feature-request, c-thg
