### ISSUE TITLE
Allow for label configuration using magic link

### ISSUE THREAD

**Issue by Aharic** [gravitational/teleport#11432] opened 2022-03-24 19:20 UTC
### What
Customers have requested the ability to be able to add labels/label-blocks when using the magic link to auto-join servers to teleport.

### How
Either as a flag or as an option to configure parameters in the WebUI before generating link.

### Why
Customer request.

**Comment by zmb3** [comment] 2022-03-25 23:22
Duplicate of #10342?

**Closed** 2022-06-06 19:40 UTC
Labels: feature-request
