### ISSUE TITLE
tsh v9 breaks tsh v8 functionality

### ISSUE THREAD

**Issue by anurag-work** [gravitational/teleport#14592] opened 2022-07-18 18:20 UTC
# Expected behavior

The following should work:
```
# tsh version
Teleport v8.3.14 git:v8.3.14-0-g1433d2456 go1.17.11
# tsh login --proxy=root-proxy.company.com:3080 --auth=corporate
# tsh ssh sjc37p1xxxxxxx 
```

# Current behavior:
```
# tsh version
Teleport v9.2.1 git:v9.2.1-0-gc6daeda62 go1.17.9
# tsh login --proxy=root-proxy.company.com:3080 --auth=corporate
# tsh ssh sjc37p1xxxxxxx
ERROR: access denied to anurag connecting to sjc37p1xxxxxxxon cluster root-cluster
```

Bug details:
- Teleport cluster and client agent is v9.3.5 . connecting via teleport agent

**Comment by strideynet** [comment] 2022-08-04 10:15
Is this a duplicate of https://github.com/gravitational/teleport/issues/14592 ?

**Comment by zmb3** [comment] 2022-08-04 19:30
This *is* #14592 :-)

**Comment by strideynet** [comment] 2022-08-04 23:47
> This _is_ #14592 :-)

🤦  Meant https://github.com/gravitational/teleport/issues/14604

**Comment by r0mant** [comment] 2022-08-05 22:27
Yes, it's the same issue. Let's close this one.

**Closed by r0mant** 2022-08-05 22:27 UTC
Labels: bug, c-te
