### ISSUE TITLE
Terminal is broken when using tsh ssh

### ISSUE THREAD

**Issue by epicfilemcnulty** [gravitational/teleport#1644] opened 2018-01-31 03:03 UTC
**What happened**:

When you connect to a node via **tsh ssh** terminal does not work correctly --
when you type, and reach the end of the line, and proceed typing, normally you would expect your cursor to go to the first position of the line below. However, when using **tsh**, instead of that cursor goes back to the first position of the current line, so when you continue typing, you are overwriting your prompt and whatever you have typed after that.

The same bug can be observed when using openSSH client, configured to work with teleport as described in the [official](https://gravitational.com/teleport/docs/2.4/admin-guide/#using-teleport-with-openssh) manual, i.e. connecting to the teleport proxy. 

When you connect to the same node via openssh client directly (i.e. using sshd on the node, without teleport proxies), terminal works correctly.

**What you expected to happen**:
Same terminal behaviour as when using plain openssh setup.

**How to reproduce it (as minimally and precisely as possible)**:

* [Install](https://gravitational.com/teleport/docs/2.4/admin-guide/#installing) teleport 
* Create at least one user
* Connect to a node as this user via tsh:
`tsh ssh --proxy=yourproxy --user=teleport_user allowed-ssh-login@your-teleport-node`
* Start typing till you reach the end of the line, proceed beyond, and instead of going to the first position
of the line below your cursor will go to the first position of the current line.

**Environment**:
- Teleport version (use `teleport version`): Teleport v2.4.0 git:v2.4.0-0-ge9d6645
- Tsh version (use `tsh version`): Teleport v2.4.0 git:v2.4.0-0-ge9d6645
- OS (e.g. from /etc/os-release): 
> NAME="Ubuntu"
> VERSION="16.04.3 LTS (Xenial Xerus)"
> ID=ubuntu
> ID_LIKE=debian
> PRETTY_NAME="Ubuntu 16.04.3 LTS"
> VERSION_ID="16.04"
> HOME_URL="http://www.ubuntu.com/"
> SUPPORT_URL="http://help.ubuntu.com/"
> BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
> VERSION_CODENAME=xenial
> UBUNTU_CODENAME=xenial

**Comment by klizhentas** [comment] 2018-01-31 03:08
could be a dupe of #1567

**Comment by epicfilemcnulty** [comment] 2018-01-31 05:14
@klizhentas most probably is, I've rebuilt v2.4.0 with the commit from #1567, and the problem is gone.

**Comment by klizhentas** [comment] 2018-01-31 06:03
k, let's close this for now, but feel free to reopen if it turns out to be not the case.

**Closed by klizhentas** 2018-01-31 06:03 UTC
