### ISSUE TITLE
Error on bootstrap from cluster backup

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#9531] opened 2021-12-22 04:14 UTC
### Description

**What happened**:
Unable to load backup on another machine. This is a complex env that has been upgraded continuously from v6 to v8. 

Running
`tctl get all --with-secrets > backup.yaml`
On another machine
```bash
teleport start --bootstrap=backup.yaml
ERROR: cannot dynamically unmarshal resources of kind "role"
```

**What you expected to happen**:
A extraction and bootstrap on another machine would work.

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. A complex environment in Teleport
2.do a `tctl get all --with-secrets > backup.yaml` 
3. run a `teleport start --bootstrap=backup.yaml` on a sep machine

### Server Details
- Teleport version (run `teleport version`): 8.0.7
- Server OS (e.g. from `/etc/os-release`): mac

**Comment by zmb3** [comment] 2021-12-22 18:37
Loading resources in this way requires that Teleport has registered an unmarshaler.

For OSS, we register them for: users, cert authorities, trusted clusters, and Github connectors.

For enterprise, we also register them for: roles, OIDC connectors, and SAML connectors.

If this is not working in enterprise builds, then it sounds like there's a bug and `e/tool/modules.init()` is not running or not running in time.

**Comment by zmb3** [comment] 2022-07-05 21:32
closing as duplicate of #9547

**Closed by zmb3** 2022-07-05 21:32 UTC
Labels: bug
