### ISSUE TITLE
explorer.exe crashes when trying to run as other user

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#27127] opened 2023-05-30 18:07 UTC
If you right click and choose "Run as different user" when using non-AD access via Teleport, `explorer.exe` crashes.

![image](https://github.com/gravitational/teleport/assets/897821/3f78c424-e632-4a13-8445-469e35c79792)

This happens with an existing user and also when using an auto-created host user.

```
Faulting application name: explorer.exe, version: 10.0.17763.3887, time stamp: 0x5c06012d
Faulting module name: teleport.dll, version: 12.4.5.0, time stamp: 0x00000000
Exception code: 0x80000003
Fault offset: 0x00000000000657a1
Faulting process id: 0xc8c
Faulting application start time: 0x01d9931cba7eaba0
Faulting application path: C:\Windows\explorer.exe
Faulting module path: C:\Windows\System32\teleport.dll
Report Id: 39318a5d-3f4d-4a01-847a-26a32b43b53b
Faulting package full name: 
Faulting package-relative application ID: 
```

![image](https://github.com/gravitational/teleport/assets/897821/0a82ac2d-5ac7-4422-93e9-b6b6ec6e21aa)

This happens reliably with the same fault offset.

Teleport version:
- Teleport cluster: `Teleport Enterprise v12.4.5 git:api/v12.4.5-0-g9a00c36 go1.20.4`
- Teleport DLL version: 12.4.5

![Screenshot 2023-05-30 at 15 00 20](https://github.com/gravitational/teleport/assets/897821/a795c976-aa0a-406c-a29c-79a25e574876)

- Windows version: Server 2019
![image](https://github.com/gravitational/teleport/assets/897821/066f15d7-667a-49c0-8be3-8d01be347081)

`C:\Windows\Logs\teleport.ap`:
```
{"authPackageId":11,"file":"auth.go:560","level":"info","msg":"initializing","time":"2023-05-26T20:57:14Z"}
{"file":"auth.go:286","level":"info","logon type":10,"msg":"logging user","time":"2023-05-26T21:00:23Z"}
{"file":"auth.go:158","level":"info","msg":"No create user OID","time":"2023-05-26T21:00:23Z"}
{"error":"No mapping between account names and security IDs was done.","file":"auth.go:395","level":"error","msg":"can't lookup user","name":"Gus","time":"2023-05-26T21:00:23Z"}
{"file":"auth.go:598","level":"info","luid":{"LowPart":311079,"HighPart":0},"msg":"terminated","time":"2023-05-26T21:00:28Z"}
{"file":"auth.go:598","level":"info","luid":{"LowPart":312932,"HighPart":0},"msg":"terminated","time":"2023-05-26T21:00:29Z"}
{"file":"auth.go:598","level":"info","luid":{"LowPart":312367,"HighPart":0},"msg":"terminated","time":"2023-05-26T21:00:29Z"}
{"file":"auth.go:286","level":"info","logon type":10,"msg":"logging user","time":"2023-05-26T21:10:47Z"}
{"file":"auth.go:146","level":"info","msg":"Found create user OID","time":"2023-05-26T21:10:47Z"}
{"file":"auth.go:165","group":"Teleport Users","level":"info","msg":"creating group","time":"2023-05-26T21:10:47Z"}
{"file":"auth.go:217","group":"Teleport Users","level":"info","msg":"adding to group","name":"Gus","time":"2023-05-26T21:10:47Z"}
{"file":"auth.go:423","groups":["S-1-5-32-544","S-1-5-32-555","S-1-5-21-307509166-4219123982-918714338-1009"],"level":"info","msg":"account","primary":"S-1-5-21-307509166-4219123982-918714338-513","time":"2023-05-26T21:10:47Z","user":"S-1-5-21-307509166-4219123982-918714338-1008","username":"EC2AMAZ-893J9EF\\Gus"}
{"file":"auth.go:433","level":"info","luid":{"LowPart":520090,"HighPart":0},"msg":"LUID","name":"Gus","time":"2023-05-26T21:10:47Z"}
{"file":"auth.go:286","level":"info","logon type":10,"msg":"logging user","time":"2023-05-30T13:56:14Z"}
{"file":"auth.go:146","level":"info","msg":"Found create user OID","time":"2023-05-30T13:56:14Z"}
{"file":"auth.go:423","groups":["S-1-5-32-544","S-1-5-32-555","S-1-5-21-307509166-4219123982-918714338-1009"],"level":"info","msg":"account","primary":"S-1-5-21-307509166-4219123982-918714338-513","time":"2023-05-30T13:56:14Z","user":"S-1-5-21-307509166-4219123982-918714338-1008","username":"EC2AMAZ-893J9EF\\Gus"}
{"file":"auth.go:433","level":"info","luid":{"LowPart":35232407,"HighPart":0},"msg":"LUID","name":"Gus","time":"2023-05-30T13:56:14Z"}
{"file":"auth.go:598","level":"info","luid":{"LowPart":35232616,"HighPart":0},"msg":"terminated","time":"2023-05-30T13:56:14Z"}
{"file":"auth.go:598","level":"info","luid":{"LowPart":35232407,"HighPart":0},"msg":"terminated","time":"2023-05-30T13:56:14Z"}
{"file":"auth.go:598","level":"info","luid":{"LowPart":35212742,"HighPart":0},"msg":"terminated","time":"2023-05-30T13:56:14Z"}
{"file":"auth.go:598","level":"info","luid":{"LowPart":35214147,"HighPart":0},"msg":"terminated","time":"2023-05-30T13:56:16Z"}
{"file":"auth.go:598","level":"info","luid":{"LowPart":35214131,"HighPart":0},"msg":"terminated","time":"2023-05-30T13:56:16Z"}
{"file":"auth.go:286","level":"info","logon type":10,"msg":"logging user","time":"2023-05-30T17:32:15Z"}
{"file":"auth.go:146","level":"info","msg":"Found create user OID","time":"2023-05-30T17:32:15Z"}
{"file":"auth.go:423","groups":["S-1-5-32-544","S-1-5-32-555","S-1-5-21-307509166-4219123982-918714338-1009"],"level":"info","msg":"account","primary":"S-1-5-21-307509166-4219123982-918714338-513","time":"2023-05-30T17:32:15Z","user":"S-1-5-21-307509166-4219123982-918714338-1008","username":"EC2AMAZ-893J9EF\\Gus"}
{"file":"auth.go:433","level":"info","luid":{"LowPart":36700739,"HighPart":0},"msg":"LUID","name":"Gus","time":"2023-05-30T17:32:15Z"}
{"file":"auth.go:598","level":"info","luid":{"LowPart":36700946,"HighPart":0},"msg":"terminated","time":"2023-05-30T17:32:16Z"}
{"file":"auth.go:598","level":"info","luid":{"LowPart":36700739,"HighPart":0},"msg":"terminated","time":"2023-05-30T17:32:16Z"}
{"file":"auth.go:598","level":"info","luid":{"LowPart":36681095,"HighPart":0},"msg":"terminated","time":"2023-05-30T17:32:16Z"}
{"file":"auth.go:598","level":"info","luid":{"LowPart":36683225,"HighPart":0},"msg":"terminated","time":"2023-05-30T17:32:17Z"}
{"file":"auth.go:598","level":"info","luid":{"LowPart":36682445,"HighPart":0},"msg":"terminated","time":"2023-05-30T17:32:17Z"}
{"file":"auth.go:286","level":"info","logon type":10,"msg":"logging user","time":"2023-05-30T17:32:21Z"}
{"file":"auth.go:146","level":"info","msg":"Found create user OID","time":"2023-05-30T17:32:21Z"}
{"file":"auth.go:423","groups":["S-1-5-32-544","S-1-5-32-555","S-1-5-21-307509166-4219123982-918714338-1009"],"level":"info","msg":"account","primary":"S-1-5-21-307509166-4219123982-918714338-513","time":"2023-05-30T17:32:21Z","user":"S-1-5-21-307509166-4219123982-918714338-1008","username":"EC2AMAZ-893J9EF\\Gus"}
{"file":"auth.go:433","level":"info","luid":{"LowPart":36742484,"HighPart":0},"msg":"LUID","name":"Gus","time":"2023-05-30T17:32:21Z"}
{"file":"auth.go:598","level":"info","luid":{"LowPart":36742686,"HighPart":0},"msg":"terminated","time":"2023-05-30T17:32:22Z"}
{"file":"auth.go:598","level":"info","luid":{"LowPart":36742484,"HighPart":0},"msg":"terminated","time":"2023-05-30T17:32:22Z"}
{"file":"auth.go:598","level":"info","luid":{"LowPart":36723317,"HighPart":0},"msg":"terminated","time":"2023-05-30T17:32:22Z"}
{"file":"auth.go:598","level":"info","luid":{"LowPart":36724823,"HighPart":0},"msg":"terminated","time":"2023-05-30T17:32:23Z"}
{"file":"auth.go:598","level":"info","luid":{"LowPart":36724557,"HighPart":0},"msg":"terminated","time":"2023-05-30T17:32:23Z"}
```

`C:\Windows\Logs\teleport.cp`:
```
{"file":"credential_provider_filter.go:65","level":"info","msg":"valid PIN found, redirecting to Teleport credential provider","time":"2023-02-10T19:33:00Z"}
{"file":"crypto.go:71","level":"info","msg":"start of sign process","time":"2023-02-10T19:33:00Z"}
{"file":"credential_provider_filter.go:65","level":"info","msg":"valid PIN found, redirecting to Teleport credential provider","time":"2023-02-10T19:54:11Z"}
{"file":"crypto.go:71","level":"info","msg":"start of sign process","time":"2023-02-10T19:54:12Z"}
{"file":"credential_provider_filter.go:65","level":"info","msg":"valid PIN found, redirecting to Teleport credential provider","time":"2023-03-14T19:12:40Z"}
{"file":"crypto.go:71","level":"info","msg":"start of sign process","time":"2023-03-14T19:12:40Z"}
{"file":"credential_provider_filter.go:65","level":"info","msg":"valid PIN found, redirecting to Teleport credential provider","time":"2023-03-14T19:12:50Z"}
{"file":"crypto.go:71","level":"info","msg":"start of sign process","time":"2023-03-14T19:12:51Z"}
{"file":"credential_provider_filter.go:65","level":"info","msg":"valid PIN found, redirecting to Teleport credential provider","time":"2023-03-14T19:17:19Z"}
{"file":"crypto.go:71","level":"info","msg":"start of sign process","time":"2023-03-14T19:17:20Z"}
{"file":"credential_provider_filter.go:65","level":"info","msg":"valid PIN found, redirecting to Teleport credential provider","time":"2023-03-14T21:07:15Z"}
{"file":"crypto.go:71","level":"info","msg":"start of sign process","time":"2023-03-14T21:07:15Z"}
{"file":"credential_provider_filter.go:47","level":"error","msg":"unknown message type","time":"2023-05-05T16:40:04Z","type":2}
{"file":"credential_provider.go:112","level":"warning","msg":"no PIN available","time":"2023-05-05T16:40:04Z"}
{"file":"credential_provider_filter.go:65","level":"info","msg":"valid PIN found, redirecting to Teleport credential provider","time":"2023-05-05T16:48:03Z"}
{"file":"crypto.go:71","level":"info","msg":"start of sign process","time":"2023-05-05T16:48:04Z"}
{"file":"credential_provider_filter.go:47","level":"error","msg":"unknown message type","time":"2023-05-05T16:51:26Z","type":2}
{"file":"credential_provider.go:119","level":"warning","msg":"no PIN available","time":"2023-05-05T16:51:27Z"}
{"file":"credential_provider_filter.go:65","level":"info","msg":"valid PIN found, redirecting to Teleport credential provider","time":"2023-05-05T16:57:51Z"}
{"file":"crypto.go:71","level":"info","msg":"start of sign process","time":"2023-05-05T16:57:52Z"}
{"file":"credential_provider_filter.go:65","level":"info","msg":"valid PIN found, redirecting to Teleport credential provider","time":"2023-05-10T20:13:50Z"}
{"file":"crypto.go:71","level":"info","msg":"start of sign process","time":"2023-05-10T20:13:51Z"}
{"file":"credential_provider_filter.go:65","level":"info","msg":"valid PIN found, redirecting to Teleport credential provider","time":"2023-05-10T20:14:03Z"}
{"file":"crypto.go:71","level":"info","msg":"start of sign process","time":"2023-05-10T20:14:04Z"}
{"file":"credential_provider_filter.go:47","level":"error","msg":"unknown message type","time":"2023-05-11T13:20:47Z","type":2}
{"file":"credential_provider.go:119","level":"warning","msg":"no PIN available","time":"2023-05-11T13:20:47Z"}
{"file":"credential_provider_filter.go:47","level":"error","msg":"unknown message type","time":"2023-05-12T01:17:44Z","type":2}
{"file":"credential_provider.go:119","level":"warning","msg":"no PIN available","time":"2023-05-12T01:17:44Z"}
{"file":"credential_provider_filter.go:47","level":"error","msg":"unknown message type","time":"2023-05-17T18:34:58Z","type":2}
{"file":"credential_provider.go:119","level":"warning","msg":"no PIN available","time":"2023-05-17T18:34:58Z"}
{"file":"credential_provider_filter.go:65","level":"info","msg":"valid PIN found, redirecting to Teleport credential provider","time":"2023-05-19T13:45:51Z"}
{"file":"crypto.go:71","level":"info","msg":"start of sign process","time":"2023-05-19T13:45:51Z"}
{"file":"credential_provider_filter.go:65","level":"info","msg":"valid PIN found, redirecting to Teleport credential provider","time":"2023-05-19T13:45:56Z"}
{"file":"crypto.go:71","level":"info","msg":"start of sign process","time":"2023-05-19T13:45:57Z"}
{"file":"credential_provider_filter.go:47","level":"error","msg":"unknown message type","time":"2023-05-19T13:51:53Z","type":2}
{"file":"credential_provider.go:119","level":"warning","msg":"no PIN available","time":"2023-05-19T13:51:53Z"}
{"file":"credential_provider_filter.go:65","level":"info","msg":"valid PIN found, redirecting to Teleport credential provider","time":"2023-05-26T20:55:29Z"}
{"file":"crypto.go:71","level":"info","msg":"start of sign process","time":"2023-05-26T20:55:29Z"}
{"file":"credential_provider_filter.go:65","level":"info","msg":"valid PIN found, redirecting to Teleport credential provider","time":"2023-05-26T20:55:40Z"}
{"file":"crypto.go:71","level":"info","msg":"start of sign process","time":"2023-05-26T20:55:41Z"}
{"file":"credential_provider_filter.go:65","level":"info","msg":"valid PIN found, redirecting to Teleport credential provider","time":"2023-05-26T21:00:22Z"}
{"file":"crypto.go:71","level":"info","msg":"start of sign process","time":"2023-05-26T21:00:23Z"}
{"file":"credential_provider_filter.go:65","level":"info","msg":"valid PIN found, redirecting to Teleport credential provider","time":"2023-05-26T21:10:47Z"}
{"file":"crypto.go:71","level":"info","msg":"start of sign process","time":"2023-05-26T21:10:47Z"}
{"file":"credential_provider_filter.go:65","level":"info","msg":"valid PIN found, redirecting to Teleport credential provider","time":"2023-05-30T13:56:13Z"}
{"file":"crypto.go:71","level":"info","msg":"start of sign process","time":"2023-05-30T13:56:14Z"}
{"file":"credential_provider_filter.go:65","level":"info","msg":"valid PIN found, redirecting to Teleport credential provider","time":"2023-05-30T17:32:15Z"}
{"file":"crypto.go:71","level":"info","msg":"start of sign process","time":"2023-05-30T17:32:15Z"}
{"file":"credential_provider_filter.go:65","level":"info","msg":"valid PIN found, redirecting to Teleport credential provider","time":"2023-05-30T17:32:20Z"}
{"file":"crypto.go:71","level":"info","msg":"start of sign process","time":"2023-05-30T17:32:21Z"}
```

**Comment by zmb3** [comment] 2023-05-30 19:48
Duplicate of gravitational/teleport.e#1233

**Closed by zmb3** 2023-05-30 19:48 UTC
Labels: bug, desktop-access
