### ISSUE TITLE
Kubernetes authentication for Automation

### ISSUE THREAD

**Issue by jamesmaidment** [gravitational/teleport#2985] opened 2019-09-13 17:04 UTC
When authenticating to trusted clusters using `tsh login` the maximum duration for the `~/.kube/config` certificate is 30 hours https://github.com/gravitational/teleport/blob/master/lib/defaults/defaults.go#L363

This means we are unable to use our CI servers to deploy to Kubernetes clusters automatically as the certificates require replacing every 30 hours.

Is there plans to add the ability to generate a long lived service token to be able to authenticate to federated clusters without the default expiry period (as per the existing [SSH Certificates For Automation](https://gravitational.com/teleport/docs/user-manual/#ssh-certificates-for-automation))?

**Comment by klizhentas** [comment] 2019-09-13 17:39
that's a good point, we've been thinking about it and wrote https://github.com/gravitational/teleport/issues/2825 this seems to be a duplicate

**Comment by klizhentas** [comment] 2019-09-13 17:40
I've added this to 4.2 milestone

**Comment by klizhentas** [comment] 2019-09-13 17:40
closing this as a duplicate of #2825

**Closed by klizhentas** 2019-09-13 17:40 UTC
