### ISSUE TITLE
Show TOTP secret in register UI

### ISSUE THREAD

**Issue by dsseng** [gravitational/teleport#3472] opened 2020-03-25 16:13 UTC
### Feature Request
When a user registers, the QR code with TOTP is shown. But some people would like to type the secret manually, to e.g. use a PC TOTP generator.

### Motivation
Improve compatibility and make the project more comfortable to use.

### Who's it for?
Almost anybody

**Comment by benarent** [comment] 2020-03-26 18:57
Thanks for the creating a feature request, this is reasonable. I've tagged it appropriately and we'll review when we come back to login/signup issues.

**Comment by sh7dm** [comment] 2020-03-26 19:00
If you want, I can help implementing this one! I'd like to contribute to this awesome project!

**Comment by kanersps** [comment] 2023-02-20 18:48
No activity on this for over 2 years, this seems like a rather simple UI change to do. Any reason for the extreme holdup?

**Comment by strideynet** [comment] 2024-04-26 11:07
Dupe of https://github.com/gravitational/teleport/issues/18289

**Closed by strideynet** 2024-04-26 11:07 UTC
Labels: enhancement, login/signup
