### ISSUE TITLE
Discrepancy between `Instance` system roles and configuration

### ISSUE THREAD

**Issue by espadolini** [gravitational/teleport#13788] opened 2022-06-23 11:23 UTC
Expected behavior:
The `Instance` role credentials are issued according to the services configured in an agent, and are reissued accordingly to configuration changes. 

Current behavior:
If a valid token is provided, the `Instance` credentials list all system roles available for that token; upon changing the configuration to disable or enable (assuming credentials already exist or a token for the newly added services is provided) individual services, the `Instance` credentials are not updated.

Bug details:
- Teleport version: v10.0.0-alpha.2 (b58c843dd986336b70bd8bc07ca9cd96401d3363)

**Comment by fspmarshall** [comment] 2022-08-12 03:02
Having the `Instance` cert encode the total capabilities granted to the instance is intended behavior.  I hadn't considered that a new token being used later might allow the instance to take on additional roles not granted by the initial token.  That will need to be addressed somehow.  Gonna have to give it some thought, as it seems to me that neither addition nor replacement are obviously correct.

**Comment by fspmarshall** [comment] 2024-05-31 15:10
Fixed in https://github.com/gravitational/teleport/pull/41467

**Closed by fspmarshall** 2024-05-31 15:10 UTC
Labels: bug
