### ISSUE TITLE
Provide further examples and argument options to the Go API client docs

### ISSUE THREAD

**Issue by pschisa** [gravitational/teleport#17806] opened 2022-10-25 17:48 UTC
## Applies To
https://goteleport.com/docs/api/getting-started/
https://pkg.go.dev/github.com/gravitational/teleport/api/client

## Details
Request for more robust documentation around our Go API client.  Providing more functional examples and listing arguments available would be a good start.

**Comment by zmb3** [comment] 2022-11-03 22:02
Duplicate of #5489

**Closed by zmb3** 2022-11-03 22:02 UTC
Labels: documentation, feature-request, c-nx
