### ISSUE TITLE
Github SSO to enterprise not working

### ISSUE THREAD

**Issue by mgaredia** [gravitational/teleport#10034] opened 2022-01-29 03:22 UTC
### Description

**What happened**:
I am trying to setup Github SSO using my enterprise but Unable to point to my enterprise github e.g. github.mycompany.com . It always redirects to github.com.

**What you expected to happen**:
You should be able to set github url to point to enterprise url.

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Setup oAuth App for teleport app e.g. teleport-demo.mycompany.com
2. Perform Step 3/3 SSO for Kubernetes from this link - https://goteleport.com/docs/kubernetes-access/getting-started/cluster/
3.  It redirects always to github.com instead of github.mycompany.com

### Server Details
- Teleport version (run `teleport version`): 8.1.0
- Server OS (e.g. from `/etc/os-release`):RHEL 7
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): Dedicatd
- Additional details: Kubernetes v1.22.3

### Client Details
- Tsh version (`tsh version`):
- Computer OS (e.g. Linux, macOS, Windows):
- Browser version (for UI-related issues):
- Installed via (e.g. apt, yum, brew, website download):
- Additional details:

### Debug Logs
Please include or attach debug logs, when appropriate. Obfuscate sensitive information!
- Start Teleport with --debug flag (`teleport --debug`)
- Run tsh with --debug flag (`tsh --debug`)

**Comment by stevenGravy** [comment] 2022-01-29 04:40
Currently the `lib/auth/github.go` sets the specific github urls.  If you want to fork and set this to your enterprise values that should work.  

```go

const (
	// GithubAuthURL is the Github authorization endpoint
	GithubAuthURL = "https://github.com/login/oauth/authorize"

	// GithubTokenURL is the Github token exchange endpoint
	GithubTokenURL = "https://github.com/login/oauth/access_token"

	// GithubAPIURL is the Github base API URL
	GithubAPIURL = "https://api.github.com"

	// MaxPages is the maximum number of pagination links that will be followed.
	MaxPages = 99
)
```

**Comment by evilmog** [comment] 2022-02-14 18:56
Can we make this configurable from the auth server teleport.yaml file?

**Comment by stevenGravy** [comment] 2022-02-14 18:59
No, not currently.

**Comment by ak-aozasa** [comment] 2022-08-17 06:14
Hi,
I also want!!

**Comment by zmb3** [comment] 2022-10-18 22:58
Closing as duplicate of #6340

**Closed by zmb3** 2022-10-18 22:58 UTC
Labels: bug
