### ISSUE TITLE
'admin' -> 'admin' on Leaf cluster is missing Trusted Cluster and Roles

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#3555] opened 2020-04-09 15:23 UTC
### Description

**What happened**:
After updating my testing cluster to `5.0.0-alpha-1`, I lost the ability to edit auth connectors, roles and trusted clusters.  I'm currently mapping roles to be admin - admin. 

<details>
        <summary>Role on Trusted Cluster</summary>

```yaml 
kind: role
metadata:
  id: 1586287005456534853
  name: admin
spec:
  allow:
    kubernetes_groups:
    - '{{internal.kubernetes_groups}}'
    logins:
    - '{{internal.logins}}'
    - root
    node_labels:
      '*': '*'
    rules:
    - resources:
      - role
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - auth_connector
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - session
      verbs:
      - list
      - read
    - resources:
      - trusted_cluster
      verbs:
      - list
      - create
      - read
      - update
      - delete
    - resources:
      - event
      verbs:
      - list
      - read
  deny:
    logins: null
  options:
    cert_format: standard
    enhanced_recording:
    - command
    - network
    forward_agent: true
    max_session_ttl: 30h0m0s
    port_forwarding: true
version: v3
```
</details>

<details>
        <summary>Trusted Cluster Config on Leaf</summary>

```yaml
kind: trusted_cluster
metadata:
  id: 1586290635113169468
  name: teleport5auth
spec:
  enabled: true
  role_map:
  - local:
    - admin
    remote: admin
  token: bfc55d1d51146xxx
  tunnel_addr: teleport-5.practice.io:3024
  web_proxy_addr: teleport-5.practice.io:3080
version: v2
```
</details>

### Gif recording showing behaviour. 
![Screen Recording 2020-04-09 at 08 22 AM](https://user-images.githubusercontent.com/559288/78911548-4d7e3f80-7a3b-11ea-9ec6-87eb4d39df21.gif)

**Comment by alex-kovoy** [comment] 2020-04-14 15:45
I disabled Roles, Trusted Clusters, and Auth Connectors on the leaf clusters because we cannot resolve mapped ACLs on the client side per @klizhentas  request.

**Comment by klizhentas** [comment] 2020-04-14 15:55
@benarent that's on purpose. We should not be editing admin data of the leaf clusters via this interface.

**Comment by alex-kovoy** [comment] 2020-04-14 15:56
closed by design

**Closed by alex-kovoy** 2020-04-14 15:56 UTC
Labels: bug, hornet
