### ISSUE TITLE
WebUI: Add ability to customize web terminal

### ISSUE THREAD

**Issue by ekk1** [gravitational/teleport#25055] opened 2023-04-24 06:35 UTC
What would you like Teleport to do?
Hi, I was wondering if it's possible to customize some style in the web terminal, eg font famliy and size, themes and etc.
And there are some shortcuts that seems not working on the web terminal, like Ctrl+W, which should delete a word if using a local terminal, and it will instead close the whole page when using the web terminal, it's hard to change the habit...

What problem does this solve?
I think it could help improve the experience on using the web terminal.

If a workaround exists, please include it.
Font size can be alternatively changed by zooming the whole page, but it will also change size on tabs and etc.

**Comment by zmb3** [comment] 2023-04-24 13:34
Duplicate of #15368

**Closed** 2023-04-24 13:33 UTC
Labels: feature-request
