### ISSUE TITLE
do not show expired items passed a threshold

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#27414] opened 2023-06-05 19:38 UTC
What would you like Teleport to do?

Do not show expired resources (nodes, kubernetes cluster,..) after a certain threshold.  

What problem does this solve?

Currently even if the resource like a Kubernetes server listing has expired we will continue to show it.  That confuses the users and the resource is no longer available. This can happen in environments like DynamoDB where the `ttl` is not always enforced.

**Comment by zmb3** [comment] 2023-06-05 19:41
Duplicate of #19885

**Closed by zmb3** 2023-06-05 19:41 UTC
Labels: feature-request, aws
