### ISSUE TITLE
Teleport TSH on 4.3 is getting verbose.

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#4078] opened 2020-07-18 00:44 UTC
### Description

**What happened**:
While testing the latest version, we are showing a lot of flags / commands. This is pretty overwhelming for new users, wonder if we should show a more condensed version as default. 

```
➜  teleport git:(benarent/docs/metrics) tsh
Usage: tsh [<flags>] <command> [<args> ...]

TSH: Teleport Authentication Gateway Client

Flags:
  -l, --login                    Remote host login
      --proxy                    SSH proxy address
      --user                     SSH proxy user [benarent]
      --ttl                      Minutes to live for a SSH session
  -i, --identity                 Identity file
      --cert-format              SSH certificate format
      --insecure                 Do not verify server's certificate and host name. Use only in test environments
      --auth                     Specify the type of authentication connector to use.
      --skip-version-check       Skip version checking between server and client.
  -d, --debug                    Verbose logging to stdout
      --use-local-ssh-agent      Load generated SSH certificates into the local ssh-agent (specified via $SSH_AUTH_SOCK). You can also set
                                 TELEPORT_USE_LOCAL_SSH_AGENT environment variable. Default is true.
      --enable-escape-sequences  Enable support for SSH escape sequences. Type '~?' during an SSH session to list supported sequences. Default is enabled.
  -J, --jumphost                 SSH jumphost

Commands:
  help         Show help.
  version      Print the version
  ssh          Run shell or execute a command on a remote SSH node
  join         Join the active SSH session
  play         Replay the recorded SSH session
  scp          Secure file copy
  ls           List remote SSH nodes
  clusters     List available Teleport clusters
  login        Log in to a cluster and retrieve the session certificate
  logout       Delete a cluster certificate
  status       Display the list of proxy servers and retrieved certificates

Try 'tsh help [command]' to get help for a given command.

```

**What you expected to happen**:

**Comment by stevenGravy** [comment] 2020-07-19 14:20
Agree.  The commands are more interesting. then flags.    I would suggest at least removing the flags and instruction to do `tsh help <command>' to get get flags and arguments.  we could also provide a documentation link to that version for cli. 

 I also don't think we ever use its title here "Teleport Authentication Gateway Client".   That's not used  anywhere I can find on the site.

**Comment by awly** [comment] 2020-07-20 16:25
Part of the problem is a pile of global flags.
We use [a single shared function](https://github.com/gravitational/teleport/blob/master/tool/tsh/tsh.go#L918-L1128) to build a teleport client for all commands. This makes the function itself too big, but also causes us to set global flags unnecessarily.

The only truly global flag is `-d`.

**Comment by webvictim** [comment] 2020-07-23 16:56
Another way we could handle this is to put global flags under a separate command in the same way `kubectl` does:

```console
$ kubectl 

Basic Commands (Beginner):
  create         Create a resource from a file or from stdin.
  expose         Take a replication controller, service, deployment or pod and expose it as a new Kubernetes Service
...
<snip>

Usage:
  kubectl [flags] [options]

Use "kubectl <command> --help" for more information about a given command.
Use "kubectl options" for a list of global command-line options (applies to all commands).

$ kubectl options
The following options can be passed to any command:

      --add-dir-header=false: If true, adds the file directory to the header
      --alsologtostderr=false: log to standard error as well as files
      --as='': Username to impersonate for the operation
      --as-group=[]: Group to impersonate for the operation, this flag can be repeated to specify multiple groups.
...
<snip>
```

**Comment by zmb3** [comment] 2022-11-02 16:38
I'm going to close this since we have #13780 which is more up to date.

**Closed by zmb3** 2022-11-02 16:38 UTC
Labels: ux, tsh, cli
