### ISSUE TITLE
Desktop Access for Multi-AD Domains (Parent & Subdomain)

### ISSUE THREAD

**Issue by BrianGalfond-Teleport** [gravitational/teleport#20735] opened 2023-01-25 21:01 UTC
What would you like Teleport to do?
Desktop Access does not currently work with multi-AD architectures (parent/child domains). After publishing the Teleport CA to the parent domain and attempting to discover resources located in a child domain, Teleport is unable to authenticate with the LDAP server for these suspected reasons which would need to be fixed:

- Teleport has insufficient permisisons to update the CRL in the parent, because it’s using a service account for the child
- Desktop discovery fails because we get the equivalent of an LDAP redirect when we query the root, and we don’t “follow” the redirect to the child

What problem does this solve?
Provide Desktop Access support for mutli-AD architectures.

If a workaround exists, please include it.

**Comment by zmb3** [comment] 2023-01-25 22:57
Duplicate of #20233?

**Closed** 2023-01-27 20:01 UTC
Labels: feature-request, windows, sales-onboarding, desktop-access
