### ISSUE TITLE
WebUI web session timeout is not refreshed when a user is interacting with Web App session 

### ISSUE THREAD

**Issue by smallinsky** [gravitational/teleport#32729] opened 2023-09-28 10:07 UTC
## What
When a user interacting with Teleport Web app (like Grafana), a separate web app session is created. This session is distinct from the main UI Web session. Interactions within the Grafana app will not refresh the idle timeout for the main WebUI session. In the result after `web_idle_timeout` user will be logged from the Grafana App Web session. 

##  how to reproduce the issue ? 

1. Set low `web_idle_timeout`  like: `45s`:  
```
auth_service:
  web_idle_timeout: 45s
```
2. Log into webUI and run and interact with  Grafana Web App: 

https://github.com/gravitational/teleport/assets/22402974/1dfe0254-a192-47ec-820a-22604941ce8f

3. After 45s of inactivity  in main WebUI session a user will be logout from the Grafana even is user was actively using web app

Grafana app web session was terminated due  `web_idle_timeout` timeout  triggered from main WebUI web session ( this behavior was introduced in [9124](https://github.com/gravitational/teleport/issues/9124))

## Expected behavior: 
The main webUI session timeout should be refreshed when user is interacting with one of the web app session so web_idle_timeout won't trigger user logout action.

**Comment by zmb3** [comment] 2023-09-28 13:27
Duplicate of #32616?

**Closed** 2023-09-28 15:32 UTC
Labels: bug, ui, application-access
