### ISSUE TITLE
A node should be removed from presence service when it gets disconnected

### ISSUE THREAD

**Issue by alex-kovoy** [gravitational/teleport#1001] opened 2017-05-17 21:22 UTC
Right now when a node gets disconnected, it takes ~30sec for teleport to reflect the change. We should decrease that time interval for a better user experience if possible.

**Comment by kontsevoy** [comment] 2017-06-09 19:14
@alex-kovoy won't fix. this is by design.

**Closed by kontsevoy** 2017-06-09 19:14 UTC
