### ISSUE TITLE
Fix cluster name for k8s recording proxy

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#2935] opened 2019-08-23 15:16 UTC
**What happened**: When viewing recorded kubectl exec sessions via a trusted cluster, it has the node as `remote.kube.proxy.teleport.cluster.local` rather than the actual node or cluster.

**What you expected to happen**: This should be more informative - provide information about which cluster/node where possible.

**How to reproduce it (as minimally and precisely as possible)**: View recorded k8s sessions from a trusted cluster via web UI.

<img width="1671" alt="Screen Shot 2019-05-01 at 12 12 25 PM" src="https://user-images.githubusercontent.com/897821/63603302-407d1080-c57e-11e9-832d-276003c85e3b.png">

**Comment by russjones** [comment] 2020-04-07 17:33
Duplicate of https://github.com/gravitational/teleport/issues/3528

**Comment by awly** [comment] 2020-04-23 23:06
Closing this, let's track in #3528

**Closed by awly** 2020-04-23 23:06 UTC
Labels: R1, enhancement, kubernetes
