### ISSUE TITLE
`tctl sso configure github` produces an untestable connector spec

### ISSUE THREAD

**Issue by tcsc** [gravitational/teleport#31396] opened 2023-09-03 23:55 UTC
Expected behavior:
```console
$ tctl sso configure github --id $(cat ./github.client-id) --secret $(cat ./github.secret) --teams-to-roles GGUXGXM3Q5QDN6CD,Admin,editor -r GGUXGXM3Q5QDN6CD,everyone,access | tctl sso test
INFO [CLIENT]    RedirectURL empty, resolving automatically.
INFO [CLIENT]    RedirectURL set to "https://sso.dev-trent.net:443/v1/webapi/github/callback"
If browser window does not open automatically, open it by clicking on the link:
 http://127.0.0.1:50272/40573469-96a7-48b4-b15e-e8eb1694a428
Success! Logged in as: tcsc
--------------------------------------------------------------------------------
Authentication details:
# ... and so on
```

Current behavior:
```console
$ tctl sso configure github --id $(cat ./github.client-id) --secret $(cat ./github.secret) --teams-to-roles GGUXGXM3Q5QDN6CD,Admin,editor -r GGUXGXM3Q5QDN6CD,everyone,access | tctl sso test
INFO [CLIENT]    RedirectURL empty, resolving automatically.
INFO [CLIENT]    RedirectURL set to "https://sso.dev-trent.net:443/v1/webapi/github/callback"
ERROR: Failed to create auth request. Check the auth connector definition for errors. Error: rpc error: code = Unknown desc = url scheme is empty
```

**NOTE:** The generated connector works when added to a Teleport cluster, but it looks like something is adding the missing fields when the connector is saved

Bug details:
- Teleport version: Teleport Enterprise v14.0.0-alpha.2 git:api/v14.0.0-alpha.2-0-g71aea8d go1.21.0

**Comment by tcsc** [comment] 2023-09-04 10:59
Turns out this is what happens when you use an _Enterprise_ `tctl` to test the sso connector on an Enterprise cluster.

Using an _OSS_ `tctl` on an Enterprise cluster works as expected.

**Comment by zmb3** [comment] 2023-09-04 14:42
Duplicate of #31387?

**Closed** 2023-09-05 23:44 UTC
Labels: bug, test-plan-problem, enterprise
