### ISSUE TITLE
[v.9.0] /docs/pages/setup/reference/resources.mdx   kind: token docs are missing

### ISSUE THREAD

**Issue by ramachittala** [gravitational/teleport#12138] opened 2022-04-21 06:59 UTC
## Details
Describe the documentation improvements you wish to see.

### Category

- New Feature
- Improve Existing

there is command to create the token by using `tctl create <file name>`

`kind:token` docs are missing from the dynamic resource page.  

https://goteleport.com/docs/setup/reference/resources/?scope=enterprise#dynamic-resources

**Comment by zmb3** [comment] 2022-04-21 14:45
Closing as duplicate of #11930 and #11079

**Closed by zmb3** 2022-04-21 14:45 UTC
Labels: documentation
