### ISSUE TITLE
Teleport Connect access requests does not match Web UI behavior on the same version

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#38912] opened 2024-03-03 16:00 UTC
Expected behavior:

Teleport Connect access requests would match the same fields as in the Web UI to create a access request.

Current behavior:

Teleport Connect does not include Max Access Duration and Request expiry nor pre-populate reviewers. Reviewers is probably more of a nice to have but access duration and expiration is expected. This limits being able to use Teleport Connect for the same type of requests.

Web UI:
![image](https://github.com/gravitational/teleport/assets/60704961/b6d3aa68-fc2a-4756-9239-407631908834)

Connect
![image](https://github.com/gravitational/teleport/assets/60704961/e19c0b9e-5431-4ca4-a855-28e83d2d2adb)

Bug details:
- Teleport version: 15.1.0
- Recreation steps

Attempt the same access request in Web UI and Teleport

**Comment by zmb3** [comment] 2024-03-03 21:57
Duplicate of #38017

**Closed by zmb3** 2024-03-03 21:57 UTC
Labels: bug, access-requests, teleport-connect
