### ISSUE TITLE
Machine-Id - Allow  Kubernetes Outputs to target clusters using wildcards

### ISSUE THREAD

**Issue by MarkCupitt** [gravitational/teleport#39325] opened 2024-03-14 05:38 UTC
## What would you like Teleport to do?

Machine-Id - Allow  Kubernetes Outputs to target clusters using wildcards

eg:

```
          version: v2
          auth_server: auth.authserver.com:443
          onboarding:
            join_method: token
            token: "$bottoken"
          storage:
            type: directory
            path: /var/lib/teleport/bot
          outputs:
            - type: kubernetes
              kubernetes_cluster: *   ( or cluster-=*, regex or whatever)
              destination:
                type: directory
                path: /home/ponderosa/machine-id/(use cluster name here)
```

Change this process as documented

> The output must be configured with a destination and the name of the Kubernetes cluster that should be encoded in the credentials produced by tbot. At this time, each output can only contain credentials for a single Kubernetes cluster. If your bot needs to connect to multiple Kubernetes clusters, create an output for each cluster.

## What problem does this solve?

In an environment where clusters come and go dynamically, having to specify individual outputs means that the machine-id has to be invalidated, the yaml file updated manually and then the bot redeployed. We are using machine-i in a pod deployed in a management cluster for CI/Cd and other management functions, this also means the pod will need to be restarted, thus incurring downtime

## If a workaround exists, please include it.

We deploy machine-id in a Ununtu22.04 container running as a pod in a K8's CLuster.

The deployment contains a script that runs at startup that installs teleport, mounts a secret that contains the tbot clusterlist and join token, then starts tbot running as a background process.  The script will poll for the secret being non-empty and only start tbot when the secret is complete. The secret has a list of clusters to be included. The script creates the tbot.yaml file dynamically based on the secret content.

### kustomize.yaml
```
secretGenerator:
  - name: {{ponderosa_tbot_join_secret_name}}
    namespace: {{namespace_ponderosa}}
    literals:
    - token=
    - clusterlist=
```
### deployment.yaml

```
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{namespace_ponderosa}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ponderosa
  namespace: {{namespace_ponderosa}}
spec:
  selector:
    matchLabels:
      app: ponderosa
  replicas: 1 
  template: # create pods using pod definition in this template
    metadata:
      name: ponderosa
      namespace: {{namespace_ponderosa}}
      labels:
        app: ponderosa
    spec:
      imagePullSecrets:
        - name: {{ponderosa_image_pull_secret_name}}
      securityContext:
        runAsUser: 1000
        runAsGroup: 1001
        fsGroup: 1001
      volumes: 
        - name: "tbot-join"
          secret:
            secretName: {{ponderosa_tbot_join_secret_name}}
      containers:
      - name: ponderosa
        image: {{ponderosa_image_version}}
        imagePullPolicy: Always
        volumeMounts:
          - name: "tbot-join"
            mountPath: /home/ponderosa/tbot
        env:

        livenessProbe:
          exec:
            command:
            - cat
            - /home/ponderosa/tbot.yaml
        startupProbe:
          exec:
            command:
            - cat
            - /home/ponderosa/tbot.yaml
          failureThreshold: 30
          periodSeconds: 20
        
        # readinessProbe:
        #   exec:
        #     command:
        #     - cat
        #     - /tmp/healthy
        #   initialDelaySeconds: 5
        #   periodSeconds: 5

        command: ["/bin/bash", "-c"]
        args:
        - |

Note: additional setup redacted


          echo "START: `date` "
          echo "START: `date` "
          echo "START: `date` ===================================================================================="
          echo "START: `date` Install Teleport"
          curl -s https://goteleport.com/static/install.sh | bash -s {{teleport_helm_version}}
          sudo teleport node configure --token={{teleport_node_join_token}} --proxy="auth.authserver.work" -o file
          sudo sed -i "/^\([[:space:]]*nodename: \).*/s//\1{{target.name}}-ponderosa/" /etc/teleport.yaml
          sudo teleport start --config="/etc/teleport.yaml"&
          echo "START: `date` "

          echo "START: `date` "
          echo "START: `date` ===================================================================================="
          echo "START: `date` Setup for TBOT"
          echo "START: `date` "

          echo "START: `date` WARNING: Kubernetes MAY restart the pod if you take too long to get the tbot join secret"
          echo "START: `date` To configure the join secret, update the cluster list in common/ponderosa/v1.0.1/tbot.sh, then run it"
          echo "START: `date` "
          sudo mkdir -p /var/lib/teleport/bot
          sudo chown root:root /var/lib/teleport/bot

          while true; 
            do echo "START: `date` Waving the Magic Wand and waiting for tbot configs to appear from the tbot-join secret..."
            echo "START: `date` To configure the join secret, update the cluster list in common/ponderosa/v1.0.1/tbot.sh, then run it"
            if [ -s /home/ponderosa/tbot/token ] && [ -s /home/ponderosa/tbot/clusterlist ]; then
                break
            fi
            sleep 15
          done
          echo "START: `date` Great! Got Em .. Configuring TBot Now ..."

          bottoken=$(head -n 1 /home/ponderosa/tbot/token)
          clusterlist=$(head -n 1 /home/ponderosa/tbot/clusterlist )

          echo "START: `date` Bottoken: $bottoken"
          echo "START: `date` Clusterlist: $clusterlist"
          echo "START: `date` "

          IFS=', ' read -r -a clusterarray <<< "$clusterlist"

          echo "START: `date` Creating TBot Yaml config file /home/ponderosa/tbot.yaml"

          cat <<EOF > /home/ponderosa/tbot.yaml
          version: v2
          auth_server: auth.authserver.work:443
          onboarding:
            join_method: token
            token: "$bottoken"
          storage:
            type: directory
            path: /var/lib/teleport/bot
          outputs:
          EOF

          for cluster in "${!clusterarray[@]}"
          do
          echo "START: `date` Adding Cluster: ${clusterarray[$cluster]}"
          cat <<EOF >> /home/ponderosa/tbot.yaml
            - type: kubernetes
              kubernetes_cluster: ${clusterarray[$cluster]}
              destination:
                type: directory
                path: /home/ponderosa/machine-id/${clusterarray[$cluster]}
          EOF
          done

          echo "START: `date` Yaml is Ready to go .. Starting TBot Now"
  
          #sudo /usr/local/bin/tbot start -c /home/ponderosa/tbot.yaml &> tbot_log.txt &
          sudo /usr/local/bin/tbot start -c /home/ponderosa/tbot.yaml &

          echo "START: `date` TBot Started as a background process"
          echo "START: `date` "
          echo "START: `date` "
          echo "START: `date` ===================================================================================="

Note: additional setup redacted

        resources:
          limits:
            cpu: {{ponderosa_resources_limits_cpu}}
            memory: {{ponderosa_resources_limits_memory}}
          requests:
            cpu: {{ponderosa_resources_requests_cpu}}
            memory: {{ponderosa_resources_requests_memory}}


```
### tbot.sh

Bash Script to remove old bot and create a new one, update the secret

```
#!/bin/bash

echo ""
echo ""

# Teleport ref to the cluster we will be deploying the pod on
TARGET="o2-k8s-engineering"

# this is the list of clusters that teleport can see currently
export CLUSTERLIST="d1-k8s-engineering,o2-k8s-engineering,b1-k8s-engineering,r1-k8s-engineering"

echo "Configuring TBot Startup with Teleport Machine-Id to Target CLuster: $TARGET"
echo "This script will create a new token for the TBot, and update the secret in the target cluster"


echo "Clusters: $CLUSTERLIST"
echo ""
echo "Removing old Machine Id"
tctl bots rm o2-ponderosa-robot

echo ""
echo "Creating a new Join Token ... "
export TOKEN=$(tctl bots add o2-ponderosa-robot --roles=ponderosa --logins=ponderosa --ttl 12h | sed -n -e 's/^.*The bot token: //p')

echo ""
echo "Logging into Target Deployment Cluster $TARGET"
tsh kube login $TARGET

echo ""
echo "Updating the TBot Secret in $TARGET"
kubectl patch secret tbot-join -n ponderosa  --patch="{\"stringData\": { \"token\": \"$TOKEN\",\"clusterlist\": \"$CLUSTERLIST\"  }}"

echo ""
echo "NOTE: token is only valid for one use, and will expire in 12 hours"
echo "NOTE: If you restart the pod, you wil have to run this script again"
echo ""
echo "Finished .. Pod should see the secret shortly .."
echo ""



```

**Comment by zmb3** [comment] 2024-03-14 15:51
Duplicate of #31753

**Closed by zmb3** 2024-03-14 15:51 UTC
Labels: feature-request, machine-id
