### ISSUE TITLE
enable customisation of scrollback (custom number of lines or unlimited) in `tsh` browser session

### ISSUE THREAD

**Issue by ArunNadda** [gravitational/teleport#11136] opened 2022-03-15 00:33 UTC
### What
`tsh` session in browser has default `history scroll` setting which cannot be changed. we should provide option to configure this setting (like with any other terminal apps) or even provide option to set it to infinite.

### How
might need to expose `xterm.js`?

### Why
Sometimes audit team and/or reporting teams run scripts in browser tsh terminal and need to copy all the terminal output once scripts are complete. Having option of `infinite scroll` in `browser terminal` will help in this case.

### Workaround
User can login using other OS terminals and use `unlimited scrollback` option, but if they want to use GUI terminal there is no workaround.

**Comment by zmb3** [comment] 2023-01-17 18:32
Closing as duplicate of (the newer) #20293

**Closed by zmb3** 2023-01-17 18:32 UTC
Labels: feature-request, c-af, c-ixr, c-tz
