### ISSUE TITLE
GCS Buckets for external audit log storage

### ISSUE THREAD

**Issue by au-abd** [gravitational/teleport#45385] opened 2024-08-12 15:59 UTC
What would you like Teleport to do?
Add GCS bucket support for external audit log storage

What problem does this solve?
Store audit logs in GCS buckets. Similar to what Teleport does now for AWS S3.

If a workaround exists, please include it.

**Comment by zmb3** [comment] 2024-08-12 17:27
Duplicate of #41251

**Closed by zmb3** 2024-08-12 17:27 UTC
Labels: feature-request
