### ISSUE TITLE
user "bot-X" has already been issued a renewable certificate and cannot be issued another

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#10937] opened 2022-03-08 05:30 UTC
### Description
**What happened**:

While testing Machine ID, I've ran into a few errors. I can't seem to connect as I'm getting this error message. 

```
root@ip-10-0-0-66:/home/ubuntu# tbot start --config=/etc/tbot.yaml      --data-dir=/var/lib/teleport      --destination-dir=/opt/machine-id      --token=xxx      --auth-server=teleport-9a.asteroid.earth:443
WARN [TBOT]      CLI parameters are overriding destinations from /etc/tbot.yaml config/config.go:196
INFO [TBOT]      Attempting to generate new identity from token tbot/main.go:192
INFO [AUTH]      Attempting registration via proxy server. auth/register.go:165
INFO [AUTH]      Attempting registration with auth server. auth/register.go:165
WARN [AUTH]      Joining cluster without validating the identity of the Auth Server. This may open you up to a Man-In-The-Middle (MITM) attack if an attacker can gain privileged network access. To remedy this, use the CA pin value provided when join token was generated to validate the identity of the Auth Server. auth/register.go:321
ERROR: user "bot-robot" has already been issued a renewable certificate and cannot be issued another; consider deleting and recreating the bot, Post "https://teleport.cluster.local/v2/tokens/register": remote error: tls: internal error
```

**Comment by timothyb89** [comment] 2022-03-08 18:13
This happens when (it appears as though) multiple bot instances are trying to register under the same user. In theory this should be difficult to do anymore but clearly there's some edge cases left. Per the error message, the "solution" is to delete and recreate the bot, though I'd like to put as many obstacles in the way of reaching this point as possible.

Do you have a sequence of `tctl` and `tbot` commands that reproduces the issue? What join method and token type are you using?

**Comment by Sverik** [comment] 2022-11-18 13:38
Same happens for me. First I get Machine ID working just fine. Then, after some time, some cert expires. Following this guide then: [tbot shows a "bad certificate error" at startup ](https://goteleport.com/docs/machine-id/troubleshooting/#tbot-shows-a-bad-certificate-error-at-startup), I get to the same point. Following the guide I remove the bot, then add it again.

    tctl bots rm runner-3-1
    tctl bots add runner-3-1 --roles=deploy,cluster-access-all

Then update bot's configuration and update the token. I restart the Machine ID process and this is what I get:

    ERROR: user "bot-runner-3-1" has already been issued a renewable certificate and cannot be issued another; consider deleting and recreating the bot, Get "https://teleport.cluster.local/v2/cacert": remote error: tls: internal error

**Comment by Kartograf** [comment] 2023-02-13 07:53
> Same happens for me. First I get Machine ID working just fine. Then, after some time, some cert expires. Following this guide then: [tbot shows a "bad certificate error" at startup ](https://goteleport.com/docs/machine-id/troubleshooting/#tbot-shows-a-bad-certificate-error-at-startup), I get to the same point. Following the guide I remove the bot, then add it again.
> 
> ```
> tctl bots rm runner-3-1
> tctl bots add runner-3-1 --roles=deploy,cluster-access-all
> ```
> 
> Then update bot's configuration and update the token. I restart the Machine ID process and this is what I get:
> 
> ```
> ERROR: user "bot-runner-3-1" has already been issued a renewable certificate and cannot be issued another; consider deleting and recreating the bot, Get "https://teleport.cluster.local/v2/cacert": remote error: tls: internal error
> ```

We have the same. This happens when the machine-id certificate expires. To work around the problem, we create a bot with a new name, but with a large number of bots, this can be problematic

**Comment by timothyb89** [comment] 2023-02-13 19:31
We have a feature request to help ease the reset process: #13091

If possible for your use-case, a potential workaround might be to use one of our alternative joining methods that avoids token-based joining altogether. We've supported AWS IAM-based joining since launch but have recently added support for OIDC-based joining on GitHub Actions and CircleCI. These join methods don't use renewable certificates at all and will never encounter this error.

**Comment by Sverik** [comment] 2023-02-13 19:44
Well, I'm using GitLab CI, runners are VMs in my own infra, it doesn't look
like it would be an option. Still, thanks for the suggestion, and good to
hear that new possibilities are implemented.

E, 13. veebruar 2023 21:31 Tim Buckley ***@***.***> kirjutas:

**Comment by timothyb89** [comment] 2023-02-13 20:40
In that instance, we have similar support for GitLab in the works: https://github.com/gravitational/teleport/issues/17059

**Comment by strideynet** [comment] 2023-05-25 15:36
Closed by https://github.com/gravitational/teleport/issues/26885

**Closed by strideynet** 2023-05-25 15:36 UTC
Labels: bug, machine-id
