### ISSUE TITLE
Add a web_idle_timeout to log people out of the web UI after a customisable time period

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#4574] opened 2020-10-16 18:36 UTC
### Feature Request
`max_session_ttl` is currently tied to the “certificate” expiration time, which may be several hours. `client_idle_timeout` covers disconnecting interactive SSH/Kubernetes sessions which are left idle. There is a use case for a separate `web_idle_timeout` which will automatically log the web UI out after a period of inactivity and force a new sign-in.

It's not possible to use `max_session_ttl` to limit this (as is the current recommendation) because enforcing `disconnect_expired_cert: true` and having a required 1 hour minimum `max_session_ttl` to support longer debugging sessions means that the web UI can sit signed in and idle for up to an hour (which is a risk)

### Motivation
Users may leave their browsers signed in with powerful roles and walk away from their computers, leaving them unlocked. A cluster administrator would like a safeguard against that happening by forcing them to log out after being idle for a configurable period of time.

### Who's it for?
OSS User, Pro, Enterprise

**Comment by robertogiordani** [comment] 2021-02-11 13:50
@russjones any ETA?

**Comment by travelton** [comment] 2021-05-18 14:59
@russjones This seems to be a duplicate of #6092, is that correct?

**Comment by russjones** [comment] 2021-07-16 02:21
Let's make this ticket specifically about the Web UI part of the implementation.

**Closed** 2021-09-11 01:18 UTC
Labels: feature-request, c-ib
