### ISSUE TITLE
Support IAM joining for trusted clusters

### ISSUE THREAD

**Issue by Aharic** [gravitational/teleport#12287] opened 2022-04-28 00:45 UTC
What would you like Teleport to do?

Right now users can use either a dynamic or static token to join two teleport clusters in a trust relationship, but they cannot utilize methods like a ec2 tokens or those used by our auto-join features. 

What problem does this solve?

Ability to easily create and recreate trusted clusters without having to set static tokens (insecure) or generate dynamic tokens whenever a trusted cluster relationship needs to be created or re-established (requires additional planning in CI/CD pipelines). This is especially burdensome whenever a trusted-cluster that was created with a dynamic token needs to be updated with new role mappings because it requires the trust to be fully recreated.

If a workaround exists, please include it.

Using static or dynamic tokens.

**Comment by zmb3** [comment] 2022-06-10 16:00
Closing as duplicate of #12226

**Closed by zmb3** 2022-06-10 16:00 UTC
Labels: feature-request, c-nt
