### ISSUE TITLE
[tsh] Error when trying to list nodes when using identity file

### ISSUE THREAD

**Issue by FireDrunk** [gravitational/teleport#22774] opened 2023-03-08 12:39 UTC
Expected behavior:
List of nodes

Current behavior:
Error regarding SSH Key handshake

Bug details:
- Teleport version 12.0.4

Recreation:
- Create an identity file
- Use it to `ssh`
- Use it to `ls`

Example:
```shell
❯ tsh -i ./signed.auth --proxy <server> ssh user@server
[user@server ~]$ 

❯ tsh -i ./signed.auth --proxy <server> ls
ERROR: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
```
It seems something is going wrong during argument parsing.
When using tsh login interactively, and using `tsh ls` the results are fine:

```shell
❯ tsh ls
Node Name                      Address        Labels                                                                                                                                                     
------------------------------ -------------- ---------------------------------------------------------------------------------------------------------------------------------------------------------- 
server1                      ⟵ Tunnel       hostname=localhost.localdomain,teleport.internal/resource-id=139f2958-cf5b-4ecc-9126-0c4b310cbef1                               
server2                      ⟵ Tunnel       environment=acc,hostname=localhost.localdomain,teleport.internal/resource-id=89919a19-2d56-421c-801d-fdfbad03eef2                  
vm-sandbox-shared-teleport-001 127.0.0.1:3022 hostname=vm-sandbox-shared-teleport-001,azure/CostCenter=,azure/CreatedBy=terraform,azure/Environment=sandbox,azure/Service=shared
```

**Comment by FireDrunk** [comment] 2023-03-08 14:28
This might be related to [#22466](https://github.com/gravitational/teleport/issues/22466)

**Comment by strideynet** [comment] 2023-03-08 15:50
> This might be related to [#22466](https://github.com/gravitational/teleport/issues/22466)

Yup - I'd say that's the same root cause. I'll close this ticket as a dupe.

**Closed by strideynet** 2023-03-08 15:50 UTC
Labels: bug
