### ISSUE TITLE
`github` auth preference with no connectors breaks `tbot proxy app` and `tsh -i ... proxy app`

### ISSUE THREAD

**Issue by timothyb89** [gravitational/teleport#16107] opened 2022-09-02 17:30 UTC
Expected behavior:

`tbot proxy app` should work regardless of server auth configuration

Current behavior:

A lingering `auth_service.authentication.type` set to `github` breaks proxies:
```
$ tbot proxy --destination-dir=/opt/machine-id --proxy=<...> app --port=1234 example-app

ERROR: no github connectors found

ERROR: unable to execute tsh
executing `tsh proxy`
exit status 1
```

Bug details:
- Teleport version: 10.1
- Recreation steps
- Debug logs

**Comment by webvictim** [comment] 2022-09-13 16:02
This is the same for `saml` and `oidc` too. It also breaks `tsh login`.

**Comment by strideynet** [comment] 2023-12-01 18:14
Closed as duplicate of https://github.com/gravitational/teleport/issues/34523

**Closed by strideynet** 2023-12-01 18:14 UTC
Labels: bug, tsh, machine-id
