### ISSUE TITLE
SFTP failure events are not emitted into the audit log

### ISSUE THREAD

**Issue by bl-nero** [gravitational/teleport#31417] opened 2023-09-04 16:59 UTC
Expected behavior:
After using `tsh scp`, I'd expect to see events `T3004I`, `T3004E`, `T3005I`, `T3005E` to be visible in the audit log.

Current behavior:
None of these events are emitted — neither for upload or download, and neither for successes or failures.

Bug details:
- Teleport version: 14.0.0-alpha.2
- Recreation steps
1. Sign in as a user whose role has the `ssh_file_copy` flag set to `true`. Use `tsh scp` to upload files back and forth.
2. Repeat with a user whose role has the `ssh_file_copy` flag set to `false`.
3. Search the audit log for any of the event codes mentioned in the _Expected behavior_ section.

**Comment by zmb3** [comment] 2023-09-04 22:02
This is likely expected behavior and an out of date test plan. tsh scp was updated to use SFTP instead of SCP several releases ago. 

Do you see SFTP events in the audit log?

**Comment by bl-nero** [comment] 2023-09-05 10:57
@zmb3 I have just tested the same scenarios on a cluster that is a fresh v14 (previously, I was using an upgraded case, v13->v14). The "freshly operating" v14 adds some `SFTP Open` and `SFTP Setstat`, and `User [restricted] requested subsystem [sftp]` events (only in success scenarios). However, I can still see no equivalent log entries on the upgraded cluster (searching for "sftp" in the audit log).

**Comment by zmb3** [comment] 2023-09-05 17:54
@capnspacehook can you double check this and determine whether there is a regression here or whether the test plan just needs to be updated to account for SFTP?

**Comment by capnspacehook** [comment] 2023-09-05 22:39
I can't reproduce your behavior, on both an upgraded cluster and a new cluster I see SFTP events. No audit events are emitted when a user who isn't allowed to copy files attempts to, but that's not a regression but possible a different issue.

**Comment by zmb3** [comment] 2023-09-05 22:48
> but that's not a regression but possible a different issue

Let's file an issue for that. One of the major reasons you'd want an audit log is to detect when people try to do things they aren't permitted to.

**Comment by capnspacehook** [comment] 2024-01-20 05:20
Closing in favor of https://github.com/gravitational/teleport/issues/36820

**Closed by capnspacehook** 2024-01-20 05:20 UTC
Labels: bug, test-plan-problem, audit-log, sftp
