### ISSUE TITLE
Remote tctl fails when /etc/teleport.yaml is present

### ISSUE THREAD

**Issue by zmb3** [gravitational/teleport#26691] opened 2023-05-22 15:47 UTC
When attempting to run remote tctl on a host with an `/etc/teleport.yaml` file, users are presented with the following error:

```
ERROR: tctl must be either used on the auth server or provided with the identity file via --identity flag
```

This occurs even when there are identity files in the active tsh profile.

While it's not super common for people to attempt to run `tctl` from a teleport instance which is not the auth server, it does happen and should still work if tsh credentials are available.

This situation could be made worse by the upcoming "connect my computer" feature for the Teleport Team plan, as remote tctl will be required to administer the cluster and connecting your computer may place a teleport.yaml file on the system.

**Comment by stevenGravy** [comment] 2023-05-22 21:02
Happens often when folks are trying out Teleport and do a local installation and then moving to a hosted version.

**Comment by strideynet** [comment] 2023-05-25 10:14
Is this a dupe of https://github.com/gravitational/teleport/issues/25620 ?

**Closed** 2023-05-25 14:49 UTC
Labels: bug, tctl
