### ISSUE TITLE
teleport-operator managed TeleportRole prevents the use of resources discovered by the teleport-agent

### ISSUE THREAD

**Issue by dmitry-mightydevops** [gravitational/teleport#33511] opened 2023-10-16 09:56 UTC
Expected behavior:
After applying the proper role I should be able to see the resources discovered by the teleport-agent in the GUI

Current behavior:
Role created, databases/apps are not listed in the GUI.

Detailed info is in the discussion:
https://github.com/gravitational/teleport/discussions/33103

Bug details:
- Teleport version: 
```sh
Teleport v14.0.1 git:api/v14.0.1-0-g2108b20 go1.21.1
```
- Recreation steps
https://github.com/gravitational/teleport/discussions/33103
- Debug logs

**Comment by hugoShaka** [comment] 2023-11-09 20:39
Duplicate of https://github.com/gravitational/teleport/issues/27938

**Closed by hugoShaka** 2023-11-09 20:39 UTC
Labels: bug
