### ISSUE TITLE
Metadata validation fail

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#7045] opened 2021-05-26 05:55 UTC
```
helm install teleport-agent ./teleport-kube-agent --set kubeClusterName=${CLUSTER?}\
>     --set proxyAddr=${PROXY?} --set authToken=${TOKEN?} --create-namespace --namespace=cookie
Error: rendered manifests contain a resource that already exists. Unable to continue with install: PodSecurityPolicy "teleport-agent" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-namespace" must equal "cookie": current value is "teleport-agent"
```

**Comment by webvictim** [comment] 2021-05-26 13:41
I think this is expected because you're trying to install two agents into the same cluster. If you want this to succeed, you'll need to override the `clusterRoleName` and `clusterRoleBindingName` to match the name of the release:

```
helm install teleport-agent ./teleport-kube-agent \
  --create-namespace \
  --namespace=cookie \
  --set kubeClusterName=${CLUSTER?} \
  --set proxyAddr=${PROXY?} \
  --set authToken=${TOKEN?} \
  --set clusterRoleName=teleport-agent \
  --set clusterRoleBindingName=teleport-agent
```

We can theoretically fix this by just hardcoding the names of `clusterRole`, `clusterRoleBinding` and `serviceAccount` to the release name (which must be unique) but I figure @awly had a reason for exposing the values as he did: https://github.com/gravitational/teleport/blob/master/examples/chart/teleport-kube-agent/values.yaml#L69-L74

**Comment by webvictim** [comment] 2021-05-26 18:31
I spoke to @awly and he can't remember the reason for exposing the values. If it was intended that it would allow advanced users to provision their own objects, it wouldn't have worked as expected because the chart will fail to install when it can't create the objects itself anyway. As such, #7057 contains a fix for this issue.

**Closed** 2021-06-09 20:14 UTC
Labels: bug, helm
