### ISSUE TITLE
Yubikey error blocks using Teleport Connect

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#30030] opened 2023-08-04 12:18 UTC
Expected behavior:

An error would allow dismissing the issue or at least give further information.

Current behavior:

After upgrading to 13.3.1 experiencing a lockout to access any functionality.  Had to remove the user data directory. I have backed up the user data dir.  Putting it back in the error is repeated.

![image](https://github.com/gravitational/teleport/assets/60704961/80e49a81-2bdc-47d2-b25c-10f7d099574e)

Bug details:
- Teleport version: 13.3.1
- Recreation steps

I don't know exactly what's causing this. I can share the data dir which repeatedly causes this.

**Comment by gzdunek** [comment] 2023-08-04 14:41
The problem happens because we have `Storage.ReadAll()` in `StartHeadlessWatchers()` which is called during the app initialization. `Storage.ReadAll()` returns an error when ybukiey is not connected. We should catch this error instead of crashing the app.

The workaround is to have yubikey connected when starting the app.

**Comment by ravicious** [comment] 2023-08-07 08:45
@stevenGravy Do you use [hardware-based private keys](https://goteleport.com/docs/access-controls/guides/hardware-key-support/)?

@gzdunek What should we do after catching the error? `Storage.ReadAll` is mostly used to get the list of all profiles on startup, which lets us see which profiles have valid keys and which require login. I suppose in this situation we could consider the profile to not have a valid key and force the user to log in again?

@Joerger Do you know what's the state of hardware-based PK support in Connect? I looked at [RFD 80](https://github.com/gravitational/teleport/blob/master/rfd/0080-hardware-key-support.md) and it seems like Connect supports only the login happy path and ssh, but no db proxies, right?

**Comment by gzdunek** [comment] 2023-08-07 10:12
>@gzdunek What should we do after catching the error? Storage.ReadAll is mostly used to get the list of all profiles on startup, which lets us see which profiles have valid keys and which require login. I suppose in this situation we could consider the profile to not have a valid key and force the user to log in again?

Yes, it seems to me that it should work this way, when the user tries to interact with that profile, they will be prompted to log in again (as usual).

**Comment by stevenGravy** [comment] 2023-08-08 01:35
> @stevenGravy Do you use [hardware-based private keys](https://goteleport.com/docs/access-controls/guides/hardware-key-support/)?
> 
> @gzdunek What should we do after catching the error? `Storage.ReadAll` is mostly used to get the list of all profiles on startup, which lets us see which profiles have valid keys and which require login. I suppose in this situation we could consider the profile to not have a valid key and force the user to log in again?
> 
> @Joerger Do you know what's the state of hardware-based PK support in Connect? I looked at [RFD 80](https://github.com/gravitational/teleport/blob/master/rfd/0080-hardware-key-support.md) and it seems like Connect supports only the login happy path and ssh, but no db proxies, right?

I had been trying hardware based keys for a period. I had taken it off the user's roles at one point.

**Comment by zmb3** [comment] 2024-06-25 16:34
@ravicious @Joerger can we close this as a duplicate of #34415?

**Comment by Joerger** [comment] 2024-06-25 20:22
@zmb3 This is separate - We need to add some UX improvements here when the user removes the yubikey where their private key is stored. The user should be prompted with a better error message to either log out or connect their yubikey.

**Closed** 2024-10-23 07:39 UTC
Labels: bug, teleport-connect, c-cpd
