### ISSUE TITLE
add windows desktop role to teleport-kube-agent chart

### ISSUE THREAD

**Issue by programmerq** [gravitational/teleport#23111] opened 2023-03-15 13:56 UTC
### What would you like Teleport to do?

Add support for the windows desktop service to the teleport-kube-agent chart

### What problem does this solve?

This would allow users to run the windows service via the chart, similar to how they can deploy a database, kube, or app access agent via the chart

### If a workaround exists, please include it.

fork the chart or use a different deploy method

**Comment by zmb3** [comment] 2023-03-15 17:22
Duplicate of #15956 and #22402.

**Closed by zmb3** 2023-03-15 17:22 UTC
Labels: feature-request, helm
