### ISSUE TITLE
Improve error message on node joining a cluster with existing state

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#10108] opened 2022-02-02 17:22 UTC
### Description

**What happened**:

* Node has been joined to existing cluster.
* User has tried to join a node to a different cluster.

Node has failed and reported an unclear error

```bash
User Message: Get &#34;https://teleport.cluster.local/v2/domain&#34;: x509: certificate is valid for *.teleport-staging.example.com, teleport-staging.example.com, not abc1234fgwaetfaegfa.teleport.cluster.local] service/connect.go:867
```

```bash
DEBU [PROC:1]    Failed to connect to Auth Server through tunnel. error:[Get "https://teleport.cluster.local/v2/domain": ssh: handshake
failed: ssh: no authorities for hostname: example.com:443] proxy-addr:example.com:443 service/connect.go:868

ERRO [PROC:1]    Node failed to establish connection to cluster: Failed to connect to Auth Server directly or over tunnel, no methods remaining.. service/connect.go:68
```

Instead, a node should report more clear error:

```
This node is already a member of a cluster `cluster-name`. To re-join the node, remove `/var/lib/teleport` and try again.
```

### Server Details
- Teleport version (run `teleport version`):
- Server OS (e.g. from `/etc/os-release`):
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware):
- Additional details:

### Client Details
- Tsh version (`tsh version`):
- Computer OS (e.g. Linux, macOS, Windows):
- Browser version (for UI-related issues):
- Installed via (e.g. apt, yum, brew, website download):
- Additional details:

### Debug Logs
Please include or attach debug logs, when appropriate. Obfuscate sensitive information!
- Start Teleport with --debug flag (`teleport --debug`)
- Run tsh with --debug flag (`tsh --debug`)

**Comment by webvictim** [comment] 2022-02-04 21:15
This is pretty much a duplicate of our favourite [#/var/lib/teleport](https://github.com/gravitational/teleport/issues/2838)

**Closed** 2022-04-05 17:57 UTC
Labels: bug, getting-started, c-pg
