### ISSUE TITLE
Easier way to switch current cluster

### ISSUE THREAD

**Issue by felixdesouza** [gravitational/teleport#11646] opened 2022-03-31 22:36 UTC
### What
I work with multiple clusters, and switching between them is a bit annoying. It's nice that once you've logged in, the last logged in cluster is the active cluster. But if I have multiple valid sessions to different clusters, the only way to work against a different cluster is to provide the `--cluster` argument. There is no way to switch the "active" cluster, without just logging in again, which interrupts the flow.

### How
Have a command `tsh activate <cluster-name>` or something of its sort. That would just set the current cluster to whatever is in `tsh status` and if it has expired, then just do a login flow. 

Alternatively, have a `tsh login` not bother initiating a new login flow if the token is currently valid.

### Why
Quality of life changes really.

### Workaround
The workaround is to set `--cluster` and just have aliases, but it feels weird for this to be partially stateful.

**Comment by zmb3** [comment] 2022-04-01 16:40
Thanks for filing this @felixdesouza - it's something we've recently been discussing.

I'm going to close this as a duplicate of #10956, feel free to follow that issue for progress.

**Closed by zmb3** 2022-04-01 16:40 UTC
Labels: feature-request, tsh
