### ISSUE TITLE
Flaky tests

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#450] opened 2016-06-09 19:40 UTC
I've encountered several issues when running tests for Teleport:

Flaky tests
---------------

Here are the tests that were failing for me:

```
----------------------------------------------------------------------
FAIL: sshserver_test.go:198: SrvSuite.TestShell

sshserver_test.go:225:
    c.Assert(strings.Contains(string(buf), "150"), Equals, true)
... obtained bool = false
... expected bool = true

time="0001-01-01T00:00:00Z" level=info msg="ssh.server: client disconnected" component=node fields=map[login:jenkins teleportUser:jenkins id:27 local:127.0.0.1:51655 remote:127.0.0.1:35657] file="_obj_test/sshserver.go:820" 
time="0001-01-01T00:00:00Z" level=info msg="session.Close(87492ba2-2dff-11e6-8767-0242ac110002)" file="_obj_test/sess.go:435" 
time="0001-01-01T00:00:00Z" level=info msg="party.io.copy(874a448f-2dff-11e6-8767-0242ac110002) closed" component=node fields=map[local:127.0.0.1:51655 remote:127.0.0.1:35657 login:jenkins teleportUser:jenkins id:27] file="_obj_test/sess.go:789" 
time="0001-01-01T00:00:00Z" level=info msg="SSH server 127.0.0.1:51655 exited" file="sshutils/server.go:144" 
time="0001-01-01T00:00:00Z" level=info msg="party[874a448f-2dff-11e6-8767-0242ac110002].Close()" component=node fields=map[remote:127.0.0.1:35657 login:jenkins teleportUser:jenkins id:27 local:127.0.0.1:51655] file="_obj_test/sess.go:958" 
time="0001-01-01T00:00:00Z" level=info msg="session.close(writer=874a448f-2dff-11e6-8767-0242ac110002)" file="_obj_test/sess.go:447" 
time="0001-01-01T00:00:00Z" level=info msg="session.io.copy() stopped" file="_obj_test/sess.go:548" 
time="0001-01-01T00:00:00Z" level=info msg="session.removeParty(sess(127.0.0.1:35657->127.0.0.1:51655, user=jenkins, id=27) party(id=874a448f-2dff-11e6-8767-0242ac110002))" component=node fields=map[local:127.0.0.1:51655 remote:127.0.0.1:35657 login:jenkins teleportUser:jenkins id:27] file="_obj_test/sess.go:604" 
time="0001-01-01T00:00:00Z" level=debug msg="PTY is closed" file="_obj_test/term.go:176" 
OOPS: 14 passed, 1 FAILED
--- FAIL: TestSrv (5.53s)
```

```
time="0001-01-01T00:00:00Z" level=info msg="127.0.0.1:34224 ready to accept connections" file="_obj_test/server.go:151" 
time="0001-01-01T00:00:00Z" level=info msg="127.0.0.1:34224 accepted connection from 127.0.0.1:43830" file="_obj_test/server.go:175" 

----------------------------------------------------------------------
FAIL: server_test.go:47: ServerSuite.TestStartStop

server_test.go:64:
    c.Assert(err, IsNil)
... value *errors.errorString = &errors.errorString{s:"ssh: handshake failed: EOF"} ("ssh: handshake failed: EOF")

OOPS: 0 passed, 1 FAILED
--- FAIL: TestSSHUtils (0.08s)
FAIL
coverage: 16.9% of statements
FAIL    github.com/gravitational/teleport/lib/sshutils  0.153s
=== RUN   TestSCP
time="0001-01-01T00:00:00Z" level=info msg="SCP: serving sink" file="_obj_test/scp.go:227" 
```

```
o test -v github.com/gravitational/teleport/integration/...
=== RUN   TestIntegrations
Connection to 127.0.0.1:40538 closed from the remote side

----------------------------------------------------------------------
FAIL: integration_test.go:266: IntSuite.TestInteractive

integration_test.go:287:
    c.Assert(err, check.IsNil)
... value *trace.TraceErr = &trace.TraceErr{Err:(*net.OpError)(0xc820173ae0), Traces:trace.Traces{trace.Trace{Path:"/gopath/src/github.com/gravitational/teleport/lib/client/api.go", Func:"github.com/gravitational/teleport/lib/client.(*TeleportClient).ConnectToProxy", Line:803}, trace.Trace{Path:"/gopath/src/github.com/gravitational/teleport/lib/client/api.go", Func:"github.com/gravitational/teleport/lib/client.(*TeleportClient).SSH", Line:272}}, Message:"dial tcp 127.0.0.1:33598: getsockopt: connection refused", DebugMessage:""} ("dial tcp 127.0.0.1:33598: getsockopt: connection refused")

no active tunnels to cluster site-A
Failed connecting to cluster site-A: ssh: subsystem request failed
OOPS: 4 passed, 1 FAILED
--- FAIL: TestIntegrations (17.15s)
FAIL
exit status 1
FAIL	github.com/gravitational/teleport/integration	17.169s
```

I've got success rate about 3/7 on running tests

## Hanging tests

`make test` hangs all the time. Only `cd build.assets && make test` works. I would expect `make test` to work too.

**Comment by kontsevoy** [comment] 2016-06-12 22:04
@klizhentas: I am having difficulty reproducing this.
Can you please attach the following:

- your `.bashrc` and `.profile`
- output of `env` command
- output of `go env`
- output of `sudo netstat -lptne`

Thanks.

**Comment by klizhentas** [comment] 2016-06-12 22:22
It's intermittent. These are failed tests from Jenkins runs - you can see them all in Jenkins logs

**Comment by kontsevoy** [comment] 2016-06-12 22:25
I have never seen the latter two errors in Jenkins. In fact I have never seen them on any of the machines where we build Teleport regularly. But you started seeing this after you moved to a new laptop. Please send me the data I requested.

**Comment by kontsevoy** [comment] 2016-06-14 01:55
Yo. I fixed the 1st issue, but the latter two are specific to your laptop environment.

**Comment by kontsevoy** [comment] 2016-07-01 21:49
Closing for now since we haven't seen failed tests on Jenkins in a while

**Closed by kontsevoy** 2016-07-01 21:49 UTC
Labels: bug
