### ISSUE TITLE
Audit log says role created while changing the role policy

### ISSUE THREAD

**Issue by nivasomu** [gravitational/teleport#23257] opened 2023-03-17 19:42 UTC
Expected behavior:
While making changes to the role definition in the teleport the audit log is supposed to log as `User role changed` or `User role modified`

Current behavior:
For every change to the role definition in the teleport, the audit log logs it as `User role created` this brings confusion to the user. 

<img width="344" alt="Screenshot 2023-03-18 at 12 35 24 AM" src="https://user-images.githubusercontent.com/13088331/226002635-1a007944-ba27-423a-8f55-eb4a5e09604f.png">

Bug details:
- Recreation steps
    - Make a change to the role and check the audit logs

**Comment by zmb3** [comment] 2023-06-08 17:49
Duplicate of #18489

**Closed by zmb3** 2023-06-08 17:49 UTC
Labels: bug, c-va
