### ISSUE TITLE
Enhanced Disk Recording Mode not working

### ISSUE THREAD

**Issue by scottpgallagher** [gravitational/teleport#16843] opened 2022-09-29 15:54 UTC
Expected behavior:
When setting 
`    enhanced_recording:
    - disk`
there would be audit events in the Teleport audit logs.

Current behavior:
When setting 
`    enhanced_recording:
    - disk`
there is nothing in the Teleport audit logs that relate to disk events

Bug details:
- Teleport version: 10.2.6
- Recreation steps: Enable the above in a role, login to a ssh system and review Teleport audit logs
- Debug logs

**Comment by zmb3** [comment] 2022-09-29 17:07
Duplicate of #16053?

**Closed** 2022-09-29 17:22 UTC
Labels: bug, bpf
