### ISSUE TITLE
Research and adjust RPM instructions to avoid warnings

### ISSUE THREAD

**Issue by alexfornuto** [gravitational/teleport#19611] opened 2022-12-22 17:04 UTC
Our `install-linux.mdx` partial includes instructions for installing Teleport enterprise from an RPM package we provide. This method creates warnings in the output of the install command.

The hope is to find a way to install our rpm release without creating these warnings, possibly by first importing our public key to the target system.

        I'm not familiar with RPM, but if there's away to do this that doesn't create a warning that would be preferable. Do we just need to verify it against Teleport's public key?

_Originally posted by @zmb3 in https://github.com/gravitational/teleport/pull/17498#discussion_r1054901983_

**Comment by zmb3** [comment] 2022-12-23 04:55
https://forums.opensuse.org/t/problem-with-warning-nokey-while-installing-a-source-rpm/75326

**Comment by ptgott** [comment] 2024-08-28 17:48
Closing this issue since `install-linux.mdx` [no longer includes the warning](https://github.com/gravitational/teleport/blob/595ad004144e23f013f71070de35313eb140d9e5/docs/pages/includes/install-linux.mdx). Confirmed that the one-line installation script runs without the warning on a Rocky Linux container when installing a Teleport RPM package.

**Closed by ptgott** 2024-08-28 17:48 UTC
Labels: documentation, installation
