### ISSUE TITLE
Session playing denied in leaf cluster with roles where participant logic

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#32029] opened 2023-09-17 13:55 UTC
Expected behavior:

A user can play sessions with the `where` clause for sessions they participated in as they do in the root cluster.

```yaml
    - resources:
      - session
      verbs:
      - read
      - list
      where: contains(session.participants, user.metadata.name)
```

Current behavior:

Users are denied playing sessions in leaf nodes they participated in.

Bug details:
- Teleport version: 15 master and 13 confirmed. Assume 14 as well.
- Recreation steps

1. Create a OOTB root and leaf cluster. 
2. Assign a user the pre set role `access`. 
3. Create a trusted cluster mapping from leaf to root with `access` mapped to `access`
4. Create a user at root with logins `root` with `access` role
5. Access a SSH node in the leaf
6. No sessions will list in the leaf view
7. Attempt to play from the audit log listing in the leaf

- Debug logs

```

2023-09-17T09:48:56-04:00             DEBU Mapped roles [access] of remote user "steven" to local roles [access] and traits map[aws_role_arns:[] azure_identities:[] db_names:[] db_roles:[] db_users:[] gcp_service_accounts:[] host_user_gid:[] host_user_uid:[] kubernetes_groups:[] kubernetes_users:[] logins:[root -teleport-internal-join] windows_logins:[]]. services/access_checker.go:1097
2023-09-17T09:48:56-04:00 [AUDIT]     DEBU SearchSessionEvents(0001-01-01 00:00:00 +0000 UTC, 2023-09-17 13:48:56.147375 +0000 UTC, 500) events/auditlog.go:917
2023-09-17T09:48:56-04:00 [AUDIT]     DEBU SearchSessionEvents(0001-01-01 00:00:00 +0000 UTC, 2023-09-17 13:48:56.147375 +0000 UTC, order=0, limit=500, cond="equals(sid, \"8226c91f-eb88-43cc-b572-33322074c0b3\")") events/filelog.go:364
2023-09-17T09:48:56-04:00 [AUDIT]     DEBU Called findInFile(/tmp/leaf/log/c453cc7f-3a50-4504-b5ae-6b2fc722f19e/2023-09-17.00:00:00.log, {eventTypes:[session.end windows.desktop.session.end] condition:0x10303f870}). events/filelog.go:531
2023-09-17T09:48:56-04:00 [RBAC]      INFO Access to read session in namespace default denied to roles access,default-implicit-role: no allow rule matched. services/role.go:2917
```

**Comment by zmb3** [comment] 2023-09-17 18:28
Duplicate of #12324?

**Closed** 2023-09-17 18:28 UTC
Labels: bug, trusted-cluster, audit-log
