### ISSUE TITLE
Include email attribute in SAML response when using Teleport as an IdP.

### ISSUE THREAD

**Issue by vip8439** [gravitational/teleport#30589] opened 2023-08-16 23:09 UTC
What would you like Teleport to do? Include an assertion for email address. For example:
```
<saml:Attribute Name="User.Email"
 NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:unspecified">
 <saml:AttributeValue xsi:type="xs:anyType">testuser@youremail.com
 </saml:AttributeValue>
 </saml:Attribute>
```

What problem does this solve? Allows me to use Teleport as an IdP for Slack (the email attribute is required in the SAML response).

If a workaround exists, please include it. None

**Comment by zmb3** [comment] 2024-02-04 02:32
Duplicate of #23128

**Closed by zmb3** 2024-02-04 02:32 UTC
Labels: feature-request, sso, saml-idp
