### ISSUE TITLE
Weird state when adding a user to Teleport OSS with `--roles` specified

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#6342] opened 2021-04-07 20:48 UTC
### Description

**What happened**:

Adding a user to a Teleport OSS cluster with the new Enterprise-like `tctl users add gus --roles=admin` syntax puts the user in a weird state where they don't have any logins associated with them. 

Using the old `tctl users add gus root` syntax prints a deprecation warning, but works as expected.

**What you expected to happen**:

Both formats should work the same.

### Reproduction Steps

Create a user with the Enterprise syntax:
```
~/go/src/github.com/gravitational/teleport(gus/helm/improvements-2) » kubectl exec deploy/teleport -- tctl users add gus --roles=admin
User "gus" has been created but requires a password. Share this URL with the user to complete user setup, link is valid for 1h:
https://gke.teleportdemo.net:443/web/invite/4a8ab46003978921f435488c44ae1091

NOTE: Make sure gke.teleportdemo.net:443 points at a Teleport proxy which users can access.
```

Set up in the browser, then try to log in with `tsh login` - see the weird `-teleport-nologin` entry:

```
~/go/src/github.com/gravitational/teleport(gus/helm/improvements-2) » tsh login --proxy=gke.teleportdemo.net:443
Enter password for Teleport user gus:
Enter your OTP token:
> Profile URL:        https://gke.teleportdemo.net:443
  Logged in as:       gus
  Cluster:            gke.teleportdemo.net
  Roles:              admin*
  Logins:             -teleport-nologin-9ff4e9fe-28b1-464c-919f-2f1aa4f5fbaf
  Kubernetes:         enabled
  Kubernetes cluster: "gke.teleportdemo.net"
  Valid until:        2021-04-08 05:29:34 -0300 ADT [valid for 12h0m0s]
  Extensions:         permit-agent-forwarding, permit-port-forwarding, permit-pty

~/go/src/github.com/gravitational/teleport(gus/helm/improvements-2) » tctl get user/gus
kind: user
metadata:
  id: 1617827102752982792
  name: gus
spec:
  created_by:
    time: "2021-04-07T20:25:02.709214033Z"
    user:
      name: c5425483-15d9-4038-9f2b-61a4a0bc4aa8.gke.teleportdemo.net
  expires: "0001-01-01T00:00:00Z"
  roles:
  - admin
  status:
    is_locked: false
    lock_expires: "0001-01-01T00:00:00Z"
    locked_time: "0001-01-01T00:00:00Z"
  traits:
    logins: null
version: v2
```

Remove user and re-add using old syntax:

```
~/go/src/github.com/gravitational/teleport(gus/helm/improvements-2*) » kubectl exec deploy/teleport -- tctl users rm gus
User "gus" has been deleted

~/go/src/github.com/gravitational/teleport(gus/helm/improvements-2*) » kubectl exec deploy/teleport -- tctl users add gus root
NOTE: Teleport 6.0 added RBAC in Open Source edition.

In the future, please create a role and use a new format with --roles flag:

$ tctl users add "gus" --roles=[add your role here]

We will deprecate the old format in the next release of Teleport.
Meanwhile we are going to assign user "gus" to role "admin" created during migration.

User "gus" has been created but requires a password. Share this URL with the user to complete user setup, link is valid for 1h:
https://gke.teleportdemo.net:443/web/invite/780d4409ecd22385b55668c1bbba9761

NOTE: Make sure gke.teleportdemo.net:443 points at a Teleport proxy which users can access.
```

Create the user via web UI and log in via `tsh` again - see that the `gus` user now has the `admin` role and `root` login as is expected:
```
~/go/src/github.com/gravitational/teleport(gus/helm/improvements-2*) » tsh login --proxy=gke.teleportdemo.net:443
Enter password for Teleport user gus:
Enter your OTP token:
> Profile URL:        https://gke.teleportdemo.net:443
  Logged in as:       gus
  Cluster:            gke.teleportdemo.net
  Roles:              admin*
  Logins:             root
  Kubernetes:         enabled
  Kubernetes cluster: "gke.teleportdemo.net"
  Kubernetes users:   gus
  Kubernetes groups:  
  Valid until:        2021-04-08 05:35:19 -0300 ADT [valid for 12h0m0s]
  Extensions:         permit-agent-forwarding, permit-port-forwarding, permit-pty
```

### Server Details
- Teleport version (run `teleport version`): `Teleport v6.0.2 git:v6.0.2-0-g1cb1420b7 go1.15.5`
- Server OS (e.g. from `/etc/os-release`): `Ubuntu 20.04.2 LTS (Focal Fossa)`
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): GKE
- Additional details:

### Client Details
- Tsh version (`tsh version`): `Teleport v6.0.2 git:v6.0.2-0-g1cb1420b7 go1.15.5`

**Comment by awly** [comment] 2021-04-07 21:30
+1, you also can no longer set `--k8s-users` or `--k8s-groups` when creating a local user.
I had to manually edit the user object via `tctl`.

**Comment by webvictim** [comment] 2021-04-08 13:15
The admin role created is also very unprivileged:

```yaml
kind: role
metadata:
  id: 1617825013604683680
  labels:
    migrate-v6.0: "true"
  name: admin
spec:
  allow:
    app_labels:
      '*': '*'
    db_labels:
      '*': '*'
    db_names:
    - '{{internal.db_names}}'
    db_users:
    - '{{internal.db_users}}'
    kubernetes_groups:
    - '{{internal.kubernetes_groups}}'
    kubernetes_labels:
      '*': '*'
    kubernetes_users:
    - '{{internal.kubernetes_users}}'
    logins:
    - '{{internal.logins}}'
    node_labels:
      '*': '*'
    rules:
    - resources:
      - event
      verbs:
      - list
      - read
    - resources:
      - session
      verbs:
      - list
      - read
  deny: {}
  options:
    cert_format: standard
    enhanced_recording:
    - command
    - network
    forward_agent: true
    max_session_ttl: 30h0m0s
    port_forwarding: true
version: v3
```

This means that the initial user created can't see users, roles or auth connectors in the web UI, which seems different to the default Enterprise `admin` role.

**Comment by tcsc** [comment] 2021-05-10 02:02
@webvictim I think I'm missing something here. WRT to not creating associating a user with a login, isn't this behaving as designed? In the legacy examples you're specifically assigning the `root` login to the new user:

```bash
$ tctl users add gus root
```
...and in the RBAC examples, you don't specify any logins, so you don't get any:

```bash
$ tctl users add gus --roles=admin
```
This would get you what you want:
```bash
$ tctl users add gus --roles=admin --logins=root
```

**Comment by tcsc** [comment] 2021-05-10 06:16
@awly 

> +1, you also can no longer set `--k8s-users` or `--k8s-groups` when creating a local user.
> I had to manually edit the user object via `tctl`.

After a bit of digging, it turns out you _can_ still use `--k8s-users` or `--k8s-groups`, you just can't mix them with the new-style RBAC `--logins` and `--roles`. But to be fair, the error message is pretty unhelpful. 

It _does_ appear that there is no way to specify an individual user's k8s users and groups in the new style. I assume that the intent is that all k8s user config is going be managed with roles, rather than at an individual user level? Is that a good assumption?

**Comment by webvictim** [comment] 2021-05-10 15:48
@tcsc Your comment is correct.  My point is mostly that this is inconsistent between OSS and Enterprise - Enterprise seems to source its list of available logins from the set of roles you have (perhaps as a union with the logins trait), whereas it looks like OSS may still rely solely on the logins trait.

I haven’t investigated this in huge detail, it was just odd to see this behaviour that has worked for many versions in Enterprise not working the same in OSS now that roles have been added.

**Comment by tcsc** [comment] 2021-05-11 05:46
OK, so when building a new backend from scratch, OSS Teleport will create an `admin` role that allows the the `root` login and then immediately downgrade it via migration to one that does _not_ allow `root`. Is this the desired behaviour @klizhentas?

The comments around the migration mention a migration role called `ossuser`, but the code explicitly refers to the `admin` role.

**Comment by klizhentas** [comment] 2021-05-13 00:15
Let's discourage usage of `admin` blanket role - it is too permissive. Instead, we have two new presets `access` and `editor`. That can be used to access resources and edit resources respectively.

This should work:

```bash
tctl users add alice --roles=access --logins=test
```

I don't think we need any additional migrations or downgrades. We had to migrate all users to `admin` role with downgraded privileges because it was the only way to make OSS work with trusted clusters.

In all future references, we can refer to `access` and `editor` role.

We can add support of `--k8s-users` and `--k8s-roles` flags back, so this will work:

```
tctl users add taylor --roles=access --k8s-users= --k8s-groups-...
```

This will work because `access` has a reference to `internal.` traits.

**Comment by tcsc** [comment] 2021-05-13 00:44
So, the practical upshot of this discussion is to 

1. restore `--k8s-users` and `--k8s-roles` flags when using the new RBAC syntax
2. leave the downgraded admin role as-is

Is that everyone else's understanding?

**Comment by awly** [comment] 2021-05-20 22:09
@tcsc this is fixed now, right?

**Comment by russjones** [comment] 2021-05-20 23:34
@awly @tcsc Yes, fixed in https://github.com/gravitational/teleport/pull/6849.

**Closed by russjones** 2021-05-20 23:34 UTC
Labels: bug, oss
