### ISSUE TITLE
Add more optional parameters to the JWT integration

### ISSUE THREAD

**Issue by Erick-Reyes** [gravitational/teleport#22266] opened 2023-02-24 21:35 UTC
What would you like Teleport to do?
Add more optional [parameters](https://www.rfc-editor.org/rfc/rfc7517#page-8) to the JWT integration. 
e.g. 
- `kid`

***Note: Any and all parameters would be good to add. 

What problem does this solve?
Easier to work with 3rd party apps as you never know what to expect. 
e.g. 
RabbitMQ integration with JWT

If a workaround exists, please include it.
A hacky workaround is available, but it would be nice to not do this.

**Comment by zmb3** [comment] 2023-02-24 23:30
Duplicate of #20289?

**Comment by Erick-Reyes** [comment] 2023-02-27 14:23
@zmb3 looks very similar. I think we can merge them as this is just enhancing the ask to add more optional parameters to the JWT integration.

**Comment by zmb3** [comment] 2023-02-27 15:08
Ok, I'll close this one then.

**Closed by zmb3** 2023-02-27 15:08 UTC
Labels: feature-request, good-to-have, c-thg, to-be-reviewed
