### ISSUE TITLE
tctl tokens add does not respect --ttl

### ISSUE THREAD

**Issue by stz-richter** [gravitational/teleport#14988] opened 2022-07-28 13:01 UTC
**Expected behavior:**
When adding tokens with `tctl tokens add` and specifying the option `--ttl`, the token should be valid for that TTL.

**Current behavior:**
The output after adding the token detects the TTL correctly, but `tctl tokens ls` sets every TTL to 30 minutes (while the default in `--help` is 1 hour).

```
$ tctl tokens add --ttl 120m --type node --value foo
The invite token: foo.
This token will expire in 120 minutes.

Run this on the new node to join the cluster:

> teleport start \
   --roles=node \
   --token=baz \
   --ca-pin=sha256:<> \
   --auth-server=<>:3025

Please note:

  - This invitation token will expire in 120 minutes
  - <>:3025 must be reachable from the new node

$ tctl tokens ls
Token                          Type     Labels Expiry Time (UTC)
------------------------------ -------- ------ ----------------------------
foo                            Node            28 Jul 22 13:29 UTC (29m58s)
```

**Bug details:**
- Teleport version: 10.0.2
- Recreation steps: `tctl tokens add --value foo --type node --ttl 2h`

**Comment by tigrato** [comment] 2022-07-28 14:14
Duplicate of #14916

**Closed by tigrato** 2022-07-28 14:14 UTC
Labels: bug
