### ISSUE TITLE
Separately configure ttl for expiry and ttl for the session of access request

### ISSUE THREAD

**Issue by akgoteleport** [gravitational/teleport#16202] opened 2022-09-07 16:47 UTC
What would you like Teleport to do?
Access Requests currently expire based on the max_session_ttl defined in the role that is requested and Only allows the requester to use this role for x hour from time of request.

The expiry time for the ttl and ttl for the session after the access request is approved should be separately configured.

What problem does this solve?
When a resource access request is created, its TTL is immediately started - as opposed to started when the request is accepted. So the user may miss their window entirely if the request is not accepted within max_session_ttl: x

Teleport Version: 10.1.4

If a workaround exists, please include it.
NA

**Comment by zmb3** [comment] 2022-09-07 17:05
Closing as a duplicate of #14040. I've tagged that one with `c-ty`.

**Closed by zmb3** 2022-09-07 17:05 UTC
Labels: feature-request, c-ty
