### ISSUE TITLE
tsh 14.0 from macOS Sonoma cannot connect with certificate issues

### ISSUE THREAD

**Issue by SMillerDev** [gravitational/teleport#32531] opened 2023-09-26 02:19 UTC
Expected behavior:
`tsh ssh --cluster cluster-x server-y` will start an SSH session on a server

Current behavior:
After login in and authenticating with touchID
```console
$ tsh ssh -d --cluster cluster-x server-y
2023-09-26T04:11:10+02:00 INFO [CLIENT]    ALPN connection upgrade required for "teleport.domain.com:443": true. client/api.go:723
2023-09-26T04:11:10+02:00 DEBU [CLIENT]    Skipping connection to the local ssh-agent. client/keyagent.go:137
2023-09-26T04:11:10+02:00 DEBU [KEYSTORE]  Reading certificates from path "/Users/sean.molenaar/.tsh/keys/teleport.domain.com/sean-ssh/cluster-x-cert.pub". client/keystore.go:354
2023-09-26T04:11:10+02:00 DEBU [KEYSTORE]  Teleport TLS certificate valid until "2023-09-26 14:07:05 +0000 UTC". client/client_store.go:106
2023-09-26T04:11:10+02:00 INFO [KEYAGENT]  Loading SSH key for user "sean" and cluster "cluster-x". client/keyagent.go:196
2023-09-26T04:11:10+02:00 DEBU [KEYSTORE]  Teleport TLS certificate valid until "2023-09-26 14:07:05 +0000 UTC". client/client_store.go:106
2023-09-26T04:11:10+02:00 DEBU [KEYSTORE]  Teleport TLS certificate valid until "2023-09-26 14:07:05 +0000 UTC". client/client_store.go:106
2023-09-26T04:11:10+02:00 DEBU [KEYSTORE]  Teleport TLS certificate valid until "2023-09-26 14:07:05 +0000 UTC". client/client_store.go:106
2023-09-26T04:11:10+02:00 DEBU             ALPN connection upgrade for teleport.domain.com:3023. client/alpn_conn_upgrade.go:187
2023-09-26T04:11:10+02:00 DEBU [KEYSTORE]  Teleport TLS certificate valid until "2023-09-26 14:07:05 +0000 UTC". client/client_store.go:106
2023-09-26T04:11:10+02:00 DEBU [KEYSTORE]  Teleport TLS certificate valid until "2023-09-26 14:07:05 +0000 UTC". client/client_store.go:106
2023-09-26T04:11:10+02:00 DEBU [CLIENT]    Attempting to issue a single-use user certificate with an MFA check. client/cluster_client.go:105

ERROR REPORT:
Original Error: transport.ConnectionError connection error: desc = &#34;transport: Error while dialing: failed to dial: unable to establish proxy stream\n\trpc error: code = Unavailable desc = connection error: desc = \&#34;transport: Error while dialing: tls: failed to verify certificate: x509: “7b5563ef-4099-494e-b21f-29476f71046f.cluster-x” certificate is not standards compliant\&#34;&#34;
Stack Trace:
        github.com/gravitational/teleport/api@v0.0.0/client/client.go:1617 github.com/gravitational/teleport/api/client.(*Client).GenerateUserSingleUseCerts
        github.com/gravitational/teleport/lib/client/cluster_client.go:241 github.com/gravitational/teleport/lib/client.(*ClusterClient).performMFACeremony
        github.com/gravitational/teleport/lib/client/cluster_client.go:106 github.com/gravitational/teleport/lib/client.(*ClusterClient).SessionSSHConfig
        github.com/gravitational/teleport/lib/client/api.go:1742 github.com/gravitational/teleport/lib/client.(*TeleportClient).connectToNodeWithMFA
        github.com/gravitational/teleport/lib/client/api.go:1623 github.com/gravitational/teleport/lib/client.(*TeleportClient).ConnectToNode.func2
        runtime/asm_arm64.s:1197 runtime.goexit
User Message: connection error: desc = &#34;transport: Error while dialing: failed to dial: unable to establish proxy stream\n\trpc error: code = Unavailable desc = connection error: desc = \&#34;transport: Error while dialing: tls: failed to verify certificate: x509: “7b5563ef-4099-494e-b21f-29476f71046f.cluster-x” certificate is not standards compliant\&#34;&#34;
```

Bug details:
- Teleport version: 14.0.0 on client, cluster, trusted cluster and my local machine
- Recreation steps: Not sure, it seems to just be: run `tsh ssh` from the latest macOS version.
- Debug logs: See above

**Comment by zmb3** [comment] 2023-09-26 18:34
Which version of `tsh` are you on exactly? I upgraded to Sonoma and don't see this behavior. Additionally, the line numbers in the stack trace shown above don't appear to match up with v14.0.0.

**Comment by coltonparsons-vgs** [comment] 2023-09-26 18:47
I'm experiencing the same issue:

### Version Information
```sh
tsh version
```

```
Teleport v14.0.0 git:v14.0.0-0-g599429b9 go1.21.1
Proxy version: 14.0.0
Proxy: teleport.vgs.io:443
```

### Debug Output
```sh
tsh -d ls
```

```
2023-09-26T11:45:45-07:00 INFO [CLIENT]    ALPN connection upgrade required for "teleport.vgs.io:443": true. client/api.go:723
2023-09-26T11:45:45-07:00 INFO [CLIENT]    no host login given. defaulting to colton client/api.go:1060
2023-09-26T11:45:45-07:00 INFO [CLIENT]    [KEY AGENT] Connected to the system agent: "/private/tmp/com.apple.launchd.MwA3IdjUNY/Listeners" client/api.go:4562
2023-09-26T11:45:45-07:00 DEBU [KEYSTORE]  Reading certificates from path "/Users/colton/.tsh/keys/teleport.vgs.io/colton.parsons@verygoodsecurity.com-ssh/sso-okta-cert.pub". client/keystore.go:354
2023-09-26T11:45:45-07:00 DEBU [KEYSTORE]  Teleport TLS certificate valid until "2023-09-27 06:44:27 +0000 UTC". client/client_store.go:106
2023-09-26T11:45:45-07:00 INFO [KEYAGENT]  Loading SSH key for user "colton.parsons@verygoodsecurity.com" and cluster "sso-okta". client/keyagent.go:196
2023-09-26T11:45:45-07:00 DEBU [KEYSTORE]  Teleport TLS certificate valid until "2023-09-27 06:44:27 +0000 UTC". client/client_store.go:106
2023-09-26T11:45:45-07:00 DEBU [KEYSTORE]  Teleport TLS certificate valid until "2023-09-27 06:44:27 +0000 UTC". client/client_store.go:106
2023-09-26T11:45:45-07:00 DEBU [KEYSTORE]  Teleport TLS certificate valid until "2023-09-27 06:44:27 +0000 UTC". client/client_store.go:106
2023-09-26T11:45:45-07:00 DEBU             ALPN connection upgrade for teleport-trunk.vgs.io:3023. client/alpn_conn_upgrade.go:187
2023-09-26T11:45:45-07:00 DEBU [KEYSTORE]  Teleport TLS certificate valid until "2023-09-27 06:44:27 +0000 UTC". client/client_store.go:106

ERROR REPORT:
Original Error: *trace.ConnectionProblemError connection error: desc = &#34;transport: Error while dialing: failed to dial: unable to establish proxy stream\n\trpc error: code = Unavailable desc = connection error: desc = \&#34;transport: Error while dialing: tls: failed to verify certificate: x509: “7fd50b84-120e-4cc0-82c5-b94a6469c74f.sso-okta” certificate is not standards compliant\&#34;&#34;
Stack Trace:
	github.com/gravitational/teleport/api@v0.0.0/client/client.go:3106 github.com/gravitational/teleport/api/client.(*Client).GetResources
	github.com/gravitational/teleport/api@v0.0.0/client/client.go:3238 github.com/gravitational/teleport/api/client.GetResourcePage[...]
	github.com/gravitational/teleport/api@v0.0.0/client/client.go:3305 github.com/gravitational/teleport/api/client.GetAllResources[...]
	github.com/gravitational/teleport/lib/client/api.go:2282 github.com/gravitational/teleport/lib/client.(*TeleportClient).ListNodesWithFilters
	github.com/gravitational/teleport/tool/tsh/common/tsh.go:2155 github.com/gravitational/teleport/tool/tsh/common.onListNodes.func1
	github.com/gravitational/teleport/lib/client/api.go:570 github.com/gravitational/teleport/lib/client.RetryWithRelogin
	github.com/gravitational/teleport/tool/tsh/common/tsh.go:2154 github.com/gravitational/teleport/tool/tsh/common.onListNodes
	github.com/gravitational/teleport/tool/tsh/common/tsh.go:1313 github.com/gravitational/teleport/tool/tsh/common.Run
	github.com/gravitational/teleport/tool/tsh/common/tsh.go:540 github.com/gravitational/teleport/tool/tsh/common.Main
	github.com/gravitational/teleport/tool/tsh/main.go:24 main.main
	runtime/proc.go:267 runtime.main
	runtime/asm_arm64.s:1197 runtime.goexit
User Message: connection error: desc = &#34;transport: Error while dialing: failed to dial: unable to establish proxy stream\n\trpc error: code = Unavailable desc = connection error: desc = \&#34;transport: Error while dialing: tls: failed to verify certificate: x509: “7fd50b84-120e-4cc0-82c5-b94a6469c74f.sso-okta” certificate is not standards compliant\&#34;&#34;
```

Downgrading to tsh v13 works around the issue for now.

**Comment by coltonparsons-vgs** [comment] 2023-09-26 18:53
Side note: the key error message seems to be

```certificate is not standards compliant```

but I don't know which standards this refers to. (Is tsh v14 FIPS by default or something?)

**Comment by zmb3** [comment] 2023-09-26 19:15
> Is tsh v14 FIPS by default or something?

No, this message comes from macOS if it doesn't like a certificate. Still looking in to what certificate it doesn't like and why.

**Comment by vietvudanh** [comment] 2023-09-27 05:47
I had problem with tsh 14.0.0, MacOS Monterey (12.), self host proxy with let's encrypt. The log was:

```ERROR: connection error: desc = "transport: Error while dialing: failed to dial: unable to establish proxy stream\n\trpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: tls: failed to verify certificate: x509: "uuid.<proxy host>" certificate is not standards compliant\""```

When I downgrade tsh to 13.4.1 it connects just fine.

**Comment by zmb3** [comment] 2023-09-27 18:08
So tsh v13 would first attempt to connect with the new gRPC API that's supported in teleport 14, and would fall back to the old SSH connection method if the gRPC one failed. In tsh v14 the fallback was eliminated.

I suspect this certificate issue has also been present on tsh v13 for you and it went unnoticed due to the fallback behavior. (We could confirm this with a trace)

**Comment by zmb3** [comment] 2023-09-27 20:54
Thanks @coltonparsons-vgs - that was just enough to help me identify the issue. Fix is on the way.

**Comment by keenan-v1** [comment] 2023-10-10 17:27
Curious, any word on when this will be released?

**Comment by apiening** [comment] 2023-10-11 10:18
I have the same issue. Only downgrading to teleport 13.x solved it for me.
I will be happy to try the fixed version as soon as it is released. Please let us know when it is available.

**Comment by webvictim** [comment] 2023-10-11 17:09
This should be in 14.0.3 which will be released this week.

**Comment by keenan-v1** [comment] 2023-10-11 21:48
I just downloaded tsh 14.0.3 and tested it, I'm still getting this error on macOS Ventura 13.6:

```
ERROR: connection error: desc = "transport: Error while dialing: failed to dial: unable to establish proxy stream\n\trpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: tls: failed to verify certificate: x509: “<uuid>.<proxy-host>” certificate is not standards compliant\""
```

Like the person earlier in this thread, we use a load balancer with TLS termination.

**Comment by coltonparsons-vgs** [comment] 2023-10-12 01:47
I can confirm I'm having the same issue as keenan-v1 (tsh 14.0.3 on MacOS Ventura 13.6).

I'll see if I can get a Sonoma box going to test it there.

**Comment by SMillerDev** [comment] 2023-10-12 06:47
Can't reopen it, but after updating the proxy host and my local tsh install to 14.0.3 and restarting teleport on the proxy host I now get it on `tsh login --proxy <host>` as well, so... not much improved for me.

**Comment by webvictim** [comment] 2023-10-12 11:58
Could someone having this issue share the full output of their `tsh` command when using `tsh --debug` please?

**Comment by SMillerDev** [comment] 2023-10-12 12:01
Replaced the target host with `host1` and the proxy with `bastion`, but otherwise this is the full output.

```console
~ $ tsh ssh --debug --cluster m2mobi host1.m2mobi.com
2023-10-12T13:59:02+02:00 INFO [CLIENT]    ALPN connection upgrade required for "bastion.m2mobi.com:443": true. client/api.go:723
2023-10-12T13:59:02+02:00 DEBU [CLIENT]    Skipping connection to the local ssh-agent. client/keyagent.go:137
2023-10-12T13:59:02+02:00 DEBU [KEYSTORE]  Reading certificates from path "/Users/sean.molenaar/.tsh/keys/bastion.m2mobi.com/sean-ssh/m2mobi-cert.pub". client/keystore.go:355
2023-10-12T13:59:02+02:00 DEBU [KEYSTORE]  Teleport TLS certificate valid until "2023-10-12 18:43:42 +0000 UTC". client/client_store.go:106
2023-10-12T13:59:02+02:00 INFO [KEYAGENT]  Loading SSH key for user "sean" and cluster "m2mobi". client/keyagent.go:196
2023-10-12T13:59:02+02:00 DEBU [KEYSTORE]  Teleport TLS certificate valid until "2023-10-12 18:43:42 +0000 UTC". client/client_store.go:106
2023-10-12T13:59:02+02:00 DEBU [KEYSTORE]  Teleport TLS certificate valid until "2023-10-12 18:43:42 +0000 UTC". client/client_store.go:106
2023-10-12T13:59:02+02:00 DEBU [KEYSTORE]  Teleport TLS certificate valid until "2023-10-12 18:43:42 +0000 UTC". client/client_store.go:106
2023-10-12T13:59:02+02:00 DEBU [KEYSTORE]  Teleport TLS certificate valid until "2023-10-12 18:43:42 +0000 UTC". client/client_store.go:106
2023-10-12T13:59:02+02:00 DEBU             ALPN connection upgrade for bastion.m2mobi.com:3023. client/alpn_conn_upgrade.go:187
2023-10-12T13:59:02+02:00 DEBU [KEYSTORE]  Reading certificates from path "/Users/sean.molenaar/.tsh/keys/bastion.m2mobi.com/sean-ssh/m2mobi-cert.pub". client/keystore.go:355
2023-10-12T13:59:02+02:00 DEBU [KEYSTORE]  Teleport TLS certificate valid until "2023-10-12 18:43:42 +0000 UTC". client/client_store.go:106
2023-10-12T13:59:02+02:00 DEBU [CLIENT]    Attempting to issue a single-use user certificate with an MFA check. client/cluster_client.go:135

ERROR REPORT:
Original Error: transport.ConnectionError connection error: desc = &#34;transport: Error while dialing: failed to dial: unable to establish proxy stream\n\trpc error: code = Unavailable desc = connection error: desc = \&#34;transport: Error while dialing: tls: failed to verify certificate: x509: “7b5563ef-4099-494e-b21f-29476f71046f.m2mobi” certificate is not standards compliant\&#34;&#34;
Stack Trace:
        github.com/gravitational/teleport/api@v0.0.0/client/client.go:1630 github.com/gravitational/teleport/api/client.(*Client).GenerateUserSingleUseCerts
        github.com/gravitational/teleport/lib/client/cluster_client.go:271 github.com/gravitational/teleport/lib/client.(*ClusterClient).performMFACeremony
        github.com/gravitational/teleport/lib/client/cluster_client.go:136 github.com/gravitational/teleport/lib/client.(*ClusterClient).SessionSSHConfig
        github.com/gravitational/teleport/lib/client/api.go:1738 github.com/gravitational/teleport/lib/client.(*TeleportClient).connectToNodeWithMFA
        github.com/gravitational/teleport/lib/client/api.go:1619 github.com/gravitational/teleport/lib/client.(*TeleportClient).ConnectToNode.func2
        runtime/asm_arm64.s:1197 runtime.goexit
User Message: connection error: desc = &#34;transport: Error while dialing: failed to dial: unable to establish proxy stream\n\trpc error: code = Unavailable desc = connection error: desc = \&#34;transport: Error while dialing: tls: failed to verify certificate: x509: “7b5563ef-4099-494e-b21f-29476f71046f.m2mobi” certificate is not standards compliant\&#34;&#34;
```

**Comment by webvictim** [comment] 2023-10-12 12:07
@greedy52 Do you think this could be related to connection upgrades somehow?

**Comment by greedy52** [comment] 2023-10-12 13:47
I tested v14.0.3 with my ALB setup and it's working fine. I suspect it is related to the cluster name as a single word (no dots) and not 100% sure. Let me try to repro it.

**Comment by greedy52** [comment] 2023-10-12 14:15
> 2023-10-12T13:59:02+02:00 INFO [CLIENT]    ALPN connection upgrade required for "bastion.m2mobi.com:443": true. client/api.go:723
> 2023-10-12T13:59:02+02:00 DEBU             ALPN connection upgrade for bastion.m2mobi.com:3023. client/alpn_conn_upgrade.go:187

Notice the port is different. Same thing here.

> 2023-09-26T11:45:45-07:00 INFO [CLIENT]    ALPN connection upgrade required for "teleport.vgs.io:443": true. client/api.go:723
> 2023-09-26T04:11:10+02:00 DEBU             ALPN connection upgrade for teleport.domain.com:3023. client/alpn_conn_upgrade.go:187

So I am assuming TLS routing is not enabled. Connection upgrade should NOT be applied to 3023.

I am setting up this, will update this comment with my findings.

**Closed** 2023-10-12 18:51 UTC
Labels: bug, tsh, mac

**Comment by keenan-v1** [comment] 2023-10-20 16:05
Just popping back to say everything is working now. Thank you!

**Comment by SMillerDev** [comment] 2023-10-21 07:47
I just tried, same for me. Thanks everyone!

**Comment by coltonparsons-vgs** [comment] 2023-10-23 15:47
I can confirm as well, tsh `14.1.0` works perfectly for us. Thank you!

**Comment by vietvudanh** [comment] 2023-11-08 06:54
Thank team, working well with tsh `14.1.1`.
