### ISSUE TITLE
Re-establishing a Trusted Cluster

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#3678] opened 2020-05-07 15:39 UTC
### Description

**What happened**:

Having issues when trying to re-establish a trusted cluster…
the scenario:
1. deploy Teleport cluster A
2. deploy Teleport cluster B
3. (get trusted_cluster token from A) Apply trusted-cluster.yaml on B (pointing to A)
4. remove remote cluster (on A - `tctl rm rc/B`)
5. remove trusted cluster (on B - `tctl rm tc/A`)
6. (get new token from A) Apply trusted-cluster.yaml to B (pointing to A)

The connection (reverse tunnel) doesn’t seem to get established on A
```
DEBU [PROXY:SER] Requesting connection to @remote-auth-server [] in remote cluster. cluster:bastion-X reversetunnel/remotesite.go:585
WARN [PROXY:SER] Request for connection to remote site failed: bastion-X is offline: no active tunnels to teleport-test-bastion found. cluster:bastion-X reversetunnel/remotesite.go:593
DEBU [AUTH]      Dial to addr teleport.cluster.local failed: bastion-X is offline. auth/clt.go:302
WARN [REVERSE:S] Re-init the cache on error: all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing bastion-X is offline". cache/cache.go:333
```

I did notice this in the logs: `DEBU [PROC:1]    Creating sqlite backend for [reverse bastion-X]. service/service.go:1282`
Is it perhaps trying to use old connection information (from the first setup) and the sqlite backend doesn’t get cleaned-up/re-inialized when the new connection is established?
full logs on A after the trusted-cluster.yaml is applied on B:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

### Environment
- Teleport version (use `teleport version`):
- Tsh version (use `tsh version`):
- OS (e.g. from `/etc/os-release`):

- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware):

**Browser environment**

- Browser Version (for UI-related issues):
- Install tools:
- Others:

**Relevant Debug Logs If Applicable**

- `tsh --debug`
- `teleport --debug`

**Comment by benarent** [comment] 2020-05-07 15:41
The customer has followed this instructions from https://github.com/gravitational/teleport/issues/2075. We need to replicate locally to test.

**Comment by awly** [comment] 2020-05-13 18:07
I can't reproduce this issue locally following these instructions. Which teleport version were you running?
We also have an integration test for [this specific scenario](https://github.com/gravitational/teleport/blob/master/integration/integration_test.go#L1753-L1798).

**Comment by stmuraka** [comment] 2020-05-21 01:48
@awly 
was running v 4.2.6 at the time
data is on local storage - sqlite
non-HA configuration - single node
deployed in Kubernetes
no recovery.
The scenario is when the leaf cluster is explicitly deleted. Then a new leaf cluster with the same cluster name is deployed and adds a trusted cluster

**Comment by awly** [comment] 2020-05-21 17:32
@stmuraka to clarify - you were adding a _completely different_ teleport cluster as leaf with the same name. Like so:
- make cluster named `root`
- make cluster named `leaf`
- make **another** cluster named `leaf` (with a different proxy endpoint)
- add the first `leaf` cluster to `root` as trusted
- tunnel comes up
- delete trusted cluster config
- add the second `leaf` cluster to `root` as trusted
- tunnel doesn't come up

**Comment by awly** [comment] 2020-05-21 17:45
Hmm, I still can't reproduce this.
Neither on `master`, nor with v4.2.6.

Maybe this behavior is flaky? Or maybe there was something else preventing your new re-created leaf proxy from talking to root?
@stmuraka are you able to consistently reproduce this or was it a one-time problem?

**Comment by stmuraka** [comment] 2020-05-21 18:14
@awly clarification on the steps...

1. make cluster named `root`
2. make cluster named `leaf`
3. ~~make another cluster named leaf (with a different proxy endpoint)~~
4. add the ~~first~~ `leaf` cluster to `root` as trusted
5. tunnel comes up
6. ~~delete trusted cluster config~~
6. destroy `leaf` cluster
7. ~~add the second leaf cluster to root as trusted~~
7. remove remote  cluster `leaf` from `root` cluster (`tctl rm rc/leaf`)
8.  make cluster named `leaf`
9.  add the `leaf` cluster to `root` as trusted
10. tunnel doesn't come up

**Comment by awly** [comment] 2020-05-21 18:38
Thanks! Still works on my local setup with both master and 4.2.6.
I did notice that if I forget to `tctl rm rc/leaf` on `root`, the tunnel goes into reconnect loop. Is it possible this step was skipped when you tried?
@stmuraka are you able to reproduce this?

**Comment by stmuraka** [comment] 2020-05-21 19:57
@awly 
I did remove the `leaf` cluster on `root`

After recreating and adding the `leaf` cluster (step 11).
A connection does seem to be established - perhaps step 12 `tunnel does not come up` is the wrong description of the result.

on `root`:
```
kind: remote_cluster
metadata:
  name: leaf
status:
  connection: online
  last_heartbeat: 2020-05-21T19:27:01.911109041Z
version: v3
```

on `leaf`:
```
kind: trusted_cluster
metadata:
  id: 1590088920374052327
  name: root
spec:
  enabled: true
  role_map:
  - local:
    - iks-user
    remote: iks-user
  token: token
  tunnel_addr: root:3024
  web_proxy_addr: root:443
version: v2
```

on the `leaf` cluster logs:
```
DEBU [PROXY:AGE] Outbound tunnel for root connected to 1 proxies. cluster:leaf reversetunnel/agentpool.go:371
```

however when executing things like `kubectl get namespaces`, I receive the following error:
```
Error from server (InternalError): an error on the server ("Internal Server Error") has prevented the request from succeeding
```

on the `root` cluster, the last entry in the log is
```
> INFO [RBAC]      Access to create user in namespace default denied to roles Proxy,default-implicit-role: no allow rule matched. services/role.go:1939
> DEBU [PROXY:SER] Dialing from myip:53248 to remote.kube.proxy.teleport.cluster.local. cluster:leaf reversetunnel/remotesite.go:521
> DEBU [PROXY:SER] Requesting connection to remote.kube.proxy.teleport.cluster.local [] in remote cluster. cluster:stmuraka-tekton-bastion reversetunnel/remotesite.go:585
> ERRO             Error forwarding to https://remote.kube.proxy.teleport.cluster.local/api?timeout=32s, err: leaf is offline forward/fwd.go:180
```
however @klizhentas said those are normal.

perhaps I should clean, re-depoy, and try to recreate again

**Comment by awly** [comment] 2020-05-27 18:29
Found it, I wasn't doing any k8s requests after re-creating the trusted cluster.
The k8s proxy was indeed caching references to the old tunnel and attempting to reuse them after close.

Fix is in https://github.com/gravitational/teleport/pull/3773

@stmuraka did you experience any issues with non-k8s actions?

**Comment by stmuraka** [comment] 2020-05-27 18:45
@awly I haven't tested non-k8

**Closed** 2020-06-01 20:17 UTC
Labels: bug, c-ib, trusted-cluster
