### ISSUE TITLE
Support use of `teleport-kube-agent` with the `teleport-cluster` Helm chart

### ISSUE THREAD

**Issue by philip-teleport** [gravitational/teleport#30542] opened 2023-08-16 07:58 UTC
What would you like Teleport to do?

Support the use of the `teleport-kube-agent` in tandem with the `teleport-cluster` Helm chart.

What problem does this solve?

By default, the `teleport-cluster` is made available for access by Teleport users and the `kubeClusterName` value allows you to define the name that is used. As a result of this, when automating the deployment of the `teleport-kube-agent` across all Kubernetes clusters, the Teleport cluster must be explicitly excluded from this automation. It would be easier to automate the deployment of the `teleport-kube-agent` if the `teleport-kube-agent` could be used in tandem with the `teleport-cluster` Helm chart. Updating the `teleport-cluster` Helm chart to allow you to toggle cluster access on or off would support this.

If a workaround exists, please include it.

N/A

**Comment by webvictim** [comment] 2023-08-16 12:25
I think this may already be tracked by https://github.com/gravitational/teleport/issues/23211

**Comment by zmb3** [comment] 2024-01-02 15:55
Duplicate of #23211

**Closed by zmb3** 2024-01-02 15:55 UTC
Labels: feature-request, helm, c-cpd
