### ISSUE TITLE
Desktop access without AD / LDAP

### ISSUE THREAD

**Issue by raphaelbkt** [gravitational/teleport#12389] opened 2022-05-03 15:40 UTC
Hi,

I would like to use Teleport Desktop Access to access standalone Windows servers (without Active Directory or ldaps server, ie not being part of a domain).
I have a network with local accounts which is not part of a Active Directory domain, I would like to access it with Teleport Desktop Access with local accounts on the windows server.

I saw from the documentations https://goteleport.com/docs/desktop-access/reference/configuration/ that Desktop Access can be configured in two modes:
- the mode gateway (direct mode ?)(with AD and is covered in the documentation),
- the mode node (Iot mode ?)(local ?) but I can't seem to find any documentation. I tried to unset windows_desktop_service.listen_addr in teleport 9.1.2 to force Iot mode - does it needs AD or LDAPS available ?) but service does not start after modification.

I tried to include 
mode: node in the windows_desktop_service from the teleport.yaml
but the teleport service keeps restarting afterwards.

I also see that for teleport 9.1.2 there is only Windows tsh binary, no teleport binary that we could install on a Windows Server.
I see that there is a page for the client https://github.com/gravitational/teleport/projects/8 but I don't understand if feature is in progress or stopped ?

Thanks

Raphaël

**Comment by zmb3** [comment] 2022-05-03 15:48
Hi there, this is a common request and something we are investigating. 

Both of the deployment modes you reference require Active Directory. Additionally, you are correct that there is not a Windows binary, teleport itself must still run on Linux for now.

I'm going to close this as a duplicate of #10166 - feel free to subscribe to that issue for updates.

**Closed** 2022-05-03 15:48 UTC
Labels: feature-request
