### ISSUE TITLE
Use non-default service account for pre-hook Jobs

### ISSUE THREAD

**Issue by bradyz7** [gravitational/teleport#48477] opened 2024-11-05 21:13 UTC
What would you like Teleport to do?
The pods created by the [auth pre-deploy job](https://github.com/gravitational/teleport/blob/master/examples/chart/teleport-cluster/templates/auth/predeploy_job.yaml) and [proxy pre-deploy job](https://github.com/gravitational/teleport/blob/master/examples/chart/teleport-cluster/templates/proxy/predeploy_job.yaml) use the default service account. Instead, the pods should respect the service account set in [serviceAccount.name](https://goteleport.com/docs/reference/helm-reference/teleport-cluster/#serviceaccountname)

What problem does this solve?
This is similar to https://github.com/gravitational/teleport/issues/21421 for the test jobs in teleport-cluster using the default service account

If a workaround exists, please include it.
No, we don't have a workaround at the moment

**Comment by zmb3** [comment] 2024-11-05 21:57
Duplicate of #21384?

**Comment by bradyz7** [comment] 2024-11-06 13:25
> Duplicate of [#21384](https://github.com/gravitational/teleport/issues/21384)?

Not exactly, it seems https://github.com/gravitational/teleport/issues/21384 is to have the option for the proxy service account to have a different name besides `{{- coalesce .Values.serviceAccount.name .Release.Name -}}-proxy`, while the ask here is to be able to set an alternative service account for the auth and proxy pre-deploy jobs at all.

**Closed** 2024-11-06 21:38 UTC
Labels: helm
