### ISSUE TITLE
db agent crash with large query

### ISSUE THREAD

**Issue by programmerq** [gravitational/teleport#18306] opened 2022-11-09 18:37 UTC
## Expected Behavior

The agent shouldn't crash due to a user action.

## Current Behavior

When connected to a redshift database with dbeaver, a query that accidentally returned a large amount of data caused the db agent to crash.

> The proxy recorded a total o 37 queries from his client in the 5 minutes or so preceding the crash. However, the second-to-last of the recorded queries was made in error. The dev failed to add a LIMIT clause to a query of a large table; its pretty typical for a massive select to crash a GUI client and that is what happened here: Dbeaver crashed, reporting an "out of memory error". Immediately after this, the db_service proxy failed.

> he ran a SELECT without a LIMIT clause on a table that exceeded the memory limitation for his dbeaver install. He managed to fire off a second SELECT clause after this which did have a LIMIT clause. Then he restarted Dbeaver and by then the proxy was unresponsive.

additional info from the dba that encountered the error:

> I let the query run for ~1minute since I've found redshift can be a bit slow for small queries, but that seemed excessive. Then I tried canceling the query and closing the connection tab. At that point dbeaver started to freeze up. Often dbeaver doesn't cancel queries gracefully and I have to close the tab, but I never had it freeze before. At some point it gave me some message about being out of memory. I can't remember the exact details here unfortunately, but I believe it somewhat recovered. I restarted it anyway when I couldn't connect to the other databases.

```
Oct 11 20:36:07 teleport-db-proxy teleport: 2022-10-11T20:36:07Z ERRO [DB:SERVIC] Failed to send message to client. db:myredshift error:[EOF] from:server id:688af722-3aad-46a5-b1cf-c41265a2a3cf postgres/engine.go:401
Oct 11 20:36:07 teleport-db-proxy teleport: panic: runtime error: slice bounds out of range [1836:1833]
Oct 11 20:36:07 teleport-db-proxy teleport: goroutine 78558953 [running]:
Oct 11 20:36:07 teleport-db-proxy teleport: github.com/jackc/chunkreader/v2.(*ChunkReader).Next(0xc007bf3600, 0x5)
Oct 11 20:36:07 teleport-db-proxy teleport: /tmp/gomodcache/github.com/jackc/chunkreader/v2@v2.0.1/chunkreader.go:61 +0x365
Oct 11 20:36:07 teleport-db-proxy teleport: github.com/jackc/pgproto3/v2.(*Backend).Receive(0xc002c276c0)
Oct 11 20:36:07 teleport-db-proxy teleport: /tmp/gomodcache/github.com/jackc/pgproto3/v2@v2.2.0/backend.go:166 +0x344
Oct 11 20:36:07 teleport-db-proxy teleport: github.com/gravitational/teleport/lib/srv/db/postgres.(*Engine).receiveFromClient(0xc008003960, 0x5c8e3d8, 0xc006702fd0, 0x2b75d06, 0xc0044c3c80)
Oct 11 20:36:07 teleport-db-proxy teleport: /go/src/github.com/gravitational/teleport/lib/srv/db/postgres/engine.go:293 +0x11c
Oct 11 20:36:07 teleport-db-proxy teleport: created by github.com/gravitational/teleport/lib/srv/db/postgres.(*Engine).HandleConnection
Oct 11 20:36:07 teleport-db-proxy teleport: /go/src/github.com/gravitational/teleport/lib/srv/db/postgres/engine.go:148 +0x3a5
Oct 11 20:36:07 teleport-db-proxy systemd: teleport.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Oct 11 20:36:07 teleport-db-proxy systemd: Unit teleport.service entered failed state.
Oct 11 20:36:07 teleport-db-proxy systemd: teleport.service failed.
```

It appears that the teleport agent panics when it failed to write the data on the now-closed connection back to the client.

This occurred on a 10.3.x cluster.

**Comment by greedy52** [comment] 2022-11-09 18:56
maybe related to https://github.com/jackc/pgproto3/commit/fd427c06da934db1e3a73859ba6bed4d0810fb08

**Comment by smallinsky** [comment] 2022-11-10 13:32
> maybe related to https://github.com/jackc/pgproto3/commit/fd427c06da934db1e3a73859ba6bed4d0810fb08
>> Oct 11 20:36:07 teleport-db-proxy teleport: panic: runtime error: slice bounds out of range [1836:1833]

> hints a negative value

We are already using fixed version since v11  but it worth to upgrade v10 and v9 https://github.com/gravitational/teleport/pull/18342 

Not sure if we can relay at stacktrace but it looks that non negative: `5` int value was passed to `ChunkReader.Next(i int)`: 
```
github.com/jackc/chunkreader/v2.(*ChunkReader).Next(0xc007bf3600, 0x5)
```

**Comment by greedy52** [comment] 2022-11-10 16:08
interesting. i tried a small program but I cannot repro similar stacktrace on the `Next` call
```
package main

import (
	"bytes"
	"fmt"

	"github.com/jackc/chunkreader/v2"
)

func main() {
	cr := chunkreader.New(bytes.NewBuffer([]byte("abcdef")))

	for _, i := range []int{3, 1, -3} {
		b, e := cr.Next(i)
		fmt.Println(string(b), e)
	}
}
```
And `go run .`
```
abc <nil>
d <nil>
panic: runtime error: slice bounds out of range [4:1]

goroutine 1 [running]:
github.com/jackc/chunkreader/v2.(*ChunkReader).Next(0x1020e50b8?, 0x1400000e018?)
	/Users/stevehuang/go/pkg/mod/github.com/jackc/chunkreader/v2@v2.0.1/chunkreader.go:61 +0x368
main.main()
	/Users/stevehuang/go/github.com/gravitational/teleport/tmp/main.go:14 +0x154
exit status 2
```
🤷

**Comment by smallinsky** [comment] 2022-11-10 17:49
@greedy52 
This check was added inside [(b *Backend) Receive()](https://github.com/jackc/pgproto3/commit/fd427c06da934db1e3a73859ba6bed4d0810fb08#diff-f7febf2126e4c13f0730b2d06b8a6d3bdcb748f6379770c478888c2e4ea1949eR118) function. `ChunkReader.Next(-1)` still panics but the `if b.bodyLen < 0 {` assertion make sure that bodyLen is not negative before invoking https://github.com/jackc/pgproto3/commit/fd427c06da934db1e3a73859ba6bed4d0810fb08#diff-f7febf2126e4c13f0730b2d06b8a6d3bdcb748f6379770c478888c2e4ea1949eR171

**Comment by greedy52** [comment] 2022-11-10 17:54
Yes. i was just trying to see if i can reproduce the stack trace part where there is `0x5` to understand what it is.

From the issue
```
github.com/jackc/chunkreader/v2.(*ChunkReader).Next(0xc007bf3600, 0x5)
```
The `panic: runtime error: slice bounds out of range [1836:1833]` indicates n is `-3`, which would contradict with the `0x5`

From my test program
```
github.com/jackc/chunkreader/v2.(*ChunkReader).Next(0x1020e50b8?, 0x1400000e018?)
```
so i don't even get an int value in the stacktrace.

**Comment by smallinsky** [comment] 2022-11-28 09:27
Fixed by deep update: 
https://github.com/gravitational/teleport/commit/48590de5a0220a63f8dbaa5b8506cc39d5de96e3

**Closed by smallinsky** 2022-11-28 09:27 UTC
Labels: bug, database-access, db/postgres
