### ISSUE TITLE
`TestDatabaseServerResource ` flakiness

### ISSUE THREAD

**Issue by ibeckermayer** [gravitational/teleport#22525] opened 2023-03-01 23:25 UTC
#### Link(s) to logs

- https://github.com/gravitational/teleport/actions/runs/4308676952/jobs/7515209709

#### Relevant snippet

```
    helpers_test.go:183: 
        	Error Trace:	/__w/teleport/teleport/tool/tctl/common/helpers_test.go:183
        	            				/__w/teleport/teleport/tool/tctl/common/resource_command_test.go:77
        	Error:      	Received unexpected error:
        	            	listen tcp 127.0.0.1:43399: bind: address already in use
        	Test:       	TestDatabaseServerResource
--- FAIL: TestDatabaseServerResource (2.48s)
```

**Comment by GavinFrazar** [comment] 2023-03-28 03:24
https://github.com/gravitational/teleport/actions/runs/4534844047/jobs/7989536431?pr=23601

I updated this test in a PR which triggered the flaky test detector to run it. My changes did not cause the flaky test behavior (I think).

The log output is extremely long, but it seems to be caused by some improper shutdown sequence from `makeAndRunTestAuthServer` cleanup, where it tries to cleanup the test by shutting the auth service down. 

I found that we were not propagating the process exit context to our reversetunnel server's context, which was using a `context.TODO()` instead, causing it to forever loop and spam the log message `Failed to fetch cluster peers error`:
https://github.com/gravitational/teleport/blob/8d12ed1137904ef9778e89134f21596a2e2b9fdd/lib/reversetunnel/srv.go#L400-L410
context is not propagated here, and config's `CheckAndSetDefaults` method uses `context.TODO()` when its nil, so `<-s.ctx.Done()` in the above never happens:
https://github.com/gravitational/teleport/blob/8d12ed1137904ef9778e89134f21596a2e2b9fdd/lib/service/service.go#L3514-L3544

I fixed that locally by passing `Context: process.ExitContext()`, and that reduced the log spam significantly, but the test still times out waiting on something.

**Comment by GavinFrazar** [comment] 2023-03-28 18:39
The test times out after 10 minutes of waiting for the process to shut down. I'm not really sure why the fix worked - maybe it just prevents some unrealistic state where the auth server starts and is told to shutdown almost immediately.
https://github.com/gravitational/teleport/pull/23601/commits/fe09597a442649bde827cbb6c170a71f204a6317#diff-57c71883e91acf2b364878003a3e0ab43b99b8fa0b4661bf7811ff2b4e13bd43R246-R280

**Comment by GavinFrazar** [comment] 2023-05-20 02:18
@smallinsky should we close this? I can't reproduce this test failure and no one has reported this test flaky since March

**Closed** 2023-05-22 07:58 UTC
Labels: flaky tests
