### ISSUE TITLE
DBeaver/PGAdmin not able to connect to postgres with non-multiplexing cluster

### ISSUE THREAD

**Issue by programmerq** [gravitational/teleport#16384] opened 2022-09-13 21:59 UTC
### Expected behavior:

After trying various combinations of connecting directly to the postgres proxy port, running `tsh proxy db`, and `tsh proxy db --tunnel`, it appears that a non-multiplexed instance of teleport with a separate DNS name for web and non-web services break accessing postgres with java clients.

### Current behavior:

Basic cluster info: this was set up with the terraform+aws scripts with ACM enabled. Some changes were made. A separate nlb for all non-web ports was set up with its own DNS name. The config file reflects this.

```yaml
proxy_service:
  enabled: "yes"
  public_addr: 'teleport.example.com:443'
  ssh_public_addr: 'nlb-teleport.example.com:3023'
  tunnel_public_addr: 'nlb-teleport.example.com:3024'
  kube_public_addr: 'nlb-teleport.example.com:3026'
  mysql_public_addr: 'nlb-teleport.example.com:3036'
  postgres_public_addr: 'nlb-teleport.example.com:5432'
  kube_listen_addr: 0.0.0.0:3026
  mysql_listen_addr: 0.0.0.0:3036
  web_listen_addr: 0.0.0.0:3080
  postgres_listen_addr: 0.0.0.0:5432
```

The `teleport.example.com` DNS leads to an ALB with an ACM cert enabled.

All other services are set up on `nlb-teleport.example.com` with the respective ports in place.

---

DBeaver, pgadmin4, and other java-based database clients are not able to connect to redshift + postgres databases

When connecting to the postgres port on the proxy:

> Unable to connect to server: connection to server at "nlb-teleport.example.com" (10.0.0.22), port 5432 failed: server closed the connection unexpectedly. This probably means the server terminated abnormally before or while processing the request.

So we tried with the proxy even though multiplexing isn't used:

> An error occurred while setting up the SSL connection.

We realized that we were hitting https://github.com/gravitational/teleport/issues/6116 and manually converted the files generated by `tsh proxy db` from PEM to DER, but that resulting in the following error:

> Could not find a java cryptographic algorithm: Cannot find any provider supporting 1.2.840.113549.1.5.13.
>   Cannot find any provider supporting 1.2.840.113549.1.5.13

It seems that none of the jdbc providers know what to do with some of the x509 extensions that teleport uses, and they panic.

So we tried using `--tunnel` mode, but that resulted in behavior where tsh would report it is listening, but we got connection refused.

---

It seems like the Java / JDBC based clients can't quite handle the certs that Teleport generates for them (even with converting them to DER specifically). Additionally, the last resort tunnel mode of the proxy command failed.

It seems like we should add in some tests to deal with DER format certs and test them with various JDBC driver implementations out there.

### Bug details:
- Teleport version -  v9.3.18
- Recreation steps - set up a cluster with a separate ALB and NLB with distinct DNS names, and try to access redshift via dbeaver or pgadmin4.
- Debug logs

gz#6279

**Comment by greedy52** [comment] 2022-09-14 00:34
As discussed, this is likely a duplicate of https://github.com/gravitational/teleport/issues/14369. I will test out dbeaver with redishift to confirm if the current fix works.

**Comment by programmerq** [comment] 2022-09-14 13:24
While 14369 appears that it does address the `tsh proxy db` side of things, It'd be great for the direct dial mode to work too.

I'll gather more specific information about that type of error. I'm inclined to edit this issue to be specifically about direct dial mode only.

**Comment by greedy52** [comment] 2022-09-14 13:40
> While 14369 appears that it does address the `tsh proxy db` side of things, It'd be great for the direct dial mode to work too.

What do you mean by direct dial mode? 

I just tried DBeaver to NLB directly and it worked as well.
```
$ tsh db login --db-user stevehuang --db-name test steve-redshift
...
$ tsh db config  steve-redshift
Name:      steve-redshift
Host:      nlb.teleport.root.dev.aws.stevexin.me
Port:      3035
User:      stevehuang
Database:  test
CA:        /Users/stevehuang/.tsh/keys/teleport.root.dev.aws.stevexin.me/cas/teleport.root.dev.aws.stevexin.me.pem
Cert:      /Users/stevehuang/.tsh/keys/teleport.root.dev.aws.stevexin.me/alb-db/teleport.root.dev.aws.stevexin.me/steve-redshift-x509.pem
Key:       /Users/stevehuang/.tsh/keys/teleport.root.dev.aws.stevexin.me/alb
```
Use these to setup DBeaver host, SSL. **Must also convert the private key to der format as mentioned above.** E.g.:
```
$ openssl pkcs8 -topk8 -inform PEM -outform DER -in alb -out alb.der
```

<img width="514" alt="Screen Shot 2022-09-14 at 9 39 03 AM" src="https://user-images.githubusercontent.com/12417665/190169702-f7f3f670-094d-4aa9-a24b-ca4ed93b702c.png">

<img width="522" alt="Screen Shot 2022-09-14 at 9 39 12 AM" src="https://user-images.githubusercontent.com/12417665/190169737-74bd280c-87e0-42f7-90c2-8d051910a0ce.png">

**Comment by greedy52** [comment] 2022-09-20 15:23
@programmerq any luck getting DBeaver/PGAdmin working without the local proxy?

**Comment by programmerq** [comment] 2022-09-30 16:51
@greedy52 I was indeed able to get my dbeaver working without the local proxy. I did need to convert the key to the DER format with the following command on my mac (using the apple-provided LibreSSL 2.8.3):

```
openssl pkcs8 -topk8 -inform PEM -outform DER -in jeff -out jeff.der -nocrypt
```

I found that I needed to specify `-nocrypt` in order for dbeaver to accept the converted key.

As for auto-generating the DER format, I would be very much in favor of that. #6116 requested that, but it was closed in favor of using an authenticated tunnel. I think it would be a better security practice to have the DER key available instead of recommending the tunnel approach.

**Comment by greedy52** [comment] 2022-09-30 17:55
Yes. The authenticated tunnel is preferred. And likely we will add full multiplexing support for Teleport behind ALB in Q4 and eventually migrate existing customs to use multiplexing mode without the need of NLB.

I believe the `tsh proxy db` support for ALB is releasing in 10.3. I will sync up with others in DB team on the Der format.

**Comment by greedy52** [comment] 2022-10-12 13:51
Seems we don't plan to add the der format ATM because of the alternatives we have discussed. Though if one does want the der format, one suggestion was to utilize our tsh alias feature.

Here is an example that I managed to get it working. My `~/.tsh/config/config.yaml`:
```
$ cat ~/.tsh/config/config.yaml 
aliases:
  "postgres-login-alice": "bash -c '$TSH db login --db-user alice $0; $TSH db config $0; keyfile=$(tsh db config $0 --format json | jq -r .key); cat $keyfile | openssl pkcs8 -topk8 -inform PEM -outform DER -out $keyfile.der -nocrypt; echo \"Key (DER Format): $keyfile.der\"'"
```
which takes $0 as the database name with fixed username `alice`. Then:
```
$ tsh postgres-login-alice steve-postgres
Connection information for database "steve-postgres" has been saved.

You can now connect to it using the following command:

  tsh db connect --db-name=<name> steve-postgres

Or start a local proxy for database GUI clients:

  tsh proxy db --tunnel --db-name=<name> steve-postgres

Name:      steve-postgres
Host:      teleport.dev.aws.stevexin.me
Port:      443
User:      alice
Database:  
CA:        /Users/stevehuang/.tsh/keys/teleport.dev.aws.stevexin.me/cas/teleport.dev.aws.stevexin.me.pem
Cert:      /Users/stevehuang/.tsh/keys/teleport.dev.aws.stevexin.me/STeve-db/teleport.dev.aws.stevexin.me/steve-postgres-x509.pem
Key:       /Users/stevehuang/.tsh/keys/teleport.dev.aws.stevexin.me/STeve
Key (DER Format): /Users/stevehuang/.tsh/keys/teleport.dev.aws.stevexin.me/STeve.der

```

**Comment by greedy52** [comment] 2022-11-09 15:57
Will close this for now since `tsh proxy db` for Teleport behind is ALB change is released. #15669

And we also have the above-mentioned workarounds with Der format.

There is no plan to add der format to tsh yet. if we do, we can track that in #16950

**Closed by greedy52** 2022-11-09 15:57 UTC
Labels: bug, aws, database-access, c-bu
