### ISSUE TITLE
Autocomplete Reviewers field in Just in Time Access Requests

### ISSUE THREAD

**Issue by tenaciousdlg** [gravitational/teleport#41147] opened 2024-05-02 15:55 UTC
What would you like Teleport to do?
Provide an auto-complete option based on the string being typed into the Reviewers field in an Access Request.

![Screenshot 2024-05-02 at 10 34 46 AM](https://github.com/gravitational/teleport/assets/28679416/416376c7-36f9-47f5-95b0-3afe17a770bc)

What problem does this solve?
It prevents a user from guessing the Username of a possible reviewer.

If a workaround exists, please include it.
Today users need to manually type out a Username of a Reviewer

**Comment by zmb3** [comment] 2024-05-02 16:28
Duplicate of #30315

**Closed by zmb3** 2024-05-02 16:28 UTC
Labels: feature-request
