### ISSUE TITLE
Failed to launch: failed to open user account database

### ISSUE THREAD

**Issue by naughtydog17** [gravitational/teleport#17971] opened 2022-10-31 19:47 UTC
Hello 
I am getting the following error when conncting to some of my nodes. 
`Failed to launch: failed to open user account database`

Server details
```
Teleport server:
Debian 11
Teleport 11.0.0 git:V11.0.0.0-g0c2973d
```

All the nodes are deployed via ansible with a pinned version of teleport.

**failing node details:**
``` 
Arch Linux, 
kernel: 5.15.76-1-lts
Teleport: 11.0.0
```
Error when trying to connect to the node:
```
Failed to launch: failed to open user account database, code: %!d(<nill>).
Process exited with status 255
```
Debug log:
```
2022-10-31T08:20:48-11:00 DEBU [SESSION:N] Launching session c56e5883-67c7-44d5-90af-c758dd2492c8. srv/sess.go:871
2022-10-31T08:20:48-11:00 DEBU [NODE]      Waiting for continue signal id:1 local:x.x.x.x:40432 login:root remote:y.y.y.y:53202 teleportUser:admin1 srv/sess.go:986
2022-10-31T08:20:48-11:00 DEBU [NODE]      Got continue signal id:1 local:x.x.x.x:40432 login:root remote:y.y.y.y:53202 teleportUser:admin1 srv/sess.go:1002
2022-10-31T08:20:48-11:00 DEBU             Will join session c56e5883-67c7-44d5-90af-c758dd2492c8 for SSH connection y.y.y.y:53202. srv/ctx.go:542
2022-10-31T08:20:48-11:00 DEBU [SESSION:N] Copying from PTY to writer completed with error read /dev/ptmx: input/output error. srv/sess.go:917
2022-10-31T08:20:48-11:00 INFO [SESSION:N] Stopping session c56e5883-67c7-44d5-90af-c758dd2492c8. srv/sess.go:623
2022-10-31T08:20:48-11:00 DEBU [SESSION:N] Copying from reader to PTY completed with error <nil>. srv/sess.go:925
2022-10-31T08:20:48-11:00 DEBU [NODE]      Exec request ("/proc/self/exe") complete: 255 id:1 local:x.x.x.x:40432 login:root remote:y.y.y.y:53202 teleportUser:admin1 regular/sshserver.go:1570
2022-10-31T08:20:48-11:00 DEBU [NODE]      Releasing associated resources - context has been closed. id:1 local:x.x.x.x:40432 login:root remote:y.y.y.y:53202 teleportUser:admin1 srv/monitor.go:253
```
I have updated one of the nodes to version `teleport 11.0.1` but with the same outcome.

I have other arch nodes running and working the only difference is the LTS version.
**working node details:**
``` 
Arch Linux, 
kernel: 5.15.75-1-lts
Teleport: 11.0.0
```
I am not seeing the same` /dev/ptmx read error` on the other working nodes.

Any help would be grateful.

Regards

**Comment by zmb3** [comment] 2022-11-02 15:16
Duplicate of #17769 and #17879. This was fixed with #17812.

**Closed by zmb3** 2022-11-02 15:16 UTC
