### ISSUE TITLE
CrashLoopBackOff in Teleport cluster after upgrade to Helm chart v15.3.6 on GCP

### ISSUE THREAD

**Issue by cizara** [gravitational/teleport#41947] opened 2024-05-23 14:45 UTC
After an automatic upgrade of Teleport cluster from `v15.3.5` to `v15.3.6`, the `teleport-auth` and `teleport-proxy` ended in CrashLoopBackOff.

The log stated:
```
{"timestamp":"2024-05-23T14:34:09Z","level":"info","caller":"common/teleport.go:661","message":"Starting Teleport with a config file","version":"15.3.6","config_file":"/etc/teleport/teleport.yaml"}
{"timestamp":"2024-05-23T14:34:09Z","level":"warning","caller":"gcp/imds.go:122","message":"Access denied to instance labels, does the instance have compute.instances.get permission?","error":"Required 'compute.instances.get' permission for 'projects/ci-workana/zones/us-east4-a/instances/gke-cluster-ci-cluster-ci-primary-7706f694-0dqx'\n\taccess denied"}
ERROR: initialization failed
	rpc error: code = PermissionDenied desc = The caller does not have permission
```
These permissions aren't documented (or I couldn't find them) and break the deployment in a minor version upgrade.

Maybe related to https://github.com/gravitational/teleport/pull/41246

**Comment by zmb3** [comment] 2024-05-23 17:46
Duplicate of #41954

(I know this was opened first, but that one has more details)

**Closed by zmb3** 2024-05-23 17:46 UTC
Labels: bug

**Comment by cizara** [comment] 2024-05-30 09:14
Hi @zmb3,. sorry to bump this closed issue, but I just upgrade Teleport from `15.3.5` to `15.3.7`  and now I'm getting:

```
Defaulted container "teleport" out of: teleport, wait-auth-update (init)
{"caller":"automaticupgrades/channel.go:65","component":null,"level":"debug","message":"'default' automatic update channel not specified, teleport will serve its version by default.","timestamp":"2024-05-30T09:03:23Z"}
{"timestamp":"2024-05-30T09:03:23Z","level":"info","caller":"common/teleport.go:661","message":"Starting Teleport with a config file","version":"15.3.7","config_file":"/etc/teleport/teleport.yaml"}
{"caller":"lite/lite.go:259","component":"sqlite","level":"debug","message":"Connected to: file:/var/lib/teleport/proc/sqlite.db?_busy_timeout=10000\u0026_sync=FULL\u0026_txlock=immediate, poll stream period: 1s","timestamp":"2024-05-30T09:03:23Z"}
{"caller":"lite/lite.go:310","component":"sqlite","level":"debug","message":"journal_mode=delete, synchronous=2, busy_timeout=10000","timestamp":"2024-05-30T09:03:23Z"}
SDK 2024/05/30 09:03:23 WARN falling back to IMDSv1: operation error ec2imds: getToken, http response error StatusCode: 404, request to EC2 IMDS failed

ERROR REPORT:
Original Error: *url.Error Get &#34;https://compute.googleapis.com/compute/v1/projects/my-project/zones/us-east4-a/instances/gke-cluster-primary-7706f694-cdg9&#34;: compute: Received 403 `Unable to generate access token; IAM returned 403 Forbidden: Permission &#39;iam.serviceAccounts.getAccessToken&#39; denied on resource (or it may not exist).
This error could be caused by a missing IAM policy binding on the target IAM service account.
For more information, refer to the Workload Identity documentation:
	https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity#authenticating_to

`
Stack Trace:
	github.com/gravitational/teleport/lib/cloud/gcp/vm.go:332 github.com/gravitational/teleport/lib/cloud/gcp.(*instancesClient).GetInstance
	github.com/gravitational/teleport/lib/cloud/imds/gcp/imds.go:117 github.com/gravitational/teleport/lib/cloud/imds/gcp.(*InstanceMetadataClient).GetTags
	github.com/gravitational/teleport/lib/cloud/imds/gcp/imds.go:152 github.com/gravitational/teleport/lib/cloud/imds/gcp.(*InstanceMetadataClient).GetHostname
	github.com/gravitational/teleport/lib/service/service.go:940 github.com/gravitational/teleport/lib/service.NewTeleport
	github.com/gravitational/teleport/lib/service/service.go:703 github.com/gravitational/teleport/lib/service.newTeleportProcess
	github.com/gravitational/teleport/lib/service/service.go:719 github.com/gravitational/teleport/lib/service.Run
	github.com/gravitational/teleport/tool/teleport/common/teleport.go:663 github.com/gravitational/teleport/tool/teleport/common.OnStart
	github.com/gravitational/teleport/tool/teleport/common/teleport.go:560 github.com/gravitational/teleport/tool/teleport/common.Run
	github.com/gravitational/teleport/tool/teleport/main.go:33 main.main
	runtime/proc.go:267 runtime.main
	runtime/asm_amd64.s:1650 runtime.goexit
User Message: initialization failed
	Get &#34;https://compute.googleapis.com/compute/v1/projects/my-project/zones/us-east4-a/instances/gke-cluster-primary-7706f694-cdg9&#34;: compute: Received 403 `Unable to generate access token; IAM returned 403 Forbidden: Permission &#39;iam.serviceAccounts.getAccessToken&#39; denied on resource (or it may not exist).
This error could be caused by a missing IAM policy binding on the target IAM service account.
For more information, refer to the Workload Identity documentation:
	https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity#authenticating_to
```

Everything works ok on `15.3.5`.  Let me know if you want me to create a new bug for this

**Comment by mlachevre-pass** [comment] 2024-06-03 15:10
Same issue here. @cizara have you find a workaround ?

**Comment by cizara** [comment] 2024-06-03 15:11
no, I made a rollback. Will create a new issue as there is no response here

**Comment by cizara** [comment] 2024-06-03 15:48
created bug https://github.com/gravitational/teleport/issues/42312
