### ISSUE TITLE
Feature Request: Better Access Controls 

### ISSUE THREAD

**Issue by ekristen** [gravitational/teleport#743] opened 2017-02-01 14:43 UTC
It would be nice to allow certain users access to specific nodes only.

**Comment by kontsevoy** [comment] 2017-02-01 21:50
@ekristen this is already done for the upcoming 2.0 (it's in master). Dupe of #620

**Closed by kontsevoy** 2017-02-01 21:50 UTC

**Comment by ekristen** [comment] 2017-02-01 22:29
Thanks @kontsevoy I apologize, I missed the issue because it was already closed. I'll have to check out the code from master! Thanks.

**Comment by kontsevoy** [comment] 2017-02-01 23:46
@ekristen or wait a few weeks for 2.0 to come out. master doesn't have docs right now.
