### ISSUE TITLE
tsh not honoring installed private cacert

### ISSUE THREAD

**Issue by ckonstanski-olo** [gravitational/teleport#30516] opened 2023-08-15 21:20 UTC
OS: gentoo linux
tsh version: latest from master as of an hour ago

I have a private CA certificate that I need for work at my company. Let's say the PKI domain is `mycompany.local`. Our teleport cluster's certs are issued against this cacert. I have this cert installed on my workstation. It makes curl happy: `curl -v https://teleport.mycompany.local` shows nothing but good news. But `tsh ls` fails with the error shown below.

Expected behavior:

`tsh ls` should recognize my system-installed `mycompany.local` cacert just as curl does.

Current behavior:

When running `tsh ls`:

```
ERROR: connection error: desc = "transport: Error while dialing: failed to dial: connection error: desc = \"transport: Error while dialing: tls: failed to verify certificate: x509: certificate signed by unknown authority\""
```

Bug details:
- Teleport version
    Teleport v14.0.0-dev git:pull-2982-g10ed8e0bdf go1.21.0
    Proxy version: 13.3.1
- Recreation steps
    On a gentoo host:
      grab the above version of teleport from this github source
      Run `make full`
      Install a private cacert (place in `/usr/local/shared/ca-certificates` with a `.crt` extension and run `emerge -1 ca-certificates`)
      Verify that it is installed correctly by testing with curl or some other layer-6 exercising process
      Run `tsh ls` and note if there is a cert error
- Debug logs

```
ERROR REPORT:
Original Error: *trace.TraceErr connection error: desc = &#34;transport: Error while dialing: failed to dial: connection error: desc = \&#34;transport: Error while dialing: tls: failed to verify certificate: x509: certificate signed by unknown authority\&#34;&#34;
Stack Trace:
        github.com/gravitational/teleport/api@v0.0.0/client/client.go:3221 github.com/gravitational/teleport/api/client.GetResourcePage[...]
        github.com/gravitational/teleport/api@v0.0.0/client/client.go:3275 github.com/gravitational/teleport/api/client.GetAllResources[...]
        github.com/gravitational/teleport/lib/client/api.go:2273 github.com/gravitational/teleport/lib/client.(*TeleportClient).ListNodesWithFilters
        github.com/gravitational/teleport/tool/tsh/common/tsh.go:2161 github.com/gravitational/teleport/tool/tsh/common.onListNodes.func1
        github.com/gravitational/teleport/lib/client/api.go:556 github.com/gravitational/teleport/lib/client.RetryWithRelogin
        github.com/gravitational/teleport/tool/tsh/common/tsh.go:2160 github.com/gravitational/teleport/tool/tsh/common.onListNodes
        github.com/gravitational/teleport/tool/tsh/common/tsh.go:1321 github.com/gravitational/teleport/tool/tsh/common.Run
        github.com/gravitational/teleport/tool/tsh/common/tsh.go:545 github.com/gravitational/teleport/tool/tsh/common.Main
        github.com/gravitational/teleport/tool/tsh/main.go:24 main.main
        runtime/proc.go:267 runtime.main
        runtime/asm_amd64.s:1650 runtime.goexit
User Message: connection error: desc = &#34;transport: Error while dialing: failed to dial: connection error: desc = \&#34;transport: Error while dialing: tls: failed to verify certificate: x509: certificate signed by unknown authority\&#34;&#34;
```

**Comment by zmb3** [comment] 2023-08-15 21:59
This is probably not related to your problem, but note that you are running a newer version of `tsh` than your cluster is running, which is not officially supported.

**Comment by ckonstanski-olo** [comment] 2023-08-15 23:26
That's valid. But the error just showed up very recently. I've been running from master for a while now. I could step back one commit at a time until it works, and then I'd know which commit caused it.

**Comment by zmb3** [comment] 2023-08-15 23:45
It may also be that you recently upgraded to Go 1.21 which has some
changes in crypto/tls

**Comment by ckonstanski-olo** [comment] 2023-08-16 02:36
Downgrading to go-1.20.7 did nothing. So I re-upgraded to go-1.21.0 and looked for a teleport commit where it went from working to broken. Found it at `ff6a81a8bd2157beb624bc412c0ed696b26d7e43`.

```
commit ff6a81a8bd2157beb624bc412c0ed696b26d7e43
Author: rosstimothy <39066650+rosstimothy@users.noreply.github.com>
Date:   Tue Aug 8 22:10:44 2023 -0400

    Removes support for legacy ssh connections to the Proxy (#30043)
    
    In preparation for v14 we can remove support for SSH connections
    to the Proxy from the `api/proxy.Client` since all supported instances
    should all be serving the TransportService.
```

**Comment by zmb3** [comment] 2023-08-16 13:46
Ah, that is to be expected then (you're running an unreleased tsh from master which contains code that will be in our v14 release)

**Comment by ckonstanski-olo** [comment] 2023-08-16 14:16
OK, closing this bug and checking out v13. Cautiously optimistic that this issue will not occur once we get our proxy on v14.

**Comment by ckonstanski-olo** [comment] 2023-08-16 15:09
`tross/client_system_store` breaks.

**Comment by ckonstanski-olo** [comment] 2023-08-16 16:04
I get the exact same error as outlined at the top of this bug report.

```
ERROR REPORT:
Original Error: *trace.TraceErr connection error: desc = &#34;transport: Error while dialing: failed to dial: connection error: desc = \&#34;transport: Error while dialing: tls: failed to verify certificate: x509: certificate signed by unknown authority\&#34;&#34;
Stack Trace:
        github.com/gravitational/teleport/api@v0.0.0/client/client.go:3221 github.com/gravitational/teleport/api/client.GetResourcePage[...]
        github.com/gravitational/teleport/api@v0.0.0/client/client.go:3275 github.com/gravitational/teleport/api/client.GetAllResources[...]
        github.com/gravitational/teleport/lib/client/api.go:2273 github.com/gravitational/teleport/lib/client.(*TeleportClient).ListNodesWithFilters
        github.com/gravitational/teleport/tool/tsh/common/tsh.go:2161 github.com/gravitational/teleport/tool/tsh/common.onListNodes.func1
        github.com/gravitational/teleport/lib/client/api.go:556 github.com/gravitational/teleport/lib/client.RetryWithRelogin
        github.com/gravitational/teleport/tool/tsh/common/tsh.go:2160 github.com/gravitational/teleport/tool/tsh/common.onListNodes
        github.com/gravitational/teleport/tool/tsh/common/tsh.go:1321 github.com/gravitational/teleport/tool/tsh/common.Run
        github.com/gravitational/teleport/tool/tsh/common/tsh.go:545 github.com/gravitational/teleport/tool/tsh/common.Main
        github.com/gravitational/teleport/tool/tsh/main.go:24 main.main
        runtime/proc.go:267 runtime.main
        runtime/asm_amd64.s:1650 runtime.goexit
User Message: connection error: desc = &#34;transport: Error while dialing: failed to dial: connection error: desc = \&#34;transport: Error while dialing: tls: failed to verify certificate: x509: certificate signed by unknown authority\&#34;&#34;
```

**Comment by ckonstanski-olo** [comment] 2023-08-17 16:43
Ubuntu and gentoo differ in how they manage certs written to `/usr/local/shared/ca-certificates` and installed via `update-ca-certificates`. Ubuntu adds the cert to the `/etc/ssl/certs/ca-certificates.pem` bundle. But gentoo doesn't do this. Instead it symlinks `/usr/local/shared/ca-certificates/<cert_CN>.crt` to `/etc/ssl/certs/<cert_CN>.pem`. Could this be a distinction with a difference?

**Comment by ckonstanski-olo** [comment] 2023-08-17 19:00
I'm poking several gentoo systems really hard with a stick and some cracks are beginning to show around cacert handling. Nothing concrete to share yet.

**Comment by ckonstanski-olo** [comment] 2023-08-31 14:22
No good. Tried with both the latest from `HEAD` and also the initial breaking commit `ff6a81a8bd2157beb624bc412c0ed696b26d7e43`. Interestingly I get a somewhat different error with `HEAD`. There is the addition of a proxy error.

`HEAD`:
```
$ SSL_CERT_DIR=/etc/ssl/certs SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt tsh ls -v
ERROR: connection error: desc = "transport: Error while dialing: failed to dial: unable to establish proxy stream\n\trpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: tls: failed to verify certificate: x509: certificate signed by unknown authority\""
```

`ff6a81a8bd2157beb624bc412c0ed696b26d7e43`:
$ SSL_CERT_DIR=/etc/ssl/certs SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt tsh ls -v
ERROR: connection error: desc = "transport: Error while dialing: failed to dial: connection error: desc = \"transport: Error while dialing: tls: failed to verify certificate: x509: certificate signed by unknown authority\""
```

**Comment by ckonstanski-olo** [comment] 2023-09-05 16:16
Re-reading this thread to see if I missed anything. I am indeed on go 1.21. Also I never mentioned that I can successfully do a `tsh login`. One would think that it should be susceptible to the same issue, but it isn't.

Looking for the go 1.21 changelog to see if there's anything I can do on the platform side.

**Comment by ckonstanski-olo** [comment] 2023-09-11 01:41
I reproduced the issue with Debian 12 unstable and go 1.21.1. The behavior is identical to gentoo.

**Comment by ckonstanski-olo** [comment] 2023-09-12 16:24
I added my cert to `/usr/local/share/ca-certificates/` and then ran `update-ca-certificates`. Then I verified its existence in the bundle by running `awk -v cmd='openssl x509 -noout -subject' '/BEGIN/{close(cmd)};{print | cmd}' < /etc/ssl/certs/ca-certificates.crt | grep <something_unique_to_my_CN>`.

**Comment by ckonstanski-olo** [comment] 2023-09-15 13:29
Would you like a copy of my debian VM wherein the issue is reproduced?

**Comment by zmb3** [comment] 2023-12-03 18:02
Closing due to inactivity. Feel free to open a new issue if you're still having trouble and have a consistent set of steps we can use to reproduce.

**Closed by zmb3** 2023-12-03 18:02 UTC
Labels: bug
