### ISSUE TITLE
Provide ARM docker images for teleport

### ISSUE THREAD

**Issue by programmerq** [gravitational/teleport#7451] opened 2021-07-01 14:55 UTC
### What

Currently amd64 images are provided at quay.io/gravitational/teleport and quay.io/gravitational/teleport-ent but no ARM images are provided.

Since teleport supports arm, could arm images be added to the build pipeline?

### How

This could be done with multiarch images, or the arm images could be put into an alternate quay repo

### Why

containerized ARM deployment

### Workaround

Custom image building and maintenance (not ideal)

**Comment by benarent** [comment] 2021-07-01 17:27
Duplicate of https://github.com/gravitational/teleport/issues/3384

**Comment by zmb3** [comment] 2022-08-15 16:46
Closing as duplicate.

**Closed by zmb3** 2022-08-15 16:46 UTC
Labels: feature-request, c-sn, A0
