### ISSUE TITLE
Node name doesn't appear in session view when recording at proxy

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#3906] opened 2020-06-25 15:04 UTC
**What happened**: When `session_recording` is set to `proxy`, node names don't appear in the session view.

![2020-06-25-120226__1705x636__maim](https://user-images.githubusercontent.com/897821/85745121-d3756280-b6db-11ea-9cee-bb1bdc9730ed.png)

**What you expected to happen**: Node names should appear. Even if we've changed this view recently (as I understand we have) then the node name/IP address still needs to be easily visible in the UI.

**How to reproduce it (as minimally and precisely as possible)**: Log into a node with `session_recording` set to `proxy`. Observe.

### Environment
- Teleport version (use `teleport version`): `Teleport Enterprise v4.3.0-master.1git:v4.2.0-alpha.5-444-g3976a9977-dirty go1.13.2`

**Comment by webvictim** [comment] 2022-05-16 14:11
This is still an issue in 9.2.3 FYI - but the node names appear as `N/A` now.

**Comment by Joerger** [comment] 2022-05-17 17:59
We use the `session.end` event to get this data, and it looks like right now the hostname is being set from the ssh server info. In forwarding mode, this is the forwarding server. 

So this needs to be fixed by retrieving the node data from the Node rather than the Proxy. The node being connected to must be somewhere in the forwarding call-stack, and from that point onward we should propogate the underlying node's info (probably in the `ServerContext`) so it's available to the forwarding server.

Also, this is showing `N/A` because the forwarding server does not set it's hostname in its `GetInfo` method - https://github.com/gravitational/teleport/blob/414c82a34161839210496afca938af2649f5b89b/lib/srv/forward/sshserver.go#L415-L428

This doesn't appear to be a regression - I scanned through the past several major releases.

**Closed** 2022-07-28 11:05 UTC
Labels: ux, good-starter-issue, hornet
