### ISSUE TITLE
Teleport Go client keeps giving context deadline exceeded

### ISSUE THREAD

**Issue by narang99** [gravitational/teleport#15194] opened 2022-08-04 06:51 UTC
Im using the teleport Go client along with tbot.    
The Go client basically reads the Identity file dumped by tbot and authenticates with the server.   
The issue is that it is very unreliable, it works sometimes and many times it errors out with Context Deadline Exceeded errors.  

There is no change in code between the scenarios, I dont know why this keeps happening.  

The relevant code is this:
```go
func GetClient() (*client.Client, context.Context, error) {
	ctx := context.Background()
	clt, err := client.New(ctx, client.Config{
		Addrs: []string{
			AUTH_SERVER,
		},
		Credentials: []client.Credentials{
			client.LoadIdentityFile(IDENTITY_FILE),
		},
	})

	if err != nil {
		fmt.Println("Failed to create the client")
		return nil, nil, err
	}

	return clt, ctx, err
}
```

Note: I create the client on every request to the server because of the rotating Identity File and currently no problems with the performance aspect of it

Thanks!

**Comment by strideynet** [comment] 2022-08-04 10:39
We probably need a little more detail to investigate this, as it could be caused by a genuine connectivity issue between where your client is running and the Teleport server. I believe the default deadline for connections is quite generous (30 seconds), so this should work in most cases. Do you experience the same issue when your code is running on the same host as the one you are connecting to ? Do you have redacted logs available from the host you are connecting to ?

**Comment by narang99** [comment] 2022-08-05 06:49
Both the client and the auth server run on AWS. the host hasn't changed.   
You want me to get logs from the auth server?  Do you mean this file: `/var/lib/teleport/log/` from the auth server host?

**Comment by jnavarrof** [comment] 2023-03-09 12:34
Same problem using `tsh`. 

```shell
✗  tsh --debug --proxy $PROXY --user $USER login $CLUSTER
2023-03-09T12:32:15Z DEBU [TSH]       Web proxy port was not set. Attempting to detect port number to use. tsh/tsh.go:3584
2023-03-09T12:32:15Z DEBU [TSH]       Resolving default proxy port (insecure: false) tsh/resolve_default_addr.go:112
2023-03-09T12:32:15Z DEBU [TSH]       Trying $PROXY:3080... tsh/resolve_default_addr.go:100
2023-03-09T12:32:15Z DEBU [TSH]       Trying $PROXY:443... tsh/resolve_default_addr.go:100
2023-03-09T12:32:20Z DEBU [TSH]       Waiting for all in-flight proxy address tests to finish tsh/resolve_default_addr.go:141
2023-03-09T12:32:20Z DEBU [TSH]       Proxy address test failed error:[Get "$PROXY:3080/webapi/ping": context deadline exceeded] tsh/resolve_default_addr.go:64
2023-03-09T12:32:20Z DEBU [TSH]       Proxy address test failed error:[Get "$PROXY:443/webapi/ping": context deadline exceeded] tsh/resolve_default_addr.go:64

ERROR REPORT:
Original Error: context.deadlineExceededError context deadline exceeded
Stack Trace:
	github.com/gravitational/teleport/tool/tsh/tsh.go:3591 main.setClientWebProxyAddr
	github.com/gravitational/teleport/tool/tsh/tsh.go:3263 main.makeClientForProxy
	github.com/gravitational/teleport/tool/tsh/tsh.go:3152 main.makeClient
	github.com/gravitational/teleport/tool/tsh/tsh.go:1530 main.onLogin
	github.com/gravitational/teleport/tool/tsh/tsh.go:1110 main.Run
	github.com/gravitational/teleport/tool/tsh/tsh.go:487 main.main
	runtime/proc.go:250 runtime.main
	runtime/asm_amd64.s:1594 runtime.goexit
User Message: context deadline exceeded
```

**Comment by strideynet** [comment] 2023-05-03 09:17
This confusing error is likely caused by https://github.com/gravitational/teleport/issues/25535

Try adding `grpc.WithReturnConnectionError()` to your client's DialOpts, e.g:

```go
	cfg := client.Config{
		Addrs: []string{proxyAddr},
		Credentials: []client.Credentials{
			client.LoadIdentityFile(identityFilePath),
		},
		DialOpts: []grpc.DialOption{
			grpc.WithReturnConnectionError(),
		},
```

**Comment by strideynet** [comment] 2023-05-03 09:17
Closing as dupe of #25535

**Closed by strideynet** 2023-05-03 09:17 UTC
Labels: bug, machine-id
