### ISSUE TITLE
Unit tests appear to use live data (instead of fixtures)

### ISSUE THREAD

**Issue by kontsevoy** [gravitational/teleport#1414] opened 2017-10-17 00:37 UTC
I have tried to run unit tests on a machine which actually had teleport installed and running (i.e. `/var/lib/teleport` was "occupied"). The unit tests failed:

```
----------------------------------------------------------------------
FAIL: configuration_test.go:535: ConfigTestSuite.TestPermitUserEnvironment

configuration_test.go:575:
    c.Assert(err, check.IsNil, comment)
... value *trace.TraceErr = &trace.TraceErr{Err:(*trace.AccessDeniedError)(0xc42037c130), Traces:trace.Traces{trace.Trace{Path:"/home/ekontsevoy/go/src/github.com/gravitational/teleport/lib/utils/utils.go", 
Func:"github.com/gravitational/teleport/lib/utils.ReadPath", Line:61}, trace.Trace{Path:"/home/ekontsevoy/go/src/github.com/gravitational/teleport/lib/config/configuration.go", 
Func:"github.com/gravitational/teleport/lib/config.ApplyFileConfig", Line:299}, trace.Trace{Path:"/home/ekontsevoy/go/src/github.com/gravitational/teleport/lib/config/configuration.go", 
Func:"github.com/gravitational/teleport/lib/config.Configure", Line:633}, trace.Trace{Path:"/home/ekontsevoy/go/src/github.com/gravitational/teleport/lib/config/configuration_test.go", 
Func:"github.com/gravitational/teleport/lib/config.(*ConfigTestSuite).TestPermitUserEnvironment", Line:574}, trace.Trace{Path:"/opt/go/src/runtime/asm_amd64.s", Func:"runtime.call32", Line:514}, trace.Trace{Path:"/opt/go/src/reflect/value.go", Func:"reflect.Value.call", Line:437}, trace.Trace{Path:"/opt/go/src/reflect/value.go", Func:"reflect.Value.Call", Line:302}, trace.Trace{Path:"/home/ekontsevoy/go/src/github.com/gravitational/teleport/vendor/gopkg.in/check.v1/check.go", 
Func:"github.com/gravitational/teleport/vendor/gopkg.in/check%2ev1.(*suiteRunner).forkTest.func1", Line:764}, trace.Trace{Path:"/home/ekontsevoy/go/src/github.com/gravitational/teleport/vendor/gopkg.in/check.v1/check.go", 
Func:"github.com/gravitational/teleport/vendor/gopkg.in/check%2ev1.(*suiteRunner).forkCall.func1", Line:658}, trace.Trace{Path:"/opt/go/src/runtime/asm_amd64.s", 
Func:"runtime.goexit", Line:2198}}, Message:"open /var/lib/teleport/webproxy_cert.pem: permission denied"} ("open /var/lib/teleport/webproxy_cert.pem: permission denied")
... Test 0

OOPS: 10 passed, 1 FAILED
--- FAIL: TestConfig (0.01s)
FAIL
```

Looks like this test actually goes into `/var/lib/teleport` instead of using a temporary directory or something....

**Comment by russjones** [comment] 2018-01-13 01:55
I could not reproduce this issue. I think it's because of the changes we made recently in how the web proxies certificate is loaded.

I'm going to close this for now, let's re-open it if we can reproduce it in the future.

**Closed by russjones** 2018-01-13 01:55 UTC
Labels: P2, test problem
