### ISSUE TITLE
Provide SCP terminal interaction to show progress

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#7956] opened 2021-08-18 01:16 UTC
### What
Provide the progress of SCP uploads to match the regular SCP interaction.

### How
Provide a interface output like regular sCP

### Why
This shows progress of the SCP whereas now you don't get a in-progress indicator.

### Workaround
use scp with ssh client enabled with Teleport

**Comment by zmb3** [comment] 2022-08-10 21:02
Closing as duplicate of #2009

**Closed by zmb3** 2022-08-10 21:02 UTC
Labels: feature-request, ux, tsh, scp, cli
