### ISSUE TITLE
Application service disappeared after upgrade.

### ISSUE THREAD

**Issue by Venture200** [gravitational/teleport#42677] opened 2024-06-10 08:55 UTC
Expected behavior:
Application Service should be always there

Current behavior:
Application Service either doesn't show up/appears/disappears

Bug details:
- Teleport version
v15.3.7

- Recreation steps
Apply the configs

- Debug logs
```
Jun 10 08:31:28 redacted teleport[1113]: 2024-06-10T08:31:28Z INFO [NODE:1:CA] Cache "node" first init succeeded. cache/cache.go:1001
Jun 10 08:31:28 redacted teleport[1113]: 2024-06-10T08:31:28Z INFO [NODE:1]    Service is starting in tunnel mode. pid:1113.1 service/service.go:2886
Jun 10 08:31:28 redacted teleport[1113]: 2024-06-10T08:31:28Z INFO [APP:SERVI] Cache "apps" first init succeeded. cache/cache.go:1001
Jun 10 08:31:29 redacted teleport[1113]: 2024-06-10T08:31:29Z INFO [NODE]      Creating (interactive) session 1b3030f8-2666-4c5e-8723-f2e63da2f35f. id:1 idle:4h0m0s local:redacted:36072 login:opsadmin remote:redacted:30454 teleportUser:redacted srv/sess>
Jun 10 08:31:29 redacted teleport[1113]: 2024-06-10T08:31:29Z INFO [SESSION:N] New party ServerContext(redacted:30454->redacted:36072, user=opsadmin, id=1) party(id=41a4e6dd-25a6-4d53-af53-7418825701e2) joined the session with participant mode: peer. s>
Jun 10 08:31:29 redacted teleport[1113]: 2024-06-10T08:31:29Z INFO [AUDIT]     session.start addr.remote:redacted:30454 cluster_name:redacted code:T2000I ei:0 event:session.start initial_command:[] login:opsadmin namespace:default private_>
Jun 10 08:31:29 redacted teleport[1113]: 2024-06-10T08:31:29Z INFO [AZURE:FWD] Failed to load workload identity. Using managed identity. pid:1113.1 error:[no client ID specified. Check pod configuration or set ClientID in the options] azure/credential.go:70
Jun 10 08:31:29 redacted teleport[1113]: 2024-06-10T08:31:29Z INFO [APP:SERVI] All applications successfully started. pid:1113.1 service/service.go:5702
Jun 10 08:31:29 redacted teleport[1113]: 2024-06-10T08:31:29Z INFO [PROC:1]    The new service has started successfully. Starting syncing rotation status. pid:1113.1 sync_interval:10m0s service/connect.go:648
Jun 10 08:31:29 redacted teleport[1113]: 2024-06-10T08:31:29Z WARN             Inventory control stream failed: inventory control stream closed: control stream not configured to support app server heartbeats inventory/inventory.go:198
Jun 10 08:33:26 redacted teleport[1113]: 2024-06-10T08:33:26Z WARN             roles ot0_vc-ssh,ot0_administrator,ot0_access-administrator,default-implicit-role can not forward agent for opsadmin regular/sshserver.go:1931
```

Teleport yaml file

```
version: v3
teleport:
  nodename: redacted
  data_dir: /var/lib/teleport
  join_params:
    token_name: welcome123
    method: token
  proxy_server: redacted:443
  log:
    output: stderr
    severity: INFO
    format:
      output: text
  ca_pin: ""
  diag_addr: "127.0.0.1:3000"
auth_service:
  enabled: "no"
ssh_service:
  enabled: "yes"
  labels:
    application: "repo"
    environment: "prod"
    zone: "ot0"
  commands:
  - name: hostname
    command: [hostname]
    period: 1h
  - name: teleport
    command: ["/bin/sh", "-c", "teleport version | cut -d \' \' -f2"]
    period: 1h
app_service:
    enabled: yes
    debug_app: true
    apps:
    - name: repo
      description: "Nexus Repository"
      public_addr: redacted
      uri: http://127.0.0.1:8081
      labels:
        application: repo
        environment: prod
        zone: ot0
      insecure_skip_verify: true
      rewrite:
        headers:
        - "x-proxy-user: {{internal.kubernetes_users}}"
proxy_service:
  enabled: "no"
```

**Comment by zmb3** [comment] 2024-06-10 13:37
Duplicate of #42040

**Closed by zmb3** 2024-06-10 13:37 UTC
Labels: bug

**Comment by Venture200** [comment] 2024-06-10 13:46
@zmb3 it doesn't happen to my other applications, two specific ones got affected
