### ISSUE TITLE
Teleport nodes unable to join cluster on 6.1.2

### ISSUE THREAD

**Issue by Aharic** [gravitational/teleport#6665] opened 2021-04-29 22:26 UTC
### Description

**What happened**:
When a brand new teleport ssh node is spun up, it cannot join the cluster even if a valid token and CA pin are configured. Dialing the auth server through tunnel repeats the error: ```Get "https://teleport.cluster.local/v2/domain": ssh: handshake failed: no matching keys found.```

**What you expected to happen**:
Node should be able to join Teleport cluster with valid token and CA pin.

### Server Details
- Teleport version (run `teleport version`): 6.1.2

### Client Details
- Tsh version (`tsh version`): 6.1.2

### Debug Logs
Please include or attach debug logs, when appropriate. Obfuscate sensitive information!
```
NFO             Generating new host UUID: 7a477fca-a031-4055-93ac-4d34678bb8d1. service/service.go:596
DEBU [SQLITE]    Connected to: file:/var/lib/teleport/proc/sqlite.db?_busy_timeout=10000&_sync=OFF, poll stream period: 1s lite/lite.go:172
DEBU [SQLITE]    Synchronous: 0, busy timeout: 10000 lite/lite.go:217
DEBU [KEYGEN]    SSH cert authority started with no keys pre-compute. native/native.go:103
DEBU [PROC:1]    Adding service to supervisor. service:register.node service/supervisor.go:184
DEBU [PROC:1]    Adding service to supervisor. service:ssh.node service/supervisor.go:184
DEBU [PROC:1]    Adding service to supervisor. service:ssh.shutdown service/supervisor.go:184
DEBU [PROC:1]    Adding service to supervisor. service:common.rotate service/supervisor.go:184
DEBU [PROC:1]    Service has started. service:ssh.node service/supervisor.go:245
DEBU [PROC:1]    No signal pipe to import, must be first Teleport process. service/service.go:781
DEBU [PROC:1]    Service has started. service:register.node service/supervisor.go:245
INFO [PROC:1]    Joining the cluster with a secure token. service/connect.go:353
DEBU [PROC:1]    Generating new key pair for Node first-time-connect. service/connect.go:261
DEBU [PROC:1]    Service has started. service:ssh.shutdown service/supervisor.go:245
DEBU [PROC:1]    Service has started. service:common.rotate service/supervisor.go:245
DEBU [AUTH]      Registering node to the cluster. auth-servers:[{proxy.example.com:443 tcp }] auth/register.go:125
DEBU [AUTH]      The first specified auth server appears to be a proxy. auth/register.go:139
INFO [AUTH]      Attempting registration via proxy server. auth/register.go:145
DEBU [CLIENT]    HTTPS client init(proxyAddr=proxy.example.com:443, insecure=false) client/weblogin.go:211
INFO [AUTH]      Successfully registered via proxy server. auth/register.go:152
DEBU [PROC:1]    Deleted generated key pair Node first-time-connect. service/connect.go:247
INFO [PROC:1]    Node has obtained credentials to connect to cluster. service/connect.go:382
DEBU [PROC:1]    Attempting to connect to Auth Server directly. service/connect.go:810
DEBU [PROC:1]    Failed to connect to Auth Server directly. service/connect.go:816
DEBU [PROC:1]    Attempting to connect to Auth Server through tunnel. proxy.example.com:3024 service/connect.go:837
DEBU [HTTP:PROX] No valid environment variables found. proxy/proxy.go:207
DEBU [HTTP:PROX] No valid environment variables found. proxy/proxy.go:207
DEBU [HTTP:PROX] No proxy set in environment, returning direct dialer. proxy/proxy.go:122
DEBU [HTTP:PROX] No proxy set in environment, returning direct dialer. proxy/proxy.go:122
WARN [PROC:1]    Failed to close Auth Server tunnel client. error:[<nil>] service/connect.go:926
DEBU [PROC:1]    Failed to connect to Auth Server through tunnel. proxy-addr:proxy.example.com:3024 service/connect.go:840
ERRO [PROC:1]    Node failed to establish connection to cluster: Get "https://teleport.cluster.local/v2/domain": x509: certificate is valid for ingress.local, not 706c6174666f726d2d6d616e6167656d656e742d73746167696e67.teleport.cluster.local, Get "https://teleport.cluster.local/v2/domain": ssh: handshake failed: no matching keys found. service/connect.go:67
```
From here it just repeats over and over again.

**Comment by Aharic** [comment] 2021-04-29 22:27
Related to bug #6272

**Comment by Joerger** [comment] 2021-04-29 22:31
It looks like they are trying to connect through tunnel, so the actual error here is `Get "https://teleport.cluster.local/v2/domain": ssh: handshake failed: no matching keys found.`. The other error is there in case you are actually trying to connect to the auth server. Sorry for the confusion, I'll try to clear up this aggregated error in another PR.

**Comment by Aharic** [comment] 2021-06-12 02:07
An issue matching the same logs and trace was discovered this evening while troubleshooting in another network running on 6.1.5 

Following information was captured during the troubleshoot session:

On the auth server we see the following when the node attempts to register:

```
INFO [CA]        Generating TLS certificate {0x475b548 0xc001b5c020 1.3.9999.1.7=#1320666c79776865656c2d74656c65706f72742d75732e666c79776865656c2e696f,CN=37a9710a-3063-4a79-b3b1-b64426b38aed.cluster-name.example.com,O=Node,POSTALCODE=null,STREET= 2031-06-09 20:07:44.588259741 +0000 UTC [node01 37a9710a-3063-4a79-b3b1-b64426b38aed]}. common_name:37a9710a-3063-4a79-b3b1-b64426b38aed.cluster-name.example.com dns_names:[node01 37a9710a-3063-4a79-b3b1-b64426b38aed] locality:[] not_after:2031-06-09 20:07:44.588259741 +0000 UTC org:[Node] org_unit:[] tlsca/ca.go:600
INFO [AUTH]      Node "node01" [37a9710a-3063-4a79-b3b1-b64426b38aed] has joined the cluster. auth/auth.go:1536
```

At the same time, on the node we see the following:

```
Jun 11 16:39:01 node01 teleport[18584]: INFO [PROC:1]    Joining the cluster with a secure token. service/connect.go:353
Jun 11 16:39:01 node01 teleport[18584]: DEBU [PROC:1]    Generating new key pair for Node first-time-connect. service/connect.go:261
Jun 11 16:39:02 node01 teleport[18584]: DEBU [AUTH]      Registering node to the cluster. auth-servers:[{proxy.example.com:443 tcp }] auth/register.go:125
Jun 11 16:39:02 node01 teleport[18584]: DEBU [AUTH]      The first specified auth server appears to be a proxy. auth/register.go:139
Jun 11 16:39:02 node01 teleport[18584]: INFO [AUTH]      Attempting registration via proxy server. auth/register.go:145
Jun 11 16:39:02 node01 teleport[18584]: DEBU [CLIENT]    HTTPS client init(proxyAddr=proxy.example.com:443, insecure=false) client/weblogin.go:211
Jun 11 16:39:02 node01 teleport[18584]: INFO [AUTH]      Successfully registered via proxy server. auth/register.go:152
Jun 11 16:39:02 node01 teleport[18584]: DEBU [PROC:1]    Deleted generated key pair Node first-time-connect. service/connect.go:247
Jun 11 16:39:02 node01 teleport[18584]: INFO [PROC:1]    Node has obtained credentials to connect to cluster. service/connect.go:382
Jun 11 16:39:02 node01 teleport[18584]: DEBU [PROC:1]    Attempting to connect to Auth Server directly. service/connect.go:810
Jun 11 16:39:02 node01 teleport[18584]: DEBU [PROC:1]    Failed to connect to Auth Server directly. service/connect.go:816
Jun 11 16:39:02 node01 teleport[18584]: DEBU [PROC:1]    Attempting to connect to Auth Server through tunnel. proxy-addr:proxy.proxy.example.com:3024 service/connect.go:837
Jun 11 16:39:02 node01 teleport[18584]: DEBU [HTTP:PROX] No valid environment variables found. proxy/proxy.go:207
Jun 11 16:39:02 node01 teleport[18584]: DEBU [HTTP:PROX] No proxy set in environment, returning direct dialer. proxy/proxy.go:122
Jun 11 16:39:02 node01 teleport[18584]: DEBU [HTTP:PROX] No valid environment variables found. proxy/proxy.go:207
Jun 11 16:39:02 node01 teleport[18584]: DEBU [HTTP:PROX] No proxy set in environment, returning direct dialer. proxy/proxy.go:122
Jun 11 16:39:32 node01 teleport[18584]: WARN [PROC:1]    Failed to close Auth Server tunnel client. error:[<nil>] service/connect.go:926
Jun 11 16:39:32 node01 teleport[18584]: DEBU [PROC:1]    Failed to connect to Auth Server through tunnel. proxy-addr:proxy.proxy.example.com:3024 service/connect.go:840
Jun 11 16:39:32 node01 teleport[18584]: ERRO [PROC:1]    Node failed to establish connection to cluster: Get "https://teleport.cluster.local/v2/domain": x509: certificate is valid for ingress.local, not 666c79776865656c2d74656c65706f72742d75732e666c79776865656c2e696f.teleport.cluster.local, Get "https://teleport.cluster.local/v2/domain": dial tcp 35.xx.xx.xx:3024: i/o timeout. service/connect.go:67
```

The node appears to be failing on the [newClientThroughTunnel](https://github.com/gravitational/teleport/blob/7bff7c41bda0f36898e9063aaacd5539ce062489/lib/service/connect.go#L914) function. 

From here we dug into the contents of the sqlite.db file in the /var/lib/teleport/proc directory to check the contents of the certs obtained from the auth and confirm the credentials being presented to the proxy, but found all three tables completely empty.

**Comment by Joerger** [comment] 2021-06-14 20:49
@Aharic The first error can be ignored, so the error to look into is `Get "https://teleport.cluster.local/v2/domain": dial tcp 35.xx.xx.xx:3024: i/o timeout`.

My PR (#6722) to clarify these errors wasn't backported to v6 yet, my apologies. Can you try having the customer run a debug build of this PR branch - #7295? This should be pushed into the next 6.2 patch release and will help in debugging issues like this.

**Comment by Joerger** [comment] 2021-06-15 17:52
I'm going to close this issue since it has been an issue of misleading errors and should be resolved by previous fixes.

Make sure to look at the 2 aggregated errors after `Node failed to establish connection to cluster`. The first is for direct auth dialing and the second is for remote auth dialing. Decide which is the cause of the bug, and then make a new issue for that specific error if needed.

Once the clarifying changes mentioned above are released, it should be even easier to differentiate the errors with separate stack traces.

**Closed by Joerger** 2021-06-15 17:52 UTC
Labels: bug, c-vw
