### ISSUE TITLE
Provide systemd service that maintains user sessions

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#30723] opened 2023-08-19 12:14 UTC
What would you like Teleport to do?

The Teleport systemd configuration supports maintaining sessions with a service restart. 

What problem does this solve?

Allows for sessions to persist with a service restart.  The default configuration will kill SSH and other user sessions. Typically restarted after a upgrade.  This is the same behavior supported by `sshd`. Currently admins have to manually run a process as described in https://goteleport.com/docs/management/admin/upgrading-the-teleport-binary/.  This would also make automatic upgrades more palatable as they could allow for persisting sessions.

If a workaround exists, please include it.

Admins have to configure the systemd service to support this or manually

**Comment by zmb3** [comment] 2023-09-26 19:27
Duplicate of #8184

**Closed by zmb3** 2023-09-26 19:27 UTC
Labels: feature-request
