### ISSUE TITLE
`--bootstrap` should not fail with a leaf `cert_authority` object.

### ISSUE THREAD

**Issue by programmerq** [gravitational/teleport#33715] opened 2023-10-19 18:48 UTC
When a cluster has a `trusted_cluster` there is a `cert_authority` object that gets created in the storage backend that holds only the public keys.

When changing backends while following [this guide in the docs](https://goteleport.com/docs/management/operations/backup-restore/#migrating-backends), users are instructed to export the current state, and then import it into a fresh backend instance with `teleport start --bootstrap ...`

The `tctl get all --with-secrets` will return users, roles, cert_authorities, and connectors. That includes any `cert_authority` objects that belong to clusters other than this cluster, but they do not (and should not) have private keys. When the bootstrap is attempted, the following error can happen:

```console
% teleport start -d --bootstrap bootstrap.yaml
2023-10-19T10:25:39-04:00 INFO             Using license from /var/lib/teleport/license.pem expires at 2122-05-18 00:18:40 +0000 UTC,supports kubernetes,supports application access,supports database access,supports desktop access. process/license.go:46
2023-10-19T10:25:39-04:00 DEBU [SQLITE]    Connected to: file:/var/lib/teleport/proc/sqlite.db?_busy_timeout=10000&_sync=FULL&_txlock=immediate, poll stream period: 1s lite/lite.go:254
2023-10-19T10:25:39-04:00 DEBU [SQLITE]    journal_mode=delete, synchronous=2, busy_timeout=10000 lite/lite.go:305
2023-10-19T10:25:40-04:00 DEBU [PROC:1]    Using sqlite backend. pid:42762.1 service/service.go:5437
2023-10-19T10:25:40-04:00 DEBU [SQLITE]    Connected to: file:/var/lib/teleport/backend/sqlite.db?_busy_timeout=10000&_sync=FULL&_txlock=immediate, poll stream period: 1s lite/lite.go:254
2023-10-19T10:25:40-04:00 DEBU [SQLITE]    journal_mode=delete, synchronous=2, busy_timeout=10000 lite/lite.go:305
2023-10-19T10:25:40-04:00 DEBU [PROC:1]    Creating in-memory backend for [auth]. pid:42762.1 service/service.go:2181
2023-10-19T10:25:40-04:00 INFO [AUTH]      Applying 24 bootstrap resources (first initialization) auth/init.go:316

ERROR REPORT:
Original Error: *trace.BadParameterError expected PEM-encoded block
Stack Trace:
	github.com/gravitational/teleport/lib/utils/certs.go:111 github.com/gravitational/teleport/lib/utils.ParsePrivateKeyPEM
	github.com/gravitational/teleport/lib/auth/keystore/software.go:70 github.com/gravitational/teleport/lib/auth/keystore.(*softwareKeyStore).getSigner
	github.com/gravitational/teleport/lib/auth/keystore/manager.go:151 github.com/gravitational/teleport/lib/auth/keystore.(*Manager).getSSHSigner
	github.com/gravitational/teleport/lib/auth/keystore/manager.go:131 github.com/gravitational/teleport/lib/auth/keystore.(*Manager).GetSSHSigner
	github.com/gravitational/teleport/lib/auth/init.go:880 github.com/gravitational/teleport/lib/auth.checkResourceConsistency
	github.com/gravitational/teleport/lib/auth/init.go:317 github.com/gravitational/teleport/lib/auth.initCluster
	github.com/gravitational/teleport/lib/auth/init.go:293 github.com/gravitational/teleport/lib/auth.Init.func1
	github.com/gravitational/teleport/lib/backend/helpers.go:220 github.com/gravitational/teleport/lib/backend.RunWhileLocked
	github.com/gravitational/teleport/lib/auth/init.go:284 github.com/gravitational/teleport/lib/auth.Init
	github.com/gravitational/teleport/lib/service/service.go:1732 github.com/gravitational/teleport/lib/service.(*TeleportProcess).initAuthService
	github.com/gravitational/teleport/lib/service/service.go:1086 github.com/gravitational/teleport/lib/service.NewTeleport
	github.com/gravitational/teleport/e/tool/teleport/process/process.go:57 github.com/gravitational/teleport/e/tool/teleport/process.NewTeleport
	github.com/gravitational/teleport/lib/service/service.go:685 github.com/gravitational/teleport/lib/service.Run
	github.com/gravitational/teleport/e/tool/teleport/main.go:28 main.main
	runtime/proc.go:267 runtime.main
	runtime/asm_amd64.s:1650 runtime.goexit
User Message: initialization failed
	refusing to bootstrap backend
		expected PEM-encoded block
```

I ran this in a debugger and found that it was failing on the one `cert_authority` object that had no `privake_key` data, and had a different cluster name than the other `cert_authority` objects. Removing the offending yaml document allowed Teleport to bootstrap properly.

Example:

```yaml
---
kind: cert_authority
metadata:
  id: 1697654000000000000
  name: realcluster.example.com
spec:
  active_keys:
    ssh:
    - private_key: LS0tLS...
      public_key: c3NoLX...
    tls:
    - cert: LS0tLS...
      key: LS0tLS...
  additional_trusted_keys: {}
  cluster_name: realcluster.example.com
  type: host
sub_kind: host
version: v2
---
kind: cert_authority
metadata:
  id: 1697654000000000001
  name: othercluster.example.com
spec:
  active_keys:
    ssh:
    - public_key: c3NoLX...
    tls:
    - cert: LS0tLS...
  additional_trusted_keys: {}
  cluster_name: othercluster.example.com
  type: host
sub_kind: host
version: v2
```

```console
% teleport version
Teleport Enterprise v14.0.3 git:v14.0.3-0-g4d1c2ac go1.21.3
```

**Comment by stevenGravy** [comment] 2023-10-25 12:35
Duplicate of https://github.com/gravitational/teleport/issues/9547

**Closed** 2023-10-25 18:47 UTC
Labels: bug
