### ISSUE TITLE
GPG Error

### ISSUE THREAD

**Issue by Alex-Giaquinto** [gravitational/teleport#34171] opened 2023-11-02 19:59 UTC
Expected behavior: Install teleport

Current behavior:
`Err:4 https://apt.releases.teleport.dev/ubuntu jammy InRelease
  Unknown error executing apt-key`
`W: GPG error: https://apt.releases.teleport.dev/ubuntu jammy InRelease: Unknown error executing apt-key
E: The repository 'https://apt.releases.teleport.dev/ubuntu jammy InRelease' is not signed.`

Bug details:
- Teleport version = 14.1.1
- Recreation steps
- Debug logs

**Comment by Alex-Giaquinto** [comment] 2023-11-02 20:26
@stevenGravy I am using an ec2 running Ubuntu 22.04. Not sure what the issue is here.

**Comment by stevenGravy** [comment] 2023-11-02 20:30
thanks @Alex-Giaquinto , not seeing any issues after a quick deploy. Can you confirm this is up to date machine?  I'd compare if you have another fresh environment.

**Comment by stevenGravy** [comment] 2023-11-02 20:35
No, what region are you seeing this in?

**Comment by Alex-Giaquinto** [comment] 2023-11-02 20:35
us-east-2

**Comment by Alex-Giaquinto** [comment] 2023-11-02 20:37
Weirdly, if I remove the follow `[signed-by=/usr/share/keyrings/teleport-archive-keyring.asc]` from `deb [signed-by=/usr/share/keyrings/teleport-archive-keyring.asc]  https://apt.releases.teleport.dev/ubuntu jammy stable/v14` it works.

**Comment by stevenGravy** [comment] 2023-11-03 10:47
Are you following the install script?

**Comment by Alex-Giaquinto** [comment] 2023-11-03 14:19
Yes I am

**Comment by Alex-Giaquinto** [comment] 2023-11-03 18:18
@stevenGravy is there a way to edit the install script so it skips over adding the repo & key?

**Comment by pschisa** [comment] 2023-11-16 16:10
+1 encountered another case of this, I am also not yet able to recreate

**Comment by mokabaddi** [comment] 2024-01-18 16:38
I had the same problem today and found that it was related to a permissions issue. Replicated on a "fresh" ubuntu22.04 docker container and running the following solves it.

`chmod 644 /usr/share/keyrings/teleport-archive-keyring.asc`

**Comment by mokabaddi** [comment] 2024-01-19 15:47
Further information, if the umask on the system is different to the default, that is when this issue is likely to occur.

Using a vanilla ubuntu image, the umask is 0022. On this instance 
```
root@host:/# umask
0022
```

The system I was having a problem on, the default umask was 0077.

Simple fix is to just chmod the keyring file to make sure it has the correct permissions.

To replicate the issue change the permissions on the keyring file:

```
root@host:/# chmod 600 /usr/share/keyrings/teleport-archive-keyring.asc
root@host:/# apt-get update
Hit:1 https://apt.releases.teleport.dev/ubuntu jammy InRelease
Err:1 https://apt.releases.teleport.dev/ubuntu jammy InRelease
  Unknown error executing apt-key
Hit:2 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:3 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:4 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:5 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Reading package lists... Done
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://apt.releases.teleport.dev/ubuntu jammy InRelease: Unknown error executing apt-key
W: Failed to fetch https://apt.releases.teleport.dev/ubuntu/dists/jammy/InRelease  Unknown error executing apt-key
W: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by bmailhe** [comment] 2024-03-26 14:06
I had the same issue, with a `umask 0027`, I had to `chmod 644 /usr/share/keyrings/teleport-archive-keyring.asc` to fix. I'm running a 
```shell
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
````

**Comment by pschisa** [comment] 2024-08-05 19:28
duplicate of https://github.com/gravitational/teleport/issues/21698#issue-1581013251 maybe?

**Comment by zmb3** [comment] 2024-08-25 00:32
Yes, thanks for identifying the duplicate

**Closed** 2024-08-25 00:32 UTC
Labels: bug, c-vd, c-mzz
