### ISSUE TITLE
Improve visibility  and troubleshooting of SSO login failures

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#47248] opened 2024-10-05 11:32 UTC
Expected behavior:

A unsuccessful SSO login would provide a message that works for a non-admin user and admin. Esp in the case of cloud this can be frustrating as the admin user does not have access the process log, just the Audit log. There should also be some links to troubleshooting. As we know when the person is in cloud this is a good point to let them know about support if they're completely locked out.

Current behavior:

A user is told to check the Teleport log. If I'm someone who just accesses and doesn't administrator Teleport I could have no access to the Teleport log.

![Image](https://github.com/user-attachments/assets/6d4f2e10-c812-4837-b413-4b417117bc12)

Bug details:
- Teleport version: 16.4.2
- Recreation steps

1. Configure a sso login
2. Have a user who's traits do not map to a role
3. Attempt to login

**Comment by zmb3** [comment] 2024-10-07 22:07
Duplicate of https://github.com/gravitational/teleport/issues/17486

**Closed by zmb3** 2024-10-07 22:07 UTC
Labels: bug, sso, error-msg
