### ISSUE TITLE
X11 Forwarding Support

### ISSUE THREAD

**Issue by sjperkins** [gravitational/teleport#2283] opened 2018-10-12 14:42 UTC
Would it be possible for Teleport to support X11 Forwarding as supported by the -X and -Y options in the OpenSSH client?

As I understand it, this is currently only possible by using OpenSSH clients and servers within the Teleport ecosystem, i.e. [Using Teleport with OpenSSH](https://gravitational.com/teleport/docs/admin-guide/#using-teleport-with-openssh). However, this seems to rely on manually exporting teleport public keys to each OpenSSH server's authorized_keys file, which seems suboptimal considering the great Teleport ecosystem.

I realise that https://github.com/gravitational/teleport/issues/308 was closed, but the reason for this seem to revolve around the difficulty of replaying X11 session commands, rather than forwarding X11 pipes. I don't see replaying X11 commands as a necessity but I might be misunderstanding Teleport's architectural model.

**Comment by Wikunia** [comment] 2019-07-12 10:28
X11 forwarding would be really appreciated

**Comment by benarent** [comment] 2020-05-21 16:08
Duplicate of https://github.com/gravitational/teleport/issues/3401

**Closed by benarent** 2020-05-21 16:08 UTC
Labels: feature request
