### ISSUE TITLE
tsh does not appear to respect HTTPS_PROXY

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#9072] opened 2021-11-19 01:46 UTC

**Comment by russjones** [comment] 2021-11-19 01:47
@stevenGravy Can you provide reproduction steps?

**Comment by stevenGravy** [comment] 2021-11-21 16:08
@programmerq has a detailed example here https://gist.github.com/programmerq/d053ae8acde4c7e467b44a32817750ef

**Comment by evilmog** [comment] 2022-02-14 19:05
Confirmed TELEPORT is not honouring HTTPS_PROXY, this is causing some operational problems

**Comment by zmb3** [comment] 2022-06-24 23:05
@r0mant is there anything left to be done for HTTPS_PROXY?

**Comment by zmb3** [comment] 2023-02-20 16:19
My understanding is that this was supposed to be fixed by #10209, but I just tried Jeff's example from above on 12.0.2 and it's not working.

```
[root@680588a42d63 ~]# tsh -d login --user admin --proxy teleport --insecure
DEBU [TSH]       Web proxy port was not set. Attempting to detect port number to use. tsh/tsh.go:3543
DEBU [TSH]       Resolving default proxy port (insecure: true) tsh/resolve_default_addr.go:110
DEBU [TSH]       Trying teleport:3080... tsh/resolve_default_addr.go:98
DEBU [TSH]       Trying teleport:443... tsh/resolve_default_addr.go:98
DEBU [TSH]       Proxy address test failed error:[Get "https://teleport:3080/webapi/ping": context deadline exceeded] tsh/resolve_default_addr.go:62
DEBU [TSH]       Waiting for all in-flight proxy address tests to finish tsh/resolve_default_addr.go:136
DEBU [TSH]       Proxy address test failed error:[Get "https://teleport:443/webapi/ping": context deadline exceeded] tsh/resolve_default_addr.go:62

ERROR REPORT:
Original Error: context.deadlineExceededError context deadline exceeded
Stack Trace:
	github.com/gravitational/teleport/tool/tsh/tsh.go:3550 main.setClientWebProxyAddr
	github.com/gravitational/teleport/tool/tsh/tsh.go:3224 main.makeClientForProxy
	github.com/gravitational/teleport/tool/tsh/tsh.go:3116 main.makeClient
	github.com/gravitational/teleport/tool/tsh/tsh.go:1496 main.onLogin
	github.com/gravitational/teleport/tool/tsh/tsh.go:1086 main.Run
	github.com/gravitational/teleport/tool/tsh/tsh.go:480 main.main
	runtime/proc.go:250 runtime.main
	runtime/asm_arm64.s:1172 runtime.goexit
User Message: context deadline exceeded
```

**Comment by evilmog** [comment] 2023-02-20 16:57
the problem isn't clients logging in to a system, its teleport agents
calling out to teleport proxy servers, we often deploy systems into client
environments where the only way out is a proxy and teleport won't honour
the clients proxy settings

**Comment by zmb3** [comment] 2023-02-20 18:33
This particular issue is specifically about tsh.

**Comment by evilmog** [comment] 2023-02-21 01:05
When I cut my original ticket it was about the teleport agent and then my
request was closed and merged in with this one.

I have an enterprise support agreement. It has taken over a year to get
this reply.

**Comment by russjones** [comment] 2023-02-22 18:38
@evilmog We're looking into it right now, we'll update you soon.

cc @r0mant

**Comment by atburke** [comment] 2023-02-22 23:00
@zmb3 The port guessing issue you found is a bug. #22161 should fix it.

**Closed** 2023-04-05 17:11 UTC
Labels: bug, tsh
