### ISSUE TITLE
kubeconfig has incorrect server when kube_listen_addr set

### ISSUE THREAD

**Issue by fraenkel** [gravitational/teleport#5431] opened 2021-01-28 19:27 UTC
### Description

**What happened**:

I am using a slightly modified aws HA terraform setup with a modified AMI to enable/support kube_listen_addr. `tsh kube ls` shows all the k8s clusters
`tsh kube login xxx` writes the wrong server name.

The config as defined uses the ALB for the public_addr and all xxx_public_addr uses the NLB.
What gets written into the kubeconfig for the server name is https://ALB:3026 which should be https://NLB:3026.

How do I expose a public addr for the kube service?

**What you expected to happen**:

`kubectl get ns` works

**How to reproduce it (as minimally and precisely as possible)**:
### Environment
- Teleport version (use `teleport version`): 5.1
- Tsh version (use `tsh version`): 5.1
- OS (e.g. from `/etc/os-release`): ubuntu

- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware):
AWS

**Comment by fraenkel** [comment] 2021-01-28 20:06
I switched to use
```
  kubernetes:
    enabled: yes
    listen_addr: 0.0.0.0:3026
    public_addr: ["PROXY_LB_SERVER:3026"]
```

and my kubeconfig is now correct.
Why do all the migrations say to switch to kube_listen_addr when it won't work for all situations?

**Comment by awly** [comment] 2021-01-29 00:05
Duplicate of https://github.com/gravitational/teleport/issues/5110

@fraenkel `kube_listen_addr` was a naive shorthand for the common case where the proxy has a single public address. I did not anticipate that the same proxy would have different public addresses for different ports.
Sorry for the confusion.

**Closed by awly** 2021-01-29 00:05 UTC
