### ISSUE TITLE
Have the ability to configure longer MFA sessions. 

### ISSUE THREAD

**Issue by moisesmejia1200** [gravitational/teleport#21552] opened 2023-02-09 17:06 UTC
**What would you like Teleport to do?**

Extend the per-session MFA duration/cache and make it configurable

**What problem does this solve?**

Currently doing a kubectl with per-session MFA means it requires MFA for every k8s action. Instead, it would be better if there was a per-session MFA that could be cached for ~5-10 mins

**If a workaround exists, please include it.**

No current workaround exists.

**Comment by zmb3** [comment] 2023-02-09 17:45
This is a duplicate of #7568

**Closed by zmb3** 2023-02-09 17:45 UTC
Labels: feature-request
