### ISSUE TITLE
`Unrecognized engine name: aurora` error in UI when enrolling Aurora MySQL/MariaDB

### ISSUE THREAD

**Issue by philip-teleport** [gravitational/teleport#30427] opened 2023-08-14 09:55 UTC
Expected behavior:

Successfully enrol an AWS RDS Aurora MySQL/MariaDB database in the web UI.

Current behavior:

When attempting enrol an AWS RDS Aurora MySQL/MariaDB database in the web UI, you hit an error:

`operation error RDS: DescribeDBClusters, https response error StatusCode: 400, RequestID: 4ddb7d1f-a5ec-40d9-92a3-cf639fec433a, api error InvalidParameterValue: Unrecognized engine name: aurora`

![Screenshot 2023-08-14 at 10 51 17](https://github.com/gravitational/teleport/assets/95687564/59470df6-8b54-4489-9fd9-98759c726216)

Bug details:
- Teleport version: 13.3.2

**Comment by zmb3** [comment] 2023-08-14 14:47
See #17533 and #17826

**Comment by greedy52** [comment] 2023-08-14 15:54
Duplicate of https://github.com/gravitational/teleport/issues/29974

**Closed** 2023-08-14 15:56 UTC
Labels: bug, aws, database-access
