### ISSUE TITLE
tctl create database fails when using string tls mode

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#22387] opened 2023-02-28 05:02 UTC
`tctl create` command can't unmarshal string TLS mode.

This doesn't work:

```json
{
  "kind": "db",
  "version": "v3",
  "metadata": {
    ...
  },
  "spec": {
    ...
    "tls": {
      "mode": "verify-ca"
    }
  }
}
```

Error:

```
$ tctl create -f db.json
ERROR: types.DatabaseV3.Spec: types.DatabaseSpecV3.TLS: types.DatabaseTLS.Mode: readUint32: unexpected character: �, error found in #10 byte of ...| "mode": "verify-ca"|..., bigger context ...|.amazonaws.com:3306",
    "tls": {
      "mode": "verify-ca"
    },
```

This works:

```json
{
  "kind": "db",
  "version": "v3",
  "metadata": {
    ...
  },
  "spec": {
    ...
    "tls": {
      "mode": 1
    }
  }
}
```

**Comment by GavinFrazar** [comment] 2023-03-02 22:08
related: when you use `tctl get db` or `tctl get db_server` it also prints the tls mode as an integer. I'll fix that as well.

**Comment by GavinFrazar** [comment] 2023-03-03 02:17
I made a little parser script to collect all the other protobuf types that embed an enum type either directly or transitively, and then compared that with the resources we support updating/creating via `tctl`.

This bug is for:
* `cluster_networking_config`: "proxy_listener_mode" and "routing_strategy"
* `cert_authority`: "signing_alg"
* `database`: "tls -> mode"

**Comment by GavinFrazar** [comment] 2023-03-03 21:34
From discussion in slack, the issue is also present in our terraform provider plugin, i.e. you have to use the number in resource specs:
```terraform
resource "teleport_cluster_networking_config" {
...
  spec = {
    ...
    proxy_listener_mode = 1 # "multiplex"
  }
}
```

**Comment by GavinFrazar** [comment] 2023-03-03 21:37
Fixing tctl here is pretty simple, but I think this highlights the need for a comprehensive solution to handling enums in our protobufs. Slack thread archive for future reference: https://gravitational.slack.com/archives/C0DF0TPMY/p1677795304345939

**Comment by GavinFrazar** [comment] 2023-05-17 00:30
Seeing as editing `cluster_networking_config` with tctl is not supported and doesn't actually make sense, and modifying `cert_authority` signing_alg also doesn't make much sense, I'm just going to close this issue as I've resolved the original issue for database TLS mode.

**Closed by GavinFrazar** 2023-05-17 00:30 UTC
Labels: bug
