### ISSUE TITLE
Add machine ID support for AWS CLI Access

### ISSUE THREAD

**Issue by AritraWork97** [gravitational/teleport#16935] opened 2022-10-03 11:48 UTC
What would you like Teleport to do?
I would like teleport to be able to use short lived credentials to access aws services. Like being able to use tbot
for running aws cli actions.

What problem does this solve?
This enabled using the tsh aws command on remote systems using machine id.

If a workaround exists, please include it.
Don't know if a workaround exists.

**Comment by AritraWork97** [comment] 2023-02-08 02:00
@zmb3 any updates on this? Eagerly looking forward to seeing this being implemented :)

**Comment by strideynet** [comment] 2023-12-15 10:53
Closing as duplicate of https://github.com/gravitational/teleport/issues/35746

**Closed by strideynet** 2023-12-15 10:53 UTC
Labels: feature-request, aws, application-access, c-cs, machine-id
