### ISSUE TITLE
arm64 release binaries

### ISSUE THREAD

**Issue by avsm** [gravitational/teleport#1812] opened 2018-03-23 14:45 UTC
**Environment**:
```
root@arm:~# uname -a
Linux arm2 4.10.0-26-generic #30~16.04.1-Ubuntu SMP Tue Jun 27 09:40:29 UTC 2017 aarch64 aarch64 aarch64 GNU/Linux
```

I'm using the arm64 machines available via packet.net, and the Teleport release binaries published with every release are only arm32 binaries.  Unfortunately, most arm64 hardware cannot execute arm32 code, so it would be most convenient to also have arm64 binaries published if possible.  Meanwhile, I'm compiling up my own so this isn't a blocker or anything.

**Comment by benarent** [comment] 2020-08-18 19:55
Marking as a duplicate of https://github.com/gravitational/teleport/issues/3383

**Comment by lsaavedr** [comment] 2020-10-24 17:10
please add arm64 binaries, I need build teleport in every release to my orangepi 4 machines too... please!

**Closed** 2020-10-29 02:23 UTC
Labels: arm, release-engineering
