### ISSUE TITLE
Teleport Auth connector for Okta SSO configured as IDP initiated and IP-pinning is not working. 

### ISSUE THREAD

**Issue by TeleLos** [gravitational/teleport#35318] opened 2023-12-04 15:47 UTC
Expected behavior:
This SSO configuration should allow a valid user to successfully access their Teleport cluster. 

Current behavior:
Teleport Proxy logs report the error "Pinned IP and client IP mismatch" preventing the user from accessing their Teleport cluster.  In the proxy logs, we observe that the client IP matches the customer's expected Public IP using the command: curl ifconfig.me. 

Bug details:
- Teleport version: Teleport Cloud 14.1.3
- Recreation steps
   Log in to proxy using IDP-initiated  auth connector.  
- Debug logs
  shared cloud logs with engineering

**Comment by zmb3** [comment] 2023-12-04 18:26
Looks like a duplicate of #27663, which seems to have been fixed by @AntonAM in gravitational/teleport.e#2508

**Comment by programmerq** [comment] 2023-12-04 22:29
The user that reported this is using Teleport Cloud, and has been on 14.1.3 since 16 Nov 2023. Their initial report of the issue was on 28 Nov 2023.

It looks like 14.1.3 was the first version that included https://github.com/gravitational/teleport.e/pull/2508

I ran into a similar issue when using OIDC with Teleport 14.2.1 just today, which reminded me of this issue.

**Comment by AntonAM** [comment] 2023-12-05 16:58
Yep, I found there's a bug in propagating real client IP Proxy->Auth for IdP initiated SSO flow. Will open a fix today.

**Closed** 2023-12-08 03:37 UTC
Labels: bug
