### ISSUE TITLE
Initial redirect to URI with hashtag does not work

### ISSUE THREAD

**Issue by mskl** [gravitational/teleport#49636] opened 2024-12-02 14:43 UTC
I suspect that the initial teleport redirect of URLs with `/#/` does not work correctly. It works after the user is authenticated.

**Current behavior:**

When accessing Kubeflow pipelines with URL as:

```
https://ml-pipeline-ui.company.teleport.sh/#/runs/details/d363a058-a168-484c-8905-338390b1b07d
```

I get redirected to "Sign in to Teleport" page with URL:

```
https://company.teleport.sh/web/login?redirect_uri=https://company.teleport.sh/web/launch/ml-pipeline-ui.company.teleport.sh%3Fpath%3D%252F
```

And after Okta login, the resulting URL is:

```
https://ml-pipeline-ui.company.teleport.sh/#/pipelines
```

**Expected behavior:**

After Teleport sign-in, get redirected to:

```
https://ml-pipeline-ui.company.teleport.sh/#/runs/details/d363a058-a168-484c-8905-338390b1b07d
```

Bug details:
- Teleport version: 16.4.7

**Comment by zmb3** [comment] 2024-12-02 15:21
Duplicate of #38653

**Closed by zmb3** 2024-12-02 15:21 UTC
Labels: bug
