### ISSUE TITLE
Okta Improvements

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#3882] opened 2020-06-24 01:18 UTC
### Feature Request
- [ ] Provide simple example without Group Setup
- [ ] Make it easier to bootstrap the roles in the example
- [ ] See if we can do more setup on the Okta side.
- [ ] Record a video
- [ ] Make the YAML & XML setup easier. 

### Motivation
Based on testing from 4.3 

### Who's it for?
Pro, Enterprise

**Comment by TravisGary** [comment] 2020-12-10 01:50
I think this one is now a dupe of https://github.com/gravitational/teleport/issues/4940

In the long run adding JIT provisioning with SAML or SCIM provisioning would also be a huge improvement.

**Comment by zmb3** [comment] 2022-10-04 23:13
This request is so old I'm going to close it due to inactivity. The next phase of Teleport Discover will explore bootstrapping SSO providers.

**Closed by zmb3** 2022-10-04 23:13 UTC
Labels: sso
