### ISSUE TITLE
Intermittent "special characters in resource name" issue when logging in to AWS

### ISSUE THREAD

**Issue by dancmeyers** [gravitational/teleport#21528] opened 2023-02-09 10:52 UTC
Expected behavior:

When I assume a Teleport role that grants access to AWS (either the web console through an `Application` in the Teleport web UI, or via the AWS CLI in a terminal using `tsh app login`), I expect to be reliably logged in to that AWS environment via role-assumption managed by Teleport.

Current behavior:

_Occasionally_ (given the frequency with which I am logging into and out of different AWS accounts as part of my day-to-day work, it will normally happen at least a couple of times a week), Teleport will give the error `special characters are not allowed in resource names, please use name composed only from characters, hyphens, dots, and plus signs`, and the name that was attemped. I do not know for sure whether this error is coming from Teleport itself as a result of something AWS returns, or from the AWS API as a result of something Teleport tries to do. When this error occurs, Teleport fails to log me in to the relevant app. If I retry (within the same Teleport login session), it normally works.

Error from web UI:
```
special characters are not allowed in resource names, please use name composed only from characters, hyphens, dots, and plus signs: "/key_attestations/SHA256:fh3fAaHB5BY6hwpn9Jnf83eT//1g6CtCxf9VEA4pYd8"
```

Error from `tsh` CLI:
```
ERROR: special characters are not allowed in resource names, please use name composed only from characters, hyphens, dots, and plus signs: "/key_attestations/SHA256:JSZqE0Wwk4l5+EvxO/Xj5uAsdLx9lyyJbXQ//6bQIRM"
```

Given the message, and the ID given, it _looks_ like the issue occurs when there are slashes within the SHA256 value (I have certainly never seen that error _without_ slashes in the SHA256 value), but I don't know whether it is Teleport generating that value, and the error is passed back from the AWS API when it is attempted to be used as an ID during some API action (`sts:AssumeRole`?), or whether it is generated _by_ AWS and the error is from Teleport.

Bug details:
- Teleport version: 11.1.3
- Recreation steps: Not reliably possible to reliably recreate, due to some intermittent ID generation within one of Teleport or AWS.
- Debug logs: Which logs are useful here?

**Comment by zmb3** [comment] 2023-02-09 15:17
This looks like a duplicate of #20312 which was fixed in #20314 and released in 11.3.1.

**Closed by zmb3** 2023-02-09 15:17 UTC
Labels: bug
