### ISSUE TITLE
[v.9.0] /docs/pages/setup/reference/resources.mdx

### ISSUE THREAD

**Issue by ForrestH** [gravitational/teleport#11549] opened 2022-03-29 20:34 UTC
## Details
Missing details on resource definition options for resource kinds: connector, node, cluster, github

### Category
- Improve Existing

**Comment by ForrestH** [comment] 2022-03-29 20:37
I was specifically looking for a way to point teleport to a locally hosted GitHub Enterprise for SSO instead of github.com, but I couldn't find a configuration option for that.

**Comment by zmb3** [comment] 2022-03-29 23:07
Thanks for filing this! I'm going to close as a duplicate of #11079 and #9949. Feel free to subscribe to those issues to track progress.

**Closed by zmb3** 2022-03-29 23:07 UTC
Labels: documentation
