### ISSUE TITLE
Ability to produce list of session ids from CLI

### ISSUE THREAD

**Issue by WilliamLoy** [gravitational/teleport#9131] opened 2021-11-24 19:59 UTC
### What
What would you like Teleport to do differently?
A user that can view the list of session-ids from within the Web UI should have the ability to view that same list from CLI. 
### How
How would you implement this?
tsh ls --session-id
### Why
Why do you need this?
Customers have requested the ability to produce a list of session-ids so that they can join a session without having to access the Web UI. 
### Workaround
If a workaround exists, please include it.

The only workaround is to view session-ids in the UI.

**Comment by zmb3** [comment] 2022-06-08 00:20
Closing as duplicate of #11205

**Closed by zmb3** 2022-06-08 00:20 UTC
Labels: feature-request, tsh, cu-cp
