### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by woohgit** [gravitational/teleport#488] opened 2016-08-03 09:44 UTC
I tried to compile the 1.0.0, but it's failing:

```
wooh@otaku:~/repos/gravitational/teleport$  git:(master) go get github.com/gravitational/teleport/lib/config                                            
wooh@otaku:~/repos/gravitational/teleport$  git:(master) make
make -f version.mk setver
make[1]: Entering directory `/home/wooh/repos/gravitational/teleport'
make[1]: Leaving directory `/home/wooh/repos/gravitational/teleport'
go build -o build/teleport -i -ldflags -w ./tool/teleport
go build -o build/tctl -i -ldflags -w ./tool/tctl
# _/home/wooh/repos/gravitational/teleport/tool/tctl
tool/tctl/main.go:699: cannot use i.KeySigner (type "github.com/gravitational/teleport/vendor/golang.org/x/crypto/ssh".Signer) as type "golang.org/x/crypto/ssh".Signer in argument to "golang.org/x/crypto/ssh".PublicKeys:
        "github.com/gravitational/teleport/vendor/golang.org/x/crypto/ssh".Signer does not implement "golang.org/x/crypto/ssh".Signer (wrong type for PublicKey method)
                have PublicKey() "github.com/gravitational/teleport/vendor/golang.org/x/crypto/ssh".PublicKey
                want PublicKey() "golang.org/x/crypto/ssh".PublicKey
make: *** [tctl] Error 2
```

It might be related to some dependency issue, but would be nice if we could compile teleport ourselves too. I can't test and send a PR until this is not resolved.

**Comment by klizhentas** [comment] 2016-08-03 17:11
what's your Go version?

**Comment by woohgit** [comment] 2016-08-03 18:01
```
go version go1.6 linux/amd64
```

**Comment by klizhentas** [comment] 2016-08-03 18:05
I'd need to try and reproduce with 1.6, meanwhile, can you try downgrading to:

```
go version go1.5.4 linux/amd64
export GO15VENDOREXPERIMENT=1
``

and try running `make` again?

**Comment by woohgit** [comment] 2016-08-03 18:24
Sure.

The output:

```
wooh@otaku:~/repos/gravitational/teleport$  git:(master) make
make -f version.mk setver
make[1]: Entering directory `/home/wooh/repos/gravitational/teleport'
make[1]: Leaving directory `/home/wooh/repos/gravitational/teleport'
go build -o build/teleport -i -ldflags -w ./tool/teleport
go build -o build/tctl -i -ldflags -w ./tool/tctl
# _/home/wooh/repos/gravitational/teleport/tool/tctl
tool/tctl/main.go:699: cannot use i.KeySigner (type "github.com/gravitational/teleport/vendor/golang.org/x/crypto/ssh".Signer) as type "golang.org/x/crypto/ssh".Signer in argument to "golang.org/x/crypto/ssh".PublicKeys:
        "github.com/gravitational/teleport/vendor/golang.org/x/crypto/ssh".Signer does not implement "golang.org/x/crypto/ssh".Signer (wrong type for PublicKey method)
                have PublicKey() "github.com/gravitational/teleport/vendor/golang.org/x/crypto/ssh".PublicKey
                want PublicKey() "golang.org/x/crypto/ssh".PublicKey
make: *** [tctl] Error 2
wooh@otaku:~/repos/gravitational/teleport$  git:(master) go version
go version go1.5.4 linux/amd64
wooh@otaku:~/repos/gravitational/teleport$  git:(master) echo $GOPATH
/home/wooh/repos
wooh@otaku:~/repos/gravitational/teleport$  git:(master) echo $GO15VENDOREXPERIMENT
1
```

**Comment by klizhentas** [comment] 2016-08-03 19:04
I think that may be because of your path:

```/home/wooh/repos/gravitational/teleport```

can you change the location to

```/home/wooh/repos/github.com/gravitational/teleport```

and try build again?

**Comment by woohgit** [comment] 2016-08-03 19:09
Awesome.

It's working. Strange that `go` is so strict with the location of the source code.. :)

**Comment by klizhentas** [comment] 2016-08-03 19:10
haha, yeah it can be a bit confusing. ok, closing this issue for now then

**Closed by klizhentas** 2016-08-03 19:10 UTC

**Comment by wjdavis5** [comment] 2016-09-30 12:57
@klizhentas  You may consider reopening this or linking an update to the documentation to this issue. The docs instruct people to use a git clone for this report after setting up go and trying to build from there. It should probably instead tell people to use `go get github.com/gravitational/teleport` and then use make from the resulting directory.
