### ISSUE TITLE
Session is not saved when session is closed unexpectedly

### ISSUE THREAD

**Issue by SamClinckspoor** [gravitational/teleport#1462] opened 2017-11-17 14:33 UTC
When closing a teleport session ungracefully the session/replay is not saved.

how to reproduce:
login on a host using teleport.
run `echo "this will not be saved" && reboot`

It doesn't seem to matter if you reboot inline or not.

this is on Ubuntu 16.04 using teleport 2.3.5

**Comment by aberoham** [comment] 2018-01-22 14:26
Hi Sam, this is expected behavior due to how teleport-node is responsible for shipping logs back to teleport-auth in a default (non recording proxy) configuration. This new blog post has some details:
https://blog.gravitational.com/blog/how-to-record-ssh-sessions/

Can you retry the test with teleport-proxy in "[ssh recording proxy](https://gravitational.com/teleport/docs/2.4/admin-guide/#recording-proxy-mode)" mode?

**Comment by russjones** [comment] 2020-08-10 16:14
Duplicate of https://github.com/gravitational/teleport/issues/3549.

**Closed by russjones** 2020-08-10 16:14 UTC
