### ISSUE TITLE
tsh does not support using gpg-agent & gpg keys

### ISSUE THREAD

**Issue by aelkugia** [gravitational/teleport#3143] opened 2019-11-12 21:40 UTC
**What happened**: 

If you use gpg-agent it will overwrite your GPG private keys. Current approach requires user to disable gpg-agent and use ssh-agent.

**What you expected to happen**:

tsh should support using gpg-agent and gpg keys when logging in. It's an easy work around to disable gpg-agent and use ssh-agent, but it would be nice to have to keep from switching back and forth.

**Comment by webvictim** [comment] 2019-11-25 15:01
Duplicate of #3169

**Closed by webvictim** 2019-11-25 15:01 UTC
Labels: enhancement, tsh
