### ISSUE TITLE
improve kubectl behavior in the case of expired credentials

### ISSUE THREAD

**Issue by programmerq** [gravitational/teleport#8997] opened 2021-11-15 15:32 UTC
### What
What would you like Teleport to do differently?

If a teleport session is expired, and a `kubectl` command is run, it should give the user some information about what is happening.

Currently, it simply sits and blocks the terminal. It does appear to be prompting for the password of the teleport user for which the session is expired, but there's no indication given to the end user what it wants them to do.

### How

If possible, a user-facing message would be ideal. If that's not possible, `tsh kube credentials` should exit with an error code, which should be more of a signal that the user must do something than the current silent prompt and block that happens.

### Why

Improve user experience

### Workaround

After a bit of experimenting, it appears that there's not a great workaround.

**Comment by espadolini** [comment] 2022-02-04 10:03
Ran into this yesterday - launching the same `tsh kube credentials` manually with the options described in `.kube/config` shows a password prompt, which, aiui, can't really be answered by the user but still sets the terminal in raw noecho mode (which is kind of rude) - and even if it could, the output that `kubectl` was expecting has been ruined by "Please enter password for user foo:" anyways.
Perhaps we could explore the possibility of having `tsh kube credentials` reopen stdin/stdout/stderr from `/dev/tty` and only use the original stdout to communicate with `kubectl`, if we decide to allow the user to refresh authentication halfway through `kubectl` - the simplest solution would be to just error out, however.

**Comment by espadolini** [comment] 2022-02-04 10:12
Actually, according to https://kubernetes.io/docs/reference/access-authn-authz/authentication/#input-and-output-formats it should be possible to just use `stdin` if needed, `tsh kube credentials` might just need to redirect its own regular stdout to stderr?

**Comment by r0mant** [comment] 2022-04-26 21:44
Possibly related: https://github.com/gravitational/teleport/issues/6630.

**Comment by tigrato** [comment] 2022-05-16 15:04
Duplicate of #6630

**Closed by tigrato** 2022-05-16 15:04 UTC
Labels: feature-request, ux, good-starter-issue, kubernetes-access, c-an
