### ISSUE TITLE
Provide ability to perform RBAC on SCP (down- vs. upload) in UI

### ISSUE THREAD

**Issue by jkendzorra** [gravitational/teleport#2981] opened 2019-09-12 13:35 UTC
Currently, there doesn't seem to be a way to control what user group can perform SCP; additionally, it would be great to be able to control the direction (download vs. upload).

**Comment by benarent** [comment] 2019-09-13 23:57
Hi @jkendzorra, thanks for the creating this issue. I can see how adding RBAC to SCP would be very helpful for some teams to lock down systems. Since we don't already have an open issue for this I'm going to label it `feature-request`, `scp` , I can also see adding this to our new Workflow API.

**Comment by alex-kovoy** [comment] 2020-07-17 02:41
@benarent we need to be careful with this one as not to give a false premise that uploads/downloads could be restricted by disabling SCP because you could always use tar over ssh to upload/download data.

**Comment by alex-kovoy** [comment] 2020-07-17 15:00
@benarent another option would be to add a parameter to the teleport.yml config to enable/disable this feature. That would drop any security implications.

**Comment by benarent** [comment] 2020-07-17 15:10
The origin of this request is from large teams that provide support teams with the Teleport UI Terminal to help debug customers machines. These are often only trained on the UI, and while they could setup `tsh` it's unlikely and the goal of this is to make SCP usability harder. 

I would suggest we make the option explicit that this is the UI SCP 

```
 - resources: [terminal]
    verbs: [read, ui_scp]
```

^ Perhaps using current RBAC To call out that specific feature, but open to other suggestions for fine grained RBAC / Feature flagging. 

There is no way that we could turn off SCP due to how it's built into SSH, and it's possible to workout. Building a Restricted Shell https://github.com/gravitational/teleport/issues/2578 would be something that would could explore.

**Comment by alex-kovoy** [comment] 2020-07-17 15:25
> I would suggest we make the option explicit that this is the UI SCP

Using an RBAC resource with verbs as a feature flag may look quite confusing (from security perspective). 

> There is no way that we could turn off SCP due to how it's built into SSH,

We can disable/enable both `tsh scp` and `web ui scp` features as both are part of Teleport functionality. Teleport has its own version of `scp` implementation.

**Comment by alex-kovoy** [comment] 2020-07-17 15:27
> it's unlikely and the goal of this is to make SCP usability harder.

If the goal is to make it _harder_ to use then it does not need to be part of RBAC which is intended for restricting access.

**Comment by zmb3** [comment] 2022-08-10 20:27
Closing this as a duplicate of #14661 (even though it's the original issue).

This work is ongoing and the newer issue is more up to date.

**Closed by zmb3** 2022-08-10 20:27 UTC
Labels: feature-request, ui, scp, rbac, hornet-polish, sales-onboarding, c-q7j, c-m, c-cg
