### ISSUE TITLE
When saving a user, some datetime fields are set to 0001-01-01T00:00:00Z

### ISSUE THREAD

**Issue by alex-kovoy** [gravitational/teleport#2228] opened 2018-09-17 16:37 UTC
Not sure if this is a regression but I noticed that some datetime fields are set to `0001-01-01T00:00:00Z` for several user properties. Below is an example from user structure taken from file system db.

Check `locked_time` and `created_by` feilds.

```
{
    "kind": "user",
    "version": "v2",
    "metadata": {
        "name": "user1"
    },
    "spec": {
        "roles": ["admin"],
        "traits": {
            "kubernetes_groups": null,
            "logins": null
        },
        "status": {
            "is_locked": true,
            "locked_message": "user has exceeded maximum failed login attempts",
            "locked_time": `"0001-01-01T00:00:00Z"`,
            "lock_expires": "2018-09-17T16:38:12.351716671Z"
        },
        "expires": "0001-01-01T00:00:00Z",
        "created_by": {
            "time": `"0001-01-01T00:00:00Z"`,
            "user": {
                "name": ""
            }
        }
    }
}
```

**Comment by klizhentas** [comment] 2018-09-17 17:48
I don't think it's a regression, but it's definitely something that could be improved in the future

**Comment by benarent** [comment] 2020-04-22 19:07
Closing as a duplicate of https://github.com/gravitational/teleport/issues/3590

**Closed by benarent** 2020-04-22 19:07 UTC
