### ISSUE TITLE
`TestTeletermKubeGateway` flakiness

### ISSUE THREAD

**Issue by Joerger** [gravitational/teleport#39268] opened 2024-03-12 19:42 UTC
## Failure

Looks like the failing subtest was introduced in https://github.com/gravitational/teleport/pull/35772

#### Link(s) to logs

- https://github.com/gravitational/teleport/actions/runs/8254418663/job/22578554999

#### Relevant snippet

```
2024-03-12T19:24:40.2856632Z     teleterm_test.go:436: 
2024-03-12T19:24:40.2857530Z make: *** [Makefile:913: integration] Error 1
2024-03-12T19:24:40.2858062Z         	Error Trace:	/__w/teleport/teleport/integration/proxy/proxy_helpers.go:769
2024-03-12T19:24:40.2858680Z         	            				/__w/teleport/teleport/integration/proxy/teleterm_test.go:483
2024-03-12T19:24:40.2859249Z         	            				/__w/teleport/teleport/integration/proxy/teleterm_test.go:229
2024-03-12T19:24:40.2859798Z         	            				/__w/teleport/teleport/integration/proxy/teleterm_test.go:486
2024-03-12T19:24:40.2860558Z         	            				/__w/teleport/teleport/integration/proxy/teleterm_test.go:436
2024-03-12T19:24:40.2861033Z         	Error:      	Received unexpected error:
2024-03-12T19:24:40.2861722Z         	            	the server was unable to return a response in the time allotted, but may still be processing the request (get pods)
2024-03-12T19:24:40.2862547Z         	Test:       	TestTeletermKubeGateway/leaf_with_per-session_MFA
```

**Comment by greedy52** [comment] 2024-03-13 20:25
```
{"caller":"client/client_store.go:111","component":"keystore","level":"debug","message":"Teleport TLS certificate valid until \"2024-03-12 18:15:33 +0000 UTC\".","timestamp":"2024-03-12T19:15:33Z"}
{"caller":"auth/middleware.go:352","component":"auth:69","level":"debug","message":"Server certificate cert(f0ab296a-e42e-45f1-96b7-e681f677bf3c.root.example.com issued by root.example.com:38341804160576211523548526288175966686).","timestamp":"2024-03-12T19:15:33Z"}
{"caller":"multiplexer/tls.go:152","component":"mxtls:69","dst_addr":{"IP":"127.0.0.1","Port":36833,"Zone":""},"error":"tls: failed to verify certificate: x509: certificate has expired or is not yet valid: current time 2024-03-12T19:15:33Z is after 2024-03-12T18:15:33Z","level":"warning","message":"Handshake failed.","src_addr":{"IP":"127.0.0.1","Port":40228,"Zone":""},"timestamp":"2024-03-12T19:15:33Z"}
{"caller":"alpnproxy/kube.go:180","cluster":{},"component":"conn:storage","error":"write tcp 127.0.0.1:40228-\u003e127.0.0.1:36833: write: broken pipe","gateway":"/gateways/b715f6e7-c637-4e06-ab74-84b71e787211","level":"warning","message":"Failed to reissue certificate for server 676b655f70726f6a6563745f6575726f706563656e7472616c32615f636c757374657231.leaf.example.com","resource":"/clusters/localhost/leaves/leaf.example.com/kubes/gke_project_europecentral2a_cluster1","timestamp":"2024-03-12T19:15:33Z"}
    teleterm_test.go:436: 
make: *** [Makefile:913: integration] Error 1
        	Error Trace:	/__w/teleport/teleport/integration/proxy/proxy_helpers.go:769
```
Some time advancing magic maybe? the TLS certificate issued suppose to be valid for the next hour, not the previous hour

**Comment by ravicious** [comment] 2024-03-14 15:59
Just above the actual failure there's `broken pipe` that @greedy52 tipped me off about:

```
 {"caller":"alpnproxy/kube.go:180","cluster":{},"component":"conn:storage","error":"write tcp 127.0.0.1:40228-\u003e127.0.0.1:36833: write: broken pipe","gateway":"/gateways/b715f6e7-c637-4e06-ab74-84b71e787211","level":"warning","message":"Failed to reissue certificate for server 676b655f70726f6a6563745f6575726f706563656e7472616c32615f636c757374657231.leaf.example.com","resource":"/clusters/localhost/leaves/leaf.example.com/kubes/gke_project_europecentral2a_cluster1","timestamp":"2024-03-12T19:15:33Z"}
```

This is similar to #20906, which also features `broken pipe`. I wonder if this has to do with recent changes in `lib/teleterm` that cache cluster clients between calls.

**Comment by greedy52** [comment] 2024-03-14 17:39
based on the trace, both test failure errors are caused by the `broken pipe`, when the local proxy is calling the reissue cert callback. Haven't found anything obvious yet as to why `broke pipe` happens. Cannot repro locally with mac version of `cpulimit -l 5`

**Comment by ravicious** [comment] 2024-03-15 08:36
Another clue: in all three cases where those tests have failed, the failing test is related to a leaf cluster.

**Comment by ravicious** [comment] 2024-03-18 09:44
Another v15 failure of a leaf cluster test, before the PR with disabled cache got merged.

What's noteworthy is that both tests failed in that job run:

* [`TestALPNSNIProxyDatabaseAccess/teleterm_db_gateways_cert_renewal/leaf_cluster`](https://github.com/gravitational/teleport/actions/runs/8299140007/job/22714176283#step:6:827)
* [`TestTeletermKubeGateway/leaf_with_per-session_MFA`](https://github.com/gravitational/teleport/actions/runs/8299140007/job/22714176283#step:6:2072)

**Comment by ravicious** [comment] 2024-03-18 09:58
I wonder if there's some kind of race condition where during (or after) relogin the client tries to talk to the leaf cluster, but some kind of connection between the client and the root cluster gets closed. The client thus cancels all ongoing work, including talking to the leaf cluster.

Consider these three facts:

1. All failing tests are related to leaf clusters and refreshing expired certs. 

2. When Grzegorz was working on the client cache, we had [a discussion about clients timing out after waking up the laptop from sleep](https://gravitational.slack.com/archives/C0DF0TPMY/p1709115939496249) which ultimately became #39009. [Noah said](https://gravitational.slack.com/archives/C0DF0TPMY/p1709117910142339?thread_ts=1709115939.496249&cid=C0DF0TPMY):

> One of the challenges we have is that the connection to the auth server is typically 3-4 connections that are wrapped, so if any of those gets into a weird state, the underlying connections may not necessarily be aware.

3. When we add a client to the cache, we do this:

https://github.com/gravitational/teleport/blob/a067fdebe46d1647f76dec85d601c4fe7e1fdaf1/lib/teleterm/services/clientcache/clientcache.go#L163-L178

OTOH, I haven't seen the message of `Connection has been closed, removed client from cache.` in the logs of failing tests. And I don't know a whole lot about our clients.

If it turns out that disabling the cache has helped, it'd be worthwhile to re-enable the cache after we switch from the SSH client to the gRPC one.

**Comment by ravicious** [comment] 2024-03-29 13:50
It looks like it stopped being an issue after we disabled the client cache in tests.

**Closed by ravicious** 2024-03-29 13:50 UTC
Labels: flaky tests
