### ISSUE TITLE
tsh scp does not preserve file attributes when transferring from v11 to v10 or older.

### ISSUE THREAD

**Issue by slavitch** [gravitational/teleport#20720] opened 2023-01-25 20:07 UTC
Expected behavior:

Behavior as in prior releases

Current behavior:

File attributes like "executible" not  preserved for transferred files.

Bug details (updated)
- Teleport version  11.2.2 for sending node and proxy.
- Teleport version < 11 for receiving node.
- Recreation steps

Copy a shell script `'foo.sh'` via tsh scp.  Script is executible.
Try to execute it via tsh ssh:   "tsh ssh  user@node './foo.sh'

Returns "file not found" due to rwx  attributes not being preserved.

**Comment by capnspacehook** [comment] 2023-01-25 21:22
I can't reproduce, is the machine running `tsh`, Teleport Proxy/Auth server and the Node you're connecting to all running Linux? Also are the `tsh` and Teleport Proxy/Auth server versions all 11.2.2?

**Comment by capnspacehook** [comment] 2023-01-26 20:55
What do you mean 'when the edge node isn't running SFTP'? If Teleport Nodes are new enough they will always accept properly authenticated and authorized SFTP connections. I'm also confused by what you mean by 'convert'...

**Comment by slavitch** [comment] 2023-01-31 01:23
If the sending hiat and the receiving host both run teleport 10 file attributes are preserved. If the sender is running teleport 11 and the recipient is runni g teleport 10 file attributes are bot preserved.

**Comment by jakule** [comment] 2023-03-02 19:21
@slavitch Friendly ping. If the issue is resolved for you, let us know so that we can close this issue.

**Comment by zmb3** [comment] 2023-06-29 18:42
Closing due to inactivity

**Closed by zmb3** 2023-06-29 18:42 UTC
Labels: bug, scp, sftp, waiting-reply
