### ISSUE TITLE
Teleport Quickstart Guide inconsistency

### ISSUE THREAD

**Issue by twakes** [gravitational/teleport#1775] opened 2018-03-14 22:55 UTC
**What happened**: I went through Quickstart Guide with v2.5 in documentation. When I run `sudo teleport start` I receive some warnings but do not receive the success message stated in the Quickstart Guide. Teleport is running so it appears to just be an inconsistency between v.2.5 of the docs and reality.

**What you expected to happen**:

Receive the response in the Quickstart Guide:
```
[AUTH]  Auth service is starting on 0.0.0.0:3025
[PROXY] Reverse tunnel service is starting on 0.0.0.0:3024
[PROXY] Web proxy service is starting on 0.0.0.0:3080
[PROXY] SSH proxy service is starting on 0.0.0.0:3023
[SSH]   Service is starting on 0.0.0.0:3022
```

**How to reproduce it (as minimally and precisely as possible)**:

I ran through the [Quickstart Guide](https://gravitational.com/teleport/docs/quickstart/) using the `teleport-v2.5.0-darwin-amd64-bin.tar.gz` release.

**Environment**:
- Teleport version (use `teleport version`): 2.5.0
- Tsh version (use `tsh version`): 2.5.0
- OS (e.g. from /etc/os-release): Mac OS X v10.11.6

**Browser environment**

- Browser Version (for UI-related issues):
- Install tools:
- Others:

**Relevant Debug Logs If Applicable**

- tsh --debug
- teleport --debug

**Comment by kontsevoy** [comment] 2018-03-16 00:04
duplicate of #1776

**Closed by kontsevoy** 2018-03-16 00:04 UTC
Labels: enhancement
