### ISSUE TITLE
[v.12.x] Error 404 when adding a server in docker-compose lab

### ISSUE THREAD

**Issue by xStrat0S** [gravitational/teleport#21968] opened 2023-02-17 12:09 UTC
## Applies To
https://goteleport.com/docs/try-out-teleport/docker-compose/

## Details

Got an error 404 when executing the script given for adding a server

![image](https://user-images.githubusercontent.com/70196888/219650279-d1237d61-4f1d-4eb1-8438-25bfefc45e45.png)

Solution : Update lab images from 11 to 12 in docker-compose file given in the lab tutorial.

**Comment by zmb3** [comment] 2023-02-17 15:43
This is a duplicate of #21268 and is fixed in the latest releases.

**Closed by zmb3** 2023-02-17 15:43 UTC
Labels: documentation

**Comment by xStrat0S** [comment] 2023-02-27 18:27
The docker images in the teleport-lab.yml provided by the documentation are still in version 11 which still has this anomaly.

https://raw.githubusercontent.com/gravitational/teleport/v12.0.2/docker/teleport-lab.yml
