### ISSUE TITLE
start teleport error, error info: role version "v7" is not supported

### ISSUE THREAD

**Issue by qixiangyang** [gravitational/teleport#28412] opened 2023-06-28 10:19 UTC
Expected behavior:
start teleport service normally

Current behavior:
can not start teleport service
version 13.1.5
error message: role version "v7" is not supported

<img width="584" alt="image" src="https://github.com/gravitational/teleport/assets/9353474/a303d1a6-f30d-4e89-80a3-535f8a026904">

but teleport service can start with code in branch master

Bug details:

**Comment by programmerq** [comment] 2023-06-28 14:53
The v7 role syntax is not available in the 13.x branch of Teleport.

In general, Teleport doesn't have a downgrade path, and it is not expected that an older version of Teleport will work with data structures from newer versions.

With that said, your best path forward to fix this instance will probably be to edit any v7 role objects in your storage backend directly so that they are valid v6 roles that Teleport 13.x can utilize.

**Comment by zmb3** [comment] 2023-06-28 22:42
Looks like you ran Teleport from master and then "downgraded" to a v13 release that doesn't know about this new role version.

I'm going to close this as things are currently working as designed, but feel free to reach out if the suggestions above don't work for you.

**Closed by zmb3** 2023-06-28 22:42 UTC
Labels: bug

**Comment by qixiangyang** [comment] 2023-06-29 02:49
Thank for your quickly response. 
I found the problem, because I started teleport using master branch code before, it generates data at /var/lib/teleport and saves role version as well. 
so when i checkout it to version v 13 and ran, it occurred that the role version mismatched. After deleting data at /var/lib/teleport, it runs normally.
