### ISSUE TITLE
Open ID connect support

### ISSUE THREAD

**Issue by nivasomu** [gravitational/teleport#20515] opened 2023-01-21 03:24 UTC
It will be nice to have open ID connect for Teleport

**Comment by zmb3** [comment] 2023-01-22 14:29
Teleport supports OIDD identity providers today. Can you be more specific as to what you're looking for?

**Comment by nivasomu** [comment] 2023-01-23 19:10
Sorry, @zmb3 this is meant to be Teleport as an OIDC provider not integrating with OIDC.

**Comment by pschisa** [comment] 2023-01-24 18:21
Duplicate of https://github.com/gravitational/teleport/issues/18043

**Closed by pschisa** 2023-01-24 18:21 UTC
Labels: feature-request, c-ptc
