### ISSUE TITLE
Upgrading teleport via yum update should restart teleport

### ISSUE THREAD

**Issue by programmerq** [gravitational/teleport#10251] opened 2022-02-09 17:24 UTC
### Description

**What happened**:

When upgrading from `teleport-ent-fips-8.0.6-1.x86_64` to `teleport-ent-fips-8.1.5-1.x86_64` on an ssh_service teleport node, `tsh ssh` stopped working for new connections with an error "fork/exec /usr/local/bin/teleport;6203c13f: no such file or directory"

Restarting teleport manually fixed the issue.

Additionally, going from `teleport-ent-fips-8.1.5-1.x86_64` to `teleport-ent-fips-8.2.0-1.x86_64`, a `systemctl daemon-reload` should have happened, but had to be done manually.

**What you expected to happen**:

If a restart or a daemon-reload is needed after an upgrade, yum should handle doing so.

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1.
2.
3.

### Server Details
- Teleport version (run `teleport version`):
- Server OS (e.g. from `/etc/os-release`):
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware):
- Additional details:

### Client Details
- Tsh version (`tsh version`):
- Computer OS (e.g. Linux, macOS, Windows):
- Browser version (for UI-related issues):
- Installed via (e.g. apt, yum, brew, website download):
- Additional details:

### Debug Logs
Please include or attach debug logs, when appropriate. Obfuscate sensitive information!
- Start Teleport with --debug flag (`teleport --debug`)
- Run tsh with --debug flag (`tsh --debug`)

**Comment by webvictim** [comment] 2022-03-30 20:00
Similar to #11104

**Comment by polarina** [comment] 2023-05-10 16:14
On the most common RPM based systems, like RHEL and Fedora, updating a system package does not automatically restart their services. This is by design.

It would certainly be considered a surprising behavior if Teleport were to do something counter to that.

Just my two cents.

**Comment by webvictim** [comment] 2023-05-31 14:58
I'm going to close this as the behaviour is by design rather than a bug.

**Closed by webvictim** 2023-05-31 14:58 UTC
Labels: bug, release-engineering, c-ac
