### ISSUE TITLE
Enhanced ebpf session recording doesn't identify which user performed the action during a shared session. 

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#5393] opened 2021-01-22 22:55 UTC
### Description

**What happened**:
I've been debugging an issue for a user. We've Session sharing - no possibility to distinguish between users actions #1375
 open for a while and this issue isn't solved by ebpf session recording.

**What you expected to happen**:
Enhanced session recording should provide more in-depth detail about what's happening during a session. 

**How to reproduce it (as minimally and precisely as possible)**:

1. Create two users
2. User 'bob' starts a session and doesn't type anything
3. User 'alice' joins session via https://[cluster].teleport.sh/web/cluster/[cluster]/sessions
4. Alice executes a range of commands.
5. All events attribute activity to 'Bob' 
e.g. 
```json
{
  "argv": [
    "--color=auto"
  ],
  "cgroup_id": 4294967897,
  "code": "T4000I",
  "ei": 25,
  "event": "session.command",
  "login": "root",
  "namespace": "default",
  "path": "/usr/bin/ls",
  "pid": 23119,
  "ppid": 23099,
  "program": "ls",
  "return_code": 0,
  "server_id": "cca7dcdc-78b5-4b4e-ad1b-57bff1acba17",
  "sid": "b088d7dd-58bc-4e52-b34c-5e3d050b55d1",
  "time": "2021-01-22T22:50:24.301Z",
  "uid": "bcd0ce9c-91ee-4d28-8e4e-d909255ec2f8",
  "user": "bob"
}
```

**Comment by zmb3** [comment] 2024-02-01 20:45
Closing as duplicate of #5393 (this is not specific to enhanced recording)

**Closed by zmb3** 2024-02-01 20:45 UTC
Labels: bpf, c-ib
