### ISSUE TITLE
`TestRedisPubSub` flakiness

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#18284] opened 2022-11-08 23:59 UTC
```
    access_test.go:1000: 
        	Error Trace:	/workspace/lib/srv/db/access_test.go:1000
        	Error:      	Received unexpected error:
        	            	ERR unknown command 'hello', with args beginning with: '3'
        	Test:       	TestRedisPubSub/subscribe
```

https://console.cloud.google.com/cloud-build/builds/bf935c53-b7d8-4e1e-9359-8c29c21fa474?project=ci-account&authuser=1

**Comment by greedy52** [comment] 2022-11-11 14:04
Duplicate of #18012

**Closed by greedy52** 2022-11-11 14:04 UTC
Labels: flaky tests
