### ISSUE TITLE
Join Session commands show in Audit log as wrong user

### ISSUE THREAD

**Issue by scottpgallagher** [gravitational/teleport#15306] opened 2022-08-08 15:45 UTC
Expected behavior:
When a user joins another users ssh session and issues commands then the audit log should reflect who in fact issued the commands. 

Current behavior:
Currently when a user joins another users session and issues command then the audit log shows that the person who initiated the session issued the commands when in fact they didn't.

Bug details:
- Teleport version: 10.0.1
- Recreation steps: Start a ssh session, join that session as a different user and issue commands. Check the audit log and it will show the person who initiated the session issued the command. 
- Debug logs

**Comment by scottpgallagher** [comment] 2022-08-08 15:46
Could this as an issue from an auditing perspective and to find out who in fact issued commands.

**Comment by zmb3** [comment] 2022-08-10 20:26
Closing this as a duplicate of #1375 and #3705

**Closed by zmb3** 2022-08-10 20:26 UTC
Labels: bug, bpf, audit-log
