### ISSUE TITLE
Edit Internal Logins via Web UI

### ISSUE THREAD

**Issue by sanchezzjf** [gravitational/teleport#34519] opened 2023-11-13 11:47 UTC
What would you like Teleport to do?

The ability to set the logins for windows and linux through the web UI instead of just the CLI.

What problem does this solve?

It makes easier to create the users without having to do this or via CLI or in two different places.
For example:
I create the user via Web UI and have to go to the CLI to set the correct logins for that user.

If a workaround exists, please include it.
Use both CLI and UI

**Comment by zmb3** [comment] 2023-11-13 16:56
Duplicate of #9790

**Closed by zmb3** 2023-11-13 16:56 UTC
Labels: feature-request
