### ISSUE TITLE
v13 ~ Missing Fav.icon

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#24900] opened 2023-04-20 15:22 UTC
Expected behavior:

Provide a default fav.icon
<img width="418" alt="image" src="https://user-images.githubusercontent.com/559288/233412437-3685a231-eade-4623-9a24-b99283f1d690.png">

Current behavior:
Missing Fav.icon

**Comment by zmb3** [comment] 2023-04-20 15:25
Duplicate of #24773

**Closed by zmb3** 2023-04-20 15:25 UTC
Labels: bug, ui
