### ISSUE TITLE
tsh ssh access for Windows

### ISSUE THREAD

**Issue by WilliamLoy** [gravitational/teleport#12678] opened 2022-05-16 17:53 UTC
What would you like Teleport to do?
The ability to use tsh ssh access on Windows server. 

What problem does this solve?
Customers trying to automate Windows deployments using tooling that requires SSH access aren't able to utilize Teleport tsh ssh access on Windows. 

Additionally, customers want to leverage Teleport RBAC rather than the on/off access control of sshd. 

If a workaround exists, please include it.
Use sshd for Windows to connect to Teleport.

**Comment by benarent** [comment] 2022-05-16 18:12
I just covered using 'tsh ssh' on Windows ( not server ) https://www.youtube.com/watch?v=XH047Qc45xs does this cover this use case?

**Comment by zmb3** [comment] 2022-08-09 15:00
Closing as duplicate of #9567

**Closed by zmb3** 2022-08-09 15:00 UTC
Labels: feature-request, windows, tsh
