### ISSUE TITLE
Access denied on app since the 17.x.x upgrades

### ISSUE THREAD

**Issue by zifeo** [gravitational/teleport#50575] opened 2024-12-25 10:19 UTC
**Expected behavior:**

Successfully access the exposed app via teleport.

**Current behavior:**

1. Go to your teleport interface and click on an exposed app
2. The browser shows the following [JS error](https://github.com/gravitational/teleport/blob/master/web/packages/teleport/src/AppLauncher/AppLauncher.tsx#L144-L147)

> Unable to access "app.cluster.com". This may happen if your Teleport Proxy is using untrusted or self-signed certificate. Please ensure Teleport Proxy service uses valid certificate or access the application domain directly (https://app.cluster.com) and accept the certificate exception from your browser.

No self-signed certificate, nor any warning when accessing the URL directly (but same behavior as it gets redirect to cluster.com for login). Tried in private browsing and with clean cookie/storage cache.

**Bug details:**
- Teleport version: 17.1.1 (both cluster and kube-agent)
- Recreation steps: we upgrade from 16.4.8 to 17.1.1
- Debug logs: no log... and the root JS error is hidden in the code

**Comment by zmb3** [comment] 2024-12-25 16:51
Duplicate of #50556

**Closed by zmb3** 2024-12-25 16:51 UTC
Labels: bug
