### ISSUE TITLE
Internal Error rpc error: code = PermissionDenied desc = access denied to perform action 'read' on billing 

### ISSUE THREAD

**Issue by rodlord5000** [gravitational/teleport#30655] opened 2023-08-18 02:12 UTC
Expected behavior:

User able to login successfully

Current behavior:

A role which previously worked now presents this error after logging in. User does not require any billing access, only access to the specified desktop.

Bug details:
- Teleport version
Teleport Cloud 12.4.14
- Recreation steps
- Debug logs

Role:

kind: role
metadata:
  name: redacted
spec:
  allow:
    rules:
    - resources:
      - event
      verbs:
      - list
      - read
    - resources:
      - session
      verbs:
      - read
      - list
      where: contains(session.participants, user.metadata.name)
    windows_desktop_labels:
      role: redacted
    windows_desktop_logins:
    - '{{internal.windows_logins}}'
    - redacted
  deny:
    logins:
    - guest
  options:
    cert_format: standard
    create_db_user: false
    create_desktop_user: false
    desktop_clipboard: true
    desktop_directory_sharing: true
    enhanced_recording:
    - command
    - network
    forward_agent: false
    idp:
      saml:
        enabled: true
    max_session_ttl: 8h0m0s
    pin_source_ip: false
    port_forwarding: true
    record_session:
      default: best_effort
      desktop: true
    ssh_file_copy: true
version: v5

![Screenshot 2023-08-18 101022](https://github.com/gravitational/teleport/assets/114850211/e196d6b5-b5eb-4e5e-80ce-b13e150722c8)

**Comment by zmb3** [comment] 2023-08-18 13:48
Duplicate of https://github.com/gravitational/teleport/issues/30546 (this has been fixed and will be out in the next release)

**Closed by zmb3** 2023-08-18 13:48 UTC
Labels: bug
