### ISSUE TITLE
[v.10.0] /docs/pages/installation.mdx

### ISSUE THREAD

**Issue by danielatjumo** [gravitational/teleport#15305] opened 2022-08-08 15:37 UTC
## Details
This section here: https://goteleport.com/docs/installation/?scope=enterprise#linux
```
curl https://get.gravitational.com/teleport-ent-v10.1.2-linux-amd64-bin.tar.gz.sha256
<checksum> <filename>
curl -O https://get.gravitational.com/teleport-ent-v10.1.2-linux-amd64-bin.tar.gz
shasum -a 256 teleport-ent-v10.1.2-linux-amd64-bin.tar.gz
Verify that the checksums match
tar -xzf teleport-ent-v10.1.2-linux-amd64-bin.tar.gz
cd teleport
sudo ./install
```

The `cd` line should say `cd teleport-ent` when on the enterprise page as that is what it extracts to not `teleport`.

### Category
- Improve Existing

**Comment by ptgott** [comment] 2022-11-30 23:12
Closing as a duplicate of #14787

**Closed by ptgott** 2022-11-30 23:12 UTC
Labels: documentation, z
