### ISSUE TITLE
Desktop Access for Non-Domain Connected Hosts

### ISSUE THREAD

**Issue by MarkLFT** [gravitational/teleport#15341] opened 2022-08-09 10:43 UTC
What would you like Teleport to do?
Need to be able to RDP into a Workgroup (non-domain) windows host.

What problem does this solve?
None of the computers I connect to use domains as for the number of hosts in each location it is too much overhead.  

If a workaround exists, please include it.
Currently I have to use TeamViewer, or Guacamole with port forwarding to the guacamole server.  Neither is a great fit, we are trying to get all of our support connections into a single location/system.

**Comment by strideynet** [comment] 2022-08-09 10:54
Thanks for raising this, this is a duplicate of https://github.com/gravitational/teleport/issues/10166 so I'll close this ticket down.

**Closed by strideynet** 2022-08-09 10:54 UTC
Labels: feature-request
