### ISSUE TITLE
local_proxy ping is failing while the proxy looks good

### ISSUE THREAD

**Issue by benoittgt** [gravitational/teleport#37653] opened 2024-02-01 16:48 UTC
Expected behavior:

I am able to use `tsh db connect` and connect to remote RDS db.

Current behavior:

With `tsh db connect pg-staging-xxxxxx --debug`

```
2024-02-01T17:24:25+01:00 DEBU [TSH]       /opt/homebrew/bin/psql postgres://teleport_ro@localhost:49327/db?sslrootcert=/Users/benoit.tigeot/.tsh/keys/teleport-cluster.x.x/cas/teleport-cluster.x.x.pem&sslcert=/Users/benoit.tigeot/.tsh/keys/cluster.private.x.x/benoittgt-db/teleport-cluster.x.x/pg-staging-rds.pem&sslkey=/Users/benoit.tigeot/.tsh/keys/teleport-cluster.x.x/benoittgt&sslmode=verify-full common/db.go:795
2024-02-01T17:24:25+01:00 DEBU [LOCALPROX] Accepted downstream connection. alpnproxy/local_proxy.go:194
2024-02-01T17:24:25+01:00 DEBU [LOCALPROX] Using ping connection alpnproxy/local_proxy.go:240
psql: error: connection to server at "localhost" (::1), port 49327 failed: Connection refused
```

The error is happening on random machine. 

How to better understand/debug this. Proxy looks good but it's not enough.

Bug details:
- Teleport version: Teleport v14.3.3 git: go1.21.6 / Proxy version: 14.3.3
- Recreation steps : It's a private and it's random sadly I can't
- Debug logs : see below

**Comment by zmb3** [comment] 2024-02-03 21:49
Hi there,

We're happy to look into bug reports if there are clear instructions and steps we can use to reproduce. This report only includes 3 lines of logs, no recreation steps, and no configuration, which makes it hard for us to help.

Since this is not actionable in its current form I am going to close it out. If you're able to add more information you're welcome to reopen it.

**Closed by zmb3** 2024-02-03 21:49 UTC
Labels: question
