### ISSUE TITLE
Azure SQLServer auto discovery. 

### ISSUE THREAD

**Issue by smallinsky** [gravitational/teleport#17062] opened 2022-10-05 12:41 UTC
### What
Implement auto-discovery support for  Azure SQLServer instances.

### How: 
We already supporting azure auto discovery for `mysql`, `postgres` and `redis` azure instance.  The integration should use the same mechanism for SQLServer azure instance auto discovering. 

The azureMatcher should be extended https://github.com/gravitational/teleport/blob/d319ee2734287a44e1941d55b3c4d025581b8d96/lib/srv/db/cloud/watchers/watcher.go#L198 by SQLServer Fetcher allowing to fetch and configure current SQLServer instances. 

#### Accept Criteria: 
SQLServer instances are auto discovery by teleport.

**Comment by zmb3** [comment] 2022-10-05 16:04
Duplicate of #14367?

**Closed** 2022-11-28 15:02 UTC
Labels: feature-request, database-access, azure, db/sqlserver
