### ISSUE TITLE
Machine ID for ephemeral CICD environments

### ISSUE THREAD

**Issue by hydezhao** [gravitational/teleport#12780] opened 2022-05-20 09:23 UTC
What would you like Teleport to do?
Possibility to generate long-life and reusable join token for bots.

What problem does this solve?
In our CICD workflows (gitlab-ci), we create an ephemeral docker container for each task. If we want to integration teleport into the workflow, we will need to create un bot user and use its join token to exec `tbot start` in each docker container for CICD jobs. 
The problem is that the join token is invalidated after the first connection, which means we have to create a new bot user for each CICD job execution, which is not possible because we need to login with OTP before create new bot user.

If a workaround exists, please include it.
Not found yet, please enlighten me if some one have some ideas.

**Comment by zmb3** [comment] 2022-05-20 09:47
Yep, this is coming soon in one form or another.

It's still early, but in general we prefer authenticating the workload via some means other than a shared static token. It looks like GitLab CI exposes a `$CI_JOB_TOKEN` that we might be able to use here.

I'm going to close this as a duplicate of #11017 - feel free to follow along there for updates!

**Closed by zmb3** 2022-05-20 09:47 UTC
Labels: feature-request, machine-id
