### ISSUE TITLE
`TestAppResource` flakiness

### ISSUE THREAD

**Issue by Joerger** [gravitational/teleport#14152] opened 2022-07-06 17:07 UTC
## Failure

On `branch/v9`

#### Link(s) to logs

- https://console.cloud.google.com/cloud-build/builds;region=global/071964f8-6947-4130-9e70-f06f8522c471?project=ci-account

#### Relevant snippet

```
    testing.go:967: TempDir RemoveAll cleanup: unlinkat /tmp/TestAppResource4190879378/001: directory not empty
--- FAIL: TestAppResource (6.92s)
```

**Comment by GavinFrazar** [comment] 2023-01-04 17:59
I think this test is the cause of this flaky test failure:
https://github.com/gravitational/teleport/actions/runs/3835806532/jobs/6529355920

The test times out after `TestAppResource` runs

**Comment by zmb3** [comment] 2023-04-12 22:07
No recent occurrences - closing.

**Closed by zmb3** 2023-04-12 22:07 UTC
Labels: application-access, flaky tests
