### ISSUE TITLE
Document the rest of resources

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#19715] opened 2022-12-29 00:51 UTC
Most of resources in docs reference are not documented:

https://goteleport.com/docs/reference/resources/#dynamic-resources

```
    # trusted_cluster    - Trusted Cluster resource
    # remote_cluster     - remote cluster resource
    #
    # access_request     - Access Request resource
    # access_plugin_data - allows modifying Access Request plugin data
    #
    # session            - session playback records
    # ssh_session        - an active SSH session
    # event              - structured audit logging event
    #
    #
    # lock                  - lock resource.
    # network_restrictions  - restrictions for SSH sessions
    #
    # auth_server           - Auth Service resource
    # proxy                 - Proxy Service resource
    # node                  - SSH node resource
    # app                   - application resource
    # db                    - database  resource
    # kube_cluster          - Kubernetes cluster resource
    # token                 - provisioning token resource
    # cert_authority        - certificate authority resource
    #
    # cluster_name              - resource that contains the cluster name.
    # cluster_config            - resource that holds cluster level config
    # cluster_auth_preference   - type of authentication for this cluster
    # session_recording_config  - resource for session recording config
    # cluster_audit_config      - resource that holds cluster audit config
    # cluster_networking_config - resource that holds cluster networking config
```

I think we need to spend some time and document all resources in the reference section.

**Comment by zmb3** [comment] 2022-12-29 02:35
Duplicate of #9949

**Comment by ptgott** [comment] 2022-12-29 14:16
Related: https://github.com/gravitational/teleport/issues/16948

**Comment by zmb3** [comment] 2022-12-29 17:20
I see #9949 is already in the docs team backlog, so I'll go ahead and close this one.

**Closed by zmb3** 2022-12-29 17:20 UTC
Labels: documentation
