### ISSUE TITLE
[v.10.0] /docs/pages/setup/guides/docker.mdx

### ISSUE THREAD

**Issue by lordrip** [gravitational/teleport#14824] opened 2022-07-24 10:43 UTC
## Details
Currently in Step 1/4 refers to the same image name
![image](https://user-images.githubusercontent.com/16512618/180643471-bdff0e3c-2385-4fe0-9429-f5309ef8ef33.png)

Maybe the first image should be `latest` instead
![image](https://user-images.githubusercontent.com/16512618/180643491-097036cd-8e04-40c0-9241-3b82a8f6e3a2.png)

### Category
- Improve Existing

**Comment by zmb3** [comment] 2022-07-24 16:14
Duplicate of #13026

**Closed by zmb3** 2022-07-24 16:14 UTC
Labels: documentation
