### ISSUE TITLE
tctl users ls returning duplicates

### ISSUE THREAD

**Issue by bharadwajrembar** [gravitational/teleport#2569] opened 2019-02-19 09:59 UTC
Have a question? Please use [Our Forum](https://community.gravitational.com)

**What happened**: When querying for a list of users using `tctl users ls`, each user is listed 3 times.

**What you expected to happen**: Each user must be listed once

**How to reproduce it (as minimally and precisely as possible)**: This seems to occur when we upgraded Teleport from 2.7.0 to 3.1.1.

**Environment**:
- Teleport version (use `teleport version`): Teleport v3.1.1 git:v3.1.1-0-g8c506f47 go1.11.4
- Tsh version (use `tsh version`): Teleport v3.1.1 git:v3.1.1-0-g8c506f47 go1.11.4
- OS (e.g. from /etc/os-release): Ubuntu 16.04

**Browser environment**

- Browser Version (for UI-related issues):
- Install tools:
- Others:

**Relevant Debug Logs If Applicable**
`tctl users ls --debug`
```
DEBU             DEBUG logging enabled common/tctl.go:188
DEBU [BACKEND:D] Found new flat keyspace, skipping migration. dir:/var/lib/teleport/proc dir/migrate.go:42
User               Allowed logins
------------------ -------------------------------------------------
user1 user1
user1 user1
user1 user1
user2   docker,user2
user2   docker,user2
user2   docker,user2
user3   docker,user3
user3   docker,user3
user3   docker,user3
```
Further reference: https://github.com/gravitational/teleport/issues/2107
- tsh --debug
- teleport --debug

**Comment by klizhentas** [comment] 2019-02-19 15:56
dupe of reopened #2107

**Closed by klizhentas** 2019-02-19 15:56 UTC
