### ISSUE TITLE
Validating the Auth server

### ISSUE THREAD

**Issue by patrobinson** [gravitational/teleport#1275] opened 2017-09-07 10:34 UTC
From reading the documentation and source code it appears the nodes and proxy do not validate the Auth server. They connect via HTTP over SSH, so it should be possible to install an SSH public key on each proxy/node and have it use that to validate the Auth server upon startup. In fact that's how the Trusted Cluster model appears to work, trust between auth servers is established by exchanging public keys.

**Threat**:

An attacker Man in The Middle's communications between nodes and the Auth Service (i.e. by gaining access to a host with `ec2:AllocateAddress`, `ec2:AssociateAddress` and `ec2:DisassociateAddress` permissions to all resources (because you cannot restrict these permission to a single Elastic IP Address). They use these permissions to associating the Auth Services IP with themselves, creating a new EIP for the Auth Server and assigning it to them, and wait for a Node to join. They are now able to intercept all requests and approve authentication requests that may be rejected by the auth server. They are also able to capture all session data for those nodes.

**Comment by klizhentas** [comment] 2017-09-12 18:48
seems like a dupe of #302

**Comment by kontsevoy** [comment] 2017-09-12 19:15
@patrobinson thanks for looking into this. it's in the works! Lets move the discussion to #302, I'll close this one as a duplicate.

**Closed by kontsevoy** 2017-09-12 19:15 UTC
