### ISSUE TITLE
Persist Home Directories when Using the Host User Creation Feature

### ISSUE THREAD

**Issue by corkrean** [gravitational/teleport#15511] opened 2022-08-12 22:53 UTC
**What would you like Teleport to do?**
Create a role configuration option that would allow users to persist the linux users home directory when using the host user creation feature.

**What problem does this solve?**
Some users of Teleport use the users' home directory to store files that are owned by specific users. The users would like to persist their home directory so they can store files there. 

**If a workaround exists, please include it.**
Use PAM integration

**Comment by zmb3** [comment] 2022-08-13 14:38
Closing as duplicate of #14469

**Closed by zmb3** 2022-08-13 14:38 UTC
Labels: feature-request, c-mv
