### ISSUE TITLE
Allow disabling automatic tags for nodes in cloud providers

### ISSUE THREAD

**Issue by wlopes39** [gravitational/teleport#18881] opened 2022-11-29 19:03 UTC
Possibility to disable the function

https://github.com/gravitational/teleport/pull/16218

https://github.com/gravitational/teleport/pull/12593

**Comment by williammpe** [comment] 2022-11-29 19:05
I'm same problem.
How to disable automatic tags?

**Comment by LamNapp** [comment] 2022-11-29 19:39
Interesting subject, I would like to know how to resolve this issue as well.

**Comment by zmb3** [comment] 2022-11-29 20:32
Duplicate of #17102

**Closed by zmb3** 2022-11-29 20:32 UTC
Labels: feature-request
