### ISSUE TITLE
The `app.session.start` event is not generated for `tsh app login`

### ISSUE THREAD

**Issue by espadolini** [gravitational/teleport#9536] opened 2021-12-22 10:16 UTC
After calling `tsh app login appname`, no audit event is generated, unlike what happens when starting a new app session through the web interface; this is because the `app.session.start` audit event is generated in `lib/web/apps.go:(*Handler).createAppSession` - on the "client" side of things - whereas `tsh app login` goes through `lib/auth/grpcserver.go:(*GRPCServer).CreateAppSession` directly.

As both the resources required and the access granted for `tsh app login` are equal to those of app sessions opened through the web interface, I would expect `tsh app login appname` to generate a similar audit event.

**Comment by tobiaszheller** [comment] 2022-08-18 12:27
How it can be implemented:

Move `app.session.start` from `lib/web/apps.go` and place it inside gRPC server implementation: `lib/auth/sessions.go` and emit event there. It will cover both paths from web and tsh. 
When moving from web to auth, 4 parameters will be missing:
`appUri`, `appName` - can be looked up by auth server.
`ConnectionMetadata.RemoteURL` -  can be taken from`p, ok := peer.FromContext(ctx); p.Addr()`
`ServerMetadata.ServerID` - probably needs to be passed as new argument inside `types.CreateAppSessionRequest`.


I am unassigning myself, because I am focusing on other tasks.

**Comment by zmb3** [comment] 2024-03-11 02:17
Closing as duplicate of #37054

**Closed by zmb3** 2024-03-11 02:17 UTC
Labels: bug, audit-log, application-access
