### ISSUE TITLE
Add the ability to select browser for `tsh login` from the CLI

### ISSUE THREAD

**Issue by pschisa** [gravitational/teleport#20562] opened 2023-01-23 17:42 UTC
What would you like Teleport to do?
Allow for `tsh login` to accept something like a `--browser` flag to indicate a non-default browser to open the SSO authentication request in.

What problem does this solve?
Improves the user experience for customers who have different SSO accounts dedicated to different browsers.

If a workaround exists, please include it.
Take the link output by the `tsh login` command and manually copy/paste it into the desired browser

**Comment by zmb3** [comment] 2023-01-23 21:37
Duplicate of #18115

**Closed by zmb3** 2023-01-23 21:37 UTC
Labels: feature-request, ux, tsh, c-aw
