### ISSUE TITLE
Log auth sign as events in Audit Log

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#9106] opened 2021-11-23 16:39 UTC
### What
Log in the audit log when a user initiates a `tctl auth sign`  remotely or directly on the auth service.  

### How
Add a new event type that logs the auth sign event, the details of what's being signed and the expiration date.

### Why
Provides audit tracking of creating identity files and other signed items.   This also provides a means of tracking the `ttl` of items. Not having this as a audit log event means a person could create a identity file with no tracking or monitoring they did so.

### Workaround
None

**Comment by espadolini** [comment] 2021-12-29 18:07
Dupe of #7544?

**Comment by zmb3** [comment] 2022-06-08 00:21
Closing as duplicate of #7544

**Closed by zmb3** 2022-06-08 00:21 UTC
Labels: feature-request, audit-log
