### ISSUE TITLE
Use GRPC for Reverse Tunnels

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#3972] opened 2020-07-02 17:39 UTC
Right now we use SSH for our reverse tunnel subsystem. We do this because SSH has quite robust support for multiple channels over a single connection and allows either the client or server to initiate a channel request (which we need for a reverse tunnel).

However we've had customers that run Teleport in environments where SSH is blocked. We added support for `HTTP CONNECT` to support these customers. However, some customers either don't have a working `HTTP CONNECT` proxy or can not deploy a working `HTTP CONNECT` proxy in their environment.

To support that use case (and also having the side benefit of reducing the number of ports Teleport requires) we should investigate how hard it would be/any performance impact of moving reverse tunnels to GRPC.

I don't think GRPC has support for reverse tunnels yet.

**Comment by webvictim** [comment] 2020-08-12 13:13
Related to #4141

**Comment by strideynet** [comment] 2022-05-21 19:02
Should this be closed in favour of #4447 as that issue seems to have more details?

**Comment by strideynet** [comment] 2022-11-09 20:46
Closed as duplicate of #4447

**Closed by strideynet** 2022-11-09 20:46 UTC
Labels: scale, networking
