### ISSUE TITLE
Request to implement audit logging for web app access

### ISSUE THREAD

**Issue by moisesmejia1200** [gravitational/teleport#16411] opened 2022-09-14 14:59 UTC
**What would you like Teleport to do?**

Admin would like the ability to have audit logging for all web app access, and the ability to record the following in audit logs
```
 "event": "<app_request>",
  "uid": "<uid>",
  "code": "<code>",
  "time": "<time>",
  "cluster_name": "<cluster-name>",
  "status_code": 200,
  "path": "<>",
  "raw_query": "",
  "method": "GET",
  "app_uri": "<URL>",
  "app_public_addr": "<URL>",
  "app_name": "<app name> "
} 
```

***What problem does this solve?***

This FR would allow the admin to view which resources and which HTTP verbs were used by the user. Currently, this is a blocker for the customer as they are beginning to evaluate the application access feature and require audit logging as they have in session recording.  

***If a workaround exists, please include it.***
No workaround exists at the moment

**Comment by webvictim** [comment] 2022-10-28 03:46
To be clear - this information about every web request made via Teleport is all already logged in 5-minute app session chunks. This data can be seen using `tsh play --format json <chunk_id>`.

The chunk IDs can be found in the audit log using the method described here: https://github.com/gravitational/teleport/discussions/11334#discussioncomment-2415029

This feature request is specifically to expose each line of chunk data as individual audit log events. I would speculate that we are unlikely to add this feature to Teleport due to the incredibly high number of audit events that could potentially be created and their ability to overwhelm the audit log, making it unusable. Indeed, this is the reason that the app data chunking was implemented in the first place.

**Comment by zmb3** [comment] 2022-12-21 19:22
Duplicate of #16411

**Closed by zmb3** 2022-12-21 19:22 UTC
Labels: feature-request, audit-log, c-nt
