### ISSUE TITLE
Incorrect version codename referenced for debian-bookworm

### ISSUE THREAD

**Issue by MnemonicCode** [gravitational/teleport#17658] opened 2022-10-21 13:09 UTC
https://github.com/gravitational/teleport/blob/de5228f78424f72d03e95d767d02b53655df26fc/build.assets/tooling/cmd/build-os-package-repos/runners.go#L48

Should be "bookworm", not "bookwork", I believe.

**Comment by zmb3** [comment] 2022-10-22 16:11
Duplicate of #17591

**Closed** 2022-10-22 16:11 UTC
