### ISSUE TITLE
SSH session recording exits with error `ERRO Timed out waiting for PTY copy to finish, session data  may be missing.`

### ISSUE THREAD

**Issue by tigrato** [gravitational/teleport#36852] opened 2024-01-18 12:36 UTC
Expected behavior:

SSH session recording shouldn't trigger an error when closing a session with exit

Current behavior:

```
tsh ssh ubuntu@0842d080-0b63-4244-a00e-e241d50515b0
ubuntu@ip-172-31-8-177:~$ exit
logout
the connection was closed on the remote side at  18 Jan 24 12:33 WET
``` 

And node prints:

```
2024-01-18T12:33:41Z [SESSION:N] ERRO Timed out waiting for PTY copy to finish, session data  may be missing. session_id:98cdeae5-81bc-4bf0-bf20-2b7bd1198f4e srv/sess.go:1326


```

The recording seems to exist but we shouldn't trigger that error

Bug details:
- Teleport version
- Recreation steps
- Debug logs

**Comment by jakule** [comment] 2024-01-19 23:23
Looks like duplicate of https://github.com/gravitational/teleport/issues/21267

**Comment by tigrato** [comment] 2024-01-20 19:09
> Looks like duplicate of https://github.com/gravitational/teleport/issues/21267

Yes. Closing this one

**Closed** 2024-01-20 19:09 UTC
Labels: bug, test-plan, ssh
