### ISSUE TITLE
tsh --login flag issue

### ISSUE THREAD

**Issue by papiveron** [gravitational/teleport#1471] opened 2017-11-23 05:40 UTC
Hi,

Please what is the real purpose of the `--login` flag of tsh command?
I thought it's to spefy the login user on the remote host like with ssh, but it doesn't work, and raise an access denied when using `--login` flag
Here is the behavior in my case
```
█▓▒░nixmind@mountain-view░▒▓██▓▒░ Thu Nov 23 06:31:58am
/home/nixmind> tsh ssh --proxy=teleport-proxy.domain.com --cluster=ca-cloudpractice --user=eugene.ngontang admin@teleport-cloudpractice-1
admin@ip-172-31-0-66:~$ exit
logout
the connection was closed on the remote side on  23 Nov 17 06:32 CET
█▓▒░nixmind@mountain-view░▒▓██▓▒░ Thu Nov 23 06:32:17am
/home/nixmind> tsh ssh --proxy=teleport-proxy.domain.com --cluster=ca-cloudpractice --user=eugene.ngontang teleport-cloudpractice-1 -l admin
access denied to nixmind connecting to teleport-cloudpractice-1
█▓▒░nixmind@mountain-view░▒▓██▓▒░ Thu Nov 23 06:32:33am
/home/nixmind> tsh ssh --proxy=teleport-proxy.domain.com --cluster=ca-cloudpractice --user=eugene.ngontang teleport-cloudpractice-1 --login=admin
access denied to nixmind connecting to teleport-cloudpractice-1
█▓▒░nixmind@mountain-view░▒▓██▓▒░ Thu Nov 23 06:32:42am
/home/nixmind> tsh version
Teleport v2.3.5 git:v2.3.5-0-gbc8dba6
█▓▒░nixmind@mountain-view░▒▓██▓▒░ Thu Nov 23 06:32:42am
/home/nixmind> 
```
As you can see it works when I use the syntax `admin@host`, but don't work when using `--login` flag

Thanks for help understanding

**Comment by klizhentas** [comment] 2017-11-23 20:10
from the first sight should work exactly as you have described, let me try to reproduce and get back to you

**Comment by klizhentas** [comment] 2017-11-23 23:15
hmm, I've tried to reproduce and could not. Can you add --debug flag and send me the logs from journald?

**Comment by papiveron** [comment] 2017-11-27 10:53
Hi @klizhentas 

This is what I can have with `--debug` flag.

```
▓▒░nixmind@mountain-view░▒▓██▓▒░ Mon Nov 27 11:46:25am
/home/nixmind> tsh --debug ssh --proxy=teleport-proxy.domain.com --cluster=ca-cloudpractice --user=eugene.ngontang admin@teleport-cloudpractice-1
admin@ip-172-31-0-66:~$ exit
logout
the connection was closed on the remote side on  27 Nov 17 11:46 CET
█▓▒░nixmind@mountain-view░▒▓██▓▒░ Mon Nov 27 11:46:52am
/home/nixmind> tsh --debug ssh --proxy=teleport-proxy.domain.com --cluster=ca-cloudpractice --user=eugene.ngontang teleport-cloudpractice-1  -l admin

ERROR REPORT:
Original Error: *errors.errorString access denied to nixmind connecting to teleport-cloudpractice-1
Stack Trace:
	/gopath/src/github.com/gravitational/teleport/lib/client/client.go:281 github.com/gravitational/teleport/lib/client.(*ProxyClient).ConnectToNode
	/gopath/src/github.com/gravitational/teleport/lib/client/api.go:473 github.com/gravitational/teleport/lib/client.(*TeleportClient).SSH
	/gopath/src/github.com/gravitational/teleport/tool/tsh/tsh.go:424 main.onSSH
	/gopath/src/github.com/gravitational/teleport/tool/tsh/tsh.go:283 main.Run
	/gopath/src/github.com/gravitational/teleport/tool/tsh/tsh.go:140 main.main
	/opt/go/src/runtime/proc.go:194 runtime.main
	/opt/go/src/runtime/asm_amd64.s:2198 runtime.goexit
User Message: access denied to nixmind connecting to teleport-cloudpractice-1

█▓▒░nixmind@mountain-view░▒▓██▓▒░ Mon Nov 27 11:47:39am
/home/nixmind> tsh --debug ssh --proxy=teleport-proxy.domain.com --cluster=ca-cloudpractice --user=eugene.ngontang teleport-cloudpractice-1 --login=admin

ERROR REPORT:
Original Error: *errors.errorString access denied to nixmind connecting to teleport-cloudpractice-1
Stack Trace:
	/gopath/src/github.com/gravitational/teleport/lib/client/client.go:281 github.com/gravitational/teleport/lib/client.(*ProxyClient).ConnectToNode
	/gopath/src/github.com/gravitational/teleport/lib/client/api.go:473 github.com/gravitational/teleport/lib/client.(*TeleportClient).SSH
	/gopath/src/github.com/gravitational/teleport/tool/tsh/tsh.go:424 main.onSSH
	/gopath/src/github.com/gravitational/teleport/tool/tsh/tsh.go:283 main.Run
	/gopath/src/github.com/gravitational/teleport/tool/tsh/tsh.go:140 main.main
	/opt/go/src/runtime/proc.go:194 runtime.main
	/opt/go/src/runtime/asm_amd64.s:2198 runtime.goexit
User Message: access denied to nixmind connecting to teleport-cloudpractice-1

█▓▒░nixmind@mountain-view░▒▓██▓▒░ Mon Nov 27 11:47:40am
/home/nixmind> 
```
As you can see, it does not reconize the `--login` flag, and take my current `username`, that's why I get an access denied.

Thanks for helping

Regards,

**Comment by klizhentas** [comment] 2017-11-27 18:53
ok, I need to process this, will dig into this, thanks for getting the logs

**Comment by kontsevoy** [comment] 2017-12-11 19:17
Correct, these two should be equivalent:

```
tsh ssh --login jon host
```

and 

```
tsh ssh jon@host
```

**Comment by russjones** [comment] 2018-10-11 00:07
I was able to reproduce this. I think issue is how `tsh` handles flags:

```
usage: tsh ssh [<flags>] <[user@]host> [<command>...]
```

That means to use `-l` or `--login` they have to occur before `<[user@]host>` not after.

I'm going to close this ticket for now since this just seems to be a shortcoming of the argument parsing library we use.

**Closed by russjones** 2018-10-11 00:07 UTC
