### ISSUE TITLE
Error communicating with kubernetes cluster after switching between different teleport instances

### ISSUE THREAD

**Issue by cnelson** [gravitational/teleport#6270] opened 2021-04-01 02:48 UTC
### Description
We have two teleport instances "A" and "B".  Each of these instances is a root cluster, and has several leaf-clusters attached.  Each instance has at least one kubernetes cluster connected to it.

When switching between clusters we frequently receive the error from `kubectl`
```
Unable to connect to the server: getting credentials: failed parsing client key/certificate: tls: private key does not match public key
```

**What happened**:

Log into cluster A, everything works
Log into cluster B, everything works
Switch back to cluster A (by re-logging in), everything works
Switch back to cluster B (by re-logging in ), we receive the error message above when using kubectl

This will happen with either cluster being the first one logged into.

Logging out via `tsh logout` and logging back in to the desired cluster fixes the issue.

**What you expected to happen**:

I expect to be able switch between teleport instances withouth error

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
Logout of everything
```
$ tsh logout
Logged out all users from all proxies.
```

Log in to cluster A
```
$ tsh login --proxy root-cluster-A
If browser window does not open automatically, open it by clicking on the link:
 http://127.0.0.1:63462/4035d5d3-2510-465b-90c8-aa83e0622004
  Logged in as:       cnelson
  Cluster:            root-cluster-A
  Roles:              admin*
  Logins:             cnelson, ubuntu, ec2-user
  Kubernetes:         enabled
  Kubernetes cluster: "root-cluster-A"
  Kubernetes groups:  teleport
  Valid until:        2021-04-01 07:12:13 -0700 PDT [valid for 12h0m0s]
  Extensions:         permit-agent-forwarding, permit-port-forwarding, permit-pty

# talking to k8s works fine
$ kubectl -n default get service kubernetes
NAME         TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
kubernetes   ClusterIP   192.0.2.1   <none>        443/TCP   308d
```

Log in to cluster B;  last time I was connected I was connected to a leaf cluster that leaf is automatically selected
```
$ tsh login --proxy root-cluster-B
If browser window does not open automatically, open it by clicking on the link:
 http://127.0.0.1:63646/f9e96a18-c561-4ff0-875e-6c5a25ae82fd
> Profile URL:        root-cluster-B
  Logged in as:       cnelson
  Cluster:            root-cluster-B-leaf
  Roles:              admin*
  Logins:             cnelson, ubuntu, ec2-user
  Kubernetes:         enabled
  Kubernetes groups:  teleport
  Valid until:        2021-04-01 07:13:07 -0700 PDT [valid for 12h0m0s]
  Extensions:         permit-agent-forwarding, permit-port-forwarding, permit-pty

  Profile URL:        root-cluster-A
  Logged in as:       cnelson
  Cluster:            root-cluster-A
  Roles:              admin*
  Logins:             cnelson, ubuntu, ec2-user
  Kubernetes:         enabled
  Kubernetes cluster: "root-cluster-A"
  Kubernetes groups:  teleport
  Valid until:        2021-04-01 07:12:13 -0700 PDT [valid for 11h59m0s]
  Extensions:         permit-agent-forwarding, permit-port-forwarding, permit-pty

# talking to k8s via the leaf cluster works fine
$ kubectl -n default get service kubernetes
NAME         TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)   AGE
kubernetes   ClusterIP   203.0.113.1   <none>       
```

Switch Back to cluster A
```
$ tsh login --proxy root-cluster-A
If browser window does not open automatically, open it by clicking on the link:
 http://127.0.0.1:63759/5f45da54-3fba-4daa-8208-b529456be12d
> Profile URL:        root-cluster-A
  Logged in as:       cnelson
  Cluster:            root-cluster-A
  Roles:              admin*
  Logins:             cnelson, ubuntu, ec2-user
  Kubernetes:         enabled
  Kubernetes cluster: "root-cluster-A"
  Kubernetes groups:  teleport
  Valid until:        2021-04-01 07:13:30 -0700 PDT [valid for 12h0m0s]
  Extensions:         permit-agent-forwarding, permit-port-forwarding, permit-pty

  Profile URL:        root-cluster-B
  Logged in as:       cnelson
  Cluster:            root-cluster-B-leaf
  Roles:              admin*
  Logins:             cnelson, ubuntu, ec2-user
  Kubernetes:         enabled
  Kubernetes cluster: "root-cluster-B-leaf"
  Kubernetes groups:  teleport
  Valid until:        2021-04-01 07:13:07 -0700 PDT [valid for 12h0m0s]
  Extensions:         permit-agent-forwarding, permit-port-forwarding, permit-pty

# Talking to k8s still works
$ kubectl -n default get service kubernetes
NAME         TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
kubernetes   ClusterIP   192.0.2.1   <none>        443/TCP   308d
```

Switch back to cluster B

```
$ tsh login --proxy root-cluster-B
If browser window does not open automatically, open it by clicking on the link:
 http://127.0.0.1:63798/35ec8b53-abf5-4e79-8e55-1f5d6ee56fa3
> Profile URL:        root-cluster-B
  Logged in as:       cnelson
  Cluster:            prof-leaf
  Roles:              admin*
  Logins:             cnelson, ubuntu, ec2-user
  Kubernetes:         enabled
  Kubernetes groups:  teleport
  Valid until:        2021-04-01 07:13:43 -0700 PDT [valid for 12h0m0s]
  Extensions:         permit-agent-forwarding, permit-port-forwarding, permit-pty

  Profile URL:        root-cluster-A
  Logged in as:       cnelson
  Cluster:            root-cluster-A
  Roles:              admin*
  Logins:             cnelson, ubuntu, ec2-user
  Kubernetes:         enabled
  Kubernetes cluster: "root-cluster-A"
  Kubernetes groups:  teleport
  Valid until:        2021-04-01 07:13:30 -0700 PDT [valid for 12h0m0s]
  Extensions:         permit-agent-forwarding, permit-port-forwarding, permit-pty
```

Now kubectl fails:

```
$ kubectl -n default get service kubernetes
Unable to connect to the server: getting credentials: failed parsing client key/certificate: tls: private key does not match public key
```

### Server Details
- Teleport version (run `teleport version`): `Teleport v6.0.2 git:v6.0.2-0-g1cb1420b7 go1.15.5`
- Server OS (e.g. from `/etc/os-release`): 
```
 NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): This issue occurs with deployments in AWS, Azure, and GCP
- Additional details:

### Client Details
- Tsh version (`tsh version`): `Teleport v6.0.2 git:v6.0.2-0-g1cb1420b7 go1.15.5`
- Computer OS (e.g. Linux, macOS, Windows):
```
ProductName:	Mac OS X
ProductVersion:	10.15.7
BuildVersion:	19H15
```
- Installed via (e.g. apt, yum, brew, website download): Website download

**Comment by russjones** [comment] 2021-04-06 17:49
@andrejtokarcik This might be fixed in 6.1, can you try and reproduce?

**Comment by andrejtokarcik** [comment] 2021-04-09 20:04
I don't think this is fixed in 6.1, and I'm unable to reproduce it exactly with 6.0 either. The `kubectl` calls when logged into a leaf cluster always fail for me, either with
```
Error from server: connection rejected: failed dialing through tunnel (dial tcp 0.0.0.0:3026: connect: connection refused) or directly (no tunnel connection found: no kube reverse tunnel for  found)
```
or (if `kube_listen_addr` is set to listen on port 3026) with
```
Error from server: x509: certificate signed by unknown authority
```

In the correctly handled case, kubeconfig gets updated with a user entry named `<teleportCluster>-<kubeCluster>` that is associated with a `tsh kube credentials` command, while what I'm observing with a leaf cluster is that it produces a mere `<teleportCluster>` user associated with explicit `client-certificate-data`/`client-key-data`.

It'd therefore seem it was just an accident k8s access was working when logged into a leaf cluster. The question is whether and how we should support this use case properly. @awly should be able to recommend how to proceed.

**Comment by awly** [comment] 2021-04-14 21:46
@andrejtokarcik i'd be curious to see your setup. It may contain both teleport-generated `kubeconfig` entries and entries created by something else (like the cloud provider tooling or minikube).
Teleport 5.0 and later should never end up with raw client key/cert in the `kubeconfig`.

@tcsc since you're been digging into k8s and trusted cluster plumbing recently, can you try and repro this?

**Comment by tcsc** [comment] 2021-04-15 08:12
Happy to have a peek. @andrejtokarcik - I may need to borrow your testing setup as a starting point.

**Comment by zmb3** [comment] 2024-06-25 16:37
Closing due to inactivity

**Closed by zmb3** 2024-06-25 16:37 UTC
Labels: bug, kubernetes-access
