### ISSUE TITLE
[UX] tsh login should allow bypassing --proxy

### ISSUE THREAD

**Issue by jchauncey** [gravitational/teleport#592] opened 2016-10-26 04:22 UTC
Scenario: I'm starting my day one of the first things I would do is `tsh login --proxy=my-proxy-host --user=myuser`

Expectation: I expect subsequent commands such as `tsh ls` or `tsh clusters` to use the proxy I specified above and not need  me to specify it again.

Am I wrong in expecting that to be true?

**Comment by jchauncey** [comment] 2016-10-26 04:25
Furthermore, because my laptop username does not match the username I created I have to specify `--user` for all commands. 

At that point why even bother using `tsh login`

**Comment by jchauncey** [comment] 2016-10-26 04:44
Also looks like when I do `tsh ls` no matter what i pass in for `--user` it uses my laptop username which isnt right. 

```
╰─○tsh ls --proxy=proxy-host --user="jchauncey"
access denied to login "jonathanchauncey" when connecting to : ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
```

**Comment by klizhentas** [comment] 2016-10-26 04:48
@jchauncey try `tsh --login` to set remote host login, most likely that's the remote server does rejecting the connection

**Comment by jchauncey** [comment] 2016-10-26 05:02
Whats the value for `--login`? The auth host?

**Comment by klizhentas** [comment] 2016-10-26 05:07
the login name on the host

**Comment by jchauncey** [comment] 2016-10-26 05:18
I dont get it. Why would I want to pass in `--login` for the `ls` command? I'm not wanting to login to a host just list all nodes that are possible to ssh into.

**Comment by kontsevoy** [comment] 2016-10-26 06:19
@jchauncey **exactly** what you're asking for has been implemented and it's called "user profiles". New versions of `tsh` do not require subsequent `--proxy` flags.

It's already in master branch. You can `git clone` the repo and type `make tsh` to get yourself a nicer `tsh` version. 

Let me know if that works.

**Comment by kontsevoy** [comment] 2016-10-26 06:21
Dupe of #578 (and it's done already)

**Closed** 2016-10-26 06:21 UTC
Labels: duplicate

**Comment by klizhentas** [comment] 2016-10-26 06:25
@jchauncey, to follow up on your question - If I remember it correctly, you have to supply "login" to SSH connection that matches one of the principals listed in the SSH certificate, so even if you are not technically creating interactive session, you still have to set the proper match, slightly annoying, but set by SSH proto/auth model.

**Comment by jchauncey** [comment] 2016-10-26 12:52
@kontsevoy thanks I'll do that

**Comment by jchauncey** [comment] 2016-10-26 14:31
alright rebuilt tsh from master but i still have this problem - 

```
./tsh ls --cluster=41cdb4f9-5035-4bdf-98b8-d2ff604cbab0 --proxy=<proxy host> --user=jchauncey
access denied to login "jonathanchauncey" when connecting to : ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
```
