### ISSUE TITLE
ServiceNow plugin for Access request

### ISSUE THREAD

**Issue by nivasomu** [gravitational/teleport#19558] opened 2022-12-20 23:48 UTC
Teleport has an Access request plugin for various apps like slack, Jira, etc 
Similarly, ServiceNow has access management automation capability and it would be nice to have a ServiceNow plugin to integrate the teleport access request feature with the access management automation on ServiceNow.

This helps Servicenow users to leverage the access management automation capability to grant access based on the rules and requirements inside the service now platform.

[ServiceNow docs](https://docs.servicenow.com/bundle/rome-servicenow-platform/page/build/service-portal/concept/access-management.html)

**Comment by stevenGravy** [comment] 2022-12-21 12:30
duplicate of https://github.com/gravitational/teleport/issues/15366. recommend adding `c-va` to that gh issue and closing this one.

**Closed** 2022-12-21 15:45 UTC
Labels: feature-request, access-requests, c-va
