### ISSUE TITLE
tctl users ls on fresh cluster returns null instead of empty array

### ISSUE THREAD

**Issue by rifler** [gravitational/teleport#33537] opened 2023-10-16 17:36 UTC
Expected behavior:
```bash
kubectl exec -i deployment/teleport-auth -n teleport -- tctl users ls --format=json

[]
```

Current behavior:
```bash
kubectl exec -i deployment/teleport-auth -n teleport -- tctl users ls --format=json

null
```

Bug details:
- Teleport version 13.4.0
- Recreation steps
- Debug logs

**Comment by zmb3** [comment] 2023-10-16 20:36
Duplicate of #18672

**Closed by zmb3** 2023-10-16 20:36 UTC
Labels: bug
