### ISSUE TITLE
Remote cluster removal requires restart.

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#4876] opened 2020-11-18 01:06 UTC
Customer reported that after removing a remote cluster with `tctl rm rc/some_cluster` it is still visible in the Web UI, a server restart is required to get rid of it.

This occurs in Teleport 4.4.1.

**Comment by russjones** [comment] 2021-03-02 02:33
@tcsc Can you try and reproduce this issue to see if it still occurs. If it does fix it?

**Comment by tcsc** [comment] 2021-03-12 01:06
Reproduced in 6.0, via @travelton:

> 1. Unzip the attachment.
> 2. `docker-compose up`
> 3. Exec into both the root and leaf containers and run `tctl users add root --roles=admin`
> 4. Create your users via the web UIs `https://localhost:3080` and `https://localhost:4080`
> 5. Copy the contents of the `tc.yaml` file and paste it into the leaf’s trusted cluster create section of the web UI to establish the trusted clusters
> * Now to reproduce the weirdness, exec into the root pod and delete the remote cluster `tctl rm rc/leaf`. It should disappear from the root cluster list.
> * From the leaf cluster, delete the trusted cluster from the web UI. Then with the `tc.yaml` file, create the trust again.
> * From the root cluster, try to access the leaf cluster. Here is where I ran into errors. I kept getting “leaf cluster not found”.

**Comment by tcsc** [comment] 2021-03-17 03:22
So - after getting some strange behaviour caused by poor configuration on my part, I went back to basics and tried to reproduce this again from scratch with v6.0.0., and I'm now reasonably convinced that this is fixed in v6.0.

I _do_ see the `leaf` node in the `root` UI after it is removed with `tctl rm rc/leaf`, but _only until the next page refresh_. Once the Clusters page is refreshed it is gone. Attempting to access the node *before* the page refresh results in a *node leaf is offline* message, which seems appropriate. Navigating back to the clusters page refreshes the list and does not show `leaf` as an available cluster.

@russjones, @travelton - what are your thoughts?

**Comment by travelton** [comment] 2021-03-17 14:34
@tcsc There were a few improvements in [these](https://github.com/gravitational/teleport/commits/92ed2db38ac78fdb48eba312cb4f3d0b85b4bced/lib/reversetunnel/peer.go) parts, I wonder if it was inadvertently fixed. 

Perhaps [this](https://github.com/gravitational/teleport/commit/6b53312bed9fdc94ade2739e2ba087464420a032#diff-99a6f7d1a7716833822e65219c77dc5f49f85a3b74d241453e501c75a5cd9bf7) commit fixed it? 

Thing is, I went back to a version prior to this commit and could not reproduce. :(

**Comment by tcsc** [comment] 2021-03-18 01:50
I went back and was able to replicate with 4.4.1, so I am happy to say that this has been fixed in 6.0

**Closed** 2021-03-18 01:54 UTC
Labels: bug, c-sl, c-sn, ux
