### ISSUE TITLE
Failed to flush close the stream

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#6352] opened 2021-04-08 04:07 UTC
Seeing the following on `6.1.0-rc.1` when I use `tsh ssh`.

```
WARN [AUTH:GRPC] Failed to flush close the stream. error:[
ERROR REPORT:
Original Error: *trace.ConnectionProblemError emitter has been closed
Stack Trace:
	/home/rjones/go/src/github.com/gravitational/teleport/lib/events/stream.go:422 github.com/gravitational/teleport/lib/events.(*ProtoStream).Close
	/home/rjones/go/src/github.com/gravitational/teleport/lib/events/emitter.go:453 github.com/gravitational/teleport/lib/events.(*CheckingStream).Close
	/home/rjones/go/src/github.com/gravitational/teleport/lib/auth/auth_with_roles.go:1913 github.com/gravitational/teleport/lib/auth.(*streamWithRoles).Close
	/home/rjones/go/src/github.com/gravitational/teleport/lib/auth/grpcserver.go:139 github.com/gravitational/teleport/lib/auth.(*GRPCServer).CreateAuditStream.func2
	/home/rjones/go/src/github.com/gravitational/teleport/lib/auth/grpcserver.go:214 github.com/gravitational/teleport/lib/auth.(*GRPCServer).CreateAuditStream
	/home/rjones/go/src/github.com/gravitational/teleport/vendor/github.com/gravitational/teleport/api/client/proto/authservice.pb.go:9114 github.com/gravitational/teleport/api/client/proto._AuthService_CreateAuditStream_Handler
	/home/rjones/go/src/github.com/gravitational/teleport/lib/auth/middleware.go:386 github.com/gravitational/teleport/lib/auth.(*Middleware).StreamInterceptor
	/home/rjones/go/src/github.com/gravitational/teleport/vendor/google.golang.org/grpc/server.go:1336 google.golang.org/grpc.(*Server).processStreamingRPC
	/home/rjones/go/src/github.com/gravitational/teleport/vendor/google.golang.org/grpc/server.go:1409 google.golang.org/grpc.(*Server).handleStream
	/home/rjones/go/src/github.com/gravitational/teleport/vendor/google.golang.org/grpc/server.go:746 google.golang.org/grpc.(*Server).serveStreams.func1.1
	/usr/local/go/src/runtime/asm_amd64.s:1371 runtime.goexit
User Message: emitter has been closed] auth/grpcserver.go:140
```

**Comment by r0mant** [comment] 2021-04-08 05:34
This looks like a race between `ProtoStream.Complete()`:

https://github.com/gravitational/teleport/blob/v6.1.0-rc.1/lib/events/stream.go#L392-L404

and `ProtoStream.Close()`:

https://github.com/gravitational/teleport/blob/v6.1.0-rc.1/lib/events/stream.go#L414-L426

which are called from `GRPCServer.CreateAuditStream()`:

https://github.com/gravitational/teleport/blob/v6.1.0-rc.1/lib/auth/grpcserver.go#L139
https://github.com/gravitational/teleport/blob/v6.1.0-rc.1/lib/auth/grpcserver.go#L184

The Complete() call closes the `cancelCtx` when the upload is done, and then Close() call can select either of these cases since both fire:

```
	case <-s.uploadsCtx.Done():
		return nil
	case <-s.cancelCtx.Done():
		return trace.ConnectionProblem(s.cancelCtx.Err(), "emitter has been closed")
```

There's no order to select statement cases so either one can be picked, from https://golang.org/ref/spec#Select_statements:

> If one or more of the communications can proceed, a single one that can proceed is chosen via a uniform pseudo-random selection.

So it looks like the only side-effect of this is that in some cases (when Go picks the cancelCtx.Done() branch) we'll get this warning message. Should fix this nonetheless.

**Comment by andrejtokarcik** [comment] 2021-04-13 18:06
Duplicate of https://github.com/gravitational/teleport/issues/4929?

**Comment by awly** [comment] 2021-04-19 16:08
Yep, dup of https://github.com/gravitational/teleport/issues/4929

**Closed by awly** 2021-04-19 16:08 UTC
Labels: bug
