### ISSUE TITLE
Hide login principal from web UI if no node will actually allow you to use it

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#3311] opened 2020-01-28 13:26 UTC
**What happened**: A customer set up a Teleport role for authenticating with Gitlab - this role gives the user permission to log in as `git`, but denies all labels - so Teleport will prohibit any interactive logins as the `git` user.

Unfortunately, the list of logins in the web UI is sorted alphabetically and the default username they use is lower alphabetically in the list than `git`, so now all the nodes in the web UI show a default username of `git` (which is not permitted to log in) rather than the actual username (which **is** permitted to log in)

**What you expected to happen**: We should evaluate RBAC permissions and if the node count where a given login/principal is allowed to log in equals zero, we shouldn't show the login at all in the web UI.

Alternatively, we could provide a way to de-prioritise the `git` username in the web UI and send it to the bottom of the list - similar to how we prioritise `root` to the top of the list when that username is present.

**How to reproduce it (as minimally and precisely as possible)**: Create a role adding a principal but denying all labels, then observe that the user still appears in the web UI even though no node can make use of it.

**Environment**:
- Teleport version (use `teleport version`): `Teleport Enterprise v4.2.0git:v4.2.0-0-g3090806 go1.13.2`
- Tsh version (use `tsh version`): `Teleport v4.2.0 git:v4.2.0-0-g3090806 go1.13.2`
- OS (e.g. from /etc/os-release): `Fedora 30`

**Comment by benarent** [comment] 2020-01-31 19:39
Thanks for an awesome report of the issue @webvictim 

@alex-kovoy  Do you know what we currently have in place for UI login logic? If not, I can create a proposal to address this issue.

**Comment by stevenGravy** [comment] 2020-02-23 18:49
I also see a related issue that all nodes list all users that a user can login with their roles. The security prevents the user authenticating but you get a lot of users that aren't applicable across nodes.  For example setup two roles, test and dev.  'test' role allows logging in as 'testuser' with a label match of type: test.  The same for dev with a 'devuser' with a node label match.  All of the users' nodes now list 'testuser' and 'devuser' even if that node doesn't match that role configuration.

**Comment by webvictim** [comment] 2020-02-24 12:49
Yes, this is absolutely what I wanted to fix. The command-line client has the same issue where it displays all logins but will deny you access if RBAC prevents it - however it’s less obvious because there isn’t a drop-down menu offering you the chance to log in as that user.

**Comment by benarent** [comment] 2020-02-24 17:55
We won't fix the problem that Gus has described in the next version. The edge cases can get complicated ( e.g. PAM users which are created on login ) . We are going to no longer promote `root` as the first login. I'm open to a consider a hack to fix the deprioritization via label, or we could provide customers with an ordered preference of logins via YAML.

**Comment by Aharic** [comment] 2021-06-01 17:47
Per discussion during weekly support-prod triage meeting, @awly suggested adding logging and UI messaging to give users and admins better visibility about which logins would work with specific servers to help clear up confusion.

**Comment by zmb3** [comment] 2023-02-27 15:33
I'm not able to reproduce this with the following role:

```
kind: role
version: v5
metadata:
  name: nogit
spec:
  allow:
    logins:
    - git
  deny:
    node_labels:
      '*': '*'
```

If I assign that role to my user, no nodes show up at all due to the wildcard deny.

If I don't assign that role to my user but it does exist in the backend, I do not see the `git` login in the web UI.

**Closed by zmb3** 2023-02-27 15:33 UTC
Labels: enhancement, ui, c-bi

**Comment by webvictim** [comment] 2023-02-27 19:14
I think this issue was so old that this has been independently fixed.
