### ISSUE TITLE
`tsh play` against a remote trusted cluster session uses a default API domain

### ISSUE THREAD

**Issue by mdwn** [gravitational/teleport#17192] opened 2022-10-07 20:06 UTC
Expected behavior:

When issuing `tsh play` against a session recorded on a remote trusted cluster, it should work.

Current behavior:

An error message is output.

Bug details:
- Teleport version 11.0.0-alpha2
- Recreation steps
  - Set up a root cluster and a remote trusted cluster.
  - Create a session on a node on the remote cluster while logged into the root cluster.
  - Attempt to play the session while logged into the root cluster.
- Debug logs
```
tsh play --cluster=test11.trustedteleport ee7b939d-749c-48e3-9ade-f17420b105d1
ERROR: Get "https://teleport.cluster.local/v2/namespaces/default/sessions/ee7b939d-749c-48e3-9ade-f17420b105d1/events?print=true": EOF
```

**Comment by zmb3** [comment] 2022-10-12 19:00
Did you actually run `teleport tsh play` or is that just a copy paste error?

**Comment by mdwn** [comment] 2022-10-13 18:10
> Did you actually run `teleport tsh play` or is that just a copy paste error?

Ah no, it's an artifact of my zsh shell and the directory I was in. I'll remove that so it's more clear.

**Comment by vitorenesduarte** [comment] 2023-01-12 20:37
@mdwn I followed the [trusted clusters guide](https://goteleport.com/docs/management/admin/trustedclusters/) and couldn't reproduce this.

I only got one error when I tried to play the session:
```bash
build/tsh play --cluster=vitor22.teleport.sh df7248b7-dbfd-46ea-a25e-fb7fc94e88f4
ERROR: access denied to perform action "read" on "session"
```

But `tsh play` worked after I updated the `visitor` role to include the following:
```yaml
    rules:
    - resources:
      - session
      verbs:
      - list
      - read
```

**Comment by vitorenesduarte** [comment] 2023-01-12 20:45
Closing after syncing with @mdwn as this was likely an operator error.

**Closed by vitorenesduarte** 2023-01-12 20:45 UTC
Labels: bug, tsh
