### ISSUE TITLE
`TestKube/EphemeralContainers` flakiness

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#40969] opened 2024-04-26 21:53 UTC
Failed in the merge queue: https://github.com/gravitational/teleport/actions/runs/8854528809/job/24317760696.

```
    kube_integration_test.go:1539: 
        	Error Trace:	/__w/teleport/teleport/integration/kube_integration_test.go:1539
        	            				/__w/teleport/teleport/integration/kube_integration_test.go:168
        	Error:      	Received unexpected error:
        	            	pods "test-pod" is forbidden: User "ci" cannot create resource "pods/attach" in API group "" in the namespace "teletest"
        	Test:       	TestKube/EphemeralContainers
```

**Comment by GavinFrazar** [comment] 2024-05-07 23:07
https://github.com/gravitational/teleport/actions/runs/8993318798/job/24704894991?pr=41129

```    kube_integration_test.go:1539: 
        	Error Trace:	/__w/teleport/teleport/integration/kube_integration_test.go:1539
        	            				/__w/teleport/teleport/integration/kube_integration_test.go:168
        	Error:      	Received unexpected error:
        	            	Internal error occurred: error executing command in container: unable to upgrade connection: container ephemeral-container not found in pod test-pod_teletest
        	Test:       	TestKube/EphemeralContainers
```

**Comment by GavinFrazar** [comment] 2024-05-09 19:34
https://github.com/gravitational/teleport/actions/runs/9012003224/job/24760488512?pr=41351

```
---
Connection closed: unable to upgrade connection: container ephemeral-container not found in pod test-pod_teletest
{"caller":"streamproto/proto.go:173","component":null,"error":"websocket: close sent","level":"warning","message":"Failed to read message from websocket","timestamp":"2024-05-09T03:44:41Z"}
    kube_integration_test.go:1539: 
        	Error Trace:	/__w/teleport/teleport/integration/kube_integration_test.go:1539
        	            				/__w/teleport/teleport/integration/kube_integration_test.go:168
        	Error:      	Received unexpected error:
        	            	Internal error occurred: error executing command in container: unable to upgrade connection: container ephemeral-container not found in pod test-pod_teletest
        	Test:       	TestKube/EphemeralContainers
```

**Comment by capnspacehook** [comment] 2024-05-15 13:21
I found and fixed the cause of the above race, but I've been running the test locally thousands of times with all CPU cores, 1 cpu core etc and still can't reproduce the `unable to upgrade connection` issue

**Comment by GavinFrazar** [comment] 2024-05-15 19:51
hit today as well: https://github.com/gravitational/teleport/actions/runs/9100380912/job/25015101195

```
Creating ephemeral container ephemeral-container in pod teletest/test-pod
Pod teletest/test-pod successfully patched. Waiting for container to become ready.
Ephemeral container ephemeral-container is ready.
{"caller":"proxy/sess.go:643","component":"proxy:proxy:kube","error":"unable to upgrade connection: container ephemeral-container not found in pod test-pod_teletest","level":"warning","message":"Executor failed while streaming.","pid":"44273.16","session":"9b2b15fb-43da-497c-8990-7f1329f6c1f0","timestamp":"2024-05-15T17:57:41Z"}
Teleport > Closing session...

...*snip*...

{"caller":"streamproto/proto.go:173","component":null,"error":"websocket: close sent","level":"warning","message":"Failed to read message from websocket","timestamp":"2024-05-15T17:57:41Z"}
    kube_integration_test.go:1545: 
        	Error Trace:	/__w/teleport/teleport/integration/kube_integration_test.go:1545
        	            				/__w/teleport/teleport/integration/kube_integration_test.go:173
        	Error:      	Received unexpected error:
        	            	Internal error occurred: error executing command in container: unable to upgrade connection: container ephemeral-container not found in pod test-pod_teletest
        	Test:       	TestKube/EphemeralContainers
```

different line number, so it looks like it's still there after the data race issue unfortunately.
Are you testing on a linux box or macos?
Could we consider running the test container on EKS instead of using KinD? We already have an EKS cluster running for e2e tests in `./e2e/aws`, might be worth it to try using that if the flakiness is just from the hacky kube cluster setup

**Comment by capnspacehook** [comment] 2024-05-15 22:15
I'm testing on Linux using KinD which should be very similar to what the Action runners are doing. I'm not sure how unreliable KinD is since I haven't been able to repro this test failure even when running tests overnight... I messaged Tiago about this earlier today, hopefully he can help me figure out what's causing the failures

**Comment by r0mant** [comment] 2024-05-23 03:41
@capnspacehook This is still failing: https://github.com/gravitational/teleport/actions/runs/9201793316/job/25310558380. This is from a v14 backport.

**Comment by ravicious** [comment] 2024-06-03 15:13
v16 https://github.com/gravitational/teleport/actions/runs/9352399815/job/25740482576#step:8:1359

```
     kube_integration_test.go:1546: 
        	Error Trace:	/__w/teleport/teleport/integration/kube_integration_test.go:1546
        	            				/__w/teleport/teleport/integration/kube_integration_test.go:174
        	Error:      	Received unexpected error:
        	            	Internal error occurred: error executing command in container: unable to upgrade connection: container ephemeral-container not found in pod test-pod_teletest
        	Test:       	TestKube/EphemeralContainers
```

**Comment by ravicious** [comment] 2024-06-03 16:30
v14: https://github.com/gravitational/teleport/actions/runs/9353591607/job/25744471253#step:8:780

**Comment by zmb3** [comment] 2024-06-04 19:28
https://github.com/gravitational/teleport/actions/runs/9369157057/job/25792950653?pr=42364

**Comment by tigrato** [comment] 2024-06-14 16:23
https://github.com/gravitational/teleport/pull/42068 fixed the issue.
Closing

**Closed by tigrato** 2024-06-14 16:23 UTC
Labels: flaky tests
