### ISSUE TITLE
Add support for providing alternative SSH hostnames in cert principals list

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#1743] opened 2018-03-03 19:50 UTC
Sometimes it is necessary to have alternative SSH principals in the host cert list, e.g. in case if users SSH by CNAME.

This is trivially done as we already have all the logic used in Proxy:

https://github.com/gravitational/teleport/blob/master/lib/service/service.go#L1035

**Note** this is a direct customer request.

Suggested config addition (optional)

```yaml
additional_names: 
   - luna 
   - mars
```

**Comment by klizhentas** [comment] 2018-03-03 19:51
@kontsevoy let me know if it looks good to you for 2.5.1

**Comment by kontsevoy** [comment] 2018-03-05 19:32
Is our YAML parser flexible enough to dynamically support arrays for `nodename`? This way we won't need a separate property.

**Comment by kontsevoy** [comment] 2018-03-05 19:32
@klizhentas see above

**Comment by kontsevoy** [comment] 2018-03-05 19:37
another approach is to allow comma-separated hostnames. We already use this syntax for tokens, for example, i.e:

```
nodename: "proxy.example.com, ssh.example.com"
```

**Comment by kontsevoy** [comment] 2018-03-05 19:39
@klizhentas nevermind, I like the separate property better. How about we call it what it is, i.e.:

```
nodename: proxy
node_principals: ["proxy.example.com", "teleport.example.com"]
public_addr: proxy.example.com
```

**Comment by klizhentas** [comment] 2018-04-19 19:30
Actually, let's make it list right from the start:

```yaml
public_addrs: [host:port]
```

as it just came up in POC. Also, let's switch `public_addr` to `public_addrs` in proxy as well.

@kontsevoy LGTY? that's pretty much what you originally suggested. I looked at the use-cases and many times we will need a list, so let's make it a list from the start.

**Comment by kontsevoy** [comment] 2018-04-20 21:58
@klizhentas lets move this convo to #1803

**Comment by kontsevoy** [comment] 2018-04-20 22:25
Duplicate of #1803

**Closed by kontsevoy** 2018-04-20 22:25 UTC
Labels: feature request
