### ISSUE TITLE
tsh panics on empty config file

### ISSUE THREAD

**Issue by arsenetar** [gravitational/teleport#38299] opened 2024-02-15 20:41 UTC
Expected behavior:
Adding a configuration file does not cause issues with running teleport commands such as `tsh status` even if the file is empty.

Current behavior:
When adding a configuration file for teleport `config.yaml` depending on the contents different errors that can prevent using the tool occur.  In this case a panic.

Bug details:
- Teleport version 14.3.4
- Recreation steps (start with non-logged in state)
  1. Add a empty config file
  2. Run tsh status -> it works
  3. Login to a cluster
  4. Run tsh status -> it panics
  5. Try Logout of cluster -> it panics
  6. Try login to another cluster -> it panics
  7. Delete config file
  8. Run tsh login -> it works
  9. Run tsh status -> it works
- Error output for one case:
   ```
  panic: runtime error: invalid memory address or nil pointer dereference
  [signal SIGSEGV: segmentation violation code=0x1 addr=0xa0 pc=0x2aa39ef]
  
  goroutine 1 [running]:
  github.com/gravitational/teleport/api/profile.profileFromFile({0xc00250a580, 0x1f})
          github.com/gravitational/teleport/api@v0.0.0/profile/profile.go:366 +0x8f
  github.com/gravitational/teleport/api/profile.FromDir({0xc0019da360?, 0x0?}, {0xc0025486c0?, 0xc002900000?})
          github.com/gravitational/teleport/api@v0.0.0/profile/profile.go:349 +0xca
  github.com/gravitational/teleport/lib/client.(*FSProfileStore).GetProfile(0xc0025486c0?, {0xc0025486c0?, 0x1d93601?})
          github.com/gravitational/teleport/lib/client/profile.go:144 +0x2c
  github.com/gravitational/teleport/lib/client.(*Store).ReadProfileStatus(0xc001a56f80, {0xc0025486c0?, 0x4eb2980?})
          github.com/gravitational/teleport/lib/client/client_store.go:157 +0xcd
  github.com/gravitational/teleport/lib/client.(*Store).FullProfileStatus(0xc001a56f80)
          github.com/gravitational/teleport/lib/client/client_store.go:226 +0x22e
  github.com/gravitational/teleport/tool/tsh/common.(*CLIConf).FullProfileStatus(0x0?)
          github.com/gravitational/teleport/tool/tsh/common/tsh.go:3942 +0x2f
  github.com/gravitational/teleport/tool/tsh/common.onLogin(0xc00012a000)
          github.com/gravitational/teleport/tool/tsh/common/tsh.go:1838 +0x107
  github.com/gravitational/teleport/tool/tsh/common.Run({0x628dd68, 0xc00291a500}, {0xc000122110?, 0x3, 0x3}, {0x0, 0x0, 0xc0000be6d8?})
          github.com/gravitational/teleport/tool/tsh/common/tsh.go:1338 +0xe7da
  github.com/gravitational/teleport/tool/tsh/common.Main()
          github.com/gravitational/teleport/tool/tsh/common/tsh.go:558 +0x2e5
  main.main()
          github.com/gravitational/teleport/tool/tsh/main.go:24 +0xf
   ```

**Comment by zmb3** [comment] 2024-02-15 21:05
This is a duplicate of #38188.

**Closed by zmb3** 2024-02-15 21:05 UTC
Labels: bug
