### ISSUE TITLE
public_addr is being ignored when setup with load balancer 

### ISSUE THREAD

**Issue by aelkugia** [gravitational/teleport#3823] opened 2020-06-10 21:01 UTC
**What happened**: Customer reported bug where they have F5 load balancer which maps standard ports to teleport specific ports. When using `tsh` it doesn't seem to use the `public_addr` port but instead the `listen_addr` port. (Note: If they match the ports, it seems to work fine.)

F5 load balancer which maps standard ports to teleport specific ports:

```
F5 (teleport.x.int:443)     -> Teleport (3080)
F5 (teleport.x.int:22)      -> Teleport (3023)
F5 (teleport-auth.x.int:22) -> Teleport (3025)
```
`teleport.yaml` snippet where they specified a `public_addr` for the auth server mapped to the load balancer definition above:

```
auth_service:
    listen_addr: 0.0.0.0:3025
    public_addr: teleport-auth.x.int:22
```

Some errors seen:
```
error: "Get https://teleport.cluster.local/v2/authorities/host?load_keys=false: failed connecting to node
User Message: unable to connect to auth server
```

**What you expected to happen**: The proxy configurable `public_addr` should be taken into account and mapped correctly.

**How to reproduce it (as minimally and precisely as possible)**: Setup teleport with load balancer that maps to teleport specific ports and set `public_addr` to load balancer defined port.

### Environment

- Teleport Version: 4.2.10
- TSH Version: 4.2.10
- OS: Centos7.7

**Comment by webvictim** [comment] 2020-06-10 23:18
Similar thing to #3172

**Comment by zmb3** [comment] 2022-08-11 14:53
Closing as duplicate of #3172

**Closed by zmb3** 2022-08-11 14:53 UTC
Labels: bug, ux
