### ISSUE TITLE
Feature Request: Add support for "file://" schema in the OIDC.client_secret field

### ISSUE THREAD

**Issue by smallinsky** [gravitational/teleport#38539] opened 2024-02-22 12:25 UTC
### Description
Currently, the client_secret field in the OIDC connector resource does not support the `file://` schema, which limits the flexibility of configurations, especially when integrating with file-based secrets management systems.

### Feature Request

Implement support for the `file://` schema in the client_secret field to allow referencing secrets stored in files.
Enable users to specify file paths as values for the client_secret field, similar to other properties like oidc.google_service_account_uri.
**Use Case:**

Users who utilize file-based secret management systems need the ability to reference secrets stored in files directly within the client_secret field without exposing the secret value in IaC repository. 

### Expected Behavior

Users should be able to specify file paths using the "file://" schema in the client_secret field without encountering errors.
The OIDC connector should securely retrieve and utilize the secret from the specified file path.

**Comment by zmb3** [comment] 2024-02-22 18:26
Duplicate of #6815

**Closed** 2024-02-22 18:26 UTC
Labels: feature-request, sso, support-load, getting-started
