### ISSUE TITLE
TestHSMRotation flakiness

### ISSUE THREAD

**Issue by GavinFrazar** [gravitational/teleport#19743] opened 2022-12-30 06:30 UTC
#### Link(s) to logs
- https://github.com/gravitational/teleport/actions/runs/3804233478/jobs/6471294793

#### Relevant snippet

```
panic: Emit called on uninitialized fanout instance

goroutine 4906 [running]:
github.com/gravitational/teleport/lib/services.(*Fanout).Emit(0xc0018373a0, {0xc000a9fb78, 0x1, 0xb?})
	/__w/teleport/teleport/lib/services/fanout.go:152 +0xdf8
github.com/gravitational/teleport/lib/services.(*caCollector).getResourcesAndUpdateCurrent(0xc001ca66c0, {0xa688a20, 0xc001a28440})
	/__w/teleport/teleport/lib/services/watcher.go:1285 +0x5e9
github.com/gravitational/teleport/lib/services.(*resourceWatcher).watch(0xc001ca6780)
	/__w/teleport/teleport/lib/services/watcher.go:289 +0x454
github.com/gravitational/teleport/lib/services.(*resourceWatcher).runWatchLoop(0xc001ca6780)
	/__w/teleport/teleport/lib/services/watcher.go:211 +0xe5
created by github.com/gravitational/teleport/lib/services.newResourceWatcher
	/__w/teleport/teleport/lib/services/watcher.go:121 +0x58f
FAIL	github.com/gravitational/teleport/integration/hsm	8.257s
```

Seems to be a different cause than https://github.com/gravitational/teleport/issues/13599 and https://github.com/gravitational/teleport/issues/13845

@nklaassen

**Comment by jakule** [comment] 2023-01-04 01:49
Duplicate of https://github.com/gravitational/teleport/issues/19289

**Closed by jakule** 2023-01-04 01:49 UTC
Labels: flaky tests
