### ISSUE TITLE
leaf cluster doesn't show session recording

### ISSUE THREAD

**Issue by nivasomu** [gravitational/teleport#18664] opened 2022-11-22 00:09 UTC
Expected behavior:
A user with the following role with a where condition to check for `user.metadata.name` as a participant should show all his/her session recordings,
```
kind: role  
metadata:  
 name: session  
spec:  
 allow:  
   cluster_labels:  
     '*': '*'  
   logins:  
   - '{{email.local(external.username)}}'  
   node_labels: 
     '*': '*'  
   rules:  
   - resources:  
     - ssh_session  
     verbs:  
     - '*'  
   - resources:  
     - session  
     verbs:  
     - list  
     - read  
     where: contains(session.participants, user.metadata.name)  
 deny:  
   rules:  
   - resources:  
     - ssh_session  
     verbs:  
     - list  
     - read  
     - update  
     - delete  
     where: '!contains(ssh_session.participants, user.metadata.name)'  
```

Current behavior:
But this role throws an error on a leaf cluster and doesn't list any session recordings.  

Debug logs on leaf cluster:
```
2022-11-18T21:02:19Z INFO [AUTH]      Access to list session in namespace default denied to roles fire-sre,default-implicit-role. error:[
ERROR REPORT:
Original Error: *trace.AccessDeniedError access denied to perform action &#34;list&#34; on &#34;session&#34;
Stack Trace:
	github.com/gravitational/teleport/lib/services/role.go:2560 github.com/gravitational/teleport/lib/services.RoleSet.ExtractConditionForIdentifier
	github.com/gravitational/teleport/lib/auth/auth_with_roles.go:152 github.com/gravitational/teleport/lib/auth.(*ServerWithRoles).actionForListWithCondition
	github.com/gravitational/teleport/lib/auth/auth_with_roles.go:4461 github.com/gravitational/teleport/lib/auth.(*ServerWithRoles).SearchSessionEvents
	github.com/gravitational/teleport/lib/auth/grpcserver.go:3168 github.com/gravitational/teleport/lib/auth.(*GRPCServer).GetSessionEvents
	github.com/gravitational/teleport/api@v0.0.0/client/proto/authservice.pb.go:18839 github.com/gravitational/teleport/api/client/proto._AuthService_GetSessionEvents_Handler.func1
	github.com/gravitational/teleport/lib/auth/middleware.go:397 github.com/gravitational/teleport/lib/auth.(*Middleware).withAuthenticatedUserUnaryInterceptor
	github.com/gravitational/teleport/lib/utils/grpc.go:104 github.com/gravitational/teleport/lib/utils.ChainUnaryServerInterceptors.func1.1
	github.com/gravitational/teleport/lib/limiter/limiter.go:150 github.com/gravitational/teleport/lib/limiter.(*Limiter).UnaryServerInterceptorWithCustomRate.func1
	github.com/gravitational/teleport/lib/utils/grpc.go:104 github.com/gravitational/teleport/lib/utils.ChainUnaryServerInterceptors.func1.1
	github.com/gravitational/teleport/lib/utils/grpc.go:64 github.com/gravitational/teleport/lib/utils.GRPCServerUnaryErrorInterceptor
	github.com/gravitational/teleport/lib/utils/grpc.go:104 github.com/gravitational/teleport/lib/utils.ChainUnaryServerInterceptors.func1.1
	github.com/grpc-ecosystem/go-grpc-middleware/v2@v2.0.0-rc.2.0.20220308023801-e4a6915ea237/interceptors/server.go:22 github.com/grpc-ecosystem/go-grpc-middleware/v2/interceptors.UnaryServerInterceptor.func1
	github.com/gravitational/teleport/lib/utils/grpc.go:108 github.com/gravitational/teleport/lib/utils.ChainUnaryServerInterceptors.func1
	google.golang.org/grpc@v1.49.0/server.go:1135 google.golang.org/grpc.chainUnaryInterceptors.func1.1
	go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc@v0.36.1/interceptor.go:352 go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc.UnaryServerInterceptor.func1
	google.golang.org/grpc@v1.49.0/server.go:1138 google.golang.org/grpc.chainUnaryInterceptors.func1.1
	google.golang.org/grpc@v1.49.0/server.go:1140 google.golang.org/grpc.chainUnaryInterceptors.func1
	github.com/gravitational/teleport/api@v0.0.0/client/proto/authservice.pb.go:18841 github.com/gravitational/teleport/api/client/proto._AuthService_GetSessionEvents_Handler
	google.golang.org/grpc@v1.49.0/server.go:1301 google.golang.org/grpc.(*Server).processUnaryRPC
	google.golang.org/grpc@v1.49.0/server.go:1642 google.golang.org/grpc.(*Server).handleStream
	google.golang.org/grpc@v1.49.0/server.go:938 google.golang.org/grpc.(*Server).serveStreams.func1.2
	runtime/asm_amd64.s:1594 runtime.goexit
User Message: access denied to perform action &#34;list&#34; on &#34;session&#34;] auth/auth_with_roles.go:154
```

logs from root cluster
```
Nov 18 21:04:26 ip-192-168-5-99 teleport[194662]: 2022-11-18T21:04:26Z DEBU [WEB]       Could not authenticate. error:[
Nov 18 21:04:26 ip-192-168-5-99 teleport[194662]: ERROR REPORT:
Nov 18 21:04:26 ip-192-168-5-99 teleport[194662]: Original Error: *trace.AccessDeniedError missing session cookie
Nov 18 21:04:26 ip-192-168-5-99 teleport[194662]: Stack Trace:
Nov 18 21:04:26 ip-192-168-5-99 teleport[194662]:         github.com/gravitational/teleport/lib/web/apiserver.go:3048 github.com/gravitational/teleport/lib/web.(*Handler).AuthenticateRequest
Nov 18 21:04:26 ip-192-168-5-99 teleport[194662]:         github.com/gravitational/teleport/lib/web/apiserver.go:424 github.com/gravitational/teleport/lib/web.(*Handler).authenticateWebSession
Nov 18 21:04:26 ip-192-168-5-99 teleport[194662]:         github.com/gravitational/teleport/lib/web/apiserver.go:367 github.com/gravitational/teleport/lib/web.NewHandler.func1
Nov 18 21:04:26 ip-192-168-5-99 teleport[194662]:         net/http/server.go:2109 net/http.HandlerFunc.ServeHTTP
Nov 18 21:04:26 ip-192-168-5-99 teleport[194662]:         github.com/julienschmidt/httprouter@v1.3.0/router.go:460 github.com/julienschmidt/httprouter.(*Router).ServeHTTP
Nov 18 21:04:26 ip-192-168-5-99 teleport[194662]:         github.com/gravitational/teleport/lib/web/apiserver.go:237 github.com/gravitational/teleport/lib/web.(*APIHandler).ServeHTTP
Nov 18 21:04:26 ip-192-168-5-99 teleport[194662]:         github.com/gravitational/oxy@v0.0.0-20221006122657-40fb61a9d599/ratelimit/tokenlimiter.go:118 github.com/gravitational/oxy/ratelimit.(*TokenLimiter).ServeHTTP
Nov 18 21:04:26 ip-192-168-5-99 teleport[194662]:         github.com/gravitational/oxy@v0.0.0-20221006122657-40fb61a9d599/connlimit/connlimit.go:75 github.com/gravitational/oxy/connlimit.(*ConnLimiter).ServeHTTP
Nov 18 21:04:26 ip-192-168-5-99 teleport[194662]:         go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.36.1/handler.go:204 go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*Handler).ServeHTTP
Nov 18 21:04:26 ip-192-168-5-99 teleport[194662]:         net/http/server.go:2947 net/http.serverHandler.ServeHTTP
Nov 18 21:04:26 ip-192-168-5-99 teleport[194662]:         net/http/server.go:1991 net/http.(*conn).serve
Nov 18 21:04:26 ip-192-168-5-99 teleport[194662]:         runtime/asm_amd64.s:1594 runtime.goexit
Nov 18 21:04:26 ip-192-168-5-99 teleport[194662]: User Message: missing session cookie] web/apiserver.go:369
Nov 18 21:04:29 ip-192-168-5-99 teleport[194662]: 2022-11-18T21:04:29Z DEBU [RBAC]      Check access to role(Proxy) rc(root.teleport-cse.com, labels=map[]) matchLabels=true, msg=matched, err=<nil> allow=map[*:[*]] rcLabels=map[] services/role.go:1465
```

**Comment by zmb3** [comment] 2022-11-22 01:32
Duplicate of #12324

**Closed by zmb3** 2022-11-22 01:32 UTC
Labels: bug, c-nst
