### ISSUE TITLE
Agent Failed to claim proxy with multi proxy server

### ISSUE THREAD

**Issue by saeroshi** [gravitational/teleport#22497] opened 2023-03-01 18:36 UTC
Expected behavior:
-------------------

Agent (Node) connect to cluster Teleport

Current behavior:
-----------------

Agent loop connection to cluster node with error log.
Open many tcp port with this error.

This problem does not happen with 1 proxy.

Bug details:
------------

- Teleport version : 11.3.5 or 12.0.4

For recreation :

- 1 Reverse Proxy HAProxy :
```
peers teleport-peers
	peer ha-teleport-1 10.200.0.2:10000

listen tcp-teleport-prod-proxy
	bind X.X.X.X:3023

	mode tcp
	option tcplog
	timeout client 350s
	timeout server 350s

	option httpchk
        http-check connect
        http-check send meth GET uri /healthz
        http-check expect status 200

	default-server inter 2s fall 5 rise 2 port 3000

	balance leastconn
	stick-table type ip size 1m expire 4h peers teleport-peers
	stick on src
	server teleport-app-prod-1 10.200.0.5:3023 check send-proxy
	server teleport-app-prod-2 10.200.0.6:3023 check send-proxy
	server teleport-app-prod-3 10.200.0.7:3023 check send-proxy

listen tcp-teleport-prod-tunnel
	bind X.X.X.X:3024

	mode tcp
	option tcplog
	timeout client 350s
	timeout server 350s

	option httpchk
        http-check connect
        http-check send meth GET uri /healthz
        http-check expect status 200

	default-server inter 2s fall 5 rise 2 port 3000

	balance leastconn
	stick-table type ip size 1m expire 4h peers teleport-peers
	stick on src
	server teleport-app-prod-1 10.200.0.5:3024 check send-proxy
	server teleport-app-prod-2 10.200.0.6:3024 check send-proxy
	server teleport-app-prod-3 10.200.0.7:3024 check send-proxy

listen tcp-teleport-prod-web
	bind X.X.X.X:443

	mode tcp
	option tcplog
	timeout client 350s
	timeout server 350s

	option httpchk
        http-check connect
        http-check send meth GET uri /healthz
        http-check expect status 200

	default-server inter 2s fall 5 rise 2 port 3000

	balance leastconn
	stick-table type ip size 1m expire 4h peers teleport-peers
	stick on src
	server teleport-app-prod-1 10.200.0.5:443 check send-proxy
	server teleport-app-prod-2 10.200.0.6:443 check send-proxy
	server teleport-app-prod-3 10.200.0.7:443 check send-proxy
```

- 1 Auth server :
```
version: v3
teleport:
#  nodename: teleport-auth-prod-1
  data_dir: /var/lib/teleport
  log:
    output: stderr
    severity: DEBUG
    format:
      output: text
  diag_addr: 0.0.0.0:3000

auth_service:
  enabled: true
  proxy_listener_mode: separate
  listen_addr: 0.0.0.0:3025
  cluster_name: bastion.mydomain.net
  authentication:
    type: local
    second_factor: off
  tokens:
    - "node:tY7g5ntUMVCtCoK289FcKWxVfo5bnwWU"
    - "proxy,node:PYggjm3Gb5DfdSGTusu2cD83876xAsX4"
    - "auth:KZYAmRq9cPA59U4m2zuBjk3b5Dtb6JR2"

proxy_service:
  enabled: no

ssh_service:
  enabled: "no"
```

- 2 proxy :
```
version: v3
teleport:
#  nodename: teleport-proxy-prod-X
  data_dir: /var/lib/teleport
  auth_token: PYggjm3Gb5DfdSGTusu2cD83876xAsX4
  log:
    output: stderr
    severity: DEBUG
    format:
      output: text
  diag_addr: 0.0.0.0:3000
  auth_server: 10.200.0.8:3025

auth_service:
  enabled: false

proxy_service:
  enabled: yes
  listen_addr: 0.0.0.0:3023
  ssh_public_addr: bastion.mydomain.net:3023
  tunnel_listen_addr: 0.0.0.0:3024

  web_listen_addr: 0.0.0.0:443
  public_addr: bastion.mydomain.net:443

  tunnel_public_addr: bastion.mydomain.net:3024

  https_keypairs:
  - key_file: /etc/teleport/bastion.mydomain.net/privkey.pem
    cert_file: /etc/teleport/bastion.mydomain.net/fullchain.pem
  https_keypairs_reload_interval: 1h

ssh_service:
  enabled: "no"
```

1 Agent :
```
version: v3
teleport:
  data_dir: /var/lib/teleport
  auth_token: tY7g5ntUMVCtCoK289FcKWxVfo5bnwWU
  proxy_server: bastion.mydmain.net:443
  log:
#    output: stderr
    output: stdout
    severity: DEBUG
    format:
      output: text
  diag_addr: ""
auth_service:
  enabled: false
proxy_service:
  enabled: false
ssh_service:
  enabled: true
```

Debug logs
-----------

Proxy :
```
DEBU [SSH:PROXY] Incoming connection 10.200.0.2:33184 -> 10.200.0.5:3024 version: SSH-2.0-Go, certtype: "host" pid:100213
.1 sshutils/server.go:509
DEBU [SSH:PROXY] Closed connection 10.200.0.2:33184. pid:100213.1 sshutils/server.go:514
```
Agent :
```
DEBU [PROXY:AGE] Runtime config: tunnel_strategy: agent_mesh connection_count: 1 cluster:bastion.mydomain.net reversetunnel/agentpool.go:323
DEBU [PROXY:AGE] Starting agent {bastion.mydomain.net:3024 tcp } leaseID:3 target:bastion.mydomain.net:3024 cluster:bastion.mydomain.net reversetunnel/agent.go:293
DEBU [PROXY:AGE] Changing state initial -> connecting. leaseID:3 target:bastion.mydomain.net:3024 cluster:bastion.mydomain.net reversetunnel/agent.go:281
DEBU [HTTP:PROX] No proxy set in environment, returning direct dialer. proxy/proxy.go:301
DEBU [PROXY:AGE] Changing state connecting -> closed. leaseID:3 target:bastion.mydomain.net:3024 cluster:bastion.mydomain.net reversetunnel/agent.go:281
DEBU [PROXY:AGE] Failed to connect agent. error:[
ERROR REPORT:
Original Error: *errors.errorString Failed to claim proxy: [442b7311-d86d-42ce-be96-87df9b4c2e36.bastion.mydomain.net 442b7311-d86d-42ce-be96-87df9b4c2e36 teleport-app-prod-2.bastion.mydomain.net teleport-app-prod-2 localhost 127.0.0.1 ::1 bastion.mydomain.net 10.200.0.6 remote.kube.proxy.teleport.cluster.local] claimed by another agent
Stack Trace:
	github.com/gravitational/teleport/lib/reversetunnel/agent.go:367 github.com/gravitational/teleport/lib/reversetunnel.(*agent).connect
	github.com/gravitational/teleport/lib/reversetunnel/agent.go:313 github.com/gravitational/teleport/lib/reversetunnel.(*agent).Start
	github.com/gravitational/teleport/lib/reversetunnel/agentpool.go:308 github.com/gravitational/teleport/lib/reversetunnel.(*AgentPool).connectAgent
	github.com/gravitational/teleport/lib/reversetunnel/agentpool.go:267 github.com/gravitational/teleport/lib/reversetunnel.(*AgentPool).run
	github.com/gravitational/teleport/lib/reversetunnel/agentpool.go:251 github.com/gravitational/teleport/lib/reversetunnel.(*AgentPool).Start.func1
	runtime/asm_amd64.s:1598 runtime.goexit
User Message: Failed to claim proxy: [442b7311-d86d-42ce-be96-87df9b4c2e36.bastion.mydomain.net 442b7311-d86d-42ce-be96-87df9b4c2e36 teleport-app-prod-2.bastion.mydomain.net teleport-app-prod-2 localhost 127.0.0.1 ::1 bastion.mydomain.net 10.200.0.6 remote.kube.proxy.teleport.cluster.local] claimed by another agent] cluster:bastion.mydomain.net reversetunnel/agentpool.go:269
DEBU [PROXY:AGE] Active agent count: 1 cluster:bastion.mydomain.net reversetunnel/agentpool.go:450
DEBU [PROXY:AGE] Active agent count: 1 cluster:bastion.mydomain.net reversetunnel/agentpool.go:450
DEBU [PROXY:AGE] Runtime config: tunnel_strategy: agent_mesh connection_count: 1 cluster:bastion.mydomain.net reversetunnel/agentpool.go:323
```

**Comment by yuri-1987** [comment] 2023-03-02 15:40
i have the same issue, recently started with v10.3.12

```
User Message: Failed to claim proxy: [cb77f199-2550-49b7-8090-c5706c5f002d.company-main cb77f199-2550-49b7-8090-c5706c5f002d teleport-proxy-prod-c410c-1c.company-main teleport-proxy-prod-c410c-1c localhost 127.0.0.1 ::1 cluster.company.com 10.26.6.64 remote.kube.proxy.teleport.cluster.local] claimed by another agent] cluster:company-main reversetunnel/agentpool.go:268
2023-03-02T15:35:21Z DEBU [PROXY:AGE] Active agent count: 3 cluster:company-main reversetunnel/agentpool.go:449
2023-03-02T15:35:21Z DEBU [PROXY:AGE] Active agent count: 3 cluster:company-main reversetunnel/agentpool.go:449
2023-03-02T15:35:28Z DEBU [PROXY:AGE] Runtime config: tunnel_strategy: agent_mesh connection_count: 1 cluster:company-main reversetunnel/agentpool.go:322
2023-03-02T15:35:28Z DEBU             Attempting GET cluster.company.com:443/webapi/find webclient/webclient.go:127
2023-03-02T15:35:28Z DEBU [PROXY:AGE] Starting agent {cluster.company.com:443 tcp } leaseID:12 target:cluster.company.com:443 cluster:company-main reversetunnel/agent.go:293
2023-03-02T15:35:28Z DEBU [PROXY:AGE] Changing state initial -> connecting. leaseID:12 target:cluster.company.com:443 cluster:company-main reversetunnel/agent.go:281
2023-03-02T15:35:28Z DEBU [HTTP:PROX] No proxy set in environment, returning direct dialer. proxy/proxy.go:301
2023-03-02T15:35:28Z DEBU [PROXY:AGE] Changing state connecting -> closed. leaseID:12 target:cluster.company.com:443 cluster:company-main reversetunnel/agent.go:281
2023-03-02T15:35:28Z DEBU [PROXY:AGE] Failed to connect agent. error:[
ERROR REPORT:
Original Error: *errors.errorString Failed to claim proxy: [5f1ca3a1-7810-4415-ab20-aafa6e91f616.company-main 5f1ca3a1-7810-4415-ab20-aafa6e91f616 teleport-proxy-prod-286f4-1d.company-main teleport-proxy-prod-286f4-1d localhost 127.0.0.1 ::1 cluster.company.com 10.26.9.68 remote.kube.proxy.teleport.cluster.local] claimed by another agent
Stack Trace:
        /go/src/github.com/gravitational/teleport/lib/reversetunnel/agent.go:367 github.com/gravitational/teleport/lib/reversetunnel.(*agent).connect
        /go/src/github.com/gravitational/teleport/lib/reversetunnel/agent.go:313 github.com/gravitational/teleport/lib/reversetunnel.(*agent).Start
        /go/src/github.com/gravitational/teleport/lib/reversetunnel/agentpool.go:307 github.com/gravitational/teleport/lib/reversetunnel.(*AgentPool).connectAgent
        /go/src/github.com/gravitational/teleport/lib/reversetunnel/agentpool.go:266 github.com/gravitational/teleport/lib/reversetunnel.(*AgentPool).run
        /go/src/github.com/gravitational/teleport/lib/reversetunnel/agentpool.go:250 github.com/gravitational/teleport/lib/reversetunnel.(*AgentPool).Start.func1
        /opt/go/src/runtime/asm_amd64.s:1594 runtime.goexit
User Message: Failed to claim proxy: [5f1ca3a1-7810-4415-ab20-aafa6e91f616.company-main 5f1ca3a1-7810-4415-ab20-aafa6e91f616 teleport-proxy-prod-286f4-1d.company-main teleport-proxy-prod-286f4-1d localhost 127.0.0.1 ::1 cluster.company.com 10.26.9.68 remote.kube.proxy.teleport.cluster.local] claimed by another agent] cluster:company-main reversetunnel/agentpool.go:268
```

**Comment by saeroshi** [comment] 2023-03-02 23:32
I have soluce.
Agents (nodes) must connect to all proxies, not "leastconn" but "roundrobin".
However, when a proxy disconnects, the agent (node) repeats this error and multiplies the connections.

Example :
```
tcp   ESTAB       0       0        x.x.x.x:44844   x.x.x.x:443    users:(("teleport",pid=15318,fd=45)) timer:(keepalive,5.006ms,0) ino:2673575792 sk:32a7 <->
tcp   ESTAB       0       0        x.x.x.x:43842   x.x.x.x:443    users:(("teleport",pid=15318,fd=31)) timer:(keepalive,1433c,0) ino:2673548008 sk:30ba <->
tcp    ESTAB      0       0        x.x.x.x:49726   x.x.x.x:3024   users:(("teleport",pid=10779,fd=12)) timer:(keepalive,2.504ms,0) ino:2673888343 sk:45f4 <->
tcp    ESTAB      0       0        x.x.x.x:49728   x.x.x.x:3024   users:(("teleport",pid=10779,fd=13)) timer:(keepalive,2.272ms,0) ino:2673888349 sk:45f9 <->
tcp    ESTAB      0       0        x.x.x.x:49714   x.x.x.x:3024   users:(("teleport",pid=10779,fd=9)) timer:(keepalive,5.3304s,0) ino:2673889522 sk:45ef <->
tcp    ESTAB      0       0        x.x.x.x:50382   x.x.x.x:3024   users:(("teleport",pid=10779,fd=24)) timer:(keepalive,1104c,0) ino:2673907764 sk:472c <->
tcp    ESTAB      0       0        x.x.x.x:49716   x.x.x.x:3024   users:(("teleport",pid=10779,fd=10)) timer:(keepalive,2sec,0) ino:2673885160 sk:45f2 <->
```
x50 connections....

Other problems ?

**Comment by pkrzysz** [comment] 2023-03-03 10:27
Have exactly the same problem.

I think that it's fixed if you change proxy config to v2.
I just removed line:
version: v3
And changed auth_server: server:3025 to auth_servers: ["server:3025"]

**Comment by pkrzysz** [comment] 2023-03-03 11:45
Exactly same issue with teleport 12.02. 
Teleport agents in reverse tunnel mode starts to spawn new connections, without properly closing the previous one.
A little bit different config with proxy multiplexing on.

**Comment by zmb3** [comment] 2024-01-14 23:25
Closing due to inactivity.

Agents connecting to all proxies is the expected behavior in agent mesh mode.

**Closed by zmb3** 2024-01-14 23:25 UTC
Labels: bug, c-ax
