### ISSUE TITLE
Terraform provider produced inconsistent result after apply (teleport_provision_token join_method = "gitlab")

### ISSUE THREAD

**Issue by nick-disiere** [gravitational/teleport#35947] opened 2023-12-20 19:25 UTC
Expected behavior:
Per the [doc](https://goteleport.com/docs/reference/join-methods/#gitlab-gitlab), the Gitlab join method has two optional fields - ref_protected and environment_protected. The user should be able to omit these fields from their Terraform config to omit checking the protection status of the ref/environment.

Current behavior:
During Terraform apply (no errors during build)
```
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to module.auth.teleport_provision_token.token,
│ provider
│ "module.auth.provider[\"terraform.releases.teleport.dev/gravitational/teleport\"]"
│ produced an unexpected new value: .spec.gitlab.allow[0].ref_protected: was
│ null, but now cty.False.
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.


│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to module.auth.teleport_provision_token.token,
│ provider
│ "module.auth.provider[\"terraform.releases.teleport.dev/gravitational/teleport\"]"
│ produced an unexpected new value:
│ .spec.gitlab.allow[0].environment_protected: was null, but now cty.False.
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
```
Attempting to use this token in an unprotected branch results in 

```
id token claims did not match any allow rules, invalid character '<' looking for beginning of value
```

Bug details:
- Teleport version 
  terraform.releases.teleport.dev/gravitational/teleport v14.2.3
  Teleport v14.2.4-0-g1cb5b01 go1.21.5

- Recreation steps 

```
resource "teleport_provision_token" "token" {
  metadata = {
    name        = local.bot_name
    description = "Provision token for bot"
    labels = {
      "teleport.dev/origin" = "dynamic" // This label is added on Teleport side by default
    }
  }

  spec = {
    roles       = ["Bot"]
    join_method = "gitlab"
    bot_name    = local.bot_name
    gitlab = {
      domain = "bug.report"
      allow = [
        {
          project_path = local.repo
        }
      ]
    }
  }
}
```

tbot.yaml in project
```
onboarding:
  join_method: gitlab
  token: <local.bot_name>
```

- Debug logs
Can provide on request with specific instruction

**Comment by strideynet** [comment] 2023-12-21 12:26
Does this also occur if you create the token with `tctl create -f token.yaml` ? Wondering if this is an issue with the way our Terraform provider is generated or if there's a deeper issue here.

**Comment by nick-disiere** [comment] 2023-12-21 12:36
No, creating and applying the equivalent yaml creates a working token. I was able to use that as a workaround. Terraform build sees the token and will not attempt to modify it. 

A quick look at cty.False seems to point to a bug in an optional value generator in your terraform build. An uneducated guess would be that it expects a bool, but the option has three values (true/false/unset)

**Comment by strideynet** [comment] 2023-12-22 12:31
Related to https://github.com/gravitational/teleport-plugins/issues/981

**Comment by strideynet** [comment] 2024-01-08 16:17
Closing as dupe of https://github.com/gravitational/teleport-plugins/issues/981 - we're planning to resolve this in a breaking change as part of Teleport 15

**Closed** 2024-01-08 16:17 UTC
Labels: bug
