### ISSUE TITLE
Don't let people kubectl login to Teleport Cloud 

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#5230] opened 2021-01-06 01:41 UTC
### Description

**What happened**:
While adding a new Kubernetes service I noticed that I can kube login to my Teleport Cloud instance. 

```
➜  tsh kube login asteroid-sun.teleport.sh
Logged into kubernetes cluster "asteroid-sun.teleport.sh"
➜ kubectl get pods
Error from server (InternalError): an error on the server ("") has prevented the request from succeeding
```

**What you expected to happen**:
Remove the first Kubernetes Cluster from `tsh kube ls` 
```diff
➜   tsh kube ls
Kube Cluster Name        Selected
------------------------ --------
- asteroid-sun.teleport.sh *
do-teleport-cloud
gke-teleport-cloud
```

**Comment by awly** [comment] 2021-01-06 18:51
This is a tricky one.
The reason that you see this cluster is that `proxy_service` with k8s integration enabled will also act as a `kubernetes_service` when running inside of a k8s pod.
This was the behavior before 5.0 and I didn't want to break people's setup just by updating to 5.0.

I don't want to break old configs without a good reason.
There are a few options here:
- don't register a kubernetes cluster from the proxy, but keep serving its traffic (just like pre-5.0)
- add a flag to `proxy_service.kubernetes` to disable local k8s detection
- do nothing, it's not an issue as long as your teleport pod doesn't have impersonation permissions

**Comment by benarent** [comment] 2021-01-06 19:09
Thanks Andrew, it makes more sense now.   I think we can do nothing for now and just add a note clarifying why you'll see it in the docs.

**Comment by awly** [comment] 2021-05-06 00:22
Duplicate of https://github.com/gravitational/teleport/issues/6226

**Closed by awly** 2021-05-06 00:22 UTC
Labels: docs-required, kubernetes, ux
