### ISSUE TITLE
Connect shows all SSH users

### ISSUE THREAD

**Issue by scottpgallagher** [gravitational/teleport#29636] opened 2023-07-26 16:19 UTC
Expected behavior:
For SSH Teleport connect should act like it does in presenting user logins like the web UI does. 

Current behavior:
Currently it is displaying all available logins regardless of what a role has set for labels.

Bug details:
- Teleport version
<img width="1218" alt="Screenshot 2023-07-26 at 12 19 11 PM" src="https://github.com/gravitational/teleport/assets/51385814/ed371d6f-8a45-4c29-928b-01b43c9f17f2">
<img width="1204" alt="Screenshot 2023-07-26 at 12 19 23 PM" src="https://github.com/gravitational/teleport/assets/51385814/fa954b29-a9b8-4815-8650-1f7ec48ea412">

- Recreation steps
- Debug logs

Related issues:

* Web UI
   * #6822
   * https://github.com/gravitational/teleport/pull/13266
   * https://github.com/gravitational/webapps/pull/873
* Connect
   * https://github.com/gravitational/teleport.e/issues/871

**Comment by zmb3** [comment] 2024-02-05 04:05
Looks like a duplicate of #23723

**Closed by zmb3** 2024-02-05 04:05 UTC
Labels: bug, good-starter-issue, teleport-connect
