### ISSUE TITLE
kubectl config Error from server (BadRequest) on leaf K8s 

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#3716] opened 2020-05-14 17:37 UTC
### Description
Created on behalf of a customer. 

**What happened**:
'm seeing some weird behavior in 4.2.9 with kubctl config but I'm testing with 4.2.3 servers
so I wonder if the versions are not 100% compatible

I do the following:
- log out with `tsh logout`
- log in to a "leaf" cluster `tsh login sfffff-dev`
I can see ~/.kube/config after that and it seems fine, but if I do anything with kubectl I'm getting `Error from server (BadRequest): Unable to list "/v1, Resource=pods": the server rejected our request for an unknown reason (get pods)` or `Error from server (BadRequest): the server rejected our request for an unknown reason` ; The root cluster doesn't show any requests to K8s in logs

If I log in to another cluster after that with `tsh login sfffff-azdev` everything begins work as expected. I can see requests in the logs, I can switch between contexts

when I'm observing the problem I can confirm that the server address is correct in kubeconfig server: https://tproxy.sffff-teleport.aws.reg.RETRACTED.com:3026

```
➜  ~ kubectl version
Client Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.10-dispatcher", GitCommit:"f5757a1dee5a89cc5e29cd7159076648bf21a02b", GitTreeState:"clean", BuildDate:"2020-02-06T03:31:35Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-502bfb", GitCommit:"502bfb383169b124d87848f89e17a04b9fc1f6f0", GitTreeState:"clean", BuildDate:"2020-02-07T01:31:02Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

The behavior is the same with 4.2.9 servers

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

### Environment
- Teleport version (use `teleport version`):
- Tsh version (use `tsh version`):
- OS (e.g. from `/etc/os-release`):

- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware):

**Browser environment**

- Browser Version (for UI-related issues):
- Install tools:
- Others:

**Relevant Debug Logs If Applicable**

- `tsh --debug`
- `teleport --debug`

**Comment by benarent** [comment] 2020-05-14 17:38
@awly @russjones Do you happen to know if we made any changes in the later versions of 4.2.3+?

**Comment by awly** [comment] 2020-05-18 17:44
These are the only remotely-relevant changes since 4.2.3:
- https://github.com/gravitational/teleport/pull/3639 - could affect the server URL in kubeconfig, but the user specifically checked that
- https://github.com/gravitational/teleport/pull/3404 - adds `kube_users` support, which should be purely additive. However it also refactors a lot of validation logic for k8s requests in the proxy

It would be very useful to get root/leaf proxy debug logs here.

**Comment by paul91** [comment] 2020-05-19 13:54
Can confirm I am experiencing the same behavior with tsh `4.2.9`:

1. tsh logged out/cache deleted
2. Login specifying desired leaf cluster
3. Kubectl returns BadRequest
4. Switch to another leaf cluster, kubectl works as expected
5. Switch back to original desired leaf cluster, kubectl works as expected

Before when I was using what I think was `4.2.8`, the initial login always pointed me at my main cluster instead of the desired leaf, the second login would point me where I expected. This was supposedly fixed in `4.2.9`, possible that #3639 didn't completely resolve the regression.

**Comment by webvictim** [comment] 2020-05-19 14:27
I saw this same issue in testing myself. Trying to track it down is what led me to find another bug and open https://github.com/gravitational/teleport/issues/3693

**Comment by awly** [comment] 2020-05-19 15:58
I believe https://github.com/gravitational/teleport/pull/3735 should resolve this

**Closed** 2020-06-26 22:57 UTC
Labels: bug, c-sn, kubernetes
