### ISSUE TITLE
Issue resolving usernames with Microsoft OpenID Connect/ OAuth and OIDC connector

### ISSUE THREAD

**Issue by nickbrennan1** [gravitational/teleport#9605] opened 2021-12-31 12:53 UTC
It might be useful to state in our [OIDC Identity Providers documentation](https://goteleport.com/docs/enterprise/sso/oidc/#identity-providers) that Microsoft OpenID Connect is not supported, or provide a workaround if possible. This is due to a peculiarity with the way Microsoft publishes OpenID claims authenticating corporate accounts when using OAuth endpoints.

Full description:

Trying to configure a connector to work with the OpenID Microsoft SSO using OAuth endpoints, if authenticating with corporate MS Azure login types, the `email` claim is not passed as part of the openid scope:

```
  "attributes": {
    "aio": "",
    "aud": "",
    "exp":,
    "family_name": "Simpson",
    "given_name": "Homer",
    "iat":,
    "iss": "https://login.microsoftonline.com/<redacted>/v2.0",
    "name": "Homer Simpson",
    "nbf":,
    "picture": "",
    "rh": "",
    "sub": ,
    "tid": "",
    "uti": "",
    "ver": "2.0"
```
This results in the error stack:

```
2021-12-31T11:59:44Z ERRO [WEB]       Error while processing callback. auth:oidc error:[
ERROR REPORT:
Original Error: *trace.BadParameterError missing user name
Stack Trace:
	/go/src/github.com/gravitational/teleport/lib/services/local/users.go:216 github.com/gravitational/teleport/lib/services/local.(*IdentityService).GetUser
```

Note that this only applies to corporate accounts, including `email` in the scope has no effect. When including `profile` in the scope, the email is passed as claim `preferred_username`. Using private accounts (ie hotmail) the issue is not seen, the `email` claim is passed and the connector populates the username from the `email` claim. There appears to be no useful claim included for `openid` scope type containing the email address. This appears to be a peculiarity with how Azure handles the OIDC claims rather than a Teleport bug per se. The issue is discussed [here](https://stackoverflow.com/a/49679604).

Expected behaviour would be for the connection to succeed when using a corporate account.

**Comment by zmb3** [comment] 2021-12-31 14:50
Is this with Azure AD? I've definitely used Teleport's OIDC connector with an Azure AD app before and it's worked fine.

**Comment by nickbrennan1** [comment] 2021-12-31 16:49
Ok that's interesting, I was writing the above up as I couldn't find it recorded and running it by the team prior to bringing it to Dev, but it's consistently an issue for me currently, the audit logs in the lab clearly show the different claims returned. I've run AD fine with the SAML connector

**Comment by stevenGravy** [comment] 2022-01-04 22:10
Typically the problem with OIDC with Azure AD is if the user doesn't have email.

**Comment by ptgott** [comment] 2022-10-03 18:27
Closing since this issue doesn't describe a definitive gap in the documentation. If there is a common, reproducible problem we need to document a solution to, let's open another issue to track our work on it.

**Closed by ptgott** 2022-10-03 18:27 UTC
Labels: documentation
