### ISSUE TITLE
Web Launch Loop - Failed to get session: failed to match applications.

### ISSUE THREAD

**Issue by erasedhammer99** [gravitational/teleport#16108] opened 2022-09-02 18:23 UTC
I am trying to add zabbix as a web application but when I launch it the new tab endlessly reloads never actually showing the zabbix login page. 
A packet capture shows teleport isn't even attempting to connect to the zabbix server web (no packets at all).
Teleport server can curl the zabbix server just fine.

Here is my teleport.yaml:
```
version: v2
teleport:
  nodename: tele
  data_dir: /var/lib/teleport
  log:
    output: stderr
    severity: INFO
    format:
      output: text
  ca_pin: ""
  diag_addr: ""
auth_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3025
  cluster_name: tele.example.com
  proxy_listener_mode: multiplex
ssh_service:
  enabled: "yes"
  commands:
  - name: hostname
    command: [hostname]
    period: 1m0s
app_service:
  enabled: yes
  apps:
  - name: "zabbix"
    uri: "https://192.168.3.2"
    public_addr: "zabbix.tele.example.com"
    insecure_skip_verify: true
    rewrite:
      headers:
      - "Host: 192.168.3.2"
proxy_service:
  enabled: "yes"
  public_addr: tele.example.com:443
  web_listen_addr: 0.0.0.0:443
  https_keypairs: []
  acme: {}
```

The errors in my logs:
```
2022-09-02T14:17:27 WARN [APP:WEB]   Failed to get session: failed to match applications. app/handler.go:226
2022-09-02T14:17:27 INFO [AUDIT]     cert.create cert_type:user cluster_name:tele.example.com code:TC000I ei:0 event:cert.create identity:map[expires:2022-09-03T05:35:08.00217677Z logins:[-teleport-nologin-016805c7-6ef1-4385-9587-b23406a1da09 -teleport-internal-join] roles:[access editor] route_to_app:map[cluster_name:tele.example.com name: public_addr:zabbix.tele.example.com session_id:419e5239-7f3c-4d97-b3e6-d0873d430e84] route_to_cluster:tele.example.com teleport_cluster:tele.example.com traits:map[aws_role_arns:<nil> db_names:<nil> db_users:<nil> kubernetes_groups:<nil> kubernetes_users:<nil> logins:<nil> windows_logins:<nil>] usage:[usage:apps] user:teleport-admin] time:2022-09-02T18:17:27.66Z uid:bee828b1-d4ba-4e8a-b8f8-bba086b3c00e events/emitter.go:263
2022-09-02T14:17:28 INFO [AUDIT]     app.session.start addr.remote:192.168.0.2:46496 app_name:zabbix app_public_addr:zabbix.tele.example.com app_uri:https://192.168.3.2 cluster_name:tele.example.com code:T2007I ei:0 event:app.session.start namespace:default public_addr:zabbix.tele.example.com server_id:4f005ab5-57ae-435f-bc4b-410ab53c63bb sid:419e5239-7f3c-4d97-b3e6-d0873d430e84 time:2022-09-02T18:17:28.34Z uid:4729ba5e-9aee-4cfd-a416-4a4e1019bedd user:teleport-admin events/emitter.go:263
2022-09-02T14:17:28 WARN [APP:WEB]   Failed to get session: failed to match applications. app/handler.go:226
2022-09-02T14:17:29 WARN [APP:WEB]   Failed to get session: failed to match applications. app/handler.go:226
2022-09-02T14:17:29 INFO [CA]        Generating TLS certificate {0x8c03810 0xc000ba5ab0 1.3.9999.1.7=#130d74656c652e617365632e6f7267,1.3.9999.1.5=#130d74656c652e617365632e6f7267,1.3.9999.1.6=#13147a61626269782e74656c652e617365632e6f7267,1.3.9999.1.4=#132465333065613439612d356437642d346665662d383632372d353061353737376330386136,CN=teleport-admin,OU=usage:apps,O=access+O=editor,POSTALCODE={\"aws_role_arns\":null\,\"db_names\":null\,\"db_users\":null\,\"kubernetes_groups\":null\,\"kubernetes_users\":null\,\"logins\":null\,\"windows_logins\":null},STREET=tele.example.com,L=-teleport-nologin-9f9bbe9b-bcfe-438a-91bb-ed8b8bcc8081+L=-teleport-internal-join 2022-09-03 05:35:08.003415032 +0000 UTC [] [] 5 []}. common_name:teleport-admin dns_names:[] locality:[-teleport-nologin-9f9bbe9b-bcfe-438a-91bb-ed8b8bcc8081 -teleport-internal-join] not_after:2022-09-03 05:35:08.003415032 +0000 UTC org:[access editor] org_unit:[usage:apps] tlsca/ca.go:874
2022-09-02T14:17:30 INFO [AUDIT]     app.session.start addr.remote:192.168.0.2:46496 app_name:zabbix app_public_addr:zabbix.tele.example.com app_uri:https://192.168.3.2 cluster_name:tele.example.com code:T2007I ei:0 event:app.session.start namespace:default public_addr:zabbix.tele.example.com server_id:4f005ab5-57ae-435f-bc4b-410ab53c63bb sid:e30ea49a-5d7d-4fef-8627-50a5777c08a6 time:2022-09-02T18:17:30.34Z uid:fdcb34ee-d739-4991-9e5f-bdd7ada77b0f user:teleport-admin events/emitter.go:263
2022-09-02T14:17:30 WARN [APP:WEB]   Failed to get session: failed to match applications. app/handler.go:226
2022-09-02T14:17:36 INFO [CA]        Generating TLS certificate {0x8c03810 0xc0017651e0 1.3.9999.1.7=#130d74656c652e617365632e6f7267,CN=teleport-admin,O=access+O=editor,POSTALCODE={\"aws_role_arns\":null\,\"db_names\":null\,\"db_users\":null\,\"kubernetes_groups\":null\,\"kubernetes_users\":null\,\"logins\":null\,\"windows_logins\":null},STREET=tele.example.com,L=-teleport-nologin-4ac18442-0a6d-4fab-81ec-565010a8112e+L=-teleport-internal-join 2022-09-03 05:35:08.74567175 +0000 UTC [] [] 5 []}. common_name:teleport-admin dns_names:[] locality:[-teleport-nologin-4ac18442-0a6d-4fab-81ec-565010a8112e -teleport-internal-join] not_after:2022-09-03 05:35:08.74567175 +0000 UTC org:[access editor] org_unit:[] tlsca/ca.go:874
2022-09-02T14:17:29 INFO [AUDIT]     app.session.start addr.remote:192.168.0.2:46496 app_name:zabbix app_public_addr:zabbix.tele.example.com app_uri:https://192.168.3.2 cluster_name:tele.example.com code:T2007I ei:0 event:app.session.start namespace:default public_addr:zabbix.tele.example.com server_id:4f005ab5-57ae-435f-bc4b-410ab53c63bb sid:da067971-1222-49d3-a4d3-f7b313cb2c69 time:2022-09-02T18:17:29.339Z uid:2fe112b9-e67c-42d2-875e-650c39f68fc2 user:teleport-admin events/emitter.go:263
2022-09-02T14:17:30 INFO [AUDIT]     app.session.start addr.remote:192.168.0.2:46496 app_name:zabbix app_public_addr:zabbix.tele.example.com app_uri:https://192.168.3.2 cluster_name:tele.example.com code:T2007I ei:0 event:app.session.start namespace:default public_addr:zabbix.tele.example.com server_id:4f005ab5-57ae-435f-bc4b-410ab53c63bb sid:e30ea49a-5d7d-4fef-8627-50a5777c08a6 time:2022-09-02T18:17:30.34Z uid:fdcb34ee-d739-4991-9e5f-bdd7ada77b0f user:teleport-admin events/emitter.go:263
2022-09-02T14:17:30 WARN [APP:WEB]   Failed to get session: failed to match applications. app/handler.go:226
2022-09-02T14:17:26 INFO [AUDIT]     cert.create cert_type:user cluster_name:tele.example.com code:TC000I ei:0 event:cert.create identity:map[expires:2022-09-03T05:35:08.002164311Z logins:[-teleport-nologin-c4698175-9563-4de6-93dc-7163ac3b5a52 -teleport-internal-join] roles:[access editor] route_to_app:map[cluster_name:tele.example.com name: public_addr:zabbix.tele.example.com session_id:7af27a8c-bd83-4d77-b840-2adc3afd8b0f] route_to_cluster:tele.example.com teleport_cluster:tele.example.com traits:map[aws_role_arns:<nil> db_names:<nil> db_users:<nil> kubernetes_groups:<nil> kubernetes_users:<nil> logins:<nil> windows_logins:<nil>] usage:[usage:apps] user:teleport-admin] time:2022-09-02T18:17:26.787Z uid:0c2265d4-240b-4354-a371-e1eb4e6aca90 events/emitter.go:263
2022-09-02T14:17:27 INFO [AUDIT]     app.session.start addr.remote:192.168.0.2:46496 app_name:zabbix app_public_addr:zabbix.tele.example.com app_uri:https://192.168.3.2 cluster_name:tele.example.com code:T2007I ei:0 event:app.session.start namespace:default public_addr:zabbix.tele.example.com server_id:4f005ab5-57ae-435f-bc4b-410ab53c63bb sid:7af27a8c-bd83-4d77-b840-2adc3afd8b0f time:2022-09-02T18:17:27.34Z uid:77410e97-efd8-4ff6-aba5-8e6737db92e4 user:teleport-admin events/emitter.go:263
2022-09-02T14:17:27 INFO [AUDIT]     app.session.start addr.remote:192.168.0.2:46496 app_name:zabbix app_public_addr:zabbix.tele.example.com app_uri:https://192.168.3.2 cluster_name:tele.example.com code:T2007I ei:0 event:app.session.start namespace:default public_addr:zabbix.tele.example.com server_id:4f005ab5-57ae-435f-bc4b-410ab53c63bb sid:7af27a8c-bd83-4d77-b840-2adc3afd8b0f time:2022-09-02T18:17:27.34Z uid:77410e97-efd8-4ff6-aba5-8e6737db92e4 user:teleport-admin events/emitter.go:263
2022-09-02T14:17:27 INFO [CA]        Generating TLS certificate {0x8c03810 0xc001fb2860 1.3.9999.1.7=#130d74656c652e617365632e6f7267,1.3.9999.1.5=#130d74656c652e617365632e6f7267,1.3.9999.1.6=#13147a61626269782e74656c652e617365632e6f7267,1.3.9999.1.4=#132434313965353233392d376633632d346439372d623365362d643038373364343330653834,CN=teleport-admin,OU=usage:apps,O=access+O=editor,POSTALCODE={\"aws_role_arns\":null\,\"db_names\":null\,\"db_users\":null\,\"kubernetes_groups\":null\,\"kubernetes_users\":null\,\"logins\":null\,\"windows_logins\":null},STREET=tele.example.com,L=-teleport-nologin-016805c7-6ef1-4385-9587-b23406a1da09+L=-teleport-internal-join 2022-09-03 05:35:08.00217677 +0000 UTC [] [] 5 []}. common_name:teleport-admin dns_names:[] locality:[-teleport-nologin-016805c7-6ef1-4385-9587-b23406a1da09 -teleport-internal-join] not_after:2022-09-03 05:35:08.00217677 +0000 UTC org:[access editor] org_unit:[usage:apps] tlsca/ca.go:874
2022-09-02T14:17:28 INFO [AUDIT]     app.session.start addr.remote:192.168.0.2:46496 app_name:zabbix app_public_addr:zabbix.tele.example.com app_uri:https://192.168.3.2 cluster_name:tele.example.com code:T2007I ei:0 event:app.session.start namespace:default public_addr:zabbix.tele.example.com server_id:4f005ab5-57ae-435f-bc4b-410ab53c63bb sid:419e5239-7f3c-4d97-b3e6-d0873d430e84 time:2022-09-02T18:17:28.34Z uid:4729ba5e-9aee-4cfd-a416-4a4e1019bedd user:teleport-admin events/emitter.go:263
2022-09-02T14:17:28 INFO [AUDIT]     cert.create cert_type:user cluster_name:tele.example.com code:TC000I ei:0 event:cert.create identity:map[expires:2022-09-03T05:35:08.002242582Z logins:[-teleport-nologin-50a3bdf8-0f71-4f05-bad6-1174a5573e72 -teleport-internal-join] roles:[access editor] route_to_app:map[cluster_name:tele.example.com name: public_addr:zabbix.tele.example.com session_id:da067971-1222-49d3-a4d3-f7b313cb2c69] route_to_cluster:tele.example.com teleport_cluster:tele.example.com traits:map[aws_role_arns:<nil> db_names:<nil> db_users:<nil> kubernetes_groups:<nil> kubernetes_users:<nil> logins:<nil> windows_logins:<nil>] usage:[usage:apps] user:teleport-admin] time:2022-09-02T18:17:28.67Z uid:d8e16824-b897-4827-9070-cb4b203516a3 events/emitter.go:263
2022-09-02T14:17:29 INFO [AUDIT]     app.session.start addr.remote:192.168.0.2:46496 app_name:zabbix app_public_addr:zabbix.tele.example.com app_uri:https://192.168.3.2 cluster_name:tele.example.com code:T2007I ei:0 event:app.session.start namespace:default public_addr:zabbix.tele.example.com server_id:4f005ab5-57ae-435f-bc4b-410ab53c63bb sid:da067971-1222-49d3-a4d3-f7b313cb2c69 time:2022-09-02T18:17:29.339Z uid:2fe112b9-e67c-42d2-875e-650c39f68fc2 user:teleport-admin events/emitter.go:263
2022-09-02T14:17:29 WARN [APP:WEB]   Failed to get session: failed to match applications. app/handler.go:226
2022-09-02T14:17:29 INFO [AUDIT]     cert.create cert_type:user cluster_name:tele.example.com code:TC000I ei:0 event:cert.create identity:map[expires:2022-09-03T05:35:08.003415032Z logins:[-teleport-nologin-9f9bbe9b-bcfe-438a-91bb-ed8b8bcc8081 -teleport-internal-join] roles:[access editor] route_to_app:map[cluster_name:tele.example.com name: public_addr:zabbix.tele.example.com session_id:e30ea49a-5d7d-4fef-8627-50a5777c08a6] route_to_cluster:tele.example.com teleport_cluster:tele.example.com traits:map[aws_role_arns:<nil> db_names:<nil> db_users:<nil> kubernetes_groups:<nil> kubernetes_users:<nil> logins:<nil> windows_logins:<nil>] usage:[usage:apps] user:teleport-admin] time:2022-09-02T18:17:29.698Z uid:04fdadbc-d617-4bdf-8f69-4ce066044827 events/emitter.go:263
2022-09-02T14:17:26 INFO [CA]        Generating TLS certificate {0x8c03810 0xc00114d5c0 1.3.9999.1.7=#130d74656c652e617365632e6f7267,1.3.9999.1.5=#130d74656c652e617365632e6f7267,1.3.9999.1.6=#13147a61626269782e74656c652e617365632e6f7267,1.3.9999.1.4=#132437616632376138632d626438332d346437372d623834302d326164633361666438623066,CN=teleport-admin,OU=usage:apps,O=access+O=editor,POSTALCODE={\"aws_role_arns\":null\,\"db_names\":null\,\"db_users\":null\,\"kubernetes_groups\":null\,\"kubernetes_users\":null\,\"logins\":null\,\"windows_logins\":null},STREET=tele.example.com,L=-teleport-nologin-c4698175-9563-4de6-93dc-7163ac3b5a52+L=-teleport-internal-join 2022-09-03 05:35:08.002164311 +0000 UTC [] [] 5 []}. common_name:teleport-admin dns_names:[] locality:[-teleport-nologin-c4698175-9563-4de6-93dc-7163ac3b5a52 -teleport-internal-join] not_after:2022-09-03 05:35:08.002164311 +0000 UTC org:[access editor] org_unit:[usage:apps] tlsca/ca.go:874
2022-09-02T14:17:28 WARN [APP:WEB]   Failed to get session: failed to match applications. app/handler.go:226
2022-09-02T14:17:28 INFO [CA]        Generating TLS certificate {0x8c03810 0xc001030ba0 1.3.9999.1.7=#130d74656c652e617365632e6f7267,1.3.9999.1.5=#130d74656c652e617365632e6f7267,1.3.9999.1.6=#13147a61626269782e74656c652e617365632e6f7267,1.3.9999.1.4=#132464613036373937312d313232322d343964332d613464332d663762333133636232633639,CN=teleport-admin,OU=usage:apps,O=access+O=editor,POSTALCODE={\"aws_role_arns\":null\,\"db_names\":null\,\"db_users\":null\,\"kubernetes_groups\":null\,\"kubernetes_users\":null\,\"logins\":null\,\"windows_logins\":null},STREET=tele.example.com,L=-teleport-nologin-50a3bdf8-0f71-4f05-bad6-1174a5573e72+L=-teleport-internal-join 2022-09-03 05:35:08.002242582 +0000 UTC [] [] 5 []}. common_name:teleport-admin dns_names:[] locality:[-teleport-nologin-50a3bdf8-0f71-4f05-bad6-1174a5573e72 -teleport-internal-join] not_after:2022-09-03 05:35:08.002242582 +0000 UTC org:[access editor] org_unit:[usage:apps] tlsca/ca.go:874
2022-09-02T14:17:36 INFO [AUDIT]     cert.create cert_type:user cluster_name:tele.example.com code:TC000I ei:0 event:cert.create identity:map[expires:2022-09-03T05:35:08.74567175Z logins:[-teleport-nologin-4ac18442-0a6d-4fab-81ec-565010a8112e -teleport-internal-join] roles:[access editor] route_to_cluster:tele.example.com teleport_cluster:tele.example.com traits:map[aws_role_arns:<nil> db_names:<nil> db_users:<nil> kubernetes_groups:<nil> kubernetes_users:<nil> logins:<nil> windows_logins:<nil>] user:teleport-admin] time:2022-09-02T18:17:36.568Z uid:c2982937-572d-4f1c-a1be-35463e4ddb24 events/emitter.go:263
```

I followed the setup guide for the app_service, I am confused as to why its giving me these errors.

**Comment by zmb3** [comment] 2022-09-05 21:46
Closing as duplicate of https://github.com/gravitational/teleport/issues/10519

**Closed by zmb3** 2022-09-05 21:46 UTC
Labels: bug, application-access
