### ISSUE TITLE
Provide documentation on switching backends

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#3532] opened 2020-04-07 00:16 UTC
## Summary
Users can experience the following error if they switch to a different storage backend  (`dir` storage to `firestore`, `firestore` storage to `dir`) after teleport has already been started. 

ERRO [PROC:1]    Proxy failed to establish connection to cluster: remote error: tls: bad certificate

The proxy will not connect to the auth server and Teleport will not function as expected.
Guidance or tips should be provided on what to do with the local storage (/var/lib/teleport by default) when changing backends. Removing the local storage directory resolves the issue.  

### Audience
Users going to high availability configuration for storage or switching to another high availability storage (etcd to firestore,..);

### Location
Provide in the locations that document high availability  storage.

**Comment by zmb3** [comment] 2022-08-29 21:21
Closing as duplicate of #2440

**Closed by zmb3** 2022-08-29 21:21 UTC
Labels: documentation
