### ISSUE TITLE
Panic in `TestConnectionWrapper_Read`

### ISSUE THREAD

**Issue by rosstimothy** [gravitational/teleport#24047] opened 2023-04-04 15:03 UTC
#### Link(s) to logs

- https://github.com/gravitational/teleport/actions/runs/4608626090/jobs/8144653050?pr=23865

#### Relevant snippet

```
panic: Fail in goroutine after TestConnectionWrapper_Read has completed

goroutine 94 [running]:
testing.(*common).Fail(0xc000632000)
	/opt/go/src/testing/testing.go:933 +0x1a8
testing.(*common).Fail(0xc0002fc4e0)
	/opt/go/src/testing/testing.go:927 +0x8f
testing.(*common).Errorf(0xc0002fc4e0, {0x1b43181, 0x3}, {0xc00052e840, 0x1, 0x1})
	/opt/go/src/testing/testing.go:1050 +0xaf
github.com/stretchr/testify/assert.Fail({0x1d572a0, 0xc0002fc4e0}, {0xc0002b2930, 0x66}, {0x0, 0x0, 0x0})
	/go/pkg/mod/github.com/stretchr/testify@v1.8.2/assert/assertions.go:262 +0x412
github.com/stretchr/testify/assert.NoError({0x1d572a0, 0xc0002fc4e0}, {0x1d56e60, 0xc000188500}, {0x0, 0x0, 0x0})
	/go/pkg/mod/github.com/stretchr/testify@v1.8.2/assert/assertions.go:1380 +0x127
github.com/gravitational/teleport/lib/sshutils.startSSHServer.func3()
	/__w/teleport/teleport/lib/sshutils/server_test.go:374 +0x6c
created by github.com/gravitational/teleport/lib/sshutils.startSSHServer
	/__w/teleport/teleport/lib/sshutils/server_test.go:368 +0x7da
FAIL	github.com/gravitational/teleport/lib/sshutils	0.160s
===================================================
```

**Comment by tigrato** [comment] 2023-04-06 11:38
Duplicate of #23480

**Closed by tigrato** 2023-04-06 11:38 UTC
Labels: flaky tests
