### ISSUE TITLE
Teleport using ssh can't find hostname as internal host lookups are case-sensitive.

### ISSUE THREAD

**Issue by slavitch** [gravitational/teleport#11749] opened 2022-04-05 20:48 UTC
### Description

Can connect to node "kuiper" just fine via tsh and ssh as nodename is lower case text:
Cannot connect to node  "G6FN14100L7A" over ssh as connection is converted to lowercase and lookup fails.

Connection lookups should be case-insensitive as DNS is case insensitive.

**What happened**:
Can connect to "kuiper" over tsh and ssh. Server side logs:

```
Apr  5 20:38:44 ip-172-31-20-73 teleport[120917]: 2022-04-05T20:38:44Z INFO [AUDIT]     session.end cluster_name:teleport-staging.c2ro.net code:T2004I ei:4 enhanced_recording:false event:session.end interactive:true namespace:default participants:[slavitch] server_addr:192.168.20.72:56176 server_hostname:kuiper server_id:cb8ff645-4bc5-4744-8ac1-e95f7da98d48 server_labels:map[city:Montréal consultants:false country:CA external-ip:216.46.11.210 hostname:kuiper region:Quebec restricted:false timezone:America/Toronto] session_recording:node session_start:2022-04-05T20:38:42.918352949Z session_stop:2022-04-05T20:38:44.384974951Z sid:025e9543-0954-4f43-a220-53c098b2a822 time:2022-04-05T20:38:44.385Z uid:d8be1a9a-8b26-4459-bad7-b1a2e60ff67d user:slavitch events/emitter.go:325
Apr  5 20:39:11 ip-172-31-20-73 teleport[120917]: 2022-04-05T20:39:11Z INFO [AUDIT]     session.start addr.remote:24.212.231.149:53938 cluster_name:teleport-staging.c2ro.net code:T2000I ei:0 event:session.start login:c2ro namespace:default server_addr:192.168.20.72:56176 server_hostname:kuiper server_id:cb8ff645-4bc5-4744-8ac1-e95f7da98d48 server_labels:map[city:Montréal consultants:false country:CA external-ip:216.46.11.210 hostname:kuiper region:Quebec restricted:false timezone:America/Toronto] session_recording:node sid:b84c6160-1d0b-4b03-86a0-5a7c64f79ae3 size:183:41 time:2022-04-05T20:39:11.633Z uid:d33e0d3c-509e-4ccb-964b-bfff6f870db0 user:slavitch events/emitter.go:325
```

Cannot connect to host G6FN14100L7A over ssh as hostname is converted to lower case and lookup fails.  DNS is case-insensitive.
```
Apr  5 20:29:34 ip-172-31-20-73 teleport[120917]: 2022-04-05T20:29:34Z WARN [PROXY]     "Subsystem request proxySubsys(cluster=default/teleport-staging.c2ro.net, host=g6fn14100l7a, port=3022) failed: Teleport proxy failed to connect to \"node\" agent \"g6fn14100l7a:3022\" over direct dial:\n\n  dial tcp: lookup g6fn14100l7a: Temporary failure in name resolution\n\nThis usually means that the agent is offline or has disconnected. Check the\nagent logs and, if the issue persists, try restarting it or re-registering it\nwith the cluster.." id:1512 local:172.31.20.73:443 login:c2ro remote:24.212.231.149:53916 teleportUser:slavitch regular/sshserver.go:1584
Apr  5 20:29:34 ip-172-31-20-73 teleport[120917]: 2022-04-05T20:29:34Z ERRO [NODE]      "Teleport proxy failed to connect to \"node\" agent \"g6fn14100l7a:3022\" over direct dial:\n\n  dial tcp: lookup g6fn14100l7a: Temporary failure in name resolution\n\nThis usually means that the agent is offline or has disconnected. Check the\nagent logs and, if the issue persists, try restarting it or re-registering it\nwith the cluster." regular/sshserver.go:1774
```

When connecting over tsh case is preserved and the connection is made.
```
Apr  5 20:29:49 ip-172-31-20-73 teleport[120917]: 2022-04-05T20:29:49Z INFO [AUDIT]     session.start addr.remote:24.212.231.149:53918 cluster_name:teleport-staging.c2ro.net code:T2000I ei:0 event:session.start login:c2ro namespace:default server_addr:192.168.1.49:58216 server_hostname:G6FN14100L7A server_id:b8b210af-abf8-4453-856c-451b31e9ead2 server_labels:map[city:Madrid consultants:false country:ES external-ip:83.51.13.193 hostname:tiendab-234-01 region:Madrid restricted:false timezone:Europe/Madrid] session_recording:node sid:0757c1e9-98a4-4a6b-adfc-248f7faf521c size:183:41 time:2022-04-05T20:29:49.266Z uid:f2800028-1652-4506-8586-a899b3a62bce user:slavitch events/emitter.go:325
```

**What you expected to happen**:

tsh and ssh connections work the same despite case of hostname as dns is case-insensitive. 

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1.  Create a node that uses exclusively upper case characters in the nodename.
2.  Try to connect via ssh  (ssh config > ~/.ssh/config)
3.  It fails
4.  Create a node that uses exclusively lower case characters in the nodename.
5.  Try to connect via ssh  (ssh config > ~/.ssh/config)
6.  It succeeds

The behavior should be the same no matter the case of characters in the hostname as DNS names are case-insensitive.

### Server Details
- Teleport version (run `teleport version`): Teleport v9.0.3 git:v9.0.3-0-g1cf2b3e17 go1.17.7

- Server OS (e.g. from `/etc/os-release`):  

NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

- Where are you `running` Teleport? (e.g. AWS, GCP, Dedicated Hardware): AWS
- Additional details:

### Client Details
- Tsh version (`tsh version`): Teleport v9.0.3 git:v9.0.3-0-g1cf2b3e17 go1.17.7
- Computer OS (e.g. Linux, macOS, Windows):  Ubuntu 22.04
- Browser version (for UI-related issues):
- Installed via (e.g. apt, yum, brew, website download):   Custom.
- Additional details:

### Debug Logs
Please include or attach debug logs, when appropriate. Obfuscate sensitive information!
- Start Teleport with --debug flag (`teleport --debug`)
- Run tsh with --debug flag (`tsh --debug`)

**Comment by webvictim** [comment] 2022-04-05 21:25
More or less the same thing as https://github.com/gravitational/teleport/issues/2833

**Comment by slavitch** [comment] 2022-04-05 21:56
This violates DNS:

https://datatracker.ietf.org/doc/html/rfc4343

**Comment by zmb3** [comment] 2022-06-13 23:04
Closing as duplicate of #2833

**Closed by zmb3** 2022-06-13 23:04 UTC
Labels: bug
