### ISSUE TITLE
Is Teleport v7 supplied?

### ISSUE THREAD

**Issue by JUN-KOBAYASHI** [gravitational/teleport#9241] opened 2021-12-05 04:55 UTC
### How
I'm using Debian, but with apt-get upgrade, teleport is now v8 and won't boot.
I want to use v7, is it possible?

```
# apt-cache showpkg teleport
Package: teleport
Versions:
8.0.1 (/var/lib/apt/lists/deb.releases.teleport.dev_dists_stable_main_binary-amd64_Packages) (/var/lib/dpkg/status)
 Description Language:
                 File: /var/lib/apt/lists/deb.releases.teleport.dev_dists_stable_main_binary-amd64_Packages
                  MD5: f1bd1cf1b3e199c98ee1c62707e862d7


Reverse Depends:
Dependencies:
8.0.1 -
Provides:
8.0.1 -

```

**Comment by wadells** [comment] 2021-12-20 01:34
Hi @JUN-KOBAYASHI,

My apologies -- we don't have teleport 7 available in the apt repo.  Please install it directly via dpkg. 

```
$ curl -O https://get.gravitational.com/teleport_7.3.3_amd64.deb
# snip ...
$ apt install ./teleport_7.3.3_amd64.deb
# snip ...
Setting up teleport (7.3.3) ...
$ teleport version
Teleport v7.3.3 git:v7.3.3-0-g47ccf9e5f go1.16.2
```

We do plan to provide teleport 7 via apt eventually.  For more information, see this bug https://github.com/gravitational/teleport/issues/8166

**Comment by wadells** [comment] 2021-12-20 01:34
Closing as a duplicate of #8166.

**Closed** 2022-04-29 19:55 UTC
Labels: feature-request
