### ISSUE TITLE
Node logs constantly spamming `Unable to update session` error

### ISSUE THREAD

**Issue by rosstimothy** [gravitational/teleport#15101] opened 2022-08-01 21:06 UTC
When testing 1k active sessions on a cluster I noticed that one of my nodes was constantly spamming the log with the following for hours after all of the sessions has been killed. 

```
-55fe91b25eb4" is not found srv/sess.go:1484
2022-08-01T20:57:07Z WARN [SESSION:N] Unable to update session 7adac5d3-3989-40c0-bfc0-52b4c23f0070 as active: "/namespaces/default/sessions/active/7adac5d3-3989-40c0-bfc0-52b4c23f0070" is not found srv/sess.go:1484
2022-08-01T20:57:07Z WARN [SESSION:N] Unable to update session a2baa5aa-0670-466a-96c8-18b11a5ec2d2 as active: "/namespaces/default/sessions/active/a2baa5aa-0670-466a-96c8-18b11a5ec2d2" is not found srv/sess.go:1484
2022-08-01T20:57:08Z WARN [SESSION:N] Unable to update session bf8383cb-56c4-46fb-80bb-452e3bca7008 as active: "/namespaces/default/sessions/active/bf8383cb-56c4-46fb-80bb-452e3bca7008" is not found srv/sess.go:1484
2022-08-01T20:57:08Z WARN [SESSION:N] Unable to update session a4fd0ee2-12b8-459b-a5d5-b9c29fb8960d as active: "/namespaces/default/sessions/active/a4fd0ee2-12b8-459b-a5d5-b9c29fb8960d" is not found srv/sess.go:1484
2022-08-01T20:57:08Z WARN [SESSION:N] Unable to update session 675d44be-4a13-43bb-adb9-6d2c184a6653 as active: "/namespaces/default/sessions/active/675d44be-4a13-43bb-adb9-6d2c184a6653" is not found srv/sess.go:1484
2022-08-01T20:57:08Z WARN [UPLOAD]    Skipped session recording 98fe9b32-1237-4d65-af16-073580b2418b.tar. error:[session file could be corrupted or is using unsupported format: session recording 98fe9b32-1237-4d65-af16-073580b2418b is either corrupted or is using unsupported format, remove the file /home/ubuntu/.config/log/upload/streaming/default/98fe9b32-1237-4d65-af16-073580b2418b.tar to correct the problem, remove the /home/ubuntu/.config/log/upload/streaming/default/98fe9b32-1237-4d65-af16-073580b2418b.error file to retry the upload] filesessions/fileasync.go:253
2022-08-01T20:57:08Z WARN [SESSION:N] Unable to update session 4d0dd3b0-09ab-441d-8790-e56095966197 as active: "/namespaces/default/sessions/active/4d0dd3b0-09ab-441d-8790-e56095966197" is not found srv/sess.go:1484
2022-08-01T20:57:08Z WARN [SESSION:N] Unable to update session dadf7e30-9ecc-4d9a-985b-38e2a9eb2074 as active: "/namespaces/default/sessions/active/dadf7e30-9ecc-4d9a-985b-38e2a9eb2074" is not found srv/sess.go:1484
2022-08-01T20:57:08Z WARN [SESSION:N] Unable to update session bb34d988-43f0-48d9-8d10-0832f980039f as active: "/namespaces/default/sessions/active/bb34d988-43f0-48d9-8d10-0832f980039f" is not found srv/sess.go:1484
2022-08-01T20:57:08Z WARN [SESSION:N] Unable to update session b9eb80a7-c215-489c-82af-01c37c2b3198 as active: "/namespaces/default/sessions/active/b9eb80a7-c215-489c-82af-01c37c2b3198" is not found srv/sess.go:1484
2022-08-01T20:57:08Z WARN [SESSION:N] Unable to update session 73210fa8-ca2c-4498-8734-fa9ca5ec36df as active: "/namespaces/default/sessions/active/73210fa8-ca2c-4498-8734-fa9ca5ec36df" is not found srv/sess.go:1484
2022-08-01T20:57:08Z WARN [SESSION:N] Unable to update session 8516da7f-ddf8-46e5-860c-419ab9a92dd9 as active: "/namespaces/default/sessions/active/8516da7f-ddf8-46e5-860c-419ab9a92dd9" is not found srv/sess.go:1484
```

**Comment by zmb3** [comment] 2022-08-01 21:18
@xacrimon could this be related to a session tracker heartbeat not closing properly?

**Comment by xacrimon** [comment] 2022-08-02 09:21
@zmb3 @rosstimothy This log message is coming from `s.heartbeat()` which deals with the legacy session metadata system predating session trackers. This bug is actually very old and stems from the fact that the TTL for the auth server to remove a session for this system once heartbeats stop is just a couple dozen seconds, most of this system relies on very short TTL's and refresh times (the nodes heartbeat to the auth every 2 seconds for every active session). I believe this can happen if a node disconnects or similar causing heartbeats to be missed for some time.

**Comment by zmb3** [comment] 2022-08-03 16:17
This will no longer occur after https://github.com/gravitational/teleport/pull/15155/files is merged in v11.

In v10, the warnings are harmless because nothing looks at this old session system.

In v9/v8 this may still be an issue.

**Comment by zmb3** [comment] 2022-08-11 14:59
Closing as duplicate of #5723

**Closed by zmb3** 2022-08-11 14:59 UTC
Labels: bug, audit-log

**Comment by falschgeldkind** [comment] 2023-07-13 10:56
it seems that I have the same / a similar problem:

The teleport Version is: Teleport v12.1.1 git:api/v12.1.1-0-gb9ee483 go1.19.7

`Jul 13 12:53:52 zabbix-fe.kroschke.com teleport[6048]: 2023-07-13T12:53:52+02:00 WARN [SESSION:N] Unable to update session 986a2f31-e3c2-49ad-8a50-ed8a8cfd43f8 as active: object not found srv/sess.go:1484
Jul 13 12:53:54 zabbix-fe.kroschke.com teleport[6048]: 2023-07-13T12:53:54+02:00 WARN [SESSION:N] Unable to update session 986a2f31-e3c2-49ad-8a50-ed8a8cfd43f8 as active: object not found srv/sess.go:1484
Jul 13 12:53:56 zabbix-fe.kroschke.com teleport[6048]: 2023-07-13T12:53:56+02:00 WARN [SESSION:N] Unable to update session 986a2f31-e3c2-49ad-8a50-ed8a8cfd43f8 as active: object not found srv/sess.go:1484
Jul 13 12:53:58 zabbix-fe.kroschke.com teleport[6048]: 2023-07-13T12:53:58+02:00 WARN [SESSION:N] Unable to update session 986a2f31-e3c2-49ad-8a50-ed8a8cfd43f8 as active: object not found srv/sess.go:1484
Jul 13 12:54:00 zabbix-fe.kroschke.com teleport[6048]: 2023-07-13T12:54:00+02:00 WARN [SESSION:N] Unable to update session 986a2f31-e3c2-49ad-8a50-ed8a8cfd43f8 as active: object not found srv/sess.go:1484
Jul 13 12:54:02 zabbix-fe.kroschke.com teleport[6048]: 2023-07-13T12:54:02+02:00 WARN [SESSION:N] Unable to update session 986a2f31-e3c2-49ad-8a50-ed8a8cfd43f8 as active: object not found srv/sess.go:1484
Jul 13 12:54:04 zabbix-fe.kroschke.com teleport[6048]: 2023-07-13T12:54:04+02:00 WARN [SESSION:N] Unable to update session 986a2f31-e3c2-49ad-8a50-ed8a8cfd43f8 as active: object not found srv/sess.go:1484
Jul 13 12:54:06 zabbix-fe.kroschke.com teleport[6048]: 2023-07-13T12:54:06+02:00 WARN [SESSION:N] Unable to update session 986a2f31-e3c2-49ad-8a50-ed8a8cfd43f8 as active: object not found srv/sess.go:1484
Jul 13 12:54:08 zabbix-fe.kroschke.com teleport[6048]: 2023-07-13T12:54:08+02:00 WARN [SESSION:N] Unable to update session 986a2f31-e3c2-49ad-8a50-ed8a8cfd43f8 as active: object not found srv/sess.go:1484
Jul 13 12:54:10 zabbix-fe.kroschke.com teleport[6048]: 2023-07-13T12:54:10+02:00 WARN [SESSION:N] Unable to update session 986a2f31-e3c2-49ad-8a50-ed8a8cfd43f8 as active: object not found srv/sess.go:1484
Jul 13 12:54:12 zabbix-fe.kroschke.com teleport[6048]: 2023-07-13T12:54:12+02:00 WARN [SESSION:N] Unable to update session 986a2f31-e3c2-49ad-8a50-ed8a8cfd43f8 as active: object not found srv/sess.go:1484
Jul 13 12:54:14 zabbix-fe.kroschke.com teleport[6048]: 2023-07-13T12:54:14+02:00 WARN [SESSION:N] Unable to update session 986a2f31-e3c2-49ad-8a50-ed8a8cfd43f8 as active: object not found srv/sess.go:1484
Jul 13 12:54:16 zabbix-fe.kroschke.com teleport[6048]: 2023-07-13T12:54:16+02:00 WARN [SESSION:N] Unable to update session 986a2f31-e3c2-49ad-8a50-ed8a8cfd43f8 as active: object not found srv/sess.go:1484
Jul 13 12:54:18 zabbix-fe.kroschke.com teleport[6048]: 2023-07-13T12:54:18+02:00 WARN [SESSION:N] Unable to update session 986a2f31-e3c2-49ad-8a50-ed8a8cfd43f8 as active: object not found srv/sess.go:1484
Jul 13 12:54:20 zabbix-fe.kroschke.com teleport[6048]: 2023-07-13T12:54:20+02:00 WARN [SESSION:N] Unable to update session 986a2f31-e3c2-49ad-8a50-ed8a8cfd43f8 as active: object not found srv/sess.go:1484
Jul 13 12:54:22 zabbix-fe.kroschke.com teleport[6048]: 2023-07-13T12:54:22+02:00 WARN [SESSION:N] Unable to update session 986a2f31-e3c2-49ad-8a50-ed8a8cfd43f8 as active: object not found srv/sess.go:1484
Jul 13 12:54:24 zabbix-fe.kroschke.com teleport[6048]: 2023-07-13T12:54:24+02:00 WARN [SESSION:N] Unable to update session 986a2f31-e3c2-49ad-8a50-ed8a8cfd43f8 as active: object not found srv/sess.go:1484`
