### ISSUE TITLE
Add support for SCIM

### ISSUE THREAD

**Issue by Erick-Reyes** [gravitational/teleport#13045] opened 2022-05-31 22:31 UTC
Expected behavior:
Able to see all users, even idle users. 

Current behavior:
On the console, customer only sees ~50 users on the user list. When they try to ssh with one of the users that is not in the list it's working and afterwards they are able to see the user on the list. Customer believes there is a filter on the table to only show active users from the past days. 

We clarify to customer that we actually don't sync the users from your SSO provider. We create temp auto-expiring user entries.

Customer believes this is a very weird behavior. They state that with other tools, a user is using the service for the first time a user gets created. This is important to them as it helps them understand how many users they have using Teleport and see what groups Teleport is getting for each user without having to go into their users and groups directories. 

We explained that why Teleport does this as we prioritized this flow to expire users for security reasons. We only create a user for a duration of the SSO session, then it expires. Otherwise we would either have to use SCIM (that is easy to disrupt to keep stale entries). This way we have a robust way to ensure that Teleport will not have stale/de-provisioned users in the system.

Know customer is asking: 
I need to see all of the users. can this be fixed please?

Bug details:
- Teleport version: Cloud managed/7.1.0 for agents on server
- Recreation steps: Pending
- Debug logs: Pending

**Comment by webvictim** [comment] 2022-06-03 17:03
This isn't a bug, it's working as intended.

**Comment by zmb3** [comment] 2022-08-10 22:07
Assuming we won't make any changes here, but added `needs-product-decision` to get confirmation.

**Comment by klizhentas** [comment] 2022-08-11 16:10
I think our system is more secure than SCIM-based approach that is easy to disrupt to keep the stale entries. 

However, ideal case would be to create expiring entries **and** use SCIM when possible to keep them always up to date. If SCIM connection breaks down, then entries would expire.

Let's convert this issue to my requirement above then, it would be significant product improvement for large customers.

**Comment by aberoham** [comment] 2023-01-04 18:20
SCIM is of interest to me too. It's showing up in other SSO-connected products and seems to be easier for point-and-click folks to understand compared to natural expiration/TTL.

**Comment by zmb3** [comment] 2024-02-04 03:00
@tcsc please make sure any PRs of yours that implement SCIM are properly linked to this issue (and close it if we're done! 😄 )

**Comment by zmb3** [comment] 2024-06-22 03:16
@r0mant @tcsc at what point will we be ready to say "we added support for SCIM and we can close this issue"?

Are we there already?

**Closed** 2024-10-06 00:38 UTC
Labels: feature-request, sso, c-ar
