### ISSUE TITLE
tsh kube session join "bad handshake"

### ISSUE THREAD

**Issue by jingsun-teleport** [gravitational/teleport#15111] opened 2022-08-02 02:40 UTC
**Expected behavior:**
"tsh kube join" should be working

**Current behavior:**
_Show error,_
```
Handshake failed with status 500
and body: {"kind":"Status","apiVersion":"meta.k8s.io/v1","metadata":{},"status":"Failure","message":"malformed HTTP response \"\\x00\\x00\\x18\\x04\\x00\\x00\\x00\\x00\\x00\\x00\\x05\\x00\\x10\\x00\\x00\\x00\\x03\\x00\\x00\\x00\\xfa\\x00\\x06\\x00\\x10\\x01@\\x00\\x04\\x00\\x10\\x00\\x00\"","code":500}

ERROR: websocket: bad handshake
```

**Bug details:**
**- Teleport version**
Teleport Cluster 10.0.0
tsh client 10.0.0
EKS 1.22
- Recreation steps
Two teleport users with same simiple role configuration as,
```
kind: role
version: v5
metadata:
  name: k8s-user
spec:
  allow:
    join_sessions:
    - kinds:
      - k8s
      - ssh
      modes:
      - moderator
      name: testing
      roles:
      - k8s-user
    kubernetes_groups:
    - system:masters
    kubernetes_labels:
      '*': '*'
```

One user usera start kube session as normal,
Another user userb,
1. tsh login
2. tsh kube sessions
3. tsh kube join [...] ###working ok
4. tsh kube login [...]
5. kubectl get pods -A
6. tsh kube join [...] ###getting error as above

**Comment by strideynet** [comment] 2022-08-02 14:51
Is this a duplicate of https://github.com/gravitational/teleport/issues/14775 ?

**Comment by zmb3** [comment] 2022-08-02 17:58
Yes, looks like a duplicate. Let's move this over to the original issue.

**Closed by zmb3** 2022-08-02 17:58 UTC
Labels: bug, kubernetes-access, tsh, c-fi
