### ISSUE TITLE
[v.11.0] /docs/pages/machine-id/guides/github-actions.mdx

### ISSUE THREAD

**Issue by lucasmellos** [gravitational/teleport#18855] opened 2022-11-29 14:03 UTC
## Applies To

https://goteleport.com/docs/machine-id/guides/github-actions/

## Details
The listed Action file has some path errors, Teleport has no permission to write on <code>/opt</code> and it doesn't match with <code> tsh -i ./opt/machine-id/identity</code>

The fetch credentials task should be something like

```yaml
- name: Fetch credentials
       run: >
         tbot start
         --join-method=github
         --token=github-token
        --ca-ping=sha256:<hash from tctl status command>
# Use the address of the auth/proxy server for your own cluster.
         --auth-server=example.domain:443
         --oneshot
         --destination-dir=./opt/machine-id
         --data-dir=./opt/machine-id-data
```

Adding a dot before <code>./opt/<code> on destination-dir and data-dir.

Also, there isn't a relation to ca-pin when running <code>tbot start</code>. Running it without --ca-pin throws 
```
Joining cluster without validating the identity of the Auth Server. This may open you up to a Man-In-The-Middle (MITM) attack if an attacker can gain privileged network access. To remedy this, use the CA pin value provided when join token was generated to validate the identity of the Auth Server. auth/register.go:412
```

That's why I suggest adding --ca-pin to tbot start command.

**Comment by strideynet** [comment] 2022-11-29 14:06
Dupe of https://github.com/gravitational/teleport/issues/18856

**Closed by strideynet** 2022-11-29 14:06 UTC
Labels: documentation
