### ISSUE TITLE
Duplicate Server Nodes in the Teleport UI

### ISSUE THREAD

**Issue by TeleLos** [gravitational/teleport#34853] opened 2023-11-21 19:17 UTC
Expected behavior:
Teleport Proxy UI should more accurately display the list of available server resources

Current behavior:
By executing the steps below it is possible to have duplicate node entries in the resource list. You will not see a duplicate in the tsh ls output. Nor will you see duplicate entries in tctl get nodes output. 

![Screenshot 2023-11-21 at 2 12 43 PM](https://github.com/gravitational/teleport/assets/126096298/20e94985-89e2-4d85-b6ea-f1a8386fe4c2)

Bug details:
- Teleport Cluster version 14.1.3, Teleport Node Agent 14.1.3 and 14.0.2 
- Recreation steps

1. Launch a new EC2 instance of type Amazon Linux 
2. Log into Teleport UI
3. Select Enroll New Resource of type Linux 2/2023
4. Teleport UI will provide the command to install the teleport agent on this new EC2 instance. 
5. Run the script on the new EC2 instance created 
6. Examine that the new instance is available on Teleport UI. 
7. Use the Teleport UI to connect to the new Server
8. vim the teleport configuration file at /etc/teleport.yaml
9. Modify the nodename from the default used by the script and save the changes
10. run systemctl  restart teleport.service
11. Examine the Teleport UI 

- Debug logs
1. ps aux | grep teleport shows only one teleport.service process running.

**Comment by zmb3** [comment] 2023-11-22 06:25
Duplicate of #34236

**Closed by zmb3** 2023-11-22 06:26 UTC
Labels: bug, ssh

**Comment by TeleLos** [comment] 2023-11-22 20:13
Confirmed fixed in 14.2.0
