### ISSUE TITLE
Error message when closing interactive ssh session

### ISSUE THREAD

**Issue by Kilhog** [gravitational/teleport#17879] opened 2022-10-27 14:16 UTC
Since today after upgrading Teleport to 11.0.0, I have unexpected error message when I leave a interactive ssh session : 
`Failed to launch: failed to open user account database, code: %!d(<nil>).`

Bug details:
- Teleport version : 11.0.0 & 11.0.1

**Comment by zmb3** [comment] 2022-10-28 10:00
Looks like a duplicate of #17769

**Closed** 2022-10-28 10:00 UTC
Labels: bug
