### ISSUE TITLE
Teleport Cloud login defaults to port 3080 instead of 443.

### ISSUE THREAD

**Issue by Valien** [gravitational/teleport#6061] opened 2021-03-18 20:07 UTC
### Description

**What happened**: When you run a `tsh login --user=<name> --proxy=<cloud_subdomain>.teleport.sh` it will timeout and fail with an error like this:

`Get "https://<cloud_subdomain>.teleport.sh:3080/v1/webapi/ping": dial tcp 54.186.71.177:3080: i/o timeout`

But if you add the `443` at the end like this: 

`tsh login --user=<name> --proxy=<cloud_subdomain>.teleport.sh:443`

then it will work with no issues.

**What you expected to happen**:

Because it is a SaaS hosted instance of Teleport it should default to using `443` and not try to use `3080` that is default with self-hosted/on-prem versions of Teleport. Users should not have to put in the port as it should be understood that the proxy is SSL-enabled and automatically listens on `443`

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Run `tsh login --user=<your user> --proxy=<cloud>.teleport.sh` and it will error.
2. Run `tsh login --user=<your user> --proxy=<cloud>.teleport.sh:443` and it will succeed.

### Server Details
- Teleport version (run `teleport version`): 6.0.2
- Server OS (e.g. from `/etc/os-release`): Cloud - Prod
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): Cloud - Prod
- Additional details:

### Client Details
- Tsh version (`tsh version`): 6.0.2
- Computer OS (e.g. Linux, macOS, Windows): OSX
- Browser version (for UI-related issues):
- Installed via (e.g. apt, yum, brew, website download):
- Additional details:

### Debug Logs
Please include or attach debug logs, when appropriate. Obfuscate sensitive information!
- Start Teleport with --debug flag (`teleport --debug`)
- Run tsh with --debug flag (`tsh --debug`)

**Comment by benarent** [comment] 2021-03-18 22:25
Duplicate of https://github.com/gravitational/teleport/issues/4924

**Comment by Valien** [comment] 2021-03-19 12:49
Thanks for finding the duplicate @benarent ! I searched but didn't find anything (I need to up my game on github search fu).

**Comment by russjones** [comment] 2021-03-23 17:50
Closing in preference of #4924.

**Closed by russjones** 2021-03-23 17:50 UTC
Labels: bug
