### ISSUE TITLE
Periodic invalid memory address or nil pointer in alpine

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#6614] opened 2021-04-27 18:34 UTC
### Description

**What happened**:

Periodically session uploading in alpine 3.11 result in a invalid memory addr or nil pointer as part of session upload

**What you expected to happen**:

No memory or nil pointers issues

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Deploy Teleport to alpine
2.Run repeated sessions until issue occurs.

### Server Details
- Teleport version (run `teleport version`):6.1.1
- Server OS (e.g. from `/etc/os-release`): Alpine
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): AWS
- Additional details:

### Debug Logs
Please include or attach debug logs, when appropriate. Obfuscate sensitive information!
- Start Teleport with --debug flag (`teleport --debug`)
- Run tsh with --debug flag (`tsh --debug`)
```
INFO [NODE:PROX] Connected. addr:x.x.x.132:46432 remote-addr:x.x.53.100:3024 leaseID:540 target:teleport.<hostname>:3024 reversetunnel/agent.go:347
INFO [NODE]      Creating (interactive) session 7729bfac-1fff-42d8-bee5-af657bbf0568. id:2 local:x.x.x.132:55842 login:root remote:100.64.26.42:35460 teleportUser:<redacted> srv/sess.go:211
INFO [SESSION:N] New party ServerContext(100.64.26.42:35460->x.x.x.132:55842, user=root, id=2) party(id=56da3c15-f3af-4ba7-b39c-f9f62bf2feb3) joined session: 7729bfac-1fff-42d8-bee5-af657bbf0568 srv/sess.go:1219
INFO [AUDIT]     session.start addr.remote:100.64.26.42:35460 cluster_name:<redacted> code:T2000I ei:0 event:session.start login:root namespace:default server_addr:x.x.x.132:55842 server_hostname:mariadb-588283.node.consul server_id:7486e3a5-8f7b-4b1e-9ba2-d737f8e52308 server_labels:map[IP:10.11.16.132 alpine_version:3.11 container_count:1 environment:dc1-prod kernel:4.19.56-0-std nomad_meta:hwclass:general|roam:0|vlan:83,84,90|db:mariadb-recon-0-0| teleport_version:teleport-6.0.2-r10 uptime:15:22:58 up 51 days, 21:40, load average: 2.82, 4.04, 3.77] sid:7729bfac-1fff-42d8-bee5-af657bbf0568 size:80:14 time:2021-04-16T15:23:56.354Z uid:2a9a5c4a-20d1-4721-a5d3-4f43fbe9f59e user:<redacted> events/emitter.go:317
INFO [NODE]      Creating (interactive) session b154b3a7-c57f-4cd8-9098-3671b6bf3d38. id:3 local:x.x.x.132:55842 login:root remote:100.64.23.25:35156 teleportUser:<redacted> srv/sess.go:211
INFO [SESSION:N] New party ServerContext(100.64.23.25:35156->x.x.x.132:55842, user=root, id=3) party(id=c021859b-3624-4ec1-8774-73207f98ac1d) joined session: b154b3a7-c57f-4cd8-9098-3671b6bf3d38 srv/sess.go:1219
INFO [AUDIT]     session.start addr.remote:100.64.23.25:35156 cluster_name:<redacted> code:T2000I ei:0 event:session.start login:root namespace:default teleport_version:teleport-6.0.2 <redacted>] sid:b154b3a7-c57f-4cd8-9098-3671b6bf3d38 size:39:14 time:2021-04-16T15:34:28.674Z uid:c7edc9ff-d297-4a50-a58a-f70f6994736f user:<redacted> events/emitter.go:317
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xfa216f]
goroutine 309 [running]:
github.com/gravitational/teleport/lib/events.(*UploadCompleter).CheckUploads(0xc000a98d00, 0x2f9a5f0, 0xc000a73b00, 0x0, 0x3)
 /go/src/github.com/gravitational/teleport/lib/events/complete.go:154 +0x6ef
github.com/gravitational/teleport/lib/events/filesessions.(*Uploader).Serve(0xc0009f92c0, 0xc000b90dc0, 0xc000b90dc0)
 /go/src/github.com/gravitational/teleport/lib/events/filesessions/fileasync.go:220 +0x9e5
github.com/gravitational/teleport/lib/service.(*TeleportProcess).initUploaderService.func3(0x0, 0x0)
 /go/src/github.com/gravitational/teleport/lib/service/service.go:1953 +0x48
github.com/gravitational/teleport/lib/service.(*LocalService).Serve(0xc000a83520, 0x5, 0xc000b90f58)
 /go/src/github.com/gravitational/teleport/lib/service/supervisor.go:457 +0x2a
github.com/gravitational/teleport/lib/service.(*LocalSupervisor).serve.func1(0xc000446a90, 0x2f9ae08, 0xc000a83520)
 /go/src/github.com/gravitational/teleport/lib/service/supervisor.go:246 +0x197
created by github.com/gravitational/teleport/lib/service.(*LocalSupervisor).serve
 /go/src/github.com/gravitational/teleport/lib/service/supervisor.go:241 +0x6e
```

**Comment by webvictim** [comment] 2021-04-27 20:54
I believe this is a duplicate of https://github.com/gravitational/teleport/issues/5699

I'm fairly sure this has been fixed, but it may not have been released yet.

**Comment by russjones** [comment] 2021-05-06 00:06
@stevenGravy Can you try this with Teleport 6.1.5, should be fixed now. If it is, please close this ticket.

**Closed by russjones** 2021-05-06 00:06 UTC
Labels: bug, ssh
