### ISSUE TITLE
`tsh logout` flags do not work.

### ISSUE THREAD

**Issue by SMillerDev** [gravitational/teleport#33681] opened 2023-10-19 08:49 UTC
Expected behavior:
`tsh logout --user sean` deletes certificates.

Current behavior:
```
~ [1]$ tsh logout --user
tsh: error: expected argument for flag '--user'
usage: tsh logout

Delete a cluster certificate.

Flags:
  -l, --login                    Remote host login
      --proxy                    Teleport proxy address
      --user                     Teleport user, defaults to current local user
      --ttl                      Minutes to live for a session
  -i, --identity                 Identity file
      --cert-format              SSH certificate format
      --[no-]insecure            Do not verify server's certificate and host name.
                                 Use only in test environments
      --auth                     Specify the name of authentication connector to
                                 use.
      --[no-]skip-version-check  Skip version checking between server and client.
  -d, --[no-]debug               Verbose logging to stdout
  -k, --add-keys-to-agent        Controls how keys are handled. Valid values are
                                 [auto no yes only].
      --[no-]enable-escape-sequences
                                 Enable support for SSH escape sequences.
                                 Type '~?' during an SSH session to list supported
                                 sequences. Default is enabled.
      --bind-addr                Override host:port used when opening a browser
                                 for cluster logins
      --mfa-mode                 Preferred mode for MFA and Passwordless
                                 assertions (auto, cross-platform, platform, otp)
      --[no-]headless            Use headless login. Shorthand for
                                 --auth=headless.
      --mlock                    Determines whether process memory will be locked
                                 and whether failure to do so will be accepted
                                 (off, auto, best_effort, strict).
      --piv-slot                 Specify a PIV slot key to use for Hardware Key
                                 support instead of the default. Ex: "9d"
  -J, --jumphost                 SSH jumphost

Aliases:

ERROR: expected argument for flag '--user'

~ [1]$ tsh logout --user sean
ERROR: unexpected argument: sean
```

Bug details:
- Teleport version: v14.1.0 git:v14.1.0-0-g508ccc5 go1.21.3
- Recreation steps: run `tsh logout --user`
- Debug logs

**Comment by GavinFrazar** [comment] 2024-01-18 19:46
workaround: `tsh logout --user=sean`. (no space between)

I'll fix this for next release

**Comment by zmb3** [comment] 2024-10-06 00:48
Duplicate of #9657

**Comment by GavinFrazar** [comment] 2024-10-06 18:35
this is a different issue caused by a flag parsing bug.

**Closed** 2024-10-10 17:49 UTC
Labels: bug, tsh
