### ISSUE TITLE
Integrations tiles do not resize properly

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#30251] opened 2023-08-10 00:50 UTC
When resizing the "enroll new integration" screen, integration tiles get cut off and don't resize properly:

<img width="1477" alt="Screenshot 2023-08-09 at 5 47 46 PM" src="https://github.com/gravitational/teleport/assets/339322/d2d8a79f-7be8-4914-8e65-69a235fc8092">

**Comment by zmb3** [comment] 2024-07-07 19:52
Duplicate of https://github.com/gravitational/teleport.e/issues/1981

**Closed by zmb3** 2024-07-07 19:52 UTC
Labels: bug, ui
