### ISSUE TITLE
Desktop Access 'Getting Started' guide assumes Teleport is installed

### ISSUE THREAD

**Issue by philip-teleport** [gravitational/teleport#16467] opened 2022-09-16 15:45 UTC
## Details

The Desktop Access [Getting Started](https://goteleport.com/docs/desktop-access/getting-started/#getting-started) guide assumes Teleport is installed and states that "You can reuse an existing server running any other Teleport instance".

[Step 6/7. Configure Teleport](https://goteleport.com/docs/desktop-access/getting-started/#step-67-configure-teleport) assumes that Teleport is installed and that you are re-using an existing server. For someone starting from scratch and only focussed on Desktop Access, SSH access to an existing Linux server may not have been set-up. The guide should allow for this and provide installation instructions and not require the reader to look elsewhere.

### Category
- Improve Existing

**Comment by philip-teleport** [comment] 2022-09-16 16:19
The ask is to include a section similar to [Install Teleport on your Linux host]https://goteleport.com/docs/server-access/getting-started/#step-14-install-teleport-on-your-linux-host, not for steps to deploy a cluster.

Scenario is someone is using Teleport Cloud that has never used Teleport for SSH access so has no knowledge of installing Teleport on a Linux server.

**Comment by zmb3** [comment] 2022-09-16 16:28
Gotcha. That makes total sense. This guide will likely be getting a revamp soon, I'll make sure we add some more detail here.

**Comment by zmb3** [comment] 2022-09-27 14:37
Closing as duplicate of #16397

**Closed by zmb3** 2022-09-27 14:37 UTC
Labels: documentation, desktop-access, time-to-value
