### ISSUE TITLE
Teleport 6.2 Release Plan

### ISSUE THREAD

**Issue by awly** [gravitational/teleport#6734] opened 2021-05-04 22:59 UTC
# Teleport 6.2 Release Plan

## Release Manager

Andrew Lytvynov (@awly)

## Release Date

- [x] First Alpha: May 11th, 2021.
- [x] First Beta/Testing start: May 14th 2021
- [x] First RC: May 18th 2021
- [x] Release: May 24th 2021

## Product Approvals

- [x] Security @awly
- [x] Scale @russjones
- [x] SSH and Kubernetes Access @russjones
- [x] Application and Database Access @r0mant 
- [x] Release @russjones
- [x] Documentation @klizhentas
- [x] Product @klizhentas

## Test Plan Approval

- [x] [Teleport 6.2 Test Plan](https://github.com/gravitational/teleport/issues/6651)

# Release Process

TODO: update when https://github.com/gravitational/teleport/pull/6661 has the full list

- [x] Prepare CHANGELOG/Release Notes. Must be approved be @klizhentas.
- [ ] Block merging into release branches (needs investigation).
- [x] Create release branch.
- [x] TBD.
- [x] Cut release.
- [x] Release Plugins.
- [ ] Organize release retrospective.

**Comment by russjones** [comment] 2021-05-11 20:50
@TravisGary @stevenGravy @anadeliafadeev We've released `6.2.0-alpha.1`.

**Comment by awly** [comment] 2021-05-14 19:11
Changes that will slip beta but land before RC.1
- https://github.com/gravitational/teleport/pull/6731 event iteration on UI @xacrimon 
- kube/db UI pages @kimlisa 

For the testplan, we will pause testing audit events and kube/db UI until those changes land.
Everything else in the testplan will be ready for testing starting on Monday.

**Comment by r0mant** [comment] 2021-05-14 19:14
@awly @kimlisa @klizhentas Kube/db pages (and https://github.com/gravitational/teleport/pull/6739 which adds missing CLI flags for db which new UI screen uses) need to be approved by Sasha to see if we need to make any tweaks before merging.

**Comment by r0mant** [comment] 2021-05-18 16:14
@awly FYI need to land https://github.com/gravitational/teleport/pull/6910 and https://github.com/gravitational/teleport.e/pull/264 backports before rc.1 ideally. They are backports of https://github.com/gravitational/teleport/pull/6739 and https://github.com/gravitational/teleport/pull/6739 respectively, and the latter one fails CI due to Drone license issue.

**Comment by xacrimon** [comment] 2021-05-18 16:16
Backports #6909 and https://github.com/gravitational/teleport.e/pull/263 are open for events iteration. Currently working to get them merged but waiting on reviews.

**Comment by russjones** [comment] 2021-05-19 01:19
@awly Need the following before I can sign off.

@tcsc Can you merge and backport?

* https://github.com/gravitational/teleport/pull/6849?

@webvictim Can you merge and backport?

* https://github.com/gravitational/teleport/pull/6900
* https://github.com/gravitational/teleport/pull/6886
* https://github.com/gravitational/teleport/pull/6902

**Comment by russjones** [comment] 2021-05-21 00:23
@awly I've signed off on `SSH and Kubernetes Access` and `Release Engineering`, but unchecked `Scale`, we need one more item that @xacrimon is working on https://github.com/gravitational/teleport/pull/6965.

**Comment by awly** [comment] 2021-05-21 16:32
we're delaying 6.2 release until Monday, May 24th to finish up testing and let the final fixes trickle in

**Comment by russjones** [comment] 2021-05-21 20:18
@travelton @stevenGravy @anadeliafadeev See above, we're delaying 6.2 until Monday, May 24th.

**Comment by awly** [comment] 2021-05-24 22:08
Status update:
- testplan is largely complete
  - some load tests are not done, but we have good confidence that the release is safe to cut before finishing them
  - https://github.com/gravitational/teleport/issues/7017 was found but seems like an existing 6.x bug
- @xacrimon is finished testing dynamodb index migration with Cloud
  - seems to work as expected, but slow on large deployments
  - we will cut 6.2.0 as is, and add some migration optimizations in 6.2.1
  - a note will be added to the changelog, suggesting to wait for 6.2.1 before upgrading large deployments using dynamodb
- I'm going to cut the release today and hand off 6.2.1 to @russjones

**Comment by russjones** [comment] 2021-05-24 22:54
@awly Did @alex-kovoy and @xacrimon figure out what the issue was with Cloud?

**Comment by awly** [comment] 2021-05-24 23:14
@russjones no, but it appears to be cause by a misconfiguration and not a bug in migration.

**Comment by alex-kovoy** [comment] 2021-05-24 23:25
@russjones @xacrimon said he was able to identify an issue and he will make a patch release with 25x performance increase which should let us to migrate the customers with large tables.

**Comment by russjones** [comment] 2021-05-25 01:22
@travelton @anadeliafadeev @stevenGravy Teleport 6.2 is out: https://github.com/gravitational/teleport/releases/tag/v6.2.0.

We missed getting Plugins (and Terraform) releases today, we will have those out tomorrow.

**Comment by russjones** [comment] 2021-05-25 02:19
@klizhentas Teleport 6.2 is out: https://github.com/gravitational/teleport/releases/tag/v6.2.0, will close out this ticket tomorrow once we have Plugins (Slack, Terraform, etc.) out as well.

**Comment by xacrimon** [comment] 2021-05-25 05:17
@russjones The crash loop we ran into appears to have been caused by some nodes being automatically rolled back due to the time it took for the server to start up. The nonfatal errors were caused by the work duplication we discussed and will be resolved with the locks. I also managed to make a 25x migration performance increase in the same patch due to some insights.

**Closed** 2021-05-28 22:04 UTC
Labels: release-engineering
