### ISSUE TITLE
interactive ssh does not have session with logind or wtmp

### ISSUE THREAD

**Issue by etorri** [gravitational/teleport#568] opened 2016-10-13 15:28 UTC
Hi, testing teleport and noticed that the interactive tsh/ssh session is not registered with loginctl/wtmp. In other words, when connected with "tsh ssh" to a node as user "testuser", I do "who" or "loginctl" I see other sessions but not one of "testuser".

I couldn't figure out how the interactive session is built at the node side in the code so no idea where the problem might be.

In same  system with OpenSSH sshd the sessions are registered.

Fedora 22
teleport pulled from github yesterday 12.10.

**Comment by kontsevoy** [comment] 2016-10-13 19:42
Note: need to add utmp support.

**Comment by kontsevoy** [comment] 2016-12-30 23:13
Teleport has a similar facility (audit log) and right now the cost of adding wtmp integration outweighs the benefits. Pushing for future releases.

**Comment by kontsevoy** [comment] 2017-09-22 23:44
Dupe of #742

**Closed by kontsevoy** 2017-09-22 23:44 UTC
Labels: feature request, P2

**Comment by kgtw** [comment] 2020-10-13 21:02
Hi @kontsevoy 

I see that #742 was merged and it introduced PAM functionality but it doesn't really address the feature request mentioned above about updating utmp / wtmp so that normal system commands such as `last`, `w`, `wall`, and `who` reflect the current state of active connections.

Any chance we can re-open this issue?

**Comment by webvictim** [comment] 2020-10-13 22:01
@kgtw https://github.com/gravitational/teleport/issues/3987 covers the wtmp/utmp requests and is still open - please add a +1/comment there if it's something that you'd like to see.
