### ISSUE TITLE
Machine ID: generate a kubeconfig for multiple clusters

### ISSUE THREAD

**Issue by ArunNadda** [gravitational/teleport#16863] opened 2022-09-29 21:51 UTC
#### What would you like Teleport to do?

Machine ID should make it possible to generate a kubeconfig that's valid for multiple clusters.

#### What problem does this solve?

Makes it easier to use Teleport Kubernetes access in CI/CD workflows that require access to multiple k8s clusters.

#### If a workaround exists, please include it.

Currently, i think options `destinations.directory/destinations.kubernetes_cluster` (in machineID) can be used to generate a separate kubeconfig file for each k8s cluster.

**Comment by strideynet** [comment] 2023-10-19 18:19
duplicate of https://github.com/gravitational/teleport/issues/31753

**Closed by strideynet** 2023-10-19 18:19 UTC
Labels: feature-request, machine-id, c-dv
