### ISSUE TITLE
chan_shutdown_read error on remote host after connecting with OpenSSH

### ISSUE THREAD

**Issue by Aharic** [gravitational/teleport#7153] opened 2021-06-03 00:24 UTC
### Description

**What happened**:

Starting with 6.1, OpenSSH causes following error message on remote server after connecting: `channel 1: chan_shutdown_read: shutdown() failed for fd 8 [i0 o1]: Not a socket` Seems to trigger when you run `ssh-add` (or any variant of) on remote server after connecting.

**What you expected to happen**:

OpenSSH should work without triggering errors on remote client.

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Connect to remote node via OpenSSH from a Windows client running 6.1+
2. Run `ssh-add` and observe error.

### Server Details
- Teleport version (run `teleport version`): 6.1+

### Client Details
- Tsh version (`tsh version`): 6.1+
- Computer OS (e.g. Linux, macOS, Windows): Windows

### Debug Logs
Please include or attach debug logs, when appropriate. Obfuscate sensitive information!
`channel 1: chan_shutdown_read: shutdown() failed for fd 8 [i0 o1]: Not a socket`

**Comment by EdwardDowling** [comment] 2022-06-24 14:00
@Aharic  would it be possible for a some more details on the version and perhaps some logs as well if you have the time. I have a tried several version from 6.1 onwards and can't seem to be able to reproduce the error. 
I think I must be making some incorrect assumptions somewhere when interpreting the reproduction steps.
I thought I had  managed to reproduce it for a bit but turns out that was a separate issue.

**Comment by r0mant** [comment] 2022-06-29 17:44
@EdwardDowling This is the information from the customer:

> We’ve seen this with Windows as a source host when agent forwarding is enabled.

> tested this in 9.3.6 IIRC and was still seeing issues

> Yes, easily reproducible on our end, happens on every connection where OpenSSH is used with Teleport and Agent forwarding (does not occur with tsh ssh -A)

> We are using OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2

**Comment by EdwardDowling** [comment] 2022-07-07 15:37
Additional logs from client
```
[cspann@somebox ~]$ debug2: channel 0: rcvd adjust 1
logout
debug1: client_input_channel_open: ctype auth-agent@openssh.com rchan 1 win 2097152 max 32768
debug2: fd 8 setting O_NONBLOCK
debug1: channel 1: new [authentication agent connection]
debug1: confirm auth-agent@openssh.com
Using teleport socket: /tmp/teleport-1712749559/teleport-115460.socket
debug1: client_input_channel_req: channel 0 rtype exit-status reply 0
debug2: channel 0: rcvd close
debug2: channel 0: output open -> drain
debug2: channel 0: chan_shutdown_read (i0 o1 sock -1 wfd 3 efd 7 [write])
debug2: channel 0: input open -> closed
debug2: channel 0: obuf empty
debug2: channel 0: chan_shutdown_write (i3 o1 sock -1 wfd 6 efd 7 [write])
debug2: channel 0: output drain -> closed
debug2: channel 0: almost dead
debug2: channel 0: gc: notify user
debug2: channel 0: gc: user detached
debug2: channel 0: send close
debug2: channel 0: is dead
debug2: channel 0: garbage collecting
debug1: channel 0: free: client-session, nchannels 2
debug2: channel 1: rcvd close
debug2: channel 1: output open -> drain
debug2: channel 1: chan_shutdown_read (i0 o1 sock 8 wfd 8 efd -1 [closed])
channel 1: chan_shutdown_read: shutdown() failed for fd 8 [i0 o1]: Not a socket
debug2: channel 1: input open -> closed
debug2: channel 1: obuf empty
debug2: channel 1: chan_shutdown_write (i3 o1 sock 8 wfd 8 efd -1 [closed])
debug2: channel 1: chan_shutdown_write: shutdown() failed for fd 8 [i3 o1]: Not a socket
debug2: channel 1: output drain -> closed
debug2: channel 1: send close
debug2: channel 1: is dead
debug2: channel 1: garbage collecting
debug1: channel 1: free: authentication agent connection, nchannels 1
Connection to somebox closed.
```

**Comment by EdwardDowling** [comment] 2022-07-18 11:40
Able to get similar `Not a socket` errors in v11, v9, v8 and v6.

**Comment by EdwardDowling** [comment] 2022-07-18 15:36
Have also been able to replicate a similar error when agent forwarding with the openssh client from windows to linux. 
Am no longer entirely convinced this is a Teleport specific issue.

**Comment by r0mant** [comment] 2022-07-20 03:47
@EdwardDowling I've spend a couple of hours looking into this today, and here's the results of the investigation:

- I was able to repro this using customer provided configuration, when agent forwarding is enabled using ssh client through Teleport.
- I _was not able_ to repro this when using ssh on Windows -> OpenSSH on Linux directly. Not sure how you managed to repro this without Teleport? For me (and the client) it seems to work properly?

After some troubleshooting, I think it may have something to do with how Teleport handles agent connections, specifically closing them. Particularly, commenting out this line appears to fix the issue for me as I no longer see the "not a socket" error:

https://github.com/gravitational/teleport/blob/v10.0.2/lib/teleagent/agent.go#L198

I would do the following:

- Confirm my results - make the same change and see if you also see the error gone.
- Keep troubleshooting AgentServer and how it handles connections to understand why it's happening.

**Closed** 2022-07-29 18:47 UTC
Labels: bug, good-starter-issue, OpenSSH, c-ju, c-rs
