### ISSUE TITLE
Bootstrap flag doesn't correctly setup trusted clusters.

### ISSUE THREAD

**Issue by fspmarshall** [gravitational/teleport#3642] opened 2020-04-28 22:27 UTC
Because the resources supplied to `--bootstrap` are directly injected into the backend as part of the auth server's initialization, the auth server never actually runs its normal trusted cluster [setup logic](https://github.com/gravitational/teleport/blob/bdd388e0d0bfca2008470e1d7a80223172403453/lib/auth/trustedcluster.go#L39).  This effectively causes the trusted cluster resource to be "orphaned" in the backend.

Either the `--bootstrap` flag should provide special handling for the `TrustedCluster` resource, or the `AuthServer` should notice the orphaned configuration object and attempt to finish setup.  The former is likely simpler to implement, but the latter is more resilient.

#### Workaround

Manually deleting and then re-creating the trusted cluster (`tctl rm tc/my-cluster && tctl create my-cluster.yaml`) fixes the problem.

**Comment by zmb3** [comment] 2024-02-27 19:52
Duplicate of #9547

**Closed by zmb3** 2024-02-27 19:52 UTC
Labels: bug, robustness, c-yw, c-cwv, c-awd
