### ISSUE TITLE
Add ability to configure dynamic discovery to agent Helm chart

### ISSUE THREAD

**Issue by nickbrennan1** [gravitational/teleport#10362] opened 2022-02-15 11:14 UTC
For dynamic discovery to work on an agent, resource labels are defined on the agent at startup, ie: 

```
app_service:
  enabled: "yes"
  resources:
  - labels:
      "*": "*"
```

However, it is not possible to define this in the custom helm chart, as the resources keyword is already used to define [kubernetes limits](https://goteleport.com/docs/kubernetes-access/helm/reference/#resources).

Require the ability to define resource labels to enable dynamic registration feature on kube agents

**Comment by bishalhnj** [comment] 2022-02-15 19:21
Oh! Thats great

**Comment by pschisa** [comment] 2022-02-17 19:14
seems like same request as #9846

**Comment by r0mant** [comment] 2022-04-19 19:07
Closing as a duplicate of https://github.com/gravitational/teleport/issues/9846.

**Closed by r0mant** 2022-04-19 19:07 UTC
Labels: feature-request, c-sr
