### ISSUE TITLE
request: teleport-plugins docker images for linux arm64

### ISSUE THREAD

**Issue by programmerq** [gravitational/teleport#28087] opened 2023-06-20 21:22 UTC
### What would you like Teleport to do?

Currently, images in `public.ecr.aws/gravitational/teleport-ent` and `public.ecr.aws/gravitational/teleport` are multiarch images that support amd64, arm, and arm64. The `public.ecr.aws/gravitational/teleport-plugin-*` repositories are amd64 only.

### What problem does this solve?

Some teams are moving away from x86_64 and adopting arm64, especially with the AWS Graviton servers.

### If a workaround exists, please include it.

Currently, teams must build their own container images to run teleport plugin containers on arm.

**Comment by zmb3** [comment] 2024-01-15 23:40
Closing as duplicate of #25416

**Closed by zmb3** 2024-01-15 23:40 UTC
Labels: feature-request, teleport-plugin, arm, release-engineering, c-upg
