### ISSUE TITLE
VSCode SSH support

### ISSUE THREAD

**Issue by jakule** [gravitational/teleport#16396] opened 2022-09-14 01:50 UTC
#### Expected behavior:

VSCode can connect to a node through Teleport: https://code.visualstudio.com/docs/remote/remote-overview

#### Current behavior:

VSCode fails when setting SSH connection to a node.

#### What needs to be fixed:

VSCode uses `ssh` command similar to this: ` ssh -v -T -D 58596 -o ConnectTimeout=15 node.example.com`. Currently, Teleport doesn't support `-T` switch causing VSCode to fail. `-D` flags seem to be supported in `tsh`, but not it `openssh`.
Lastly, ssh key forwarding is not implemented in Teleport `ssh -A`. This feature is not needed to get the basic VSCode functionality, but VSCode also uses it in some cases.

In some cases, VSCode can connect to a node with Teleport, but that requires setting `"remote.SSH.useLocalServer": false` which is not always possible, example: https://github.com/microsoft/vscode-remote-release/issues/6469#issuecomment-1208761662

**Comment by zmb3** [comment] 2022-09-14 02:41
Closing as duplicate of #9619

**Closed by zmb3** 2022-09-14 02:41 UTC
Labels: bug

**Comment by r0mant** [comment] 2022-09-15 00:42
@jakule Let's add the details you included in the description to the ticket Zac linked above so they're not lost.
