### ISSUE TITLE
No Listing of Roles a User is Allowed to Request in the CLI

### ISSUE THREAD

**Issue by corkrean** [gravitational/teleport#12099] opened 2022-04-19 22:33 UTC
tsh does not have a command to display the roles a user is allowed to request. This is forcing users to login into the WebUI to check what roles they have available, to check their role yaml (if they have access), or to ping an admin to ask what roles they have available. 

Ideally, there would be a tsh command to display the roles a user is allowed to request.

**Comment by zmb3** [comment] 2022-08-19 15:07
Closing as duplicate of #7693

**Closed by zmb3** 2022-08-19 15:07 UTC
Labels: enhancement, access-requests, c-pb
