### ISSUE TITLE
AMI scripts should not sync session recordings to `/etc/letsencrypt`

### ISSUE THREAD

**Issue by programmerq** [gravitational/teleport#39294] opened 2024-03-13 14:53 UTC
When using Teleport's published AMI with `USE_ACM=false`, it will use `certbot` to generate TLS certs. The `/etc/letsencrypt` directory is synchronized to the same S3 bucket used by Teleport for session recordings.

### Expected behavior:

When the `teleport-renew-cert` script runs, it should sync only the `certbot` state from S3.

### Current behavior:

When the `teleport-renew-cert` script runs, it syncs the _entire_ S3 bucket to `/etc/letsencrypt`.

https://github.com/gravitational/teleport/blob/v15.1.4/assets/aws/files/bin/teleport-renew-cert#L20

Once a cluster has enough recordings in the bucket, this will fill up the disk and can cause an outage.

### Bug details:
- Teleport version: all AMI versions appear to be affected. `v15.1.4` is the current latest version.
- Recreation steps: 
  - Create a Terraform or CloudFormation Teleport Cluster with letsencrypt enabled in HA mode.
  - Use the cluster long enough that there are enough session recordings to fill up the `/` disk on the instances.
- Debug logs: n/a

The `aws s3 sync` command should synchronize only the files necessary for `certbot` to `/etc/letsencrypt`.

**Comment by programmerq** [comment] 2024-03-13 15:03
A quick workaround:

In `/bin/teleport-renew-cert`, add the `--exclude` argument so line 20 looks like this:

```
# Fetching certbot state
aws s3 sync '--exclude=records/*' --exact-timestamps "s3://${TELEPORT_S3_BUCKET}" /etc/letsencrypt/ --sse=AES256
```

If this change is made on a live ec2 instance, it will only take effect on that instance. If the instance is replaced, the change will be lost.

This could be added to the CloudInit user data to make the change on first boot of an instance:

```
sed -i 's#^aws s3 sync --exact-timestamps "s3://${TELEPORT_S3_BUCKET}" /etc/letsencrypt/ --sse=AES256#aws s3 sync "--exclude=records/*" --exact-timestamps "s3://${TELEPORT_S3_BUCKET}" /etc/letsencrypt/ --sse=AES256#' /bin/teleport-renew-cert
```

I haven't done a full end-to-end test on this, but I wanted to share this here in case it is helpful to anyone.

**Comment by zmb3** [comment] 2024-03-15 23:05
Duplicate of #27884?

**Closed** 2024-03-19 13:45 UTC
Labels: bug, ami, c-se
