### ISSUE TITLE
More granular RBAC rules

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#1085] opened 2017-06-19 21:48 UTC
[EDIT] this is an umbrella ticket (not actionable). 

Specific rules are discussed in:

* Access to sessions: #1124 
* Access to clusters: #1125

## Problem

At the moment, we have no way to disable access to various parts of a teleport cluster. For example, the following endpoints on the Web UI largely serve different purposes and can possibly be restricted to specific user roles:

1. `/ping` - Check if the server is up.
1. `/webapi/trustedclusters/*` - Trusted Cluster token exchange.
1. `/webapi/[u2f|saml|oidc]/*` - Login.
1. `/webapi/users/*` - New user token validation.
1. `/webapi/ssh/certs/*` - Issuance of SSH certificates.
1. `/webapi/sites/*` - Operate on a cluster.
1. `/webapi/sessions/*` - Sessions.

**Proposed Solution**

ekontsevoy: this should be done as part of more flexible roles as defined in #1092

**Note**

This request comes from a commercial Teleport customer.

**Comment by alex-kovoy** [comment] 2017-06-20 15:54
Is it in addition to user permissions which also should disable certain parts of UI?

**Comment by kontsevoy** [comment] 2017-08-11 05:50
Dupe of #1200

**Closed by kontsevoy** 2017-08-11 05:50 UTC
Labels: feature request
