### ISSUE TITLE
[v.8.0] /docs/pages/database-access/guides/rds.mdx

### ISSUE THREAD

**Issue by dmelo** [gravitational/teleport#9898] opened 2022-01-23 18:04 UTC
## Details
Describe the documentation improvements you wish to see.

For RDS role based auth, on step 3, it looks like its missing the `"rds:DescribeDBClusters"` action, for the policy. Without it, teleport seems to try and get list of clusters, gets permission denied, and don't try to list db instances. 

So, the policy would be:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "rds:DescribeDBInstances",
                "rds:DescribeDBClusters",
                "rds:ModifyDBInstance",
                "iam:GetRolePolicy",
                "iam:PutRolePolicy",
                "iam:DeleteRolePolicy",
                "rds-db:connect"
            ],
            "Resource": "*"
        }
    ]
}
```

It probably also applies for Aurora and IAM user.

### Category

- New Feature
- Improve Existing
- Remove Outdated

**Comment by greedy52** [comment] 2022-01-24 14:40
@dmelo thanks for submitting the issue. 

I believe this is an actual bug described in #9412 where if `rds:DescribeDBClusters` is missing, it will not show db instances. 

The fix is already in for next release, in which permission denied errors from`rds:DescribeDBClusters` will be ignored and we will continue to add db instances.

Adding `rds:DescribeDBClusters` is the current workaround and will not be needed once the fix is released. 

Marking as duplicates of #9412.

**Comment by greedy52** [comment] 2022-01-24 14:54
Duplicate of #9412

**Closed** 2022-01-27 18:11 UTC
Labels: documentation, database-access

**Comment by greedy52** [comment] 2022-01-27 18:12
The fix mentioned above has been merged in `branch/v8` so it will be available in the next minor release.
