### ISSUE TITLE
Ability to specify start date/time for assuming Access Request for delayed TTL start

### ISSUE THREAD

**Issue by deusxanima** [gravitational/teleport#15634] opened 2022-08-18 01:42 UTC
What would you like Teleport to do?
Currently, as soon as you create an access request, the timer of the role's TTL is ticking. It would be useful to be able to set a date/time in the access request. Assuming the roles in the request would then only be possible on the specified date. 

What problem does this solve?
Allows admins to grant access to a role for a maintenance windows on weekends without having to integrate with Jira or PagerDuty if company is not using those products.

If a workaround exists, please include it.
Use Jira/PagerDuty

**Comment by zmb3** [comment] 2022-08-18 13:41
Similar to https://github.com/gravitational/teleport/issues/13277 ?

**Comment by zmb3** [comment] 2022-08-18 13:43
Maybe even a duplicate of https://github.com/gravitational/teleport/issues/14040

**Comment by zmb3** [comment] 2023-09-19 15:59
Closing as dup

**Closed by zmb3** 2023-09-19 15:59 UTC
Labels: feature-request, sales-onboarding, access-requests, c-stz, c-le
