### ISSUE TITLE
shell completion for tsh / tctl

### ISSUE THREAD

**Issue by berler** [gravitational/teleport#7170] opened 2021-06-03 18:33 UTC
### What
It would be nice if tsh commands supported bash completion for hostnames and subcommands. For example with normal ssh hostnames could be tab completed (based on hosts or aliases that are in the ssh config or the hosts file).

### How
On login or periodically tsh would build a list of valid names (for example `tsh ls -f names`) or remember past used hostnames and use this to support auto completion. The tsh executable would expose an autocomplete subcommand (where the args passed in are the args you want to complete) or provide a separate autocomplete executable.

### Why
Hostnames are often long (and often all have a similar suffix). Currently you must type (or more likely paste) the whole hostname. Auto completion for standard tsh subcommands would also avoid cases where users need to repeatedly use `help` to see the possible subcommands.

### Workaround
Write a custom completion script.

**Comment by zmb3** [comment] 2022-04-18 22:55
Duplicate of #3753

**Closed** 2022-09-08 15:09 UTC
Labels: feature-request, ux, good-starter-issue, tsh, tctl, c-na, c-q7j, cli
