### ISSUE TITLE
teleport status should optional show all running sessions

### ISSUE THREAD

**Issue by sgohl** [gravitational/teleport#13038] opened 2022-05-31 18:56 UTC
## What would you like Teleport to do?

On shared systems, users should be able to find out in a simple way, if other users (and which) are logged in right now.

This used to be done with `w` or `last`, but those outputs do not take the original teleport user into account, which in my case is different from the shared destination account (like root) on these machines.

You can view your own session with
```
teleport status
```

I think the teleport service knows all users that are currently logged in, so I'd like to see an optional argument like this
```
teleport status --all
```

## What problem does this solve?

shared system accounts for a group of users where auditing happens on teleport level.

**Comment by zmb3** [comment] 2022-06-13 22:50
Closing as duplicate of #12082.

Please follow along there for updates.

**Closed by zmb3** 2022-06-13 22:50 UTC
Labels: feature-request, server-access
