### ISSUE TITLE
Add support for `windows_desktop_service` to `teleport-kube-agent` Helm chart

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#20190] opened 2023-01-13 15:03 UTC
**What would you like Teleport to do?**

The `teleport-kube-agent` Helm chart should support the configuration and use of `windows_desktop_service` in addition to its current `kubernetes_service`, `db_service` and `app_service` support.

I think this is partially addressed by https://github.com/gravitational/teleport/pull/20129 so this issue is mainly around getting documentation written on how to set it up and use it.

**What problem does this solve?**

Simpler configuration and deployment of Teleport services inside a user's network.

**If a workaround exists, please include it.**

Fork the chart and set things up manually.

**Comment by zmb3** [comment] 2023-01-13 18:56
Duplicate of #15956

**Closed by zmb3** 2023-01-13 18:56 UTC
Labels: documentation, feature-request, helm, unlocks-potential

**Comment by webvictim** [comment] 2023-01-13 19:33
🤦‍♂️
