### ISSUE TITLE
db_service with registering AWS-hosted databases failed with two regions

### ISSUE THREAD

**Issue by jing-teleport** [gravitational/teleport#17826] opened 2022-10-26 01:22 UTC
**Expected behavior:**

db_service with registering AWS-hosted databases failed should be working in all aws regions.

**Current behavior:**

db_service with registering AWS-hosted databases failed with two regions `eu-north-1` & `sa-east-1`

After remove two regions `eu-north-1` & `sa-east-1`, all working ok.

**Bug details:**

**_- Teleport version:_** both 9.3.18 & 11.0.0 failed in my lab, 9.3.3 in customer's environment
**_- Recreation steps:_**
```
db_service:
  enabled: "yes"
  aws:
  - types: ["rds"]
    regions: ["eu-north-1", "sa-east-1", "ap-south-1", "eu-west-3", "eu-west-2", "eu-west-1", "ap-northeast-3", "ap-northeast-2", "ap-northeast-1", "ca-central-1", "ap-southeast-1", "ap-southeast-2", "eu-central-1", "us-east-1", "us-east-2", "us-west-1", "us-west-2"]
    tags:
      "*": "*"
```
**_- Debug logs_**

**9.3.18**

```
Oct 26 01:08:29 ip-10-0-*-* teleport[36940]: 2022-10-26T01:08:29Z DEBU [NODE:PROX] handleDiscovery requests channel. leaseID:2 target:***.net:443 reversetunnel/agent.go:571
Oct 26 01:08:30 ip-10-0-*-* teleport[36940]: 2022-10-26T01:08:30Z ERRO [WATCHER:C] rdsAuroraClustersFetcher(Region=eu-north-1, Labels=map[db:[aurora]]) failed. error:[
Oct 26 01:08:30 ip-10-0-*-* teleport[36940]: ERROR REPORT:
Oct 26 01:08:30 ip-10-0-*-* teleport[36940]: Original Error: *awserr.requestError InvalidParameterValue: Unrecognized engine name: aurora
Oct 26 01:08:30 ip-10-0-*-* teleport[36940]:         status code: 400, request id: f2f42573-3236-48eb-9dff-6f9cff2d358c
Oct 26 01:08:30 ip-10-0-*-* teleport[36940]: Stack Trace:
Oct 26 01:08:30 ip-10-0-*-* teleport[36940]:         /go/src/github.com/gravitational/teleport/lib/srv/db/cloud/watchers/rds.go:180 github.com/gravitational/teleport/lib/srv/db/cloud/watchers.(*rdsAuroraClustersFetcher).Get
Oct 26 01:08:30 ip-10-0-*-* teleport[36940]:         /go/src/github.com/gravitational/teleport/lib/srv/db/cloud/watchers/watcher.go:120 github.com/gravitational/teleport/lib/srv/db/cloud/watchers.(*Watcher).fetchAndSend
Oct 26 01:08:30 ip-10-0-*-* teleport[36940]:         /go/src/github.com/gravitational/teleport/lib/srv/db/cloud/watchers/watcher.go:104 github.com/gravitational/teleport/lib/srv/db/cloud/watchers.(*Watcher).Start
Oct 26 01:08:30 ip-10-0-*-* teleport[36940]:         /opt/go/src/runtime/asm_amd64.s:1581 runtime.goexit
Oct 26 01:08:30 ip-10-0-*-* teleport[36940]: User Message: InvalidParameterValue: Unrecognized engine name: aurora
Oct 26 01:08:30 ip-10-0-*-* teleport[36940]:         status code: 400, request id: f2f42573-3236-48eb-9dff-6f9cff2d358c] watchers/watcher.go:129


Oct 26 01:11:38 ip-10-0-*-* teleport[36970]: 2022-10-26T01:11:38Z DEBU [NODE:PROX] Pool is closing agent. leaseID:2 target:***.net:443 reversetunnel/agentpool.go:241
Oct 26 01:11:39 ip-10-0-*-* teleport[36970]: 2022-10-26T01:11:39Z ERRO [WATCHER:C] rdsAuroraClustersFetcher(Region=sa-east-1, Labels=map[db:[aurora]]) failed. error:[
Oct 26 01:11:39 ip-10-0-*-* teleport[36970]: ERROR REPORT:
Oct 26 01:11:39 ip-10-0-*-* teleport[36970]: Original Error: *awserr.requestError InvalidParameterValue: Unrecognized engine name: aurora
Oct 26 01:11:39 ip-10-0-*-* teleport[36970]:         status code: 400, request id: 2391122e-d1ef-4694-ad2e-58de39ef299e
Oct 26 01:11:39 ip-10-0-*-* teleport[36970]: Stack Trace:
Oct 26 01:11:39 ip-10-0-*-* teleport[36970]:         /go/src/github.com/gravitational/teleport/lib/srv/db/cloud/watchers/rds.go:180 github.com/gravitational/teleport/lib/srv/db/cloud/watchers.(*rdsAuroraClustersFetcher).Get
Oct 26 01:11:39 ip-10-0-*-* teleport[36970]:         /go/src/github.com/gravitational/teleport/lib/srv/db/cloud/watchers/watcher.go:120 github.com/gravitational/teleport/lib/srv/db/cloud/watchers.(*Watcher).fetchAndSend
Oct 26 01:11:39 ip-10-0-*-* teleport[36970]:         /go/src/github.com/gravitational/teleport/lib/srv/db/cloud/watchers/watcher.go:104 github.com/gravitational/teleport/lib/srv/db/cloud/watchers.(*Watcher).Start
Oct 26 01:11:39 ip-10-0-*-* teleport[36970]:         /opt/go/src/runtime/asm_amd64.s:1581 runtime.goexit
Oct 26 01:11:39 ip-10-0-*-* teleport[36970]: User Message: InvalidParameterValue: Unrecognized engine name: aurora
Oct 26 01:11:39 ip-10-0-*-* teleport[36970]:         status code: 400, request id: 2391122e-d1ef-4694-ad2e-58de39ef299e] watchers/watcher.go:129
```

**11.0.0**

```
Oct 26 01:49:48 ip-10-0-*-* teleport[11801]: 2022-10-26T01:49:48Z ERRO [WATCHER:C] rdsAuroraClustersFetcher(Region=eu-north-1, Labels=map[db:[aurora]]) failed. error:[
Oct 26 01:49:48 ip-10-0-*-* teleport[11801]: ERROR REPORT:
Oct 26 01:49:48 ip-10-0-*-* teleport[11801]: Original Error: *awserr.requestError InvalidParameterValue: Unrecognized engine name: aurora
Oct 26 01:49:48 ip-10-0-*-* teleport[11801]:         status code: 400, request id: ab8e2af2-0360-46d4-85cd-34ceb6c934ea
Oct 26 01:49:48 ip-10-0-*-* teleport[11801]: Stack Trace:
Oct 26 01:49:48 ip-10-0-*-* teleport[11801]:         github.com/gravitational/teleport/lib/srv/db/cloud/watchers/rds.go:169 github.com/gravitational/teleport/lib/srv/db/cloud/watchers.(*rdsAuroraClustersFetcher).Get
Oct 26 01:49:48 ip-10-0-*-* teleport[11801]:         github.com/gravitational/teleport/lib/srv/db/cloud/watchers/watcher.go:123 github.com/gravitational/teleport/lib/srv/db/cloud/watchers.(*Watcher).fetchAndSend
Oct 26 01:49:48 ip-10-0-*-* teleport[11801]:         github.com/gravitational/teleport/lib/srv/db/cloud/watchers/watcher.go:107 github.com/gravitational/teleport/lib/srv/db/cloud/watchers.(*Watcher).Start
Oct 26 01:49:48 ip-10-0-*-* teleport[11801]:         runtime/asm_amd64.s:1594 runtime.goexit
Oct 26 01:49:48 ip-10-0-*-* teleport[11801]: User Message: InvalidParameterValue: Unrecognized engine name: aurora
Oct 26 01:49:48 ip-10-0-*-* teleport[11801]:         status code: 400, request id: ab8e2af2-0360-46d4-85cd-34ceb6c934ea] watchers/watcher.go:134
```

**Comment by zmb3** [comment] 2022-10-26 11:56
This is a duplicate of #17533

**Closed by zmb3** 2022-10-26 11:56 UTC
Labels: bug
