### ISSUE TITLE
Bash/ZSH Shell Completion

### ISSUE THREAD

**Issue by anilanar** [gravitational/teleport#38965] opened 2024-03-05 16:34 UTC
### Feature Request

Add bash-completions for nodes/clusters. Example: `tsh ssh <Tab>` should work similar to how competions for `ssh` (OpenSSH) works. 

Considering [the original issue](https://github.com/gravitational/teleport/issues/3753) was closed without actually resolving it, and considering closed issues have no priority, I felt obliged to create an exact copy of it. Perhaps the original feature request wasn't specific enough that it was closed by implementing completions for commands/subcommands only and then was closed.

### Motivation

With tons configured clusters/nodes it makes switch much easier Original kingpin has that feature: https://github.com/alecthomas/kingpin#bashzsh-shell-completion
### Who's it for?
 
All: OSS User, Pro, Enterprise

**Comment by zmb3** [comment] 2024-03-05 16:52
Duplicate of #30175

**Closed by zmb3** 2024-03-05 16:52 UTC
Labels: feature-request
