### ISSUE TITLE
Modify Trusted Cluster role_map

### ISSUE THREAD

**Issue by bernardjkim** [gravitational/teleport#48330] opened 2024-11-01 23:02 UTC
### Expected behavior:
Teleport Trusted Cluster role mappings should be modifiable multiple times.

### Current behavior:
The Trusted Cluster resource can only be modified once. Additional attempts to modify the resource result in the following error:
```console
$ tctl create --force trusted_cluster.yaml
ERROR: trusted cluster "..." and/or one or more of its cert authorities have been modified, please retry
```

### Bug details:
- Teleport version: 17.0.0-alpha.2
- Recreation steps: Modify the `trusted_cluster` resource and change the `spec.role_map.local` value. Then try to change the value back to what is was before.
- Workaround: Restarting the leaf cluster Teleport service allows me to modify the `trusted_cluster` resource once, again.
- Related Issue: This feature was previously addressed in https://github.com/gravitational/teleport/issues/10568.

**Comment by zmb3** [comment] 2024-11-02 15:44
Duplicate of #48310?

**Comment by bernardjkim** [comment] 2024-11-04 17:23
It sounds like the issues may have the same root cause, but I'm not familiar enough with the implementation yet to say. @hugoShaka what do you think?

**Comment by hugoShaka** [comment] 2024-11-04 17:50
Have you tried re-fretching the resource to get the up-to-date revision ID?

This error happens when the conditional update fails, likely because of the revision ID mismatch. I think this is the expected behaviour for any resource implementing the conditional update via revision ID properly.

The error message might not be actionable enough though. Also, maybe --force should do an unconditional update? It would be less asfe though.

**Comment by hugoShaka** [comment] 2024-11-04 17:53
@espadolini  and @rosstimothy would you expect `tctl create --force` to do an unconditional update? to fetch the last revision ID and try to do an update? To honour the revision ID form the YAML manifest?

**Comment by bernardjkim** [comment] 2024-11-04 18:02
> Have you tried re-fretching the resource to get the up-to-date revision ID?

Ah, I think this was my mistake. Let me double check

**Comment by bernardjkim** [comment] 2024-11-04 19:08
Okay, so I wasn't able to repro this issue on 17.0.0-alpha.2. I was testing this before on a slightly newer dev build that I built: https://github.com/gravitational/teleport/compare/v17.0.0-alpha.2...v17.0.0-dev.bernard.10.

I'll test again when 17.0.0-alpha.3 is released to check if we've introduced a regression since 17.0.0-alpha.2.

**Comment by bernardjkim** [comment] 2024-11-05 18:36
Hey @fspmarshall I think #48009 introduced a regression.

**Comment by bernardjkim** [comment] 2024-11-05 20:09
We did some investigating and suspect that this issue may be due to a preexisting issue causing revisions between the Teleport cache and backend to fall out of sync.

We noticed that this was only an issue when running the Teleport instance on a Linux server while this was not an issue on Mac. We also found that disabling the cache would also fix the issue.

**Closed** 2024-11-05 22:26 UTC
Labels: bug, test-plan-problem, trusted-cluster
