### ISSUE TITLE
GitHub Enterprise support for GitHub OAuth app connector

### ISSUE THREAD

**Issue by inahga** [gravitational/teleport#16617] opened 2022-09-22 01:35 UTC
**What would you like Teleport to do?**
Provide support for GitHub Enterprises instances in the GitHub OAuth app connector. At the moment, [the connector is hard-coded to use github.com](https://github.com/gravitational/teleport/blob/7e036cdf42c7ce5d478e6c0cb4d41edc021c0f5f/lib/auth/github.go#L867).

I'd imagine this would be as simple as having some optional `githubURL` argument in the `github` resource spec. I'd be happy to take a stab at it, if the maintainers are interested.

**What problem does this solve?**

Allows users to use their on-premise GitHub Enterprise server to authenticate to Teleport.

**If a workaround exists, please include it.**

No available workarounds besides patching Teleport to provide support.

**Comment by zmb3** [comment] 2022-10-18 22:57
Closing as duplicate of #6340

**Closed by zmb3** 2022-10-18 22:57 UTC
Labels: feature-request
