### ISSUE TITLE
Capture files copied via scp/sftp in their entirety

### ISSUE THREAD

**Issue by programmerq** [gravitational/teleport#12638] opened 2022-05-13 19:04 UTC
What would you like Teleport to do?

Currently, a file that is copied via scp will generate an audit event, but the contents of that file are not preserved.

For both scp and the upcoming sftp support, it would be nice to have the ability to log the entire file content that was transferred.

What problem does this solve?

Increase audit and forensic capabilities

If a workaround exists, please include it.

none

gz#5147

**Comment by zmb3** [comment] 2022-05-15 13:25
Duplicate of #12560

**Comment by dmsergeevN26** [comment] 2022-05-16 08:31
This is very important for us as we need to log all files that were uploaded/downloaded to/from the machines

**Comment by klizhentas** [comment] 2022-06-01 14:55
We discussed this with a customer and they would be ok if we had an option to disable SFTP in RBAC.

**Comment by webvictim** [comment] 2022-07-18 14:02
In that case, it's related to https://github.com/gravitational/teleport/issues/2981

**Comment by zmb3** [comment] 2022-11-15 21:22
Closing since this is tracked in #12560

**Closed by zmb3** 2022-11-15 21:22 UTC
Labels: feature-request, scp, audit-log, c-nt
