### ISSUE TITLE
executing  commands via SSH on multiple nodes using labels as a selector does not work

### ISSUE THREAD

**Issue by sebschlue** [gravitational/teleport#4237] opened 2020-08-20 14:00 UTC
### Description

**What happened**: Teleport User Manual says:

```
you can still execute commands via SSH on multiple nodes using labels as a selector. This command will update all system packages on machines that run Linux:

$ tsh ssh os=ubuntu apt-get update -y
````
**What you expected to happen**: I expected the command to work as described but it fails when tested on my local test cluster.

**How to reproduce it (as minimally and precisely as possible)**:

### Environment
- Teleport version (use `teleport version`): Teleport v4.3.2 git:v4.3.2-0-gc6d702ad8 go1.13.2
- Tsh version (use `tsh version`): Teleport v4.3.2 git: go1.14.5
- OS (e.g. from `/etc/os-release`): Client: MacOS 10.15.6. Server: Ubuntu 20.04.1 LTS

- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): Local 3-node test-cluster

**Relevant Debug Logs If Applicable**

Freshly installed 3-node-test-cluster with a single test user that has been created via

`tctl users add sschlueter root`

Initial login via

`tsh --proxy=ubuntu-focal-node1 --insecure login`

```
$ tsh status
> Profile URL:  https://ubuntu-focal-node1:3080
  Logged in as: sschlueter
  Cluster:      ubuntu-focal-node1
  Roles:        admin*
  Logins:       root
  Valid until:  2020-08-21 03:54:36 +0200 CEST [valid for 12h0m0s]
  Extensions:   permit-agent-forwarding, permit-port-forwarding, permit-pty
```

```
$ tsh ls
Node Name          Address          Labels                                   
------------------ ---------------- ---------------------------------------- 
ubuntu-focal-node1 10.211.55.4:3022 arch=x86_64, hostname=ubuntu-focal-node1 
                                    os=linux                                 
ubuntu-focal-node2 10.211.55.5:3022 arch=x86_64, hostname=ubuntu-focal-node2 
                                    os=linux                                 
ubuntu-focal-node3 10.211.55.6:3022 arch=x86_64, hostname=ubuntu-focal-node3 
                                    os=linux                                
 ```

Login to single nodes is possible:

```
$ tsh ssh --login=root ubuntu-focal-node1
   exit
$ tsh ssh --login=root ubuntu-focal-node2
   exit
$ tsh ssh --login=root ubuntu-focal-node3
   exit
```

But executing a command on all nodes is not possible:

```
$ tsh ssh --login=root os=linux uptime           
error: access denied to root connecting to 10.211.55.6 on cluster ubuntu-focal-node1
```

Debug log:

```
$ tsh ssh -d --login=root os=linux uptime
INFO [CLIENT]    [KEY AGENT] Connected to the system agent: "/private/tmp/com.apple.launchd.sTOfJCKcdg/Listeners" client/api.go:2201
DEBU [KEYSTORE]  Returning SSH certificate "/Users/sschlueter/.tsh/keys/ubuntu-focal-node1/sschlueter-cert.pub" valid until "2020-08-21 03:54:36 +0200 CEST", TLS certificate "/Users/sschlueter/.tsh/keys/ubuntu-focal-node1/sschlueter-x509.pem" valid until "2020-08-21 01:54:36 +0000 UTC". client/keystore.go:277
INFO [KEYAGENT]  Loading key for "sschlueter" client/keyagent.go:113
INFO [CLIENT]    Connecting proxy=ubuntu-focal-node1:3023 login='root' method=0 client/api.go:1633
DEBU [KEYAGENT]  Validated host ubuntu-focal-node1:3023. client/keyagent.go:285
INFO [CLIENT]    Successful auth with proxy ubuntu-focal-node1:3023 client/api.go:1614
DEBU [CLIENT]    Found clusters: [{"name":"ubuntu-focal-node1","lastconnected":"2020-08-20T15:59:11.519305694+02:00","status":"online"}] client/client.go:107
DEBU [CLIENT]    Found clusters: [{"name":"ubuntu-focal-node1","lastconnected":"2020-08-20T15:59:11.52106049+02:00","status":"online"}] client/client.go:107
DEBU [KEYSTORE]  Returning SSH certificate "/Users/sschlueter/.tsh/keys/ubuntu-focal-node1/sschlueter-cert.pub" valid until "2020-08-21 03:54:36 +0200 CEST", TLS certificate "/Users/sschlueter/.tsh/keys/ubuntu-focal-node1/sschlueter-x509.pem" valid until "2020-08-21 01:54:36 +0000 UTC". client/keystore.go:277
DEBU [CLIENT]    Client  is connecting to auth server on cluster "ubuntu-focal-node1". client/client.go:435
INFO [CLIENT]    Client= connecting to node=10.211.55.6 on cluster ubuntu-focal-node1 client/client.go:539
DEBU [KEYAGENT]  Host validation failed: ssh: principal "10.211.55.6" not in the set of valid principals for given certificate: ["25641627-4504-4a73-b44d-6c0117002ad0.ubuntu-focal-node1" "25641627-4504-4a73-b44d-6c0117002ad0" "ubuntu-focal-node3.ubuntu-focal-node1" "ubuntu-focal-node3" "localhost" "127.0.0.1" "::1"]. client/keyagent.go:282

ERROR REPORT:
Original Error: *trace.AccessDeniedError access denied to root connecting to 10.211.55.6 on cluster ubuntu-focal-node1
Stack Trace:
	/private/tmp/teleport-20200728-78155-1xwdkjz/teleport-4.3.2/src/github.com/gravitational/teleport/lib/client/client.go:631 github.com/gravitational/teleport/lib/client.(*ProxyClient).ConnectToNode
	/private/tmp/teleport-20200728-78155-1xwdkjz/teleport-4.3.2/src/github.com/gravitational/teleport/lib/client/api.go:985 github.com/gravitational/teleport/lib/client.(*TeleportClient).SSH
	/private/tmp/teleport-20200728-78155-1xwdkjz/teleport-4.3.2/src/github.com/gravitational/teleport/tool/tsh/tsh.go:814 main.onSSH.func1
	/private/tmp/teleport-20200728-78155-1xwdkjz/teleport-4.3.2/src/github.com/gravitational/teleport/lib/client/api.go:329 github.com/gravitational/teleport/lib/client.RetryWithRelogin
	/private/tmp/teleport-20200728-78155-1xwdkjz/teleport-4.3.2/src/github.com/gravitational/teleport/tool/tsh/tsh.go:813 main.onSSH
	/private/tmp/teleport-20200728-78155-1xwdkjz/teleport-4.3.2/src/github.com/gravitational/teleport/tool/tsh/tsh.go:356 main.Run
	/private/tmp/teleport-20200728-78155-1xwdkjz/teleport-4.3.2/src/github.com/gravitational/teleport/tool/tsh/tsh.go:189 main.main
	/usr/local/opt/go/libexec/src/runtime/proc.go:212 runtime.main
	/usr/local/opt/go/libexec/src/runtime/asm_amd64.s:1374 runtime.goexit
User Message: access denied to root connecting to 10.211.55.6 on cluster ubuntu-focal-node1
```

**Comment by webvictim** [comment] 2020-08-20 14:13
Thanks for the report.

Duplicate of https://github.com/gravitational/teleport/issues/3709

**Closed by webvictim** 2020-08-20 14:13 UTC
