### ISSUE TITLE
`TestProxyTunnelStrategyAgentMesh` flakiness

### ISSUE THREAD

**Issue by ibeckermayer** [gravitational/teleport#13844] opened 2022-06-24 16:52 UTC
#### Link(s) to logs

- https://console.cloud.google.com/cloud-build/builds/80cc41dc-82a7-44dd-9cfb-f36f2d54fbbc?project=ci-account

#### Relevant snippet

```
    integration_test.go:3185: 
        	Error Trace:	integration_test.go:3185
        	            				proxy_tunnel_strategy_test.go:109
        	Error:      	Condition never satisfied
        	Test:       	TestProxyTunnelStrategyAgentMesh
        	Messages:   	Active tunnel connections did not reach 2 in the expected time frame
```

**Comment by zmb3** [comment] 2022-06-26 16:17
Closing as duplicate of #13631

**Closed by zmb3** 2022-06-26 16:17 UTC
Labels: flaky tests
