### ISSUE TITLE
non-repudiation of shared session activity

### ISSUE THREAD

**Issue by aberoham** [gravitational/teleport#2701] opened 2019-05-06 23:03 UTC
**What happened**: Two end-users with identical RBAC permissions are sharing a shell. One types `rm -rf /` whilst the other is watching in horror. How does a Teleport administrator know which user typed the fatal command?

**What you expected to happen**: The teleport session recording or audit log would uniquely identify input from any connected tty.

**Environment**:
- Teleport version (use `teleport version`): v3.2+

**Comment by zmb3** [comment] 2023-01-19 15:03
Duplicate of #1375

**Closed by zmb3** 2023-01-19 15:03 UTC
