### ISSUE TITLE
tctl nodes add output issues

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#6320] opened 2021-04-05 19:24 UTC
### Description

**What happened**:

The output of `tctl nodes add` gives instructions to run on a node that will not result in the expected connection for the node.

ex output of `tctl nodes add`:
```bash
Run this on the new node to join the cluster:

> teleport start \
   --roles=app \
   --token=tokenvalue \
   --ca-pin=sha256:pinnumber \
   --auth-server=172.1.6.1:3025
```

Specifically:
  - gives the auth server as a machine ip that is often not directly available to a node.  Would expect the public address specified or a method of using the proxy address: port.
  - in a cloud and the roles `db`, `kube` and `app` context does not give the proxy address and port that is required
  - For roles such as `db`, `kube`, and `app` the command would likely do nothing unless a `teleport.yaml` is already configured.  No info given on that.

If a admin wants to add a node with a particular role they run `tctl nodes add 

**What you expected to happen**:

More context is given to the user or the system can provide commands that will work in the Teleport instance environment.

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1.Login via `tsh` to a cloud environment
2.Run `tctl nodes add`
3.`teleport` start command will not work in a cloud env

### Server Details
- Teleport version (run `teleport version`): 6.0.2
- Server OS (e.g. from `/etc/os-release`): ubuntu
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): AWS

**Comment by knisbet** [comment] 2021-11-18 00:03
According to Sasha, this should automatically switch to the reverse tunnel endpoint when public_addr is set in the proxy configuration. So this may be a bug in that implementation.

**Comment by pierrebeaucamp** [comment] 2021-12-15 13:42
I believe this is a duplicate of #5429

**Closed** 2022-03-02 13:20 UTC
Labels: bug, ux, tctl, cloud, blocked
