### ISSUE TITLE
[Enhancement] Add k8s integration to session recording/audit log

### ISSUE THREAD

**Issue by aelkugia** [gravitational/teleport#3342] opened 2020-02-12 00:13 UTC
Customer feedback of extending session recording/audit log to include some k8s integration of seeing the following on users:

- pod user accessed
- what time access occurred
- what namespace
- inside what cluster

**Comment by stevenGravy** [comment] 2020-02-21 16:20
A icon or text label  indicating if a session was ssh or k8s would be helpful.

**Comment by benarent** [comment] 2020-05-12 17:05
This should be addressed by duplicate of https://github.com/gravitational/teleport/issues/3528

**Closed by benarent** 2020-05-12 17:05 UTC
Labels: enhancement
