### ISSUE TITLE
Data race

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#2358] opened 2018-11-12 19:58 UTC
Data race in https://github.com/gravitational/teleport/pull/2357/commits/43943fd5be4b58ea182e7a914e80f7de4ed3cddf.

```
=== RUN   TestSrv
==================
WARNING: DATA RACE
Write at 0x00c000bd56d0 by goroutine 175:
  github.com/gravitational/teleport/lib/services.(*CommandLabelV2).SetResult()
      /gopath/src/github.com/gravitational/teleport/lib/services/server.go:398 +0x43
  github.com/gravitational/teleport/lib/srv/regular.(*Server).updateLabel()
      /gopath/src/github.com/gravitational/teleport/lib/srv/regular/sshserver.go:585 +0x3c3
  github.com/gravitational/teleport/lib/srv/regular.(*Server).periodicUpdateLabel()
      /gopath/src/github.com/gravitational/teleport/lib/srv/regular/sshserver.go:592 +0x94

Previous read at 0x00c000bd56d0 by goroutine 130:
  github.com/gravitational/teleport/lib/services.(*CommandLabelV2).Clone()
      /gopath/src/github.com/gravitational/teleport/lib/services/server.go:392 +0x61
  github.com/gravitational/teleport/lib/srv/regular.(*Server).getCommandLabels()
      /gopath/src/github.com/gravitational/teleport/lib/srv/regular/sshserver.go:608 +0x266
  github.com/gravitational/teleport/lib/srv/regular.(*Server).syncUpdateLabels()
      /gopath/src/github.com/gravitational/teleport/lib/srv/regular/sshserver.go:574 +0x68
  github.com/gravitational/teleport/lib/srv/regular.(*SrvSuite).TestProxyReverseTunnel()
      /gopath/src/github.com/gravitational/teleport/lib/srv/regular/sshserver_test.go:672 +0x32e2
  runtime.call32()
      /opt/go/src/runtime/asm_amd64.s:522 +0x3a
  reflect.Value.Call()
      /opt/go/src/reflect/value.go:308 +0xc0
  github.com/gravitational/teleport/vendor/gopkg.in/check%2ev1.(*suiteRunner).forkTest.func1()
      /gopath/src/github.com/gravitational/teleport/vendor/gopkg.in/check.v1/check.go:763 +0xa08
  github.com/gravitational/teleport/vendor/gopkg.in/check%2ev1.(*suiteRunner).forkCall.func1()
      /gopath/src/github.com/gravitational/teleport/vendor/gopkg.in/check.v1/check.go:657 +0x89

Goroutine 175 (running) created at:
  github.com/gravitational/teleport/lib/srv/regular.(*Server).updateLabels()
      /gopath/src/github.com/gravitational/teleport/lib/srv/regular/sshserver.go:569 +0x17f
  github.com/gravitational/teleport/lib/srv/regular.(*Server).Start()
      /gopath/src/github.com/gravitational/teleport/lib/srv/regular/sshserver.go:208 +0x13e
  github.com/gravitational/teleport/lib/srv/regular.(*SrvSuite).SetUpTest()
      /gopath/src/github.com/gravitational/teleport/lib/srv/regular/sshserver_test.go:167 +0x1c6c
  runtime.call32()
      /opt/go/src/runtime/asm_amd64.s:522 +0x3a
  reflect.Value.Call()
      /opt/go/src/reflect/value.go:308 +0xc0
  github.com/gravitational/teleport/vendor/gopkg.in/check%2ev1.(*suiteRunner).runFixture.func1()
      /gopath/src/github.com/gravitational/teleport/vendor/gopkg.in/check.v1/check.go:712 +0x172
  github.com/gravitational/teleport/vendor/gopkg.in/check%2ev1.(*suiteRunner).forkCall.func1()
      /gopath/src/github.com/gravitational/teleport/vendor/gopkg.in/check.v1/check.go:657 +0x89

Goroutine 130 (running) created at:
  github.com/gravitational/teleport/vendor/gopkg.in/check%2ev1.(*suiteRunner).forkCall()
      /gopath/src/github.com/gravitational/teleport/vendor/gopkg.in/check.v1/check.go:654 +0x44c
  github.com/gravitational/teleport/vendor/gopkg.in/check%2ev1.(*suiteRunner).forkTest()
      /gopath/src/github.com/gravitational/teleport/vendor/gopkg.in/check.v1/check.go:745 +0x126
  github.com/gravitational/teleport/vendor/gopkg.in/check%2ev1.(*suiteRunner).runTest()
      /gopath/src/github.com/gravitational/teleport/vendor/gopkg.in/check.v1/check.go:800 +0x46
  github.com/gravitational/teleport/vendor/gopkg.in/check%2ev1.(*suiteRunner).run()
      /gopath/src/github.com/gravitational/teleport/vendor/gopkg.in/check.v1/check.go:606 +0x243
  github.com/gravitational/teleport/vendor/gopkg.in/check%2ev1.Run()
      /gopath/src/github.com/gravitational/teleport/vendor/gopkg.in/check.v1/run.go:92 +0x5a
  github.com/gravitational/teleport/vendor/gopkg.in/check%2ev1.RunAll()
      /gopath/src/github.com/gravitational/teleport/vendor/gopkg.in/check.v1/run.go:84 +0x129
  github.com/gravitational/teleport/vendor/gopkg.in/check%2ev1.TestingT()
      /gopath/src/github.com/gravitational/teleport/vendor/gopkg.in/check.v1/run.go:72 +0x6ff
  github.com/gravitational/teleport/lib/srv/regular.TestSrv()
      /gopath/src/github.com/gravitational/teleport/lib/srv/regular/sshserver_test.go:54 +0x38
  testing.tRunner()
      /opt/go/src/testing/testing.go:827 +0x162
==================
OK: 19 passed, 1 skipped
--- FAIL: TestSrv (12.24s)
    testing.go:771: race detected during execution of test
```

**Comment by benarent** [comment] 2020-10-06 20:34
Duplicate of #4434

**Comment by awly** [comment] 2020-10-06 20:36
Race no longer detected via `go test`

**Closed by awly** 2020-10-06 20:36 UTC
