### ISSUE TITLE
Enhanced reference for Teleport API objects

### ISSUE THREAD

**Issue by programmerq** [gravitational/teleport#31099] opened 2023-08-28 16:41 UTC
## Applies To

https://github.com/gravitational/teleport/blob/master/docs/pages/reference/resources.mdx

## Details

This reference should include all object types that `tctl` get or create can utilize. The structure information of the objects should be present and help readers develop a working mental model of Teleport's resource API objects.

This reference lists dynamic objects that can be managed via tctl, but some dynamic resources aren't included:

* `app`
* `cap` (alias for `cluster_auth_preferences`)
* `db`
* `token`
* `windows_desktop`
* `login_rules`
* `trusted_cluster`
* `okta_assignments`
* `okta_import_rules`
* `installer`
* `locks`

It would be valuable for other teleport resources that can be viewed via `tctl get` would benefit from documentation too. Here are the object types that fall under that but aren't included:

* `app_server`
* `db_server`
* `node`
* `proxy`
* `auth`
* `kube_cluster` / `kube_clusters`
* `kube_server` / `kube_servers`
* `windows_desktop_service`

## How will we know this is resolved?

Even if this is only auto-generated from the .proto files (similar to the terraform resource API), that would be fantastic.

The goal is to help users doing low-level troubleshooting have a complete reference when working with `tctl` to see the current status of the backend. 

## Related Issues

This request for creating a reference was prompted by the same issue that prompted #31097

**Comment by zmb3** [comment] 2023-08-28 18:31
Closing as a duplicate of #9949 and #16948

**Closed by zmb3** 2023-08-28 18:31 UTC
Labels: documentation
