### ISSUE TITLE
Unexpected character added to SAML auth connector created with Terraform provider

### ISSUE THREAD

**Issue by corkrean** [gravitational/teleport#13171] opened 2022-06-04 00:09 UTC
**Expected behavior:**
The Teleport Terraform provider creates a SAML auth connecter without adding extra characters. 

**Current behavior:**
The Terraform provider adds a random `2` to the entity_descriptor line. e.g.:
`entity_descriptor: |2`

entity_descriptor in the .tf file:
 ```
entity_descriptor = <<EOT
    <?xml version="1.0" encoding="UTF-8"?>
#content of the entity descriptor
EOT
```

**Bug details:**
- Teleport version: 9.3.2
- Terraform version: 1.2.2
- Teleport Terraform Provider Version: 9.30
- Recreation steps
     - Follow [these](https://goteleport.com/docs/setup/reference/terraform-provider/#teleport_saml_connector) instructions from our docs
     - Observe that a "2" is inserted on the entity_descriptor line

**Comment by klizhentas** [comment] 2022-06-07 17:44
to repro:

Follow [these](https://goteleport.com/docs/setup/reference/terraform-provider/#teleport_saml_connector) instructions from our docs

**Comment by marcoandredinis** [comment] 2022-06-08 11:13
I tried to reproduce the scenario but no luck so far
```shell
root@ship:/workspace# terraform version
Terraform v1.2.2
on linux_amd64
+ provider terraform.releases.teleport.dev/gravitational/teleport v9.3.0

root@ship:/workspace# teleport version
Teleport Enterprise v9.3.2 git:teleport-connect-preview-1.0.0.dev.1-308-gfc0b81bdc go1.18.2

root@ship:/workspace# grep -C2 Entity main.tf 
        entity_descriptor = <<EOT
  <?xml version="1.0" encoding="UTF-8"?>
<md:EntityDescriptor xmlns:md="urn:oasis:names:tc:SAML:2.0:metadata" entityID="http://www.okta.com/exk1hqp7cwfwMSmWU5d7">
<md:IDPSSODescriptor WantAuthnRequestsSigned="false" protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol">
<md:KeyDescriptor use="signing">
--
<md:SingleSignOnService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" Location="https://dev-82418781.okta.com/app/dev-82418781_evilmartiansteleportsh_1/exk1hqp7cwfwMSmWU5d7/sso/saml"/>
</md:IDPSSODescriptor>
</md:EntityDescriptor>				
EOT
    }
```
![image](https://user-images.githubusercontent.com/689271/172602740-a62701f3-fd03-481e-9bc6-4c80b2914864.png)


Are you able to always reproduce the error?

I did some tests and the Teleport validates the format of the field, so a random `2` should spit out some error

A bit of a wild guess, but cache has been impacting the provider in weird things
We had some bugs that were fixed here https://github.com/gravitational/teleport-plugins/pull/556
This is yet to be released, but to remove this possibility can you please disable cache or build the provider from current master?

**Comment by marcoandredinis** [comment] 2022-06-21 15:04
Thank you for confirming
Can you please confirm the teleport version you used? Was it also 9.3.6? Are you using Enterprise or OSS?

I'm finding it weird that there's a difference on how the YAML is being displayed
Your example is using `|` to delimit the `xml` but mine was using plain `"` :thinking: 

Can you please share the `.tf` file? Please remove any sensitive info it might have

**Comment by kelcya** [comment] 2022-06-21 17:03
The teleport version is `9.3.4` enterprise. The AMI is `gravitational-teleport-ami-ent-9.3.4`. I was previously using `9.1.1`.

saml connector resource
```
resource "teleport_saml_connector" "okta" {
  metadata = {
    name        = "okta"
    description = "Okta connector"
  }

  spec = {
    attributes_to_roles = [{
        name  = "groups"
        roles = ["editor", "access", "auditor"]
        value = "ac:teleport:admins"
      }
    ]

    acs               = "https://teleport.corp-prod1.cedarinternal.com/v1/webapi/saml/acs"
    entity_descriptor = <<EOT
    <?xml version="1.0" encoding="UTF-8"?>
    <md:EntityDescriptor xmlns:md="urn:oasis:names:tc:SAML:2.0:metadata" entityID="entity_id">
      <md:IDPSSODescriptor WantAuthnRequestsSigned="false" protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol">
          <md:KeyDescriptor use="signing">
            <ds:KeyInfo xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
                <ds:X509Data>
                  #saml_content_here
      </md:IDPSSODescriptor>
    </md:EntityDescriptor>
    EOT
  }
}
```

**Comment by marcoandredinis** [comment] 2022-06-22 15:16
That is a YAML indentation indicator, part of the YAML spec: https://yaml.org/spec/1.2.2/#8111-block-indentation-indicator
It's just a way to store multiline string (xml in this case) with a specific indentation

It shouldn't cause any issue to YAML parsers
Is there something not working because of this? If so, please let me know

If you really want to remove the `2`, please remove the spaces that are indenting the xml
It should look somthing like this:
```tf
resource "teleport_saml_connector" "okta" {
  metadata = {
    name        = "okta"
    description = "Okta connector"
  }

  spec = {
    attributes_to_roles = [{
        name  = "groups"
        roles = ["editor", "access", "auditor"]
        value = "ac:teleport:admins"
      }
    ]

    acs               = "https://teleport.corp-prod1.cedarinternal.com/v1/webapi/saml/acs"
    entity_descriptor = <<EOT
<?xml version="1.0" encoding="UTF-8"?>
<md:EntityDescriptor xmlns:md="urn:oasis:names:tc:SAML:2.0:metadata" entityID="entity_id">
    <md:IDPSSODescriptor WantAuthnRequestsSigned="false" protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol">
        <md:KeyDescriptor use="signing">
        <ds:KeyInfo xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
            <ds:X509Data>
                #saml_content_here
    </md:IDPSSODescriptor>
</md:EntityDescriptor>
EOT
  }
}
```

( Thank you, this was fun to look into :sweat_smile: )

**Comment by kelcya** [comment] 2022-06-22 20:03
No, thank you. Much appreciated. That is exactly it. I am shaking my head right now.

Sorry for the fun trouble that this caused. Learn something new everyday 😄.

Please close this issue. Thank you again.

**Closed** 2022-06-22 21:40 UTC
Labels: bug
