### ISSUE TITLE
log with timestamp

### ISSUE THREAD

**Issue by lsaavedr** [gravitational/teleport#5416] opened 2021-01-27 15:42 UTC
### Feature Request
I want to see timestamp in logs 

### Motivation
In the case of failure it is necessary the timestamp in logs to make a more deep forensic diagnostic

### Who's it for?
OSS User

Thanks <3

**Comment by benarent** [comment] 2021-01-27 17:14
Hi @lsaavedr Thanks for creating the issue. We've already an open issue in our runway milestone. Please track the below ticket. 

Duplicate of https://github.com/gravitational/teleport/issues/2676 

Would you be open to a quick call to learn more about how your OSS rollout is going? Can you email ben@goteleport.com and I'll set something up.

**Closed by benarent** 2021-01-27 17:14 UTC

**Comment by benarent** [comment] 2021-01-27 17:16
Duplicate Issue https://github.com/gravitational/teleport/issues/5416

**Comment by benarent** [comment] 2021-01-27 17:17
Duplicate of #2676

**Comment by lsaavedr** [comment] 2021-01-27 17:21
Thanks and sorry for duplicate issue...
