### ISSUE TITLE
teleport-cluster helm chart test jobs use the default service account

### ISSUE THREAD

**Issue by andrask** [gravitational/teleport#21421] opened 2023-02-07 18:33 UTC
Expected behavior:
All pod should use an application specific service account

Current behavior:
The test job pods use the namespace default service account

Bug details:
- Teleport version: 12.0.1
- Recreation steps: deploy the helm chart
- Debug logs
Extract from the auth-test pod manifest
```
apiVersion: v1
kind: Pod
  name: teleport-cluster-v12-auth-test-mlqb5
  namespace: teleport-cluster-v12
spec:
  serviceAccount: default
  serviceAccountName: default
```

**Comment by zmb3** [comment] 2023-02-07 20:14
See also #21384

**Comment by zmb3** [comment] 2024-01-14 23:34
Closing as duplicate of #21384

**Closed by zmb3** 2024-01-14 23:34 UTC
Labels: bug, helm, c-uh
