### ISSUE TITLE
Using pem file for automated tsh scripts runs into nil dereference

### ISSUE THREAD

**Issue by JoshuaBehrens** [gravitational/teleport#3983] opened 2020-07-05 23:32 UTC
### Description
I try to copy a file via tsh scp from a CI/CD to a node. The pem file has been certified from the proxy.

**What happened**:
I get a nil dereference error.

**What you expected to happen**:
It should copy a the file to the node behind the proxy.

**How to reproduce it (as minimally and precisely as possible)**:
* Setup proxy with proxy recording
* Generate pem file for second user
* Sign pem file at proxy
* Use pem file to do anything

### Environment
- Teleport version: 4.2.9 (tested with the 4.3.0-alpha2 as well)
- Tsh version: 4.2.9 (tested with the 4.3.0-alpha2 as well)
- OS: macos 10.15 and debian 10
- Where are you running Teleport?: Proxy running on a centos vm at hetzner. tsh in a Bitbucket Cloud Pipeline

**Relevant Debug Logs If Applicable**

- `tsh --debug -i my.pem --proxy teleport.example.com scp localfile root@node:remotefile`
```
INFO             Reading identity file: my.pem common/identity.go:44
DEBU [TSH]       Extracted username "user@domain.tld" from the identity file my.pem. tsh/tsh.go:967
INFO [CLIENT]    Connecting proxy=teleport.example.com:3023 login='root' method=0 client/api.go:1603
INFO [CLIENT]    Successful auth with proxy teleport.example.com:3023 client/api.go:1585
DEBU [CLIENT]    Found clusters: [{"name":"mycluster","lastconnected":"2020-07-06T01:11:47.919662751+02:00","status":"online"}] client/client.go:106
INFO [CLIENT]    Client= connecting to node=node on cluster mycluster client/client.go:573
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x485712e]

goroutine 1 [running]:
github.com/gravitational/teleport/lib/client.(*ProxyClient).ConnectToNode(0xc000712400, 0x5003a60, 0xc0003d4cc0, 0xc0002e6db0, 0x9, 0x4e3289b, 0x7, 0xc0002e6ce8, 0x8, 0x7ffeefbffb0c, ...)
	/private/tmp/teleport-20200507-15685-1a7mhlb/teleport-4.2.9/src/github.com/gravitational/teleport/lib/client/client.go:624 +0xe9e
github.com/gravitational/teleport/lib/client.(*TeleportClient).SSH(0xc00073e000, 0x5003a60, 0xc0003d4cc0, 0x0, 0x0, 0x0, 0xc00012e000, 0x0, 0x0)
	/private/tmp/teleport-20200507-15685-1a7mhlb/teleport-4.2.9/src/github.com/gravitational/teleport/lib/client/api.go:953 +0x23d
main.onSSH.func1(0x0, 0x0)
	/private/tmp/teleport-20200507-15685-1a7mhlb/teleport-4.2.9/src/github.com/gravitational/teleport/tool/tsh/tsh.go:787 +0x6c
github.com/gravitational/teleport/lib/client.RetryWithRelogin(0x5003a60, 0xc0003d4cc0, 0xc00073e000, 0xc0007879c8, 0x0, 0x1)
	/private/tmp/teleport-20200507-15685-1a7mhlb/teleport-4.2.9/src/github.com/gravitational/teleport/lib/client/api.go:314 +0x3c
main.onSSH(0xc000313440)
	/private/tmp/teleport-20200507-15685-1a7mhlb/teleport-4.2.9/src/github.com/gravitational/teleport/tool/tsh/tsh.go:786 +0xfa
main.Run(0xc000134010, 0x6, 0x6, 0x0)
	/private/tmp/teleport-20200507-15685-1a7mhlb/teleport-4.2.9/src/github.com/gravitational/teleport/tool/tsh/tsh.go:344 +0x4f29
main.main()
	/private/tmp/teleport-20200507-15685-1a7mhlb/teleport-4.2.9/src/github.com/gravitational/teleport/tool/tsh/tsh.go:185 +0xdd
```

### Debug

I already debugged into it. `proxy.teleportClient.localAgent` at the given line in stacktrace is nil. There are only two occasions when localAgent is set:
```go
	// sometimes we need to use external auth without using local auth
	// methods, e.g. in automation daemons
	if c.SkipLocalAuth {
		if len(c.AuthMethods) == 0 {
			return nil, trace.BadParameter("SkipLocalAuth is true but no AuthMethods provided")
		}
		// if the client was passed an agent in the configuration and skip local auth, use
		// the passed in agent.
		if c.Agent != nil {
			tc.localAgent = &LocalKeyAgent{Agent: c.Agent}
		}
	} else {
		// initialize the local agent (auth agent which uses local SSH keys signed by the CA):
		webProxyHost, _ := tc.WebProxyHostPort()
		tc.localAgent, err = NewLocalAgent(c.KeysDir, webProxyHost, c.Username, c.UseLocalSSHAgent)
		if err != nil {
			return nil, trace.Wrap(err)
		}
		if tc.HostKeyCallback == nil {
			tc.HostKeyCallback = tc.localAgent.CheckHostSignature
		}
	}
```
`c.SkipLocalAuth`is set to true as an identity file is given but `c.Agent` is nil so `tc.localAgent` is not set. I can't debug any further as I don't find the point where c.Agent should've been set in `tsh` the webclient seems to do it but not tsh.

**Comment by webvictim** [comment] 2020-07-06 11:35
This issue is the same thing as #3032 and is fixed in Teleport 4.3.0, which is being released this week.

The root cause is that you're trying to use a principal (`root` here) for which your certificate hasn't been granted permission. You should be able to check what principals you're able to use by running `openssl x509 -in cert-x509.pem -text | grep Subject` - the usernames you can use are in the `L=` or locality section.

**Comment by JoshuaBehrens** [comment] 2020-07-06 14:32
Snap. So my research failed to find this ticket 🙄 on the other hand it is good that we don't have an edge case here that is difficult to find out.

It is fixed in 4.3.0? I debugged in master branch and debian 10 with 4.3.0 alpha 2 fails. I thought I am at latest changes when I was debugging it.

The user on the node I like to be is in the L= sections. The user I am is the CN. So the certificate looks good to me as well.

**Comment by webvictim** [comment] 2020-07-06 14:50
I tried a similar command to yours and it worked fine for me even with a much older version of `tsh`, so it's possible that you've hit some weird edge case. The fix for #3032 is in `v4.3.0-alpha.1` even, so if you're still hitting it when building from `master`, it's likely that this is something different.

Perhaps it's the proxy recording mode which is tripping things up. I'll do a bit of testing when I'm back in the office this week and see if I can reproduce this. @awly was the one who wrote the fix; he may have a little more insight into what's going on here.

**Comment by JoshuaBehrens** [comment] 2020-07-06 14:53
During debugging I flipped `SkipLocalAuth` so I run into the else-branch but I get other things breaking there. So your suggestion is to disable proxy recording? I can try when no-one is using it today.

**Comment by webvictim** [comment] 2020-07-06 14:59
If you want to try using node recording rather than proxy recording it might rule out one possible problem. Can you also provide the output of `teleport version` from your `auth`, `proxy` and `node` instances too, please?

**Comment by JoshuaBehrens** [comment] 2020-07-06 15:02
I can provide these information later on. The targeted node is using teleport. There is a way not to use teleport on a node 😲 ? Now I am curious.

We tend to use proxy recording to have recordings in case a node is down. Well to check why the node could be down 😅

**Comment by JoshuaBehrens** [comment] 2020-07-06 20:59
On proxy (which is also auth): `git:v4.2.9-0-ga4bd6c36`
On target node: `git:v4.2.9-0-ga4bd6c36`

I switched recording from proxy to node and things are working now. I can work with it for now but on the long run I'd like to have proxy recording.

**Comment by webvictim** [comment] 2020-07-07 13:04
That’s interesting, thanks for the information. I’ll try to test proxy recording and see whether I can reproduce the same bug.

**Comment by JoshuaBehrens** [comment] 2020-07-07 13:33
I try to add as much context on request as you need to recreate it.

**Comment by russjones** [comment] 2020-07-21 21:05
Best: 2
Worst: 3

**Comment by JoshuaBehrens** [comment] 2020-07-22 06:37
> Best: 2
> Worst: 3

What does this mean? @russjones

**Comment by webvictim** [comment] 2020-07-22 08:52
@JoshuaBehrens It’s a time estimation for our internal planning.

**Comment by benarent** [comment] 2020-08-17 20:34
@awly Are we Ok to resolve this issue.

**Comment by awly** [comment] 2020-08-17 21:38
Yup!

**Closed by awly** 2020-08-17 21:38 UTC
Labels: c-ib
