### ISSUE TITLE
Google icon update for SSO

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#5356] opened 2021-01-20 14:30 UTC
### Feature Request
The google icon for the SSO login uses the google plus.  A newer icon would present better.

![image](https://user-images.githubusercontent.com/60704961/105188516-fc3ec880-5b01-11eb-8ad1-320c3bd99644.png)
vs
current icons
![image](https://user-images.githubusercontent.com/60704961/105188583-0e206b80-5b02-11eb-9f9b-29256f4bec0c.png)

### Motivation
This icon is not used by Google anymore and could cause confusion. 

### Who's it for?
Pro, Enterprise

**Comment by benarent** [comment] 2021-01-20 16:29
Duplicate of https://github.com/gravitational/teleport/issues/3896

**Comment by benarent** [comment] 2021-01-20 16:33
cc @alexwolfe

**Closed** 2022-12-24 23:15 UTC
Labels: ux, sso
