### ISSUE TITLE
Improve "tctl status" display of CA pins.

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#6032] opened 2021-03-17 01:00 UTC
At the moment `tctl status` shows the old CA pin during two thirds of CA rotation and only the new CA pin for the last third. This makes joining a cluster with a CA pin during rotation extremely difficult.

**Comment by GavinFrazar** [comment] 2022-05-30 06:39
This looks like it's already been solved unless I'm not understanding how to reproduce it @russjones

**Comment by GavinFrazar** [comment] 2022-06-03 20:37
closing this as I believe it's already been resolved

**Closed by GavinFrazar** 2022-06-03 20:37 UTC
Labels: bug, good-starter-issue
