### ISSUE TITLE
(flaky test) panic: Emit called on uninitialized fanout instance

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#18890] opened 2022-11-30 00:16 UTC
https://github.com/gravitational/teleport/actions/runs/3579032041/jobs/6019788533

Some integration proxy test fails with this panic, it's not very clear which one specifically from the logs:

```
fail (in  85.19s): github.com/gravitational/teleport/integration/proxy
```

```
panic: Emit called on uninitialized fanout instance

goroutine 71340 [running]:
github.com/gravitational/teleport/lib/services.(*Fanout).Emit(0xc000289d40, {0xc0027e7b78, 0x1, 0x10?})
	/__w/teleport/teleport/lib/services/fanout.go:152 +0xdf8
github.com/gravitational/teleport/lib/services.(*caCollector).getResourcesAndUpdateCurrent(0xc00224a3c0, {0xa25f1e0, 0xc0024aea40})
	/__w/teleport/teleport/lib/services/watcher.go:1285 +0x5e9
github.com/gravitational/teleport/lib/services.(*resourceWatcher).watch(0xc00224a480)
	/__w/teleport/teleport/lib/services/watcher.go:289 +0x454
github.com/gravitational/teleport/lib/services.(*resourceWatcher).runWatchLoop(0xc00224a480)
	/__w/teleport/teleport/lib/services/watcher.go:211 +0xe5
created by github.com/gravitational/teleport/lib/services.newResourceWatcher
	/__w/teleport/teleport/lib/services/watcher.go:121 +0x58f
FAIL	github.com/gravitational/teleport/integration/proxy	85.185s
```

**Comment by jakule** [comment] 2022-12-21 20:47
Duplicate of https://github.com/gravitational/teleport/issues/19289

**Closed by jakule** 2022-12-21 20:47 UTC
Labels: flaky tests
