### ISSUE TITLE
Teleport should store `kubectl exec -it` interactive session event commands in the event.log

### ISSUE THREAD

**Issue by stmuraka** [gravitational/teleport#3292] opened 2020-01-18 01:31 UTC
**What happened**:
During Kube interactive sessions, Teleport does not store the executed commands as structured events.

**What you expected to happen**:
Similar to Enhanced Session Recording for SSH, we would like to be able to programmatically process the commands executed in the K8 pod.

**How to reproduce it (as minimally and precisely as possible)**:

```
tsh login --proxy MyTeleportProxy
kubectl exec -it <pod> -- bash
<do some stuff>
exit
```

**Environment**:
- Teleport version (use `teleport version`): 4.2.1
- Tsh version (use `tsh version`): 4.1
- OS (e.g. from /etc/os-release): client - macOS; server K8 cluster v1.14.9; Pod/container Ubuntu 18.04.3 LTS

@benarent

**Comment by awly** [comment] 2020-08-18 16:37
Looks like a duplicate of https://github.com/gravitational/teleport/issues/3530, let's track it there.

**Closed by awly** 2020-08-18 16:37 UTC
Labels: audit-log, c-ib, kubernetes
