### ISSUE TITLE
Messages on time differences in tsh client

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#4192] opened 2020-08-12 13:18 UTC
### Description

**What happened**:
If the user's client machine time/date is set to the past you receive messages such as `error: failed to fetch TLS key for <user>` .  The user was logged in with a cert even though it doesn't dispay the `tsh` status.  If the user attempts to logout or use the cert you will get `error: ssh: cert is not yet valid`.  

**What you expected to happen**:

A warning message to check the machine date/time and possibly now allow logging in with a cert into a machine in the past.

**How to reproduce it (as minimally and precisely as possible)**:

Set the local time/date to a day or more in the past.  

### Environment
- Teleport version (use `teleport version`): 4.3.2
- Tsh version (use `tsh version`): 4.3.2
- OS (e.g. from `/etc/os-release`): ubuntu 20

- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): VM on laptop

**Comment by alex-kovoy** [comment] 2021-03-06 19:20
@russjones run into the same thing myself. Took some time to figure out because I did not have access to the server to check the server time. Had to use audit events to find the server time and compare with mine :)

**Comment by zmb3** [comment] 2022-10-17 20:29
Closing as duplicate of #3196

**Closed by zmb3** 2022-10-17 20:29 UTC
Labels: bug, ux, tsh
