### ISSUE TITLE
Intermittent test failure: TestShutdown

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#1688] opened 2018-02-15 21:38 UTC
Saw this fail on the macOS cloud box on 2649324007296c2217e5c0459a04f4198f14c928:

```
----------------------------------------------------------------------
FAIL: integration_test.go:578: IntSuite.TestShutdown

integration_test.go:631:
    retry("echo start \r\n", ".*start.*")
integration_test.go:623:
    c.Fatalf("failed to capture output: %v", pattern)
... Error: failed to capture output: .*start.*


----------------------------------------------------------------------
```

**Comment by kontsevoy** [comment] 2018-04-30 18:44
Dupe of #1778

**Closed by kontsevoy** 2018-04-30 18:44 UTC
