### ISSUE TITLE
Show resource name, label for resource requests

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#13897] opened 2022-06-27 19:28 UTC
Expected behavior:

The node name, labels including the unique node id are included in access requests.

Current behavior:

The requested list only shows the node id.  That does not show the nodename and labels which is how the user originally selected the node to request.

![image](https://user-images.githubusercontent.com/60704961/176019697-b6d2b940-27d9-406a-93a5-60c3fcce656d.png)

Bug details:
- Teleport version: 10 alpha 2
- Recreation steps
   1. Create the Access Request for a Server node
   2. Go to Review Requests to see the list of requests

gz#6316

**Comment by nklaassen** [comment] 2022-06-27 19:42
The access request currently doesn't store hostname and labels of resources, so there are a couple ways to go here.

Option 1:
Query the resource details from the UUID on the frontend.
- This requires extra api calls on the frontend, which isn't so bad, but
- resources can be in a leaf cluster, and potentially in multiple different leaf clusters. In the worst case we would need a ListResourcesRequest for each request resource kind in each leaf cluster. I'm not sure if the frontend is set up to access multiple leaf clusters "simultaneously", this could take a bit of work to get right.

Option 2:
Store labels (and hostname) as metadata in the access request when it's created.
- Storing the labels may already be necessary to implement [label-based RBAC plugin notifications](https://github.com/gravitational/teleport/blob/master/rfd/0059-search-based-access-requests.md#access-requests-rbac-plugin-notification)
- This will require a bunch of extra data to be stored in the access request, but I think it will be okay. Access requests normally expire pretty quickly.

I'm leaning toward option 2 right now.

**Comment by webvictim** [comment] 2022-08-10 20:04
Just pinging this as it's still an issue in 10.1.2:
![Screenshot 2022-08-10 at 15 45 35](https://user-images.githubusercontent.com/897821/184009433-0e98ac09-2c16-40d3-a4aa-a212d828de3e.png)

Search-based access requests are much harder to review without the actual name of the resource being requested at a glance.

**Comment by klizhentas** [comment] 2022-09-14 21:23
I am chatting with @fspmarshall about this and here are some thoughts:

Today we have this behavior:

If I can approve a blanket request for role `foo`. I can safely approve request for a subset of what `foo` requests. Therefore there is no need for additional reviewer RBAC

This change introduces the problem that we have is that if I can review the request for role `foo` I also assume that I can search as `foo` without requesting access.

@fspmarshall  proposal is require reviewer to have the same `search_as` roles to be able to see the details of the resource they are reviewing.

**Comment by fspmarshall** [comment] 2022-09-14 21:35
@klizhentas  To clarify, I'm not necessarily saying that the reviewer needs `seach_as`, but that they might need a reviewer-specific equivalent.  Something that explicitly opts them into being able to view details about the resources that they are reviewing access to if the roles they currently hold don't permit it.  Otherwise we'd have a silent escalation of existing capabilities.

Ex:

```yaml
review_requests:
  roles: [...]
  preview_as: [...]
```

\- or -

```yaml
review_requests:
  roles: [...]
  permit_preview: yes
```

**Comment by nklaassen** [comment] 2022-09-14 21:42
@klizhentas @fspmarshall I am considering a couple alternatives. I think it would be great to have the hostnames and labels stored as metadata in the access request resource so that we can easily display them in list views and so that the client doesn't need to make a bunch of extra API calls.

We cannot trust the client to send correct info with the access request create request, but we could have the proxy which originally handles the request inject it. This could happen at the HTTP endpoint used by the web UI. For `tsh` and `tctl` it's gRPC and the proxy just tunnels the connection which would make this not doable, but we could update these to use the HTTP endpoint or a new gRPC endpoint served by the proxy. The hostnames/labels metadata would have to be optional and would be missing when older tsh/tctl versions are still used.

I am drafting a short RFD listing the alternatives and tradeoffs which I'll post in the next day or 2.

**Comment by klizhentas** [comment] 2022-09-14 22:15
@nklaassen @fspmarshall I like the idea of including information about resources in the access request for a couple of reasons:

* It does not need additional RBAC properties.
* It also solves an interesting problem: It captures the intent of the actual request better. The resource can change it's labels after the request has been made. This change makes sure that access request will be evaluated against the label set **at the time of the request** not at the time of the review.

Imagine there is a node `node` that has label `env: stage`

* T1: User `alice` creates access request at time T1.
* T2: User `bob` fetches the access request for review and sees label set `env: stage` and approves the request.
* T3: Node `node` changes labels to `env: prod`. 
* T4: User `alice` attempts to access the system.

There is also alternative timeline:

* T1: User `alice` creates access request at time T1.
* T2: Node `node` changes labels to `env: prod`.
* T3: User `bob` fetches the access request for review and sees label set `env: prod` and approves the request.
* T4: User `alice` attempts to access the system.

This creates non-deterministic behavior when the same access request can lead to two different outcomes.

This will be solved, if:

* T1: User `alice` creates access request at time T1. Access request captures `env:prod` in the metadata.
* T2: User `bob` fetches the access request for review and sees label set `env: prod` and approves the request no matter what the labels are on the node at any given moment.

**Comment by fspmarshall** [comment] 2022-09-14 22:57
@klizhentas @nklaassen Apologies, I don't think I explained my concern well. We were chatting about other access request stuff and I brought this up as an afterthought because I'd been thinking about it :/

My initial concern wasn't about implementation, but rather about the abstract access-control model.  Lets say I have the following review permissions:

```yaml
review_requests:
  roles: [prod]
```

Prior to the introduction of resource-requests, that block allowed me to see access requests for role `prod`.  It did not allow me to view the *definition* of role `prod`, and this was by design.  Role `prod` might contain sensitive labels (e.g. `customer-name:<some-name>`) that an approver may not be allowed to see.

When we introduced the `search_as_roles` option, it needed to be a new explicit option (rather than an expansion of the capabilities of the `allow.request.roles` field), because having it *did* leak information about the labels and other sensitive information potentially protected by the role to the requesting party.  That was fine, since it was a new config field, and users could decide if their use case was one where the contents of the resource should be visible prior to approval or not.

When we introduced this, we didn't need to add any new reviewer RBAC because approving access to a specific resource ID via a role is a strictly more limited operation than approving the role.  Since resource IDs are random and non-identifying, there is no expansion in the capabilities of the reviewer.

If, on the other hand, we allow reviewers to see preview information about the resource (regardless of implementation), then we now leak potentially private information (such as the aforementioned `customer-id` label).  That's fine, in fact an informed reviewer is better really, but its is an escalation in reviewer capabilities.  Up to now, reviewer permissions have not granted any insight into the inner-workings of the roles, or into the nature of the resources that the role grants access to, other than the role's name (which is explicitly written in the reviewer's own roles).

Regardless of whether labels/names are fetched during load or cached during request creation, I think that we shouldn't be changing the model around what information gets to the reviewer without a corresponding change in RBAC syntax that ensures it is opt-in, rather than a change that happens automatically.

**Comment by klizhentas** [comment] 2022-09-14 23:03
@fspmarshall @nick-at-teleport we can also pursue the following:

* We can allow the reviewer to review access request for specific node ids, if this reviewer has a role in their role set that allows them to view the resources. If that's not true, they won't be able to review the access request.
* Once reviewer sees the access request, they add their review and add the labels that they see in `as-seen` alongside their review. This will lead to extra API call on behalf of user to fetch the resource, but this is OK

**Comment by fspmarshall** [comment] 2022-09-14 23:21
@klizhentas 

> We can allow the reviewer to review access request for specific node ids, if this reviewer has a role in their role set that allows them to view the resources. If that's not true, they won't be able to review the access request.

Preventing reviewers from reviewing requests for resources they themselves cannot see would be a breaking change at this point wouldn't it?  Plus, seems like there might be legitimate use-cases for this (e.g. break glass scenarios where a resource that normally most folks can't see can still be granted access to by a large number of votes).

- Once reviewer sees the access request, they add their review and add the labels that they see in as-seen alongside their review. This will lead to extra API call on behalf of user to fetch the resource, but this is OK

Asserting that your approval is conditional on one or more labels remaining unchanged seems like a cool feature, but I think having it happen automatically would be too brittle (e.g. an `uptime` dynamic label with a high-ish rate would frequently break all resource request approvals if it got asserted automatically).


What about simply loading preview info optimistically, but falling back to only showing ID as is done now?  We could roll that out now, and then roll out RBAC for additional reviewer preview capabilities later on if needed, and label assertions could also be independently rolled out.

**Comment by nklaassen** [comment] 2022-09-14 23:29
@fspmarshall agreed with https://github.com/gravitational/teleport/issues/13897#issuecomment-1247396476

You are right we could do this incrementally, but I think reviewing access requests for resources to which the reviewer does not have access may be so common that falling back to just the ID would not be acceptable for our customers who want to see the details. So we may likely do need `preview_as: [roles]` or `permit_preview: yes` to allow the reviewers to view the resources sooner than later

**Comment by klizhentas** [comment] 2022-09-14 23:34
@fspmarshall we don't need to demand that all labels are unchanged, just the ones that are relevant for the role set used to evaluate them. 

To avoid breaking change, we can pursue `preview_as` then.

**Comment by fspmarshall** [comment] 2022-09-14 23:38
@klizhentas Ah, that makes sense.  Deciding which labels were and weren't involved in an access check and then caching them would be a lot of code change, but I definitely see the appeal.

@nklaassen RE: your original impl comment (https://github.com/gravitational/teleport/issues/13897#issuecomment-1167804902 ) I strongly prefer option 3.  We usually expect the slowest network connection to be between the proxy and the client machine, since most folks' clusters are in fancy cloud networks.  Option 3 feels like a good tradeoff between efficiency and 'sticking with what works' in terms of our existing access-control structure.

**Comment by nklaassen** [comment] 2022-09-14 23:59
@fspmarshall Yep I now plan to go with basically option 3 there:

**Stage 1**:
Modify the current `getAccessRequest` endpoint called by the web UI to attempt to fill in the hostname and labels for any resources included in the request. It will call `ListResources` for each cluster that the requested resources are in. If the reviewer does not have access to the resource, the details will not be included and only the ID will be shown.

**Stage 2**:
Add
```
review_requests:
  preview_as_roles: [...]
```
to the role spec so admins can opt-in to having reviewers be able to see details for requested resources they don't normally have access to

**Comment by klizhentas** [comment] 2022-09-15 01:29
@nklaassen @fspmarshall re: capturing labels, we don't have to implement capturing labels in stages 1 or 2, we can push it back as improvement.

**Comment by zmb3** [comment] 2022-09-30 17:05
@nklaassen can we close this now?

**Comment by nklaassen** [comment] 2022-09-30 17:14
> @nklaassen can we close this now?

@zmb3 currently we only have phase 1 implemented, the reviewer must be able to access the resource in order to see the hostname. We still would like to have phase 2 `preview_as_roles` so reviewers can actually see the hostname without needing SSH access, it's probably pretty common for reviewers not to have access to prod resources which you would use access requests for. We also don't display labels yet.

Not sure if we want to keep this issue open to track those or open new issues

**Comment by zmb3** [comment] 2022-09-30 22:39
Got it - I forgot about phase 2. Fine to keep this one open.

**Closed** 2022-10-19 18:45 UTC
Labels: feature-request, ux, c-ju, access-requests, c-br
