### ISSUE TITLE
On-premise HA backends and session recordings

### ISSUE THREAD

**Issue by hydezhao** [gravitational/teleport#19269] opened 2022-12-12 07:50 UTC
What would you like Teleport to do?
For on-premise HA setup, all session recordings are available on Web UI and tsh, not only a part of it.

What problem does this solve?
Currently, when we setup HA backends in on-premise environments, only a part of session recordings are available, (depending on which auth server the proxy is communicating with). 
The root cause is that only local filesystem storage is supported for audit logs. And proxy uses Auth servers audit log to build the view of session recordings. Since audit logs are separated on different auth backends, on webUI, only a part of session recordings is available at a time. 
CF some discussion of this issue: https://github.com/gravitational/teleport/discussions/19236#discussioncomment-4352746

If a workaround exists, please include it.

**Comment by zmb3** [comment] 2022-12-12 17:46
Duplicate of #12169

**Closed by zmb3** 2022-12-12 17:46 UTC
Labels: feature-request, audit-log
