### ISSUE TITLE
AccessDeniedError error when connecting to node with two Teleport processes running

### ISSUE THREAD

**Issue by jkendzorra** [gravitational/teleport#5156] opened 2020-12-17 12:48 UTC
**What happened**:
Node unreachable; tsh error message:
`User Message: access denied to {user} connecting to {node} on cluster {cluster}`

On the node, there are two Teleport processes running:
```
root       574  0.1  0.4 2685968 73404 ?       Ssl  Mar23 519:39 /usr/local/bin/teleport start --permit-user-env --config=/etc/teleport.yaml --diag-addr=127.0.0.1:3434 --pid-file=/run/teleport/teleport.pid
root     17897  0.1  0.3 2003916 59916 ?       Sl   Sep25 179:35 /usr/local/bin/teleport start --permit-user-env --config=/etc/teleport.yaml --diag-addr=127.0.0.1:3434 --pid-file=/run/teleport/teleport.pid
```
There are lots of lines like this (old process):
```
Dec 17 12:16:49 {node} /usr/local/bin/teleport[574]: WARN [NODE]      Failed to get rotation state: database is closed
Dec 17 12:16:49 {node} /usr/local/bin/teleport[574]: WARN [NODE:BEAT] Heartbeat failed grpc: the client connection is closing.
Dec 17 12:16:50 {node} /usr/local/bin/teleport[574]: INFO [SSH:NODE]  Shutdown: waiting for 1 connections to finish. sshutils/server.go:309
Dec 17 12:16:54 {node} /usr/local/bin/teleport[574]: WARN [NODE]      Failed to get rotation state: database is closed
Dec 17 12:16:54 {node} /usr/local/bin/teleport[574]: WARN [NODE:BEAT] Heartbeat failed grpc: the client connection is closing.
Dec 17 12:16:55 {node} /usr/local/bin/teleport[574]: INFO [PROC]      Waiting for services: [ssh.node ssh.shutdown] to finish. service/signals.go:43
Dec 17 12:16:55 {node} /usr/local/bin/teleport[574]: INFO [PROC]      Waiting for services: [ssh.node ssh.shutdown] to finish. service/signals.go:43
```
The new process appears to be connected fine:
```
Dec 17 12:13:25 {node} /usr/local/bin/teleport[17897]: INFO [PROXY:AGE] Outbound tunnel stats. stats:map[connected:2 connecting:0 disconnected:0] target:{cluster} cluster:{cluster} reversetunnel/agentpool.go:367
Dec 17 12:18:30 {node} /usr/local/bin/teleport[17897]: INFO [PROXY:AGE] Outbound tunnel stats. stats:map[connected:2 connecting:0 disconnected:0] target:{cluster} cluster:{cluster} reversetunnel/agentpool.go:367
Dec 17 12:23:30 {node} /usr/local/bin/teleport[17897]: INFO [PROXY:AGE] Outbound tunnel stats. stats:map[connected:2 connecting:0 disconnected:0] target:{cluster} cluster:{cluster} reversetunnel/agentpool.go:367
Dec 17 12:28:35 {node} /usr/local/bin/teleport[17897]: INFO [PROXY:AGE] Outbound tunnel stats. stats:map[connected:2 connecting:0 disconnected:0] target:{cluster} cluster:{cluster} reversetunnel/agentpool.go:367
```

Upon login attempt, the following log entry is emitted (old PID):
```
Dec 17 12:17:33 {node} /usr/local/bin/teleport[574]: WARN [NODE]      "\nERROR REPORT:\nOriginal Error: *trace.ConnectionProblemError sql: database is closed\nStack Trace:\n\t/gopath/src/github.com/gravitational/teleport/lib/backend/lite/lite.go:888 github.com/gravitational/teleport/lib/backend/lite.convertError\n\t/gopath/src/github.com/gravitational/teleport/lib/backend/lite/lite.go:824 github.com/gravitational/teleport/lib/backend/lite.(*LiteBackend).inTransaction\n\t/gopath/src/github.com/gravitational/teleport/lib/backend/lite/lite.go:626 github.com/gravitational/teleport/lib/backend/lite.(*LiteBackend).GetRange\n\t/gopath/src/github.com/gravitational/teleport/lib/backend/report.go:75 github.com/gravitational/teleport/lib/backend.(*Reporter).GetRange\n\t/gopath/src/github.com/gravitational/teleport/lib/backend/wrap.go:71 github.com/gravitational/teleport/lib/backend.(*Wrapper).GetRange\n\t/gopath/src/github.com/gravitational/teleport/lib/services/local/trust.go:239 github.com/gravitational/teleport/lib/services/local.(*CA).GetCertAuthorities\n\t/gopath/src/github.com/gravitational/teleport/lib/cache/cache.go:557 github.com/gravitational/teleport/lib/cache.(*Cache).GetCertAuthorities\n\t/gopath/src/github.com/gravitational/teleport/lib/srv/authhandlers.go:394 github.com/gravitational/teleport/lib/srv.(*AuthHandlers).authorityForCert\n\t/gopath/src/github.com/gravitational/teleport/lib/srv/authhandlers.go:292 github.com/gravitational/teleport/lib/srv.(*AuthHandlers).IsUserAuthority\n\t/gopath/src/github.com/gravitational/teleport/vendor/golang.org/x/crypto/ssh/certs.go:344 github.com/gravitational/teleport/vendor/golang.org/x/crypto/ssh.(*CertChecker).Authenticate\n\t/gopath/src/github.com/gravitational/teleport/lib/utils/checker.go:52 github.com/gravitational/teleport/lib/utils.(*CertChecker).Authenticate\n\t/gopath/src/github.com/gravitational/teleport/lib/srv/authhandlers.go:187 github.com/gravitational/teleport/lib/srv.(*AuthHandlers).UserKeyAuth\n\t/gopath/src/github.com/gravitational/teleport/vendor/golang.org/x/crypto/ssh/server.go:448 github.com/gravitational/teleport/vendor/golang.org/x/crypto/ssh.(*connection).serverAuthenticate\n\t/gopath/src/github.com/gravitational/teleport/vendor/golang.org/x/crypto/ssh/server.go:251 github.com/gravitational/teleport/vendor/golang.org/x/crypto/ssh.(*connection).serverHandshake\n\t/gopath/src/github.com/gravitational/teleport/vendor/golang.org/x/crypto/ssh/server.go:182 github.com/gravitational/teleport/vendor/golang.org/x/crypto/ssh.NewServerConn\n\t/gopath/src/github.com/gravitational/teleport/lib/sshutils/server.go:407 github.com/gravitational/teleport/lib/sshutils.(*Server).HandleConnection\n\t/gopath/src/github.com/gravitational/teleport/lib/srv/regular/sshserver.go:287 github.com/gravitational/teleport/lib/srv/regular.(*Server).HandleConnection\n\t/gopath/src/github.com/gravitational/teleport/lib/reversetunnel/transport.go:258 github.com/gravitational/teleport/lib/reversetunnel.(*transport).start\n\t/opt/go/src/runtime/asm_amd64.s:1358 runtime.goexit\nUser Message: database is closed\n" fingerprint:ssh-rsa-cert-v01@openssh.com SHA256:{hash} local:$IP:45436 remote:$IP2:50008 user:{user} srv/authhandlers.go:397
Dec 17 12:17:33 {node} /usr/local/bin/teleport[574]: WARN [NODE]      failed login attempt events.EventFields{"error":"ssh: certificate signed by unrecognized authority", "success":false, "user":"user@example.com"} fingerprint:ssh-rsa-cert-v01@openssh.com SHA256:{hash} local:$IP:45436 remote:$IP2:50008 user:{user} srv/authhandlers.go:175
```

`systemctl stop teleport`:
```
Dec 17 12:30:58 {node} systemd[1]: teleport.service: State 'stop-sigterm' timed out. Killing.
Dec 17 12:32:29 {node} systemd[1]: teleport.service: Processes still around after SIGKILL. Ignoring.
Dec 17 12:32:29 {node} /usr/local/bin/teleport[17897]: INFO [PROC:2]    Got signal "terminated", exiting immediately. service/signals.go:87
Dec 17 12:32:29 {node} systemd[1]: Stopped Teleport SSH Node Service.
Dec 17 12:32:29 {node} systemd[1]: teleport.service: Unit entered failed state.
Dec 17 12:32:29 {node} systemd[1]: teleport.service: Failed with result 'timeout'.
```

After a restart of Teleport things are back to normal.

### Environment
- Teleport version (use `teleport version`): node: Teleport v4.3.6 git:v4.3.6-0-gfabee242d go1.13.2 (backend: 4.3.9)
- OS (e.g. from `/etc/os-release`): Ubuntu 16.04.6 LTS

- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): AWS

**Comment by jkendzorra** [comment] 2021-02-11 08:41
This can be reproduced with 5.1.0 as well.

**Comment by russjones** [comment] 2021-03-02 18:37
@jkendzorra Is this something that consistently occur or is it an intermittent issue?

**Comment by jkendzorra** [comment] 2021-03-03 08:19
@russjones this has been happening intermittently.

**Comment by tcsc** [comment] 2021-03-22 23:29
The working theory about what is happening looks like this:

- A node is running teleport as an ssh service. Let's call this Process A.
- A user establishes an ssh session onto the node via Process A
- Process A gets told to reload via a `SIGHUP`, which triggers a graceful shutdown. This causes
  - Process A to spin up a replacement process, which we'll call Process B.
  - Process B to start accepting new sessions
  - Process A to stop accepting new connections,
  - Process A to live on long enough to service the existing SSH session, and will only exit when that SSH session dies.
- It's possible that Process B and (the exiting) Process A and are fighting over the node registration, and some unlucky sessions are being routed to Process A.

**Comment by tcsc** [comment] 2021-03-22 23:35
In v6, this looks like it shouldn't be an issue for reverse-tunnelled connections as they appear to be closed as part of the node shutdown.

**Comment by russjones** [comment] 2021-03-23 03:46
@tcsc You were able to reproduce with 4.3.9 then not anymore on `branch/v6`?

**Comment by tcsc** [comment] 2021-03-23 07:22
@russjones Yeah. I made it happen once with 4.3.9, not at all with 6.0 in various configurations. Do we know how intermittently this happens on site?

I was also thinking that either...
 1. manually killing the ssh connections, or 
 2. reconfiguring the systemd unit to non-gracefully kill the teleport daemon and manage starting the replacement process itself
 
...could be potential workarounds, depending on the use case (those live ssh connections may be too valuable to make this workable, though).

**Comment by russjones** [comment] 2021-03-24 23:12
@tcsc I suspect that 6.0 also has the data race, to reproduce, in `agent.go` bump the following ticker to tick faster on the first process and leave the speed slow on the second process and you should be able to reproduce the behavior.

```go
        // time to ping:
        case <-ticker.C:
            bytes, _ := a.Clock.Now().UTC().MarshalText()
            _, err := hb.SendRequest("ping", false, bytes)
            if err != nil {
                a.log.Error(err)
                return trace.Wrap(err)
            }
            a.log.Debugf("Ping -> %v.", conn.RemoteAddr())
```

**Comment by zmb3** [comment] 2024-01-15 23:57
Closing due to inactivity.

**Closed by zmb3** 2024-01-15 23:57 UTC
Labels: bug, c-da
