### ISSUE TITLE
Terminated node is still present in cluster

### ISSUE THREAD

**Issue by igtsekov** [gravitational/teleport#4406] opened 2020-09-30 11:25 UTC
### Description
**What happened**:
I created a teleport cluster using [this how-to](https://gravitational.com/teleport/docs/aws-terraform-guide/). 
When I terminated one node it was still present in the output of `tctl nodes ls` command and shown in the UI.

**What you expected to happen**:
I expected the node to be removed from the output of `tctl nodes ls` command after it shutdowns.

**How to reproduce it (as minimally and precisely as possible)**:
Create a cluster using [this how-to](https://gravitational.com/teleport/docs/aws-terraform-guide/). Verify that the cluster is up and running. Log in to the auth server and execute `tctl nodes ls`, after that terminate the node. Execute `tctl nodes ls` again or visit the UI.

### Environment
- Teleport version (use `teleport version`): 
```teleport version
Teleport v4.3.5 git:v4.3.5-0-g122349e78 go1.13.2
```
- Tsh version (use `tsh version`):
```
tsh version
Teleport v4.3.5 git:v4.3.5-0-g122349e78 go1.13.2
```
- OS (e.g. from `/etc/os-release`):
```
cat /etc/os-release
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
```
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): `AWS`

**Browser environment**

- Browser Version (for UI-related issues):
- Install tools:
- Others:

**Relevant Debug Logs If Applicable**

- `tsh --debug`
- `teleport --debug`

**Comment by webvictim** [comment] 2020-09-30 14:00
Teleport nodes check in with a heartbeat every minute or so by default. Idle/dead nodes will be removed from the `tctl nodes ls` listing after there have been no heartbeats for around 10-15 minutes.

Did this happen for you?

**Comment by igtsekov** [comment] 2020-09-30 14:06
Yes, it did. Is there a config option for this timeout?

**Comment by luckispac** [comment] 2020-10-01 07:12
We have a similar aws setup with two load-balanced auth servers running in version Teleport Enterprise v4.2.10, in our case the dead node remained for a day or so until we noticed. 
Not sure if this fits 100% here since in our case both auth-server had different nodes (UUID) with the same name (short lived vm) and a restart on both auth servers "flushed" it.

**Comment by russjones** [comment] 2020-10-06 18:01
You can do `tctl rm nodes/uuid` to remove a node once you've shut it down.

Also, can you tell me a little bit more about your use case that you want to node to TTL out even faster.

**Comment by igtsekov** [comment] 2020-10-07 06:37
In our setup, we will have around 500 nodes that are changing constantly. We want to keep the list of nodes up to date because the nodes are accessed very often and it is very annoying to see a list that is not accurate and you might try to access a node that is terminated. The `tctl rm node / uuid` command crossed my mind, but I am not sure if it can be automated.

**Comment by webvictim** [comment] 2020-10-08 14:47
We have an issue for a better display of offline nodes (https://github.com/gravitational/teleport/issues/3657) but it isn't quite what you're asking for.

It isn't currently possible to alter the timeout, or the heartbeat interval. The reason for this decision is that on very big Teleport clusters, more regular heartbeats would generate a lot more traffic, which is undesirable for nodes which connect over the public internet. It could also give rise to a thundering herd problem when clusters are restarted.

It looks like for now there isn't an easy way to achieve what you want, I'm afraid. You could try running `tctl get nodes` every 30-60 seconds and processing the `metadata.expires` data for each node:

```yaml
kind: node
metadata:
  expires: "2020-10-08T14:47:29.352820138Z"
  id: 1602167849354187953
  labels:
    environment: demo
    role: node
  name: e97c8c9d-5ddf-4270-92a0-8e578dc85a01
spec:
  addr: 10.4.0.217:3022
  hostname: gusdemo-root-node-1
  rotation:
    current_id: ""
    last_rotated: "0001-01-01T00:00:00Z"
    schedule:
      standby: "0001-01-01T00:00:00Z"
      update_clients: "0001-01-01T00:00:00Z"
      update_servers: "0001-01-01T00:00:00Z"
    started: "0001-01-01T00:00:00Z"
  version: 4.3.0
version: v2
```

The `metadata.expires` timestamp should usually be about 9-10 minutes in the future, as the timeout is 10 minutes and the heartbeat occurs every minute to update the timestamp. If you see that this timestamp drops to 7-8 minutes in the future, you could reasonably assume that the node has gone offline and run `tctl nodes rm/id` (where id is the value of `metadata.name`). If the node does check in again, it will be readded (but nobody would be able to connect to it until this happens, which is a risk).

This would probably get you to a point where offline nodes could be removed after being offline for 1-2 minutes.

**Comment by igtsekov** [comment] 2020-10-09 06:45
Yes, it isn't what I am asking for but is a good idea and will be very helpful. Thank you for the response. I will test your workaround.

**Comment by mickeypash** [comment] 2021-09-01 13:09
@igtsekov did you end up using this workaround?

**Comment by igtsekov** [comment] 2021-09-03 06:48
This is a very strange issue. In my setup, The node is present in the tsh output (tsh ls) but not present in the database or in the `tctl`. Because of that, I cannot remove it. The `tctl rm node/<node-name>` fails with `ERROR: "/nodes/default/<node-name>" is not found.` So from where the client is getting this information?

**Comment by mickeypash** [comment] 2021-09-04 11:11
Yes that's what have been puzzled about! I've checked DynmoDB, the local sqlite.db cache and there are no nodes listed there. `tctl get nodes` and `tsh ls` do both list the information and when I ran them in debug mode they do make a call to sqlite so it must be there?

**Comment by russjones** [comment] 2021-09-05 14:49
@igtsekov @mickeypash What version of Teleport are you using? We fixed a similar issue in 6.2.11 and 7.1.0.

**Comment by mickeypash** [comment] 2021-09-07 01:09
We are using quite an old version unfortunately 4.4.8!
I think with this information I could look to prioritise the upgrade.

**Comment by igtsekov** [comment] 2021-09-07 08:03
I am using 6.0.2. I plan to update to 6.2.7. I will try to bump it to 6.2.11 to see if this is still happening. After restarting the teleport service the instance was removed automatically. I think that some cache somewhere did not update correctly.
@russjones can you prove us with more information about the fixed issue?

**Comment by zmb3** [comment] 2022-07-24 19:42
Hi all, I'm going to close this as:

1. this is expected behavior
2. we'e provided a workaround (`tctl rm`)
3. we have other related issues for improving the display of offline nodes

**Closed by zmb3** 2022-07-24 19:42 UTC

**Comment by gdubicki** [comment] 2024-03-19 21:35
I would like to ask for reconsidering this issue.

I think that if there is an [easy way to automate joining the Teleport cluster by dynamic cloud Nodes](https://goteleport.com/docs/agents/join-services-to-your-cluster/), then there should also be a similarly easy way to remove a Node.

`tbot` + `tctl rm` aren't easy.

I ended up with such a script for self removal. It may be just 2 commands, but believe me that it wasn't exactly a breeze to come up with them:

```
#!/bin/bash
    
# get the credentials for a bot user to run the next command
tbot start --data-dir=/var/lib/teleport/bot \
   --destination-dir=/opt/machine-id --token=my-bot-token \
   --join-method=gcp --auth-server=my-company.teleport.sh:443 --oneshot
    
# remove the node from the cluster
# (the env var is a workaround for https://github.com/gravitational/teleport/issues/25620)
TELEPORT_CONFIG_FILE="" tctl --auth-server=my-company.teleport.sh:443 --identity=/opt/machine-id/identity \
    rm node/$(cat /var/lib/teleport/host_uuid)
```

**Comment by arianvp** [comment] 2024-03-21 13:12
From what I remember bot users can only have 1 certificate at a time active. So it's not possible to have every instance in your cluster log in to the bot to delete themselves afterwards.  So this script needs to run centrally I think.  You can't have this snippet run on each instance in your cluster

**Comment by george-zubrienko** [comment] 2024-08-05 20:34
Stumbled across this one... in case this helps anyone - I use jq with filters to find the latest node and connect to it:

```
node_id=$(tsh ls -f json | jq '[sort_by(.metadata.id) | reverse | .[] | select(.spec.cloud_metadata.aws.account_id == "..." and .spec.hostname == "my-fixed-hostname")][0] | .metadata.name' | sed "s/\"//g")
```
Any filters that work for your case can be applied - just play with the json a bit

**Comment by Venture200** [comment] 2024-08-23 05:56
@webvictim when it takes 10 15 mins nodes to disappear does it mean that app service linked to the dead node will be there as well for 10 15 mins ? I have a HA setup, when node is dead, I can see app service is also down altho it uses load balancer IP for the app

**Comment by webvictim** [comment] 2024-08-23 11:47
Yes, the `app_service` has the same behaviour where it will take 10-15 minutes to disappear from the cluster.
