### ISSUE TITLE
Machine ID: Support secure joining using Kubernetes Service Account

### ISSUE THREAD

**Issue by timothyb89** [gravitational/teleport#17140] opened 2022-10-06 19:14 UTC
What would you like Teleport to do?

As in https://github.com/gravitational/teleport/issues/17060, Machine ID should support use of Kubernetes as an OIDC provider and allow for bots to authenticate to Teleport using their existing Kubernetes cluster credentials (JWT token).

What problem does this solve?

This allows for reusable tokens, workload validation, and secret-free joining.

If a workaround exists, please include it.

Bots can be joined in Kubernetes today using token / IAM joining, however OIDC joining can massively simplify this process.

**Comment by strideynet** [comment] 2022-10-07 10:32
https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#service-account-issuer-discovery

Kubernetes API server must be accessible by the Teleport Auth Service for this to work, unless we allow them to manually provide the CAs for the Kubernetes Service Tokens. Other option would be deploying a service to the cluster which exposes these certificates as described:

> In many cases, Kubernetes API servers are not available on the public internet, but public endpoints that serve cached responses from the API server can be made available by users or service providers. In these cases, it is possible to override the jwks_uri in the OpenID Provider Configuration so that it points to the public endpoint, rather than the API server's address, by passing the --service-account-jwks-uri flag to the API server. Like the issuer URL, the JWKS URI is required to use the https scheme.

It would be interesting to find out more about the customers use case and if their kube api server can be queried by their Teleport auth service.

**Comment by strideynet** [comment] 2023-01-25 10:49
Closing as dupe of https://github.com/gravitational/teleport/issues/19019

**Closed by strideynet** 2023-01-25 10:49 UTC
Labels: feature-request, c-cs, machine-id
