### ISSUE TITLE
Teleport crashed with nil pointer error when giving '--insecure-no-tls' option without setting 'tunnel_listen_addr'

### ISSUE THREAD

**Issue by computerphilosopher** [gravitational/teleport#24310] opened 2023-04-08 16:08 UTC
### Expected behavior

The program should not crash due to a nil pointer reference error.

### Current behavior

Teleport crashed with nil pointer error when giving '--insecure-no-tls' option without setting 'tunnel_listen_addr' flag. I have attached a config file that reproduces the error.

Bug details:

- Teleport version
  12.1.2

### Recreation steps

Set the `/etc/teleport.yaml` file to the following configuration and run the `teleport start --insecure-no-tls` command.

```yaml
version: v3
teleport:
  data_dir: /var/lib/teleport
  log:
    output: stderr
    severity: INFO
    format:
      output: text
  ca_pin: sha256:xxxxxxxxxxxxxxxxxxxx
  diag_addr: ""
  auth_server: my-auth-server:3025
  auth_token: my-token
auth_service:
  enabled: "no"
  proxy_listener_mode: multiplex
proxy_service:
  enabled: "yes"
  https_keypairs: []
  https_keypairs_reload_interval: 0s
  acme: {}
  public_addr: mine.teleport.com:443
  web_listen_addr: "0.0.0.0:443"
  mysql_listen_addr: "0.0.0.0:3306"
```

### Debug logs

```
2023-04-08T12:49:43Z DEBU [PROC:1]    Service has started. pid:29859.1 service:proxy.reversetunnel.server service/supervisor.go:275
2023-04-08T12:49:43Z INFO [PROXY:SER] Reverse tunnel service 12.1.2:api/v12.1.2-0-gbfd4ff0 is starting on . pid:29859.1 utils/cli.go:286
2023-04-08T12:49:43Z INFO [PROXY:SER] Starting 12.1.2:api/v12.1.2-0-gbfd4ff0 on  using in-memory cache pid:29859.1 service/service.go:3500
2023-04-08T12:49:43Z DEBU [PROC:1]    Broadcasting event. event:ProxyReverseTunnelReady pid:29859.1 service/supervisor.go:383
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x168d464]

goroutine 301 [running]:
github.com/gravitational/teleport/lib/limiter.(*Listener).Addr(0x5fc8f7?)
        <autogenerated>:1 +0x24
github.com/gravitational/teleport/lib/sshutils.(*Server).Addr(0x3acde5cb?)
        github.com/gravitational/teleport/lib/sshutils/server.go:312 +0x92
github.com/gravitational/teleport/lib/sshutils.(*Server).acceptConnections(0xc000179600)
        github.com/gravitational/teleport/lib/sshutils/server.go:409 +0x5b
github.com/gravitational/teleport/lib/sshutils.(*Server).Serve(0xc000090fd0?, {0x760a740?, 0xc001504768?})
        github.com/gravitational/teleport/lib/sshutils/server.go:319 +0x69
created by github.com/gravitational/teleport/lib/reversetunnel.(*server).Start
        github.com/gravitational/teleport/lib/reversetunnel/srv.go:592 +0xa5
jenkins@teleport-pro-proxy:~$ sudo service teleport start
```

### Cause of the bug

The code wrapping the reverse tunnel listener is not validating that the embedded listener is nil. 

https://github.com/gravitational/teleport/blob/40c113b8dad017613c154efaa16997a186eec7fb/lib/limiter/listener.go#L34-L39

The wrapped structure does not implement all the methods of net.Listener and delegates some of them to the embedded member.

https://github.com/gravitational/teleport/blob/40c113b8dad017613c154efaa16997a186eec7fb/lib/limiter/listener.go#L26-L29

Because the structure is not nil, it passes the defense code, but when you try to call a method implemented by the embedded member, you encounter a nil pointer reference.

https://github.com/gravitational/teleport/blob/e667486c31144de1f3180062235c3c0859106e92/lib/sshutils/server.go#L337-L340

### How to fix it

Consider modifying the `NewListener` function to look like this:

```go
func NewListener(ln net.Listener, limiter *ConnectionsLimiter) *Listener {
        if ln == nil || limiter == nil {
            return nil
        }
	return &Listener{
		Listener: ln,
		limiter:  limiter,
	}
}
```

This will make the defense code work properly. I'll make a pull request if my suggestion is accepted.

**Comment by computerphilosopher** [comment] 2023-04-28 09:52
Please review #24526

**Comment by computerphilosopher** [comment] 2023-06-14 02:55
Please review #24526

**Comment by computerphilosopher** [comment] 2023-09-01 15:17
https://github.com/gravitational/teleport/blob/e7afdfcd0d68adb267c72f3b25f195a457f1a34e/lib/limiter/listener.go#L34-L39

There are no nil check still

**Comment by computerphilosopher** [comment] 2023-12-15 01:36
Please review #24526

**Comment by zmb3** [comment] 2024-03-11 02:15
Potential duplicate of #9350

**Closed** 2024-06-21 00:50 UTC
Labels: bug, regression
