### ISSUE TITLE
Sticky shortcut keys in Windows Desktop UI

### ISSUE THREAD

**Issue by harista** [gravitational/teleport#33435] opened 2023-10-13 05:01 UTC
Expected behavior:
In windows desktops, shortcut keys should work as normal and shouldn't start sticky keys

Current behavior:
while working on the windows desktops, if we use any shortcut keys, the first key pressed becomes sticky in the session. Causing the UI to behave strange if we press any other keys. you will have to double stroke this short cut key to release the sticky key.

Bug details:
- Teleport version
14.0.0
- Recreation steps
Connect to windows desktop. press alt+tab to switch between window. rather than applying the short cut key in the server, the window on the workstation will switch. come back to the server and press any letter alone eg: D, it behaves as alt+D. Alt key becomes sticky here.
- Debug logs

**Comment by zmb3** [comment] 2023-10-13 14:15
Duplicate of #24342

**Closed by zmb3** 2023-10-13 14:15 UTC
Labels: bug
