### ISSUE TITLE
Trusted cluster create shows up as `unknown`

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#4507] opened 2020-10-09 21:26 UTC
### Description

**What happened**:

```
{
  "code": "T7000I",
  "ei": 0,
  "event": "trusted_cluster.create",
  "expires": "0001-01-01T00:00:00Z",
  "name": "iot",
  "time": "2020-10-09T21:08:05.116Z",
  "uid": "1eba9b5a-0507-449b-9ec7-26c58babdffa",
  "user": "90d6d3ed-ea26-46a9-a140-cfa3ea123108.teleport-tc-6544465bdc-mbd44"
}
```

![unknown](https://user-images.githubusercontent.com/13717/95632869-693ebe80-0a3b-11eb-894a-de2e2e0d59e8.png)

**Comment by stevenGravy** [comment] 2020-10-10 14:47
duplicate of #4307

**Closed** 2020-10-12 17:50 UTC
Labels: audit-log, ui
