### ISSUE TITLE
Session Viewing

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#924] opened 2017-04-12 00:44 UTC
**Problem**

At the moment, all users can view all other users recorded sessions. We should be able to restrict this by role. For example an admin should be able to view all recorded sessions, a users should (ideally) by only able to view their own recorded sessions or no session at all.

**Comment by tidalf** [comment] 2017-04-12 21:45
ideally the sessions from the group (role) he belongs.

**Comment by klizhentas** [comment] 2017-04-12 21:47
@tidalf sessions are not associated with roles at the moment, only with a namespace, so we need to think about the proper design for this feature. Originally I came up with namespaces to solve this particular problem, need to think how to extend/reuse namespaces for this purpose.

**Comment by kontsevoy** [comment] 2017-08-16 18:46
Dupe of #1200

**Closed by kontsevoy** 2017-08-16 18:46 UTC

**Comment by kontsevoy** [comment] 2017-09-15 17:36
Teleport 2.3 is coming out next week. It has much more granular RBAC rules, and they include session restrictions. While you cannot do read-only sessions just yet, you can turn off session access for groups of people.

**Comment by fasalsh** [comment] 2021-08-09 18:14
Hello,

I have been looking for a role statement to hide Session Recordings and Clusters option for our normal users left side tab, means those options should only available for admin users. Is there any way to achieve this using roles in teleport?

Thanks
