### ISSUE TITLE
Access Request approval date error

### ISSUE THREAD

**Issue by colinedwardwood** [gravitational/teleport#10958] opened 2022-03-08 16:42 UTC
### Description

**What happened**:
After approving an access request via the CLI `tsh request review --approve <request-id>` the detail view in the web UI shows an incorrect approval time specifically "<user-id> approved this request 2021 years ago."

**What you expected to happen**:
I expect the same behaviour as if the request was approved in the WebUI. That is, the WebUI should display some like
"<user-id> approved this request minutes ago."

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Log into WebUI, create access request.
2. Log in via CLI, approve said access request `tsh request review --approve <request-id>`
3. Return to WebUI, assume role
4. Still in WebUI, click "View" on assumed role.
5. On bottom of box, note message next to green check mark that says "<user-id> approved this message 2021 years ago."

### Server Details
- Teleport version (run `teleport version`): 
- Server OS (e.g. from `/etc/os-release`):
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware):
- Additional details:

### Client Details
- Tsh version (`tsh version`): 8.3.1
- Computer OS (e.g. Linux, macOS, Windows): macOS
- Browser version (for UI-related issues): Chrome
- Installed via (e.g. apt, yum, brew, website download):
- Additional details: confirmed by two other SEs

### Debug Logs
Please include or attach debug logs, when appropriate. Obfuscate sensitive information!
- Start Teleport with --debug flag (`teleport --debug`)
- Run tsh with --debug flag (`tsh --debug`)

**Comment by zmb3** [comment] 2022-06-13 14:32
Closing as duplicate of #9863

**Closed by zmb3** 2022-06-13 14:33 UTC
Labels: bug, access-requests
