### ISSUE TITLE
When we tsh request roles, it says cert expired, instead of that re-login action wood be good.

### ISSUE THREAD

**Issue by pnrao1983** [gravitational/teleport#28606] opened 2023-07-03 14:19 UTC
What would you like Teleport to do?

When `tsh request create --roles ...` runs, it says the cert is expired. 

Instead of returning `ERROR: ssh: cert has expired`, it would be good to trigger a re-login for a new cert to be issued.
➜  ~ tsh request create --roles kubernetes-admin
ERROR: ssh: cert has expired

What problem does this solve?

It is a feature request and enhancement. Instead of showing the cert expired it would be nice to show the re-login attempt to get a new cert.

**Comment by zmb3** [comment] 2023-07-03 14:45
cc @Joerger in case this was related to some of the tsh relogin changes you made recently.

**Comment by Joerger** [comment] 2023-07-06 17:28
> cc @Joerger in case this was related to some of the tsh relogin changes you made recently.

This isn't related, `tsh request` just does not trigger the relogin flow currently.

**Comment by zmb3** [comment] 2024-07-21 21:31
Duplicate of #13940

**Closed by zmb3** 2024-07-21 21:31 UTC
Labels: feature-request, good-starter-issue, tsh, access-requests, c-uh
