### ISSUE TITLE
Allow IdP initiated logins

### ISSUE THREAD

**Issue by jon-can** [gravitational/teleport#3899] opened 2020-06-24 22:20 UTC
### Feature Request
Teleport does not support SAML identity provider initiated logins. We would like to be able to initiate Teleport logins from Okta rather than the Teleport Web UI or CLI.

### Who's it for?
Pro

**Comment by benarent** [comment] 2020-06-24 22:22
Duplicate of #2967

**Closed** 2020-06-24 22:22 UTC
Labels: feature-request, sales-onboarding
