### ISSUE TITLE
Add Two-Factor Auth Codes to Auth Setup

### ISSUE THREAD

**Issue by binaryn3xus** [gravitational/teleport#34154] opened 2023-11-02 16:20 UTC
What would you like Teleport to do?
I would like if there was a way to view the Two Factor Auth code when setting up a new Two Factor method.

What problem does this solve?
Sometimes it is easier to copy a code than to scan a QA code for things like Bitwarden in the browser.

If a workaround exists, please include it.
Its possible to scan the QR code and then collect the key out of the URI data but that is a lot of extra steps.

Here is maybe an example of something you can do....

Provide an accordion element that hides away the secret key and allow the user to expand to copy the code.

![image](https://github.com/gravitational/teleport/assets/1706923/1c7d79f0-fae0-432b-89cd-6e73e7c79ded)

**Comment by zmb3** [comment] 2023-11-02 18:59
This is a duplicate of #2385 and is not something we're planning on investing in.

TOTP is the least secure (most phishable) MFA factor, and we're hoping to remove it entirely (in favor of more secure alternatives like webauthn or passkeys) rather than further invest in it.

**Closed by zmb3** 2023-11-02 18:59 UTC
Labels: feature-request

**Comment by binaryn3xus** [comment] 2023-11-02 19:02
I understand. Thanks for taking the time to explain why.
