### ISSUE TITLE
Log when someone views session recordings

### ISSUE THREAD

**Issue by jon-can** [gravitational/teleport#5511] opened 2021-02-08 18:18 UTC
### Feature Request
In the audit logs we would like to see if anyone has gone through and watched any session recordings.

### Motivation
Session recordings can contain sensitive information so we would like to track who is viewing the recordings.

### Who's it for?
OSS User

**Comment by zmb3** [comment] 2022-07-24 20:10
Closing as duplicate of #13880, which is being worked on now.

**Closed by zmb3** 2022-07-24 20:10 UTC
Labels: ux
