### ISSUE TITLE
The list of dynamic resources in the documentation is incomplete

### ISSUE THREAD

**Issue by mdwn** [gravitational/teleport#17272] opened 2022-10-11 15:04 UTC
## Applies To

https://goteleport.com/docs/reference/resources/

## Details

There are other dynamic resources that should be documented here.

The full list of dynamic resources can be found here: https://github.com/gravitational/teleport/blob/master/tool/tctl/common/resource_command.go#L94

**Comment by zmb3** [comment] 2022-10-11 15:17
Duplicate of https://github.com/gravitational/teleport/issues/9949

**Closed by zmb3** 2022-10-11 15:17 UTC
Labels: documentation
