### ISSUE TITLE
Moderated Session role configuration ignores resource labels

### ISSUE THREAD

**Issue by philip-teleport** [gravitational/teleport#40841] opened 2024-04-23 18:03 UTC
Expected behavior:

When implementing Moderated Sessions, the `require_session_join` policy should only be applied only to matching resources (defined by labels) within the role that the `require_session_join` policy is defined in.

Current behavior:

When implementing Moderated Sessions, the `require_session_join` policy is applied across all roles assigned to a user, rather than matching on the labels of the role it’s defined in. So when trying to enforce moderation on servers with label `env: prod` , moderation is also enforced on servers with label `env: dev`. Moderated Sessions cannot be selectively enforced.

The  Moderated Sessions [guide](https://goteleport.com/docs/access-controls/guides/moderated-sessions/) states that a user assigned the role "won't be able to start any sessions on matching resources until the policy requirements are fulfilled".

Resource rules and policies are not merged across roles and are bound by the role and only role `options` exhibit "multi-role behaviour" as defined [here](https://goteleport.com/docs/access-controls/reference/#role-options).

Bug details:
- Teleport version: v15.2.2
- Recreation steps: Follow the Moderated Sessions [doc](https://goteleport.com/docs/access-controls/guides/moderated-sessions/)
- Debug logs: N/A

**Comment by zmb3** [comment] 2024-04-23 23:29
This is a duplicate of #16794.

**Closed by zmb3** 2024-04-23 23:29 UTC
Labels: bug, moderated-sessions
