### ISSUE TITLE
Ability to manage recordings

### ISSUE THREAD

**Issue by michaelnowin** [gravitational/teleport#16322] opened 2022-09-12 12:41 UTC
What would you like Teleport to do?
Have had a prospect ask about the ability to manage and delete their own recordings within Teleport's cloud-hosted option

What problem does this solve?
Allows customers to have more control over their recording data and ensure that no data is being shared incorrectly 

If a workaround exists, please include it.
unaware of one today. Believe this is also another request here: https://github.com/gravitational/teleport/issues/10888

**Comment by zmb3** [comment] 2022-12-21 19:31
Duplicate of #10888

**Closed by zmb3** 2022-12-21 19:31 UTC
Labels: feature-request, cloud, time-to-value, c-g2
