### ISSUE TITLE
Create a guide to using Application Access with the Vault CLI

### ISSUE THREAD

**Issue by ptgott** [gravitational/teleport#10195] opened 2022-02-07 16:32 UTC
## Details
Start with this discussion forum comment: https://github.com/gravitational/teleport/discussions/6869

### Category
- Improve Existing

**Comment by stevenGravy** [comment] 2022-02-18 12:23
Good to investigate if there is a method of using our JWT or header values with vault as a method to authenticate a user.  That would be a great useful feature.

**Comment by zmb3** [comment] 2022-02-22 19:49
This looks like a duplicate of #6870

**Closed** 2022-02-22 19:53 UTC
Labels: documentation, application-access, docs-new
