### ISSUE TITLE
TLS Routing support with Teleport Proxy behind ALB

### ISSUE THREAD

**Issue by smallinsky** [gravitational/teleport#14369] opened 2022-07-12 12:26 UTC
## What
Teleport TLS Routing should work even if Teleport proxy is behind ALB and TLS connection is terminated by ALB. 
Currently, when this happens TLS routing information is lost and TLS connection received by teleport proxy ALPN Listener doesn't contain any routing information. 

Investigate possible solutions when the proxy client in case of enabled TLS Routing  wraps the TLS connection with an additional HTTP layer (WebSocket/custom connection upgrade) allowing to establish TLS connection directly to the Teleport ALPN server without TLS termination on the ALB side:

Current behavior:
```
+-----+                       +-----+                +-----------------+
| tsh |                       | ALB |                | Teleport_Proxy  |
+-----+                       +-----+                +-----------------+
   |                             |                            |
   | TLS ALPN: teleport-mysql    |                            |
   |---------------------------->|                            |
   |                             | ------------------\        |
   |                             |-| TLS Termination |        |
   |                             | |-----------------|        |
   |                             |                            |
   |                             | TLS without ALPN           |
   |                             |--------------------------->|
   |                             |                            |
````
Proposed solution: 
```
+-----+                            +-----+                            +-----------------+
| tsh |                            | ALB |                            | Teleport_Proxy  |
+-----+                            +-----+                            +-----------------+
   |                                  |                                        |
   | HTTP  GET Connection: Upgrade    |                                        |
   |--------------------------------->|                                        |
   |                                  | ------------------\                    |
   |                                  |-| TLS Termination |                    |
   |                                  | |-----------------|                    |
   |                                  |                                        |
   |                                  | HTTP GET Connection: Upgrade           |
   |                                  |--------------------------------------->|
   |                                  |                                        |
   |                                  |                                HTTP OK |
   |                                  |<---------------------------------------|
   |                                  |                                        |
   |                          HTTP OK |                                        |
   |<---------------------------------|                                        |
   |                                  |                                        |
   | TLS ALPN: teleport-mysql         |                                        |
   |-------------------------------------------------------------------------->|
   |                                  |                                        |
   ```
 

gz#6066

gz#5853

**Comment by zmb3** [comment] 2022-07-12 15:33
Is this a duplicate of #14176?

**Comment by smallinsky** [comment] 2022-09-14 11:39
@espadolini  Yes the connection upgrade logic is triggered only if ALB termination is detected. https://github.com/gravitational/teleport/pull/15669/files#diff-05d62f63ee2e81b18005d75b7238a44cdc02e4ad2869300a845bf1702cc39754R47

**Comment by zmb3** [comment] 2022-09-30 20:33
Closing as this is a duplicate of an issue we just resolved.

**Closed by zmb3** 2022-09-30 20:33 UTC
Labels: feature-request, aws, c-lu, tls-routing

**Comment by pecigonzalo** [comment] 2022-09-30 21:15
@zmb3 could you link it which one?

**Comment by zmb3** [comment] 2022-09-30 22:35
It's linked above: https://github.com/gravitational/teleport/issues/14369#issuecomment-1181918273

**Comment by pecigonzalo** [comment] 2022-10-01 07:15
That issue says it's closed in favor of this one.

**Comment by zmb3** [comment] 2022-10-01 15:37
Well, in any case, it's fixed with https://github.com/gravitational/teleport/pull/15669
