### ISSUE TITLE
Add IAM join support to the k8s agent chart.

### ISSUE THREAD

**Issue by oshati** [gravitational/teleport#12639] opened 2022-05-13 19:06 UTC
What would you like Teleport to do?
Add IAM join token support to the k8s agent chart.
https://github.com/gravitational/teleport/tree/master/examples/chart/teleport-kube-agent

What problem does this solve?
Customer considers it a nice to have

If a workaround exists, please include it.
https://goteleport.com/docs/setup/guides/joining-nodes-aws-iam/#step-34-configure-your-nodes

**Comment by hugoShaka** [comment] 2022-09-14 19:33
Closing as duplicate of https://github.com/gravitational/teleport/issues/10942

**Closed by hugoShaka** 2022-09-14 19:33 UTC
Labels: feature-request, helm, c-na
