### ISSUE TITLE
Intermittent availability of Recordings and Audit data - Kubernetes HA deployment

### ISSUE THREAD

**Issue by pankajpandey9** [gravitational/teleport#5518] opened 2021-02-09 11:24 UTC
### Description

**What happened**: Session Recordings does not show after refreshing the Teleport UI. However, may come up after refreshing multiple times

**What you expected to happen**: Recording and Audit data should be available everytime the page is refreshed

**How to reproduce it (as minimally and precisely as possible)**: Increase the number of Pods from 1 to 2 for Auth and Proxy

### Environment
- Teleport version (use `teleport version`): quay.io/gravitational/teleport-ent:5.0
- Tsh version (use `tsh version`): 5.0.2
- OS (e.g. from `/etc/os-release`): Kubernetes 1.18.2

- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): 
    Kubernetes on-premise Rancher Cluster 
    3 Worker Nodes
    2 Pods for Auth & 2 for Proxy
    etcd cluster for Auth data
    IBM Cloud Object Store buckets for Recordings
    default values for storage - NFS PVC for both the Proxy pods 
    Using NodePorts with Extenal HAProxy TCP loadbalancer

**Browser environment**: Firefox on RHEL

- Browser Version (for UI-related issues):
- Install tools:
- Others:

**Relevant Debug Logs If Applicable**

- `tsh --debug`
- `teleport --debug`

**Comment by awly** [comment] 2021-02-09 18:44
@pankajpandey9 could you also provide a (redacted) `teleport.yaml` for the auth server?

**Comment by pankajpandey9** [comment] 2021-02-09 19:21
Here is the output from one of the Auth pods.
```
teleport:
  pid_file: /var/run/teleport.pid
  data_dir: /var/lib/teleport
  # storage settings included
  log:
    output: stderr
    severity: INFO
  storage:
    audit_sessions_uri: s3://<IBM COS bucket>
    credentials_path: /root/.aws/credentials
    etcd_max_client_msg_size_bytes: 15728640
    insecure: false
    password_file: /mnt/secrets/etcd-cred.txt
    peers:
    - https://etcd-0.etcd-headless.etcd.svc.cluster.local:2379
    - https://etcd-1.etcd-headless.etcd.svc.cluster.local:2379
    - https://etcd-2.etcd-headless.etcd.svc.cluster.local:2379
    prefix: /teleport-rke/
    tls_ca_file: /var/lib/ca-certs/ca.crt
    tls_cert_file: /var/lib/ca-certs/tls.crt
    tls_key_file: /var/lib/ca-certs/tls.key
    type: etcd
    username: teleport-rke

  connection_limits:
    max_connections: 1000
    max_users: 250
auth_service:
  enabled: true
  license_file: /var/lib/license/license-enterprise.pem
  authentication:
    second_factor: "off"
    type: oidc
  tokens:
    - proxy,node:<some key>
    - trusted_cluster:<some key1>

  public_addr: dev-ocplb.<domain_name>>:3025
  cluster_name: dev-ocplb.<doamin_name>
  listen_addr: 0.0.0.0:3025
  client_idle_timeout: never
  disconnect_expired_cert: false
  keep_alive_interval: 5m
  keep_alive_count_max: 3

ssh_service:
  enabled: false

proxy_service:
  enabled: false
```

**Comment by pankajpandey9** [comment] 2021-02-11 13:48
@awly / Team
Please advise, on the issue. In case this is not the right forum, do let me know where I may ask my question? thanks.

**Comment by awly** [comment] 2021-02-11 19:49
@pankajpandey9 I suspect the culprit is the NFS PVC shared by the proxies.
In your config, the audit event log ends up being stored in `/var/lib/teleport/log` which lands on that PVC.
If this volume is lossy or inconsistent in some way, recordings and audit events get messed up.

Are you able to use [DynamoDB](https://goteleport.com/teleport/docs/admin-guide/#using-dynamodb) or [Google Firestore](https://goteleport.com/teleport/docs/admin-guide/#using-firestore) for events storage?

**Comment by pankajpandey9** [comment] 2021-02-11 20:18
@awly,
we tried with /var/lib/teleport/ also. For testing, we changed it to /var/lib/teleport/log in the helm chart so that both the proxy pods can have different hostIDs. We are using etcd cluster for Auth storage (which you may see in the teleport.yaml). 

However, if there is any such setting where we can send the events to IBM COS bucket then it will be great.

Also as per the Auth pod logs. I believe only one Pod is doing all the heavy lifting and when we refresh the UI:
The Audit Log will have older audit messages (may be from the pod which was created first) and has oidc connecter and role creation logs. However, when the page is refreshed few times the Audit logs will have different entries with session details and the recordings will be available too.. This is happening after every refresh.

Also in etcd storage I, can see all the four pods are registered under the prefix.

**Comment by awly** [comment] 2021-02-12 00:13
Thanks for the info @pankajpandey9.

To elaborate, teleport needs 3 separate data destinations:
- main process storage: local `data_dir`, `etcd`, `dynamodb` or `firestore` (in your case it's etcd)
- session recordings storage: local directory under `data_dir`, `s3` or `gcs` (in your case it's IBM COS pretending to be S3)
- audit events storage: local directory under `data_dir`, `dynamodb` or `firestore` (in your case it lands in `$data_dir/log`)

For audit events we don't support s3-like storage today. Please file a feature request if you'd like to have that as an option in the future!

In your case - when you reload the list of audit events, do you see any common events or are they always two distinct groups?
If there is no overlap, most likely your proxy/auth pods use distinct directories/volumes for audit logs.
If there is some overlap, then it could be a buggy PVC.

**Comment by pankajpandey9** [comment] 2021-02-12 14:34
@awly, Thanks for the info.
Here is what I tried:
So by default, Teleport Helm Chart creates one PVC and mounts only  on the proxy nodes (/var/lib/teleport). So both the proxy’s has same UUID and Auth Pods uses empty dir as storage.

Made changes to the helm chart and used the same PVC for the both Proxy (2 Pods) & Auth (2 Pods)
It seems that the Auth Pod shows that the volume is mounted. However, data is not being written to the PVC (NFS)

Created another PVC (teleport-authstorage) and mounted that to Auth Pods on /var/lib/teleport/log. After that the issue seems to be resolved and the data was consistent (for audit & Recording). However, the event.log file seems to have some problem as it a soft link to one of the Auth Pods logs.

**Questions**:

-  if I use /var/lib/teleport as the mountPath. Then all the hosts have same host_uuid. Not sure if this should be the right way. 
	What should be the right path to mount the PVC?
- Can we reuse the same PVC (teleport-storage) or need to create separate PVC (teleport-authstorage) for Auth Pods? Or anything else as a best practice?
- What should be storage mode ReadWriteMany or ReadWriteOnce will work?
- If there is any updated Helm Chart? Currently we are using teleport-0.0.8.tgz
- Any Plan for using etcd for storing audit events in future?

**Comment by pankajpandey9** [comment] 2021-02-18 08:32
@awly, Please help me with the answers to above questions.

**Comment by awly** [comment] 2021-02-18 22:33
@pankajpandey9 sorry for the delay.

> - if I use /var/lib/teleport as the mountPath. Then all the hosts have same host_uuid. Not sure if this should be the right way.
What should be the right path to mount the PVC?
> - Can we reuse the same PVC (teleport-storage) or need to create separate PVC (teleport-authstorage) for Auth Pods? Or anything else as a best practice?

Reusing the same PVC for separate teleport processes running in parallel sounds problematic.
As you pointed out, they end up reusing the same UUID. There's probably various file access races possible too.
@webvictim is using the same PVC intended?
I'd assume that each standalone teleport pod (proxy or auth) would need its own independent PVC, right?

I think https://github.com/gravitational/teleport/blob/master/examples/chart/teleport/HIGHAVAILABILITY.md explains exactly that: `Running multiple instances of the Authentication Services requires using a high availability storage configuration.`.

> If there is any updated Helm Chart? Currently we are using teleport-0.0.8.tgz

Yes, you can install the latest chart from our repo: https://goteleport.com/teleport/docs/installation/#helm
If you'd like to download it locally first, https://github.com/gravitational/teleport/tree/master/examples/chart/teleport is the source.

> Any Plan for using etcd for storing audit events in future?

Not at this time.
I don't think there's any technical reason preventing this, we just didn't have enough demand.
Filed https://github.com/gravitational/teleport/issues/5626 if you'd like to express your interest and track the progress.

**Comment by webvictim** [comment] 2021-02-18 22:55
> @webvictim is using the same PVC intended?

No, it's not. We also can't support the use of NFS (even via PVC) as an audit log backend for Teleport because it leads to exactly the issues you mentioned before - file locking and contention. The only currently supported highly available audit log backends for Teleport are DynamoDB and Google Firestore.

> I'd assume that each standalone teleport pod (proxy or auth) would need its own independent PVC, right?

Yes, that's correct. Even then, it won't be possible to have a shared audit log between both pods without using an HA audit log backend - DynamoDB or Google Firestore.

**Comment by pankajpandey9** [comment] 2021-02-22 10:21
Thanks @awly , @webvictim  for the detailed explanation.
Want to know what is the future plan for using MongoDB,  Couchbase for config / audit events.
In case, if it is being used already please point me to the document. Thanks

**Comment by awly** [comment] 2021-02-22 19:54
MongoDB and Chouchbase are not currently supported and it's not on the roadmap.
Here are the existing feature requests that you can upvote: [CouchDB](https://github.com/gravitational/teleport/issues/5506), [MongoDB](https://github.com/gravitational/teleport/issues/3395), [DynamoDB-compatible backends](https://github.com/gravitational/teleport/issues/3329).

I do think that we could use an HA storage option for audit events that doesn't force you to use a specific cloud provider and can be self-hosted (unlike DynamoDB and Firestore).
Maybe @klizhentas or @russjones have a thoughts?

**Comment by webvictim** [comment] 2021-02-22 22:18
Yes, the current lack of a self-hostable and provider-agnostic audit event backend is definitely a gap.

**Comment by pankajpandey9** [comment] 2021-02-23 14:36
@awly Also, need to run the pod as a non-root user and couldn't find much documentation regarding the same.. Request you to point me to some documentation. Thanks
This is what I found #2909

**Comment by awly** [comment] 2021-02-24 01:42
@pankajpandey9 I don't have much to add to https://github.com/gravitational/teleport/issues/2909 at this time.

Any teleport instance can run as non-root (except when using `ssh_service`), whether it's in a pod or not.
The only permissions it needs are:
- read access to `teleport.yaml`
- read/write access to `/var/lib/teleport` and any other files specified in `teleport.yaml` (like `kubeconfig_file`)
- opening TCP sockets for the relevant ports

Our official image (quay.io/gravitational/teleport) has everything owned by root, so you'd need to update file permissions mentioned above if you run it with a non-root user.
We don't have any specific documentation on all the steps needed to run as non-root.

I'm going to close this issue, since the root cause is not using HA audit event storage.
For any other questions, please start a [discussion](https://github.com/gravitational/teleport/discussions) or file new issues. You can also follow up on all the issues linked in this page.

**Closed by awly** 2021-02-24 01:42 UTC
