### ISSUE TITLE
Advanced Session Control

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#3526] opened 2020-04-06 19:25 UTC
### Feature request

Implement [Advanced Session Control](https://docs.google.com/document/d/11LnPljqQqlrx8kIRQUxvR6bY5YscaKJohGqeAmfuuco/edit) session management and locking parts.

**Comment by klizhentas** [comment] 2020-04-06 19:27
Covers A10 and A11
Best case: 1mo
Worst case: 2 months

**Comment by klizhentas** [comment] 2020-04-09 15:59
Additional requirement:

If a login/session is blocked, a log entry should be created.

**Comment by benarent** [comment] 2020-05-18 16:25
duplicate of #3360

**Closed** 2022-05-03 15:06 UTC
Labels: blocker
