### ISSUE TITLE
Add pagination support to Audit Events Search API

### ISSUE THREAD

**Issue by alex-kovoy** [gravitational/teleport#5388] opened 2021-01-22 05:21 UTC
Teleport Search Events API is missing a proper pagination support.

```golang
   SearchEvents(from, to time.Time, query string, limit int) ([]events.EventFields, error) 
```

It only lets you specify the startDate and endDate with the limit number. This is not enough because you cannot precisely query for the next page. 

One of the solutions would be to return iterator to the higher level API to allow for efficient pagination as Sasha suggested.

We do not need to support all storage types at once but we can start with dynamodb.

It would be great if this iterator could provide the following methods:

```
total number of records (optional)
fetch next N records
has more
```

**Comment by a-palchikov** [comment] 2021-01-22 09:13
You should not include the total number of records into the base set of  requirements - most of the time it is impossible or complex to compute. `Has more` should be enough as a common denominator. I'm not saying the total count should out of equation though but should be made available optionally.

**Comment by klizhentas** [comment] 2021-01-29 18:28
duplicate of #5435

**Closed by klizhentas** 2021-01-29 18:28 UTC
Labels: feature-request
