### ISSUE TITLE
Flaky test

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#975] opened 2017-05-09 03:03 UTC
## Description

This test is flaky

```
----------------------------------------------------------------------
FAIL: sshserver_test.go:413: SrvSuite.TestExecCommandNoLocalPtyAndRemotePty

sshserver_test.go:443:
    c.Assert(outputContains, Equals, true, Commentf("Output [%# x] does not match expected output: [%# x]", string(stdout), "1\r\n2\r\n\n"))
... obtained bool = false
... expected bool = true
... Output [0x31 0x0d 0x0a 0x32 0x0d 0x0a] does not match expected output: [0x31 0x0d 0x0a 0x32 0x0d 0x0a 0x0a]

OOPS: 20 passed, 2 skipped, 1 FAILED
--- FAIL: TestSrv (12.99s)
```

**Comment by russjones** [comment] 2017-05-09 18:27
@klizhentas I'm thinking lets remove this test for now since I was not able to reproduce it on metal. We can create a ticket to add a test to add coverage for the situation when you have no local PTY and a remote PTY.

**Comment by russjones** [comment] 2017-06-02 18:40
This should be resolved by https://github.com/gravitational/teleport/pull/1037, closing.

**Closed by russjones** 2017-06-02 18:40 UTC
Labels: bug, P0
