### ISSUE TITLE
`TestIntegrations/ReverseTunnelCollapse` flakiness

### ISSUE THREAD

**Issue by ibeckermayer** [gravitational/teleport#20013] opened 2023-01-09 20:07 UTC
#### Link(s) to logs

- https://github.com/gravitational/teleport/actions/runs/3877202944/jobs/6611940853

#### Relevant snippet

```
    integration_test.go:3202: 
        	Error Trace:	/__w/teleport/teleport/integration/integration_test.go:3202
        	            				/__w/teleport/teleport/integration/integration_test.go:106
        	Error:      	Received unexpected error:
        	            	failed to authenticate with proxy 127.0.0.1:40849: ssh: handshake failed: EOF
        	Test:       	TestIntegrations/ReverseTunnelCollapse
```

**Comment by Tener** [comment] 2023-01-11 12:01
```
    integration_test.go:3202: 
        	Error Trace:	/__w/teleport/teleport/integration/integration_test.go:3202
        	            				/__w/teleport/teleport/integration/integration_test.go:106
        	Error:      	Received unexpected error:
        	            	failed to authenticate with proxy 127.0.0.1:42477: ssh: handshake failed: EOF
        	Test:       	TestIntegrations/ReverseTunnelCollapse
```

https://github.com/gravitational/teleport/actions/runs/3892439778/jobs/6643846548

**Comment by Tener** [comment] 2023-01-11 12:04
https://github.com/gravitational/teleport/actions/runs/3892440658/jobs/6643848439

**Comment by ibeckermayer** [comment] 2023-01-11 23:06
https://github.com/gravitational/teleport/actions/runs/3896461349/jobs/6653026440

**Comment by jakule** [comment] 2023-01-12 06:31
Looks like the failure is related to proxy peering:
```
2023-01-10T19:10:51.6823419Z {"caller":"reversetunnel/agentpool.go:269","component":"proxy:agent","error":"Failed to claim proxy: [b176a1cb-630d-430e-9cdf-4bfbaea3df75.local-site b176a1cb-630d-430e-9cdf-4bfbaea3df75 cluster-main-proxy.local-site cluster-main-proxy localhost 127.0.0.1 ::1 remote.kube.proxy.teleport.cluster.local] claimed by another agent","level":"debug","message":"Failed to connect agent.","timestamp":"2023-01-10T19:08:50Z","trace.fields":{"cluster":"local-site"}}
2023-01-10T19:10:51.6823912Z {"caller":"reversetunnel/agentpool.go:450","component":"proxy:agent","level":"debug","message":"Active agent count: 1","timestamp":"2023-01-10T19:08:50Z","trace.fields":{"cluster":"local-site"}}
2023-01-10T19:10:51.6824352Z {"caller":"reversetunnel/agentpool.go:450","component":"proxy:agent","level":"debug","message":"Active agent count: 1","timestamp":"2023-01-10T19:08:50Z","trace.fields":{"cluster":"local-site"}}
```
I think that the root cause is the same as in the https://github.com/gravitational/teleport/blob/39cee50cc977204f04506375a1299be357275a2e/integration/proxy/proxy_tunnel_strategy_test.go#L150-L152

**Comment by ibeckermayer** [comment] 2023-01-12 17:49
https://github.com/gravitational/teleport/actions/runs/3904564810/jobs/6670513093

**Comment by ibeckermayer** [comment] 2023-01-13 20:39
https://github.com/gravitational/teleport/actions/runs/3899133392/jobs/6658521134

**Comment by zmb3** [comment] 2024-01-18 19:13
Closing since there have been no recent reports

**Closed by zmb3** 2024-01-18 19:13 UTC
Labels: flaky tests
