### ISSUE TITLE
Local User Password Requirement Configurability

### ISSUE THREAD

**Issue by Aharic** [gravitational/teleport#10228] opened 2022-02-08 20:50 UTC
### What
Request for ability to define password requirements for local users such as password strength and/or rules. Currently, local users do not allow admins specify password strength or rules? 

### Why
Customer ask for additional local user security hardening

**Comment by stevenGravy** [comment] 2022-02-09 03:44
similar to #1936

**Comment by wadells** [comment] 2022-06-07 17:27
closing as a dupe of https://github.com/gravitational/teleport/issues/1936.  I moved over the `c-af` and `c-qw` labels.

**Closed by wadells** 2022-06-07 17:27 UTC
Labels: feature-request, c-af, c-qw
