### ISSUE TITLE
Enhance "tctl" command to see online and offline servers 

### ISSUE THREAD

**Issue by Erick-Reyes** [gravitational/teleport#23802] opened 2023-03-29 19:18 UTC
What would you like Teleport to do?
Add a flag to the "tctl" command to show both online and offline servers on your cluster. 

What problem does this solve?
Knowing what servers in our inventory are connected to Teleport and what is not. 
e.g. 
A node is offline and wasn't deleted it. We can see that is offline. 

If a workaround exists, please include it.
Currently, we can only see connected nodes by running the: 
- tctl inventory status --connected

**Comment by stevenGravy** [comment] 2023-03-30 18:27
Nodes go offline after their expiration has passed without a heartbeat.  The expiration is retrievable via API or through the `tctl get nodes`.  Here is an example of getting nodes with their expiration from lowest to highest.

```code
tctl get nodes --format=json | jq '. |= sort_by(.metadata.expires)' | jq '.[] | .spec.hostname + ", " +.metadata.expires'
```

Example output:

```bash
"server1, 2023-03-30T18:20:56.145098847Z"
"server5, 2023-03-30T18:21:23.37459712Z"
"server4, 2023-03-30T18:21:25.250057135Z"
"server3, 2023-03-30T18:21:27.892567455Z"
"server2, 2023-03-30T18:21:28.309817686Z"
````

Using this list you could check to see which nodes are likely offline as their expiration is below for instance a 5m threshold.

**Comment by zmb3** [comment] 2023-03-31 00:52
This looks to be similar, if not a duplicate of, the following:

- #3843
- #3657

**Comment by zmb3** [comment] 2023-09-22 23:17
Closing as duplicate.

**Closed by zmb3** 2023-09-22 23:17 UTC
Labels: feature-request, tctl, c-br, to-be-reviewed
