### ISSUE TITLE
`TestProxyTunnelStrategyAgentMesh` flakiness

### ISSUE THREAD

**Issue by nklaassen** [gravitational/teleport#13631] opened 2022-06-17 18:55 UTC
## Failure
saw this fail off branch/v10

### CI Logs
- https://console.cloud.google.com/cloud-build/builds/e6c0fcec-d830-4cae-8512-ce19b7331e35;step=0?project=ci-account
- https://console.cloud.google.com/cloud-build/builds/80cc41dc-82a7-44dd-9cfb-f36f2d54fbbc?project=ci-account
- https://console.cloud.google.com/cloud-build/builds/a3df41b7-98d8-4d8e-b4d0-d53ae38a6740?project=ci-account
- https://console.cloud.google.com/cloud-build/builds/72ebc849-860d-46f1-9580-641372a7bb29?project=ci-account
- https://console.cloud.google.com/cloud-build/builds/81f3d83b-e829-43d3-9f5f-f92e2c897bd1?project=ci-account
- https://console.cloud.google.com/cloud-build/builds/95c9172b-1b23-4892-a56b-b1e626e1111a?project=ci-account
- https://console.cloud.google.com/cloud-build/builds;region=us-west1/fca8334c-03a5-4f5d-bace-3241d2c0a1be?project=ci-account

### Relevant snippet
```
    integration_test.go:3242: 
        	Error Trace:	integration_test.go:3242
        	            				proxy_tunnel_strategy_test.go:109
        	Error:      	Condition never satisfied
        	Test:       	TestProxyTunnelStrategyAgentMesh
        	Messages:   	Active tunnel connections did not reach 2 in the expected time frame
```

**Comment by zmb3** [comment] 2022-06-26 16:20
In addition to the flakiness, the code exercised by this test leaks goroutines.

`makeLoadBalancer` starts a goroutine to accept incoming connections and never closes it.

We probably need to do something like this, but it's more complicated than just this diff:

```diff
// makeLoadBalancer bootsraps a new load balancer for proxy instances.
func (p *proxyTunnelStrategy) makeLoadBalancer(t *testing.T) {
	if p.lb != nil {
		require.Fail(t, "load balancer already initialized")
	}

+	ctx, cancel := context.WithCancel(context.Background())
+	t.Cleanup(cancel)

	lbAddr := utils.MustParseAddr(net.JoinHostPort(Loopback, helpers.NewPortStr()))
-	lb, err := utils.NewLoadBalancer(context.Background(), *lbAddr)
+	lb, err := utils.NewLoadBalancer(ctx, *lbAddr)
	require.NoError(t, err)

	require.NoError(t, lb.Listen())
+	t.Cleanup(func() { lb.Close() })
	go lb.Serve()

	p.lb = lb
}
```

**Comment by zmb3** [comment] 2022-06-26 16:23
Some of the flakiness here is related to the tempdir cleanup problem. That can be fixed by using node-sync recording:

```diff
// makeAuth bootsraps a new teleport auth instance.
func (p *proxyTunnelStrategy) makeAuth(t *testing.T) {
	if p.auth != nil {
		require.Fail(t, "auth already initialized")
	}

	privateKey, publicKey, err := testauthority.New().GenerateKeyPair()
	require.NoError(t, err)

	auth := helpers.NewInstance(helpers.InstanceConfig{
		ClusterName: p.cluster,
		HostID:      uuid.New().String(),
		NodeName:    Loopback,
		Priv:        privateKey,
		Pub:         publicKey,
		Log:         utils.NewLoggerForTests(),
	})

	auth.AddUser(p.username, []string{p.username})

	conf := service.MakeDefaultConfig()
	conf.DataDir = t.TempDir()
	conf.Auth.Enabled = true
	conf.Auth.NetworkingConfig.SetTunnelStrategy(p.strategy)
+	conf.Auth.SessionRecordingConfig.SetMode(types.RecordAtNodeSync)
	conf.Proxy.Enabled = false
	conf.SSH.Enabled = false

	require.NoError(t, auth.CreateEx(t, nil, conf))
	require.NoError(t, auth.Start())

	p.auth = auth
}
```

With this change, we still occasionally see the proxies fail to come up in time, which seems to be the cause of many of our flaky tests.

**Comment by nklaassen** [comment] 2022-07-07 21:02
New failure here: https://console.cloud.google.com/cloud-build/builds;region=us-west1/365fbf4d-9061-4204-9d82-95c88bffb373?project=ci-account

**Closed** 2022-07-14 16:49 UTC
Labels: flaky tests, proxy-peering
