### ISSUE TITLE
Request: Expanded `kubectl exec` session metadata to support better auditing.

### ISSUE THREAD

**Issue by darend** [gravitational/teleport#2332] opened 2018-10-31 17:59 UTC
**What happened**:

When using the Kubernetes integration to exec into pods the session list does not report which namespace/pod the user is accessing it. It should also be possible to monitor the events (dynamodb) in order to proactively report on kubernetes sessions and capture the namespace/pod being accessed.

We should support the full list of flags for `kubectl exec` https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#exec

**What you expected to happen**:

The audit log should include the `namespace`, `container` and `pod` being accessed.

We should support / respect Kubernetes audit policy https://kubernetes.io/docs/tasks/debug-application-cluster/audit/#audit-policy 

**How to reproduce it (as minimally and precisely as possible)**:

Enable K8s integration and run `kubectl exec -it namespace/pod sh`

**Environment**:
- Teleport version (use `teleport version`): 3.0.1
- Tsh version (use `tsh version`): 3.0.1

**Comment by JacobHenner** [comment] 2019-07-23 21:47
Is this still being considered? It'd be very helpful to have k8s metadata stored along with the contents of the exec session.

**Comment by aelkugia** [comment] 2019-10-15 17:35
Hey @benarent  was this completed in 4.1? Expanding recorded sessions for kubectl has also recently came up in the community [here](https://community.gravitational.com/t/question-can-teleport-record-kubectl-commands/399).

**Comment by benarent** [comment] 2019-10-15 18:39
Thank for the ping @aelkugia . This hasn't been worked on as part of 4.1 but I've tagged this issue and we'll keep track of it.

**Comment by stevenGravy** [comment] 2020-03-09 17:54
@benarent  there is interest in making this available in a GKE setting with the  namespace, user, pod and container information.

**Comment by klizhentas** [comment] 2020-04-06 19:37
Closed as a dupe of https://github.com/gravitational/teleport/issues/3528

**Closed by klizhentas** 2020-04-06 19:37 UTC
Labels: R1, feature request, kubernetes
