### ISSUE TITLE
Build a trace collection tool

### ISSUE THREAD

**Issue by hugoShaka** [gravitational/teleport#39106] opened 2024-03-07 23:10 UTC
### What would you like Teleport to do?

As a support engineer I want to have all the relevant information to troubleshoot a customer setup, as fast as possible.

### What problem does this solve?

Support time. It takes several back and forth for the customer to send logs, values, kubernetes objects. Users often don't send the log entirely in their support request, so we end up with not enough context. This is a tedious task which can be automated to both gain hours of support, and answer customer support requests faster and more accuratelty/

### Example of traces to collect

- helm
  - get helm releases
  - get values
  - get chart manifests (the whole helm zip)
  - get teleport.yaml for auth and proxy
  - get deployments
  - get replicasets
  - get pods
  - get logs for each pod
  - scrape prometheus metrics?
- tctl / teleport auth
  - status
  - count roles
  - list locks
  - get configuration resources (cap, cnc, ...)
- helm intrusive
  - patch to add debug flag
  - measure pprof
- operator
  - get CRs
- teleport proxy
  - hit discovery endpoint
  - get proxy certs
  - lookup discovered endpoint certs

**Comment by zmb3** [comment] 2024-03-08 05:29
Duplicate of #4224?

(See also #14030)

**Closed** 2024-03-08 14:24 UTC
Labels: feature-request
