### ISSUE TITLE
display is corrupted when the browser magnification is changed

### ISSUE THREAD

**Issue by m-yonezawa** [gravitational/teleport#31557] opened 2023-09-07 07:58 UTC
Expected behavior:

Changing the browser magnification while manipulating a file in vim works fine.
I have confirmed that it works correctly with the following Teleport versions.
* 10.2.1
* 11.3.22
* 12.4.15

Current behavior:

If I change the browser magnification while manipulating a file in vim, the display is corrupted.

Bug details:
- Teleport version：v13.3.7
- Google Chrome version：116.0.5845.179（Official Build） （64 bit）
- Node Server OS：RHEL8.8
- Recreation steps
1. Connect to the node server with Google Chrome.
2. Open the file with vim.
3. Change the magnification of Google Chrome. Either zoom in/out is fine.
4. If you move the cursor, etc. in vim, the display will be broken.
- Debug logs

```
2023-09-07T13:09:26+09:00 [WEBSOCKET] WARN Failed to parse resize payload: json: cannot unmarshal number into Go value of type string session_id:143dd8a4-2143-429f-b5fd-b90bb2ddf886 web/terminal.go:1115
```

**Comment by zmb3** [comment] 2023-09-07 14:21
Duplicate of #31565

**Closed by zmb3** 2023-09-07 14:21 UTC
Labels: bug
