### ISSUE TITLE
tsh db ls is not working

### ISSUE THREAD

**Issue by nivasomu** [gravitational/teleport#19212] opened 2022-12-08 18:30 UTC
Expected behavior:
The `tsh db ls` is expected to list the database instances

Current behavior:
The `tsh db ls` is throwing a panic error 

```
panic: runtime error: slice bounds out of range [:-4]

goroutine 1 [running]:
github.com/gravitational/teleport/lib/asciitable.(*Table).truncateCell(0xc001886778?, 0x2?, {0xc000a67300?, 0x8?})
	/private/tmp/teleport-20221012-5919-1351ocj/teleport-10.3.2/lib/asciitable/table.go:149 +0x187
github.com/gravitational/teleport/lib/asciitable.(*Table).AddRow(0xc001886778, {0xc0002d8a50, 0x5, 0x5})
	/private/tmp/teleport-20221012-5919-1351ocj/teleport-10.3.2/lib/asciitable/table.go:131 +0xa6
github.com/gravitational/teleport/lib/asciitable.MakeTableWithTruncatedColumn({0xc001886968, 0x5, 0x2?}, {0xc000ca2c00, 0x70, 0x10?}, {0x1025af8a3, 0x6})
	/private/tmp/teleport-20221012-5919-1351ocj/teleport-10.3.2/lib/asciitable/table.go:116 +0x316
main.showDatabasesAsText({0x102ae2d60, 0xc000014018}, {0x0?, 0x0?}, {0xc0010d4000?, 0x70?, 0x102b053a0?}, {0xc000946100, 0x2, 0x2}, ...)
	/private/tmp/teleport-20221012-5919-1351ocj/teleport-10.3.2/tool/tsh/tsh.go:2344 +0x33e
main.showDatabases({0x102ae2d60, 0xc000014018}, {0x0, 0x0}, {0xc0010d4000, 0x70, 0x80}, {0xc000946100, 0x2, 0x2}, ...)
	/private/tmp/teleport-20221012-5919-1351ocj/teleport-10.3.2/tool/tsh/tsh.go:2224 +0x139
main.onListDatabases(0xc0002f7080)
	/private/tmp/teleport-20221012-5919-1351ocj/teleport-10.3.2/tool/tsh/db.go:95 +0x5cd
main.Run({0x102b079b0, 0xc00020d040}, {0xc0000521c0, 0x2, 0x2}, {0x0, 0x0, 0xc0000061a0?})
	/private/tmp/teleport-20221012-5919-1351ocj/teleport-10.3.2/tool/tsh/tsh.go:1037 +0xa197
main.main()
	/private/tmp/teleport-20221012-5919-1351ocj/teleport-10.3.2/tool/tsh/tsh.go:444 +0x318
```

**Comment by zmb3** [comment] 2022-12-08 18:37
This is a duplicate of #13130 and was fixed in v10.3.4. Looks like you're on 10.3.2.

**Closed by zmb3** 2022-12-08 18:37 UTC
Labels: bug, c-yk
