### ISSUE TITLE
`TestProxyTunnelStrategyAgentMesh` flakiness

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#14341] opened 2022-07-11 21:01 UTC
https://console.cloud.google.com/cloud-build/builds;region=us-west1/430ec49f-84c3-4947-bfb3-a506005a184f;step=0?authuser=1&project=ci-account

```
    integration_test.go:3190: 
        	Error Trace:	integration_test.go:3190
        	            				proxy_tunnel_strategy_test.go:110
        	Error:      	Condition never satisfied
        	Test:       	TestProxyTunnelStrategyAgentMesh
        	Messages:   	Active tunnel connections did not reach 2 in the expected time frame
```

**Comment by dboslee** [comment] 2022-07-12 14:15
Closing. Duplicate of https://github.com/gravitational/teleport/issues/13631

**Closed by dboslee** 2022-07-12 14:15 UTC
Labels: flaky tests
