### ISSUE TITLE
Support Dual authorization at the per org-defined commands / actions.  AC-3(2) 

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#3876] opened 2020-06-23 00:39 UTC
### Feature Request
A customer is looking for Dual Authorization controls on a per-session basis. The customer in case, would like something similar to 'pair debugging', but while reviewing NIST guidelines, we should review what this means in general. 

> ACCESS ENFORCEMENT | DUAL AUTHORIZATION
The information system enforces dual authorization for [Assignment: organization-defined privileged commands and/or other organization-defined actions].
Supplemental Guidance: Dual authorization mechanisms require the approval of two authorized individuals in order to execute. Organizations do not require dual authorization mechanisms when immediate responses are necessary to ensure public and environmental safety. Dual authorization may also be known as two-person control.
Related to: CP-9, MP-6

### Motivation
Customer Feedback and https://nvd.nist.gov/800-53/Rev4/control/AC-3 

### Who's it for?
Enterprise, FedRAMP

**Comment by russjones** [comment] 2020-08-13 21:34
Best: 30
Worst: 60

**Comment by klizhentas** [comment] 2020-10-26 16:15
This could be implemented as co-pilot feature - one person opens the session and the session blocks until the other person joins the session. The other person can be in active mode or in read only mode

**Comment by klizhentas** [comment] 2020-11-10 03:08
Dupe of #4736

**Comment by russjones** [comment] 2021-05-21 17:50
Closing this in favor of https://github.com/gravitational/teleport/issues/4736.

**Closed by russjones** 2021-05-21 17:50 UTC
Labels: c-pa, design-needed, enterprise
