### ISSUE TITLE
Option to only send kubernetes user instead of including k8s groups

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#9129] opened 2021-11-24 19:35 UTC
### What
Not send the `system:authenticated` group or any group as an option.  This can cause issues when a user is already set in the k8s cluster such as a GKE.

```json
  "kubernetes_groups": [
    "system:authenticated"
  ]
```

### How
Add an option in the Teleport role to not include a kubernetes group.

### Why
Causes problems with kubernetes users in GKE.

**Comment by klizhentas** [comment] 2021-11-24 20:36
Sasha: we should differentiate between empty list set by user and missing field. If an empty list is sent by user, we should send no groups. If the field is missing, we should add default value system: authenticated.

**Comment by russjones** [comment] 2021-12-15 21:14
@stevenGravy will reproduce this issue internally and verify the fix with a hotpatch.

Once @stevenGravy gives us the sign-off, we'll assign this to an engineer and get a fix out in a production release.

**Comment by r0mant** [comment] 2022-02-15 20:39
@xacrimon @klizhentas With regards to this proposal:

> we should differentiate between empty list set by user and missing field. If an empty list is sent by user, we should send no groups. If the field is missing, we should add default value system: authenticated.

Wouldn't it make a bit more sense to invert these and not send anything if kube_groups aren't present at all and append `system:authenticated` in any other case?

Then we'll basically have 2 scenarios:

1. `kube_groups == nil` -> do not send any groups
2. `kube_groups != nil && len(kube_groups) >= 0` -> append `system:authenticated` like now

@xacrimon:

The tricky bit is how to distinguish between `== nil` and `!= nil`. I would first look at how our existing roles are stored in the backend - if their kube_groups are empty, are they marshaled to empty array or nil? And can we differentiate between those 2 scenarios after unmarshaling (e.g. checking .KubeGroups == nil)?

If it turns out that right now we marshal empty kube_groups as empty array, we might have to introduce a RoleV5 to avoid breaking existing roles (otherwise if somebody has empty groups we will stop sending system:auth and break kubectl).

**Comment by r0mant** [comment] 2022-02-15 22:59
After syncing with the product team we have decided to first gather more information about the use-case and the issue before settling down on the specific UX. @stevenGravy When you get a chance, could you add more information regarding:

- What is the expected role configuration the customer is using? Are kube_users being set?
- What is the issue with sending system:authenticated group to GKE cluster?

A more detailed scenario or repro steps would be helpful. When we understand the problem better, we can make a debug build for a customer to try and confirm it fixes the issue and then nail down the specific UX.

**Comment by xacrimon** [comment] 2022-02-16 17:10
@r0mant We currently don't have a way to distinguish between no provided list or empty list. Unfortunately, due to how protobuf marshaling code works. We can't distinguish between a not provided and empty array in a type due to proto3 implicit-optional mechanics. We have two options here, we can either use custom marshaller hooks to set another field in the role definition if it's empty or we could introduce a deliberate flag to enable/disable this behaviour per role. I don't have a preference for either solution, what do you think would be cleanest?

**Comment by r0mant** [comment] 2022-02-16 18:22
@xacrimon I would try to avoid introducing extra flags unless absolutely necessary esp. to handle edge-cases like this to keep clean UX.

For the debug build we can do something really simple for the customer to try it out (e.g. `kubernetes_groups: ["donotaddsystemauth"]` will not add `system:auth` group).

For the "real" fix I have a couple ideas:

* It's a shame proto3 can't distinguish b/w empty and nil, but can yaml parser do it? Then we could move the logic of appending system:auth group at the role creation time instead at connect time. So when you create a new role (v5), somewhere in CheckAndSetDefaults we see if kube_groups are empty (but not nil) and keep them as-is and append system:auth otherwise. We'll likely have to do a migration to add system:auth to all existing roles too and not append it in the Kube forwarder. The downside is that most roles will now have system:auth explicitly specified among their kube_groups but that might also be an upside too since it's going to be explicit (vs implicitly adding it as now).

* Another idea is to leverage "deny" rules and do not append system:auth if you have `kubernetes_groups: ["system:authenticated"]` among the deny rules. We already filter out all denied kube users/groups from the final list of users/groups set in the request so it would be somewhat consistent. This will also likely be easier to implement and won't require introduction of role v5.

@klizhentas @xinding33 @russjones Do you guys have any preference for either of these ^^^ options from the UX perspective?

**Comment by xacrimon** [comment] 2022-02-16 18:42
1. It depends on impl, the Go standard specifies that an empty list be equal to nil in terms of properties and handling, how it's returned isn't specified, currently though, the one we use seem to mark empty but declared lists as nil from some cursory testing.

2. This seems like the better option to me with less weird behaviour during and after the migration process since it's consistent with how we already do a lot of things.

**Comment by r0mant** [comment] 2022-02-17 18:55
@xacrimon An update from customer:

> We’re using [Google Groups for GKE](https://cloud.google.com/kubernetes-engine/docs/how-to/google-groups-rbac) to define Kubernetes RBAC policies tied to Google Groups.  From my understanding this groups are inferred based on the logged in Kubernetes user, however when a group like "system:authenticated" is passed in then the group lookup is ignored for that user.

> The role configuration we hope to use is one that specifies the `kubernetes_users` without `kubernetes_groups` so that this Google Groups for GKE functionality continues to work for the authenticated Kubernetes user. As we are using Okta SSO (and not Kubernetes SSO) the Okta groups available via `{{external.groups}}` do not exactly align with the Google Groups of the Teleport user. As a workaround, we can specify `kubernetes_groups` like below which should work for the most part, but feels error prone:  `kubernetes_groups: ['{{external.groups}}@example.com']`.

Looks like the customer also doesn't have bandwidth to try out the debug build. Could you try and repro this scenario?

And btw, another point in favor of filtering out groups from "deny" rules is that it will allow to support not passing system:auth group not just in empty groups scenario, but in case of any kube_groups even if not empty. But we'll see what the product team says.

**Comment by russjones** [comment] 2022-03-17 21:46
Customer has indicated they do not need this feature anymore.

**Closed by russjones** 2022-03-17 21:46 UTC
Labels: feature-request, kubernetes, c-di, needs-product-decision
