### ISSUE TITLE
Enabling licensing in the default chart is inflexible

### ISSUE THREAD

**Issue by drewwells** [gravitational/teleport#22248] opened 2023-02-24 18:45 UTC
The current method of enabling licensing is difficult. There should be a more flexible way of importing the license into teleport since this is best way to run paid for Teleport.

It appears this is the way to enable licensing which is hardcoded to a secret named license.
```
auth:
  enterprise: true
```

The feature should be more flexible, I recommend something like this:
```
auth:
  license:
    enabled: true
    secretName: license
```

Now, I can introduce new config options within the license subobject and change the name of the secret.

**Comment by zmb3** [comment] 2023-02-24 20:35
Duplicate of #20404

**Closed by zmb3** 2023-02-24 20:35 UTC
Labels: feature-request, helm
