### ISSUE TITLE
Ubuntu Desktop

### ISSUE THREAD

**Issue by rprasheed** [gravitational/teleport#34328] opened 2023-11-08 08:42 UTC
What would you like Teleport to do?
Please add Ubuntu desktop resource.

What problem does this solve?
So possible to add ubuntu desktop. Now there is only Ubuntu server available.

If a workaround exists, please include it.

**Comment by stevenGravy** [comment] 2023-11-08 13:19
duplicate of https://github.com/gravitational/teleport/issues/13179

**Closed by stevenGravy** 2023-11-08 13:19 UTC
Labels: feature-request
