### ISSUE TITLE
`tsh request search` should support listing available roles

### ISSUE THREAD

**Issue by stephenjudkins** [gravitational/teleport#34735] opened 2023-11-17 21:31 UTC
What would you like Teleport to do?
You should be able to use `tsh` to show available roles to request, like one can in the web UI.

What problem does this solve?
Automation of access requests

If a workaround exists, please include it.
Hardcode the roles or look in the web UI

**Comment by zmb3** [comment] 2023-11-19 16:58
Duplicate of #7693

**Closed by zmb3** 2023-11-19 16:58 UTC
Labels: feature-request
