### ISSUE TITLE
Split out Teleport config yaml reference

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#11253] opened 2022-03-18 14:40 UTC
## Details
The Teleport config YAML reference is quite long now (12 pages on a 4k monitor).  Having a tabbed format showing shorter examples and possibly still the long version would help so users can more easily navigate. 

Possible examples:

Simple configs:
- Proxy
- Auth
- Resource (ssh, db, windows desktop..)  Services

Advanced examples of:
- Proxy
- Auth
- other applicable examples

In the case of Teleport Cloud Only show resource examples. 

### Category
- Improve Existing

**Comment by zmb3** [comment] 2022-11-03 22:04
Duplicate of #7326

**Comment by ptgott** [comment] 2023-02-06 17:34
I'm going to reopen this in favor of #7326 because it's more specific and more applicable to our docs as they exist now. One item from #7326 that we could add here is this:

> Our configuration examples display how to configure for a hypothetical (and probably mutually exclusive) set of scenarios but don't enumerate the possible values, probably don't describe what's required or not, etc. We should duplicate the YAML fields into a table like we do elsewhere but enrich the table with additional info like Type, Required or Not, Enums, etc.

**Closed** 2023-02-24 22:29 UTC
Labels: documentation
