### ISSUE TITLE
Linter in not run on mdx pages

### ISSUE THREAD

**Issue by iAdramelk** [gravitational/teleport#10107] opened 2022-02-02 16:52 UTC
https://github.com/gravitational/next/ repo, which build documentation have a linter for markdown files.

In the past this linter was bundled in docker and run on every change to `/docs/pages/**/*.mdx` files in PR. It was AFAIK done, using Drone. See drone config: https://github.com/gravitational/next/blob/main/.drone.yml

But it looks like now this integration broke at some point in time. Right now linter returns at least 5 errors and 140 warnings.

**Comment by ibeckermayer** [comment] 2022-02-02 23:33
Possibly a dupe of https://github.com/gravitational/teleport/issues/9600

**Closed** 2022-02-04 15:16 UTC
Labels: documentation
