### ISSUE TITLE
Activity view does not show most recent session recordings and page view stucked

### ISSUE THREAD

**Issue by oshati** [gravitational/teleport#13670] opened 2022-06-20 17:13 UTC
Expected behaviour:
Have the activity view report updated log of session recordings and be able to scroll through page seamless without being stuck on a single page

Current behaviour:
Activity view does not show most recent session recordings even though they exist in the bucket. In addition, as a scroll through the pages the timestamps change but all other columns stay the same and appears to be stuck on the first page

Bug details:
- Teleport version 9

screen recording of the experience shown in the link below: 
https://user-images.githubusercontent.com/74545288/174650002-a8377d49-c1b4-44c9-9e9e-91a741a03a92.mov

- .HAR file content retracted but available upon request.

gz#5559

**Comment by zmb3** [comment] 2022-06-20 21:18
@oshati can we get the specific version of Teleport that's being used here?

**Comment by oshati** [comment] 2022-06-21 17:35
Teleport Enterprise v9.2.1 git:v9.2.1-0-gc6daeda62 go1.17.9

**Comment by zmb3** [comment] 2022-08-10 21:07
I think this may be a duplicate of https://github.com/gravitational/webapps/issues/1062

**Comment by zmb3** [comment] 2022-10-17 20:32
@oshati I believe this was fixed with gravitational/webapps#1196 - can you confirm?

**Comment by zmb3** [comment] 2022-12-04 16:38
Closing due to inactivity. This should be resolved now that the activity page does not auto-refresh.

**Closed by zmb3** 2022-12-04 16:38 UTC
Labels: bug, audit-log, c-mc
