### ISSUE TITLE
Teleport doesn't start with systemd and S3 configuration

### ISSUE THREAD

**Issue by liqnuks** [gravitational/teleport#2015] opened 2018-06-18 11:09 UTC
**What happened**:

Teleport doesn't start with `audit_sessions_uri` configured to use S3 bucket on AWS with `Amazon Linux 2 LTS Candidate 2 AMI` and `systemd`.

The root cause seems because teleport doesn't use the credentials set in the configuration for s3 connector but use the credentials set in `~/.aws/credentials`.

However, when teleport is run by systemd, the credentials are not found.

**What you expected to happen**:

Teleport should use the credentials set in the configuration or documentation should be improved about S3 authentication.

**How to reproduce it (as minimally and precisely as possible)**:

Teleport configuration snippet : 
```
teleport:
[...]
  storage:
    type: dynamodb
    region: eu-west-1
    table_name: teleport.state
    access_key: <access_key>
    secret_key: <secret_key>
    audit_table_name: teleport.audit
    audit_sessions_uri: s3://<bucket_name>/session_records
[...]
```

[Systemd service configuration](https://github.com/gravitational/teleport/blob/master/examples/systemd/teleport.service)

**Environment**:
- Teleport version (use `teleport version`): `Teleport v2.6.1 git:v2.6.1-0-g63d4968f`
- Tsh version (use `tsh version`): `Teleport v2.6.1 git:v2.6.1-0-g63d4968f`
- OS (e.g. from /etc/os-release): `Amazon Linux 2 (2017.12) LTS Release Candidate`

**Relevant Debug Logs If Applicable**
```
Jun 18 10:11:59 localhost teleport: INFO [S3]        Setting up bucket "<bucket_name>". s3sessions/s3handler.go:91
Jun 18 10:11:59 localhost teleport: error: NoCredentialProviders: no valid providers in chain. Deprecated.
Jun 18 10:11:59 localhost teleport: For verbose messaging see aws.Config.CredentialsChainVerboseErrors, initialization failed```
```

**Workaround**

Edit sytemd service configuration with: 

```
[...]
[Service]
Environment="AWS_SHARED_CREDENTIALS_FILE=/<user_home>/.aws/credentials"
[...]
```

**Comment by kontsevoy** [comment] 2018-06-25 21:11
@liqnuks have you tried setting `AWS_SDK_LOAD_CONFIG=1` as described [here](https://github.com/aws/aws-sdk-go#aws-shared-config-file-awsconfig)?

**Comment by liqnuks** [comment] 2018-07-19 14:54
I've just tried on my service configuration with
```
[...]
[Service]
Environment="AWS_SDK_LOAD_CONFIG=1"
[...]
```

and this teleport configuration (with and without the audit configuration)

```
[...]
  storage:
    type: dynamodb
    region: eu-west-1
    table_name: teleport.state
    audit_table_name: teleport.events
    audit_sessions_uri: s3://<bucket_name>/records
[...]
```

I've removed the keys from the teleport configuration.

On these cases, teleport doesn't start when it's launched by systemd

```
Jul 19 14:46:04 ip-10-0-0-147 systemd: Started Teleport SSH Service.
Jul 19 14:46:04 ip-10-0-0-147 systemd: Starting Teleport SSH Service...
Jul 19 14:46:04 ip-10-0-0-147 teleport: INFO [DYNAMODB]  Initializing backend. dynamo/dynamodbbk.go:132
Jul 19 14:46:04 ip-10-0-0-147 teleport: error: initialization failed
Jul 19 14:46:04 ip-10-0-0-147 systemd: teleport.service: main process exited, code=exited, status=1/FAILURE
Jul 19 14:46:04 ip-10-0-0-147 systemd: Unit teleport.service entered failed state.
Jul 19 14:46:04 ip-10-0-0-147 systemd: teleport.service failed.
Jul 19 14:46:04 ip-10-0-0-147 systemd: teleport.service holdoff time over, scheduling restart.
```

**Comment by andrewbanchich** [comment] 2018-11-19 22:15
@kontsevoy We are having the same issue. We installed Teleport on a Linux laptop and it won't start with this config:

```
teleport:
   nodename: Removed
   storage:
     # These two settings instruct Teleport to use a specified
     # S3 bucket
     region: us-east-1
     audit_sessions_uri: s3://our-bucket-name

     # Authentication settings are optional (see below)
     access_key: removed
     secret_key: removed

auth_service:
   enabled: yes
   cluster_name: "Removed"

ssh_service:
   enabled: yes
   commands:
   - name: ip
     command: [hostname, -I]
     period: 1h0m0s
   - name: kernel
     command: [uname, -r]
     period: 1h0m0s
   - name: uptime
     command: [uptime, -p]
     period: 0h1m0s

proxy_service:
   enabled: yes
```

Looking at debug logs, I get:
```
Nov 19 17:01:56 sd-antergos systemd[1]: Stopping Teleport SSH Service...
Nov 19 17:01:56 sd-antergos systemd[1]: Stopped Teleport SSH Service.
Nov 19 17:01:56 sd-antergos systemd[1]: Started Teleport SSH Service.
Nov 19 17:01:56 sd-antergos teleport[9220]: DEBU [BACKEND:D] Found new flat keyspace, skipping migration. dir:/var/lib/teleport/proc dir/migrate.go:42
Nov 19 17:01:56 sd-antergos teleport[9220]: DEBU [KEYGEN]    SSH cert authority is going to pre-compute 25 keys. native/native.go:90
Nov 19 17:01:56 sd-antergos teleport[9220]: DEBU [PROC:1]    Using dir backend. service/service.go:1963
Nov 19 17:01:56 sd-antergos teleport[9220]: DEBU [BACKEND:D] Found new flat keyspace, skipping migration. dir:/var/lib/teleport/backend dir/migrate.go:42
Nov 19 17:01:56 sd-antergos teleport[9220]: INFO [S3]        Setting up bucket "our-bucket-name". s3sessions/s3handler.go:91
Nov 19 17:02:16 sd-antergos teleport[9220]: ERROR REPORT:
Nov 19 17:02:16 sd-antergos teleport[9220]: Original Error: *trace.BadParameterError NoCredentialProviders: no valid providers in chain. Deprecated.
Nov 19 17:02:16 sd-antergos teleport[9220]:         For verbose messaging see aws.Config.CredentialsChainVerboseErrors
Nov 19 17:02:16 sd-antergos teleport[9220]: Stack Trace:
Nov 19 17:02:16 sd-antergos teleport[9220]:         /gopath/src/github.com/gravitational/teleport/lib/events/s3sessions/s3handler.go:247 github.com/gravitational/teleport/lib/events/s3sessions.ConvertS3Error
Nov 19 17:02:16 sd-antergos teleport[9220]:         /gopath/src/github.com/gravitational/teleport/lib/events/s3sessions/s3handler.go:184 github.com/gravitational/teleport/lib/events/s3sessions.(*Handler).ensureBucket
Nov 19 17:02:16 sd-antergos teleport[9220]:         /gopath/src/github.com/gravitational/teleport/lib/events/s3sessions/s3handler.go:92 github.com/gravitational/teleport/lib/events/s3sessions.NewHandler
Nov 19 17:02:16 sd-antergos teleport[9220]:         /gopath/src/github.com/gravitational/teleport/lib/service/service.go:722 github.com/gravitational/teleport/lib/service.initUploadHandler
Nov 19 17:02:16 sd-antergos teleport[9220]:         /gopath/src/github.com/gravitational/teleport/lib/service/service.go:853 github.com/gravitational/teleport/lib/service.(*TeleportProcess).initAuthService
Nov 19 17:02:16 sd-antergos teleport[9220]:         /gopath/src/github.com/gravitational/teleport/lib/service/service.go:591 github.com/gravitational/teleport/lib/service.NewTeleport
Nov 19 17:02:16 sd-antergos teleport[9220]:         /gopath/src/github.com/gravitational/teleport/lib/service/service.go:355 github.com/gravitational/teleport/lib/service.newTeleportProcess
Nov 19 17:02:16 sd-antergos teleport[9220]:         /gopath/src/github.com/gravitational/teleport/lib/service/service.go:365 github.com/gravitational/teleport/lib/service.Run
Nov 19 17:02:16 sd-antergos teleport[9220]:         /gopath/src/github.com/gravitational/teleport/tool/teleport/common/teleport.go:167 github.com/gravitational/teleport/tool/teleport/common.OnStart
Nov 19 17:02:16 sd-antergos teleport[9220]:         /gopath/src/github.com/gravitational/teleport/tool/teleport/common/teleport.go:148 github.com/gravitational/teleport/tool/teleport/common.Run
```

**Comment by webvictim** [comment] 2020-08-17 14:55
The root cause of this error is that `systemd` blocks services from accessing any files in a user's home directory by default. This includes `~/.aws/credentials`, meaning that Teleport cannot load the AWS credentials file.

The correct way to address is to add a line to your `teleport.service` systemd unit file to indicate that these environment variables should be specifically loaded - either as described above in the first comment, or something like:

```
[...]
[Service]
EnvironmentFile=-/root/.aws/credentials
EnvironmentFile=-/root/.aws/config
[...]
```

Alternatively, you could specify the AWS credentials directly in the systemd unit file:

```
[...]
[Service]
Environment=AWS_ACCESS_KEY_ID=AKIA123123...<redacted>
Environment=AWS_SECRET_ACCESS_KEY=12398sd....<redacted>
[...]
```

I agree that the Teleport documentation should be updated to explain this better.

**Comment by Binsabbar** [comment] 2021-11-05 22:06
I wish this was documented somewhere, I was trying for days, then suddenly got it working by setting the env file location in teleport.service. I came here to write it, but saw this issue opened already.

I basically set the envs in `EnvironmentFile=-/etc/default/teleport`

⚠️  **_(ensure the permissions is set to 600 for root user !, by default the file is 644)_** ⚠️

**Comment by Binsabbar** [comment] 2022-02-08 09:39
Hi @ptgott , I noticed that now this has been added in the default installation of Teleport `EnvironmentFile=-/etc/default/teleport` (I am using teleport 8.1.4). Can this be closed?

**Comment by udf2457** [comment] 2022-07-29 08:44
@webvictim 

I stumbled across your answer trying to fix a completely unrelated (non-teleport) problem where systemd couldn't access `/root/.aws` to get my AWS credentials.

> The root cause of this error is that `systemd` blocks services from accessing any files in a user's home directory by default.

Could you elaborate further on this ?   Are you saying `ProtectHome` is enabled by default ? Or is it something else ? Any chance of a man-page location ref ?

Also, instead of your `EnvironmentFile` work around, any thoughts on `ReadOnlyPaths` ?  Since strictly speaking the AWS files are not pure environment files, they have sections (i.e `[ xyz ]`), i.e. they are not pure key-value files.

Thanks !

**Comment by udf2457** [comment] 2022-07-30 08:52
Having done a little bit of experimenting, actually I think the root-cause is not what @webvictim says.

Instead, the root-cause appears to be that systemd does not set `$HOME` and thus `~/.aws` will never be found.

The workaround that works for me is to use `EnvironmentFile` in systemd, and in that environment file, you add two parameters:

```

AWS_CONFIG_FILE=""
AWS_SHARED_CREDENTIALS_FILE=""

```

Systemd then loads the environment file, passes those two to the AWS SDK and then the SDK knows where to look.


@ptgott @Binsabbar

**Comment by alexfornuto** [comment] 2023-04-13 17:02
Revisiting this issue, according to our [current docs](https://goteleport.com/docs/reference/backends/#s3) teleport looks for environment vars in `/etc/default/teleport` by default. This documented method avoids any issues with adjusting the systemd file to point to other locations. Any alternate configuration would fall outside out scope of support, and the issues that arise from alternate locations are related to systemd limitations and are not Teleport-specific.

For this reason, I'm going to close this issue. If those tagged on this thread disagree, feel free to re-open and discuss further.

**Closed by alexfornuto** 2023-04-13 17:02 UTC
Labels: documentation, aws, c-cel
