### ISSUE TITLE
Creating Kubernetes job fails

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#11482] opened 2022-03-26 00:53 UTC
Customer has reported that trying to create a Job using Kubernetes Access fails, but works if you bypass Kubernetes Access.

```
$ kubectl create job --from=cronjob/acme-refresh -n foo-system sign-cert-verify
error: unknown object type *v1beta1.CronJob
```

```
$ kubectl create job --from=cronjob/acme-refresh -n foo-system sign-cert-verify
job.batch/sign-cert-verify created
```

Customer reported this in Teleport 6.2.14, need to check if it's still an issue with Teleport 9.

**Comment by tigrato** [comment] 2022-06-13 16:07
I could not reproduce this error in v9 or master.

```bash

kubectl create job --from=cronjob/hello  -n test  hello-job
job.batch/sign-cert created
```
@russjones, can we close it?

**Comment by russjones** [comment] 2022-08-11 16:40
@tigrato Can you verify that this doesn't work in 6.2.14 like the ticket describes? If so then we can close this issue as we know we successfully reproduced it and it no longer occurs on the latest releases of Teleport.

**Comment by tigrato** [comment] 2022-08-15 08:23
@russjones, we can reproduce it with v6.2.14, and the problem is fixed at least for v9,v10, and master.

**Closed by tigrato** 2022-08-15 08:23 UTC
Labels: bug, c-q7j, kubernetes

**Comment by russjones** [comment] 2022-08-15 14:28
@tigrato Excellent, thank you!
