### ISSUE TITLE
db access should handle a redis cluster MOVED response

### ISSUE THREAD

**Issue by programmerq** [gravitational/teleport#22992] opened 2023-03-13 17:27 UTC
### Expected behavior:

When accessing a redis cluster behind Teleport, sometimes it will get a redis MOVED redirection. Since the end user's client is interacting with Teleport's redis service, and can't follow the redirect to directly access the cluster node, Teleport should handle making the request to the other node instead.

See: https://redis.io/docs/reference/cluster-spec/#moved-redirection

### Current behavior:

The end user's redis client will get a moved redirection response back from redis and fail to connect to the real redis cluster node referenced.

Ideally, the end-user should not need to include -c at all since Teleport's db service should transparently handle those responses.

### Bug details:
- Teleport version - 
- Recreation steps - To recreate, set up a Redis cluster (elisticache works for this) with more than one redis node. Set up db access. Connect via `tsh proxy db` and include the `-c` option when launching redis-cli to enable redirect handling.
- Debug logs -

**Comment by zmb3** [comment] 2023-03-13 17:58
Duplicate of #22457?

**Closed** 2023-03-13 20:58 UTC
Labels: bug, database-access, c-cv, db/redis
