### ISSUE TITLE
Teleport Enterprise install instructions don't use DEB/RPM repos

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#23564] opened 2023-03-24 15:02 UTC
## Applies To
https://goteleport.com/docs/server-access/getting-started/?scope=enterprise#step-14-install-teleport-on-your-linux-host (partial included here)

## Details
The OSS install instructions suggest installing and using the Teleport DEB/RPM repos, but the Enterprise install instructions tell users to grab an individual DEB/RPM from our downloads page and install it manually. This makes it much harder for Enterprise users to update to new versions easily when they're released.

This also leads to Enterprise users installing OSS binaries rather than Enterprise binaries, which will work fine, but means they're missing out on security patches which are released to Enterprise first. We also recently changed our recommendation of running Enterprise auth servers with OSS components to state that Enterprise customers should always deploy Enterprise binaries everywhere.

We should overhaul the partial and include instructions for installing Enterprise (and Enterprise FIPS) DEB/RPM packages from the repos.

**Comment by zmb3** [comment] 2023-03-24 17:38
Duplicate of #21264?

**Comment by webvictim** [comment] 2023-03-24 17:49
AFAICT that's the opposite 😅 

I'm looking for _more_ usage of repos; that issue wants something _other_ than repos.

**Closed** 2023-08-18 20:58 UTC
Labels: documentation, ux
