### ISSUE TITLE
No audit events about agent forwarding

### ISSUE THREAD

**Issue by bl-nero** [gravitational/teleport#36847] opened 2024-01-18 10:10 UTC
Expected behavior:
I expect to see success/failure notifications of using agent forwarding in the audit log.

Current behavior:
There's no trace of agent forwarding in the audit log.

Bug details:
Teleport version: v15.0.0-alpha.5
1. Create a v15 cluster with at least one node.
2. Create a target EC2 instance with a custom key.
3. Optionally, disable agent forwarding in RBAC (to test the failure condition).
4. Add the custom key to local ssh-agent.
5. Use `tsh -A` to sign into any node of your cluster.
6. Use `ssh` from inside the node to connect to your target.

Note: this may be an issue with the test plan itself, but since every port forwarding attempt gets caught by the audit log, I suspect the same should happen for agent forwarding.

**Comment by bl-nero** [comment] 2024-01-25 13:31
This one also affects v14, so I'm removing the `test-plan-problem` label.

**Comment by zmb3** [comment] 2024-07-24 20:26
Looks like this is a duplicate of #4881.

**Closed by zmb3** 2024-07-24 20:26 UTC
Labels: bug, audit-log
