### ISSUE TITLE
tsh tab completions

### ISSUE THREAD

**Issue by jspiro** [gravitational/teleport#6933] opened 2021-05-19 00:07 UTC
### What
I'd like for tsh to support shell tab completions for its verbs, and maybe even resources! (e.g. how `brew` does)

### How
Programming! 🙃

### Why
Improves developer experience.

### Workaround
N/A

**Comment by zmb3** [comment] 2022-09-08 15:09
Closing as duplicate of #3753

**Closed by zmb3** 2022-09-08 15:09 UTC
Labels: feature-request, ux, tsh
