### ISSUE TITLE
Enforce IP-Based restrictions for Ephemeral Certificates for Kube, DB, Desktop

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#15565] opened 2022-08-16 15:45 UTC
What would you like Teleport to do?

Teleport provides IP- Based restrictions to SSH.  Some clients want this expanded to include at least Kube, DB and Desktop certificates.

What problem does this solve?

Provides additional security to prevent reuse of certificates from multiple IP sources.

**Comment by zmb3** [comment] 2022-08-16 16:44
Closing as duplicate of https://github.com/gravitational/teleport/issues/14702

**Closed by zmb3** 2022-08-16 16:44 UTC
Labels: feature-request, rbac
