### ISSUE TITLE
More support for copy/paste multiple pages in web sessions

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#3861] opened 2020-06-18 19:50 UTC
### Feature Request
Make it easier to copy/paste in multiple pages within a web session.    Currently you can only (or it's really difficult to get multiple pages) copy and paste from the current page view.  Often users want to copy and paste multiple pages of output such as a log.

### Motivation
Having the ability to see past pages content makes the experience more like a CLI session.  Users will then have a more consistent experience with web vs cli sessions.

### Who's it for?
OSS User, Pro, Enterprise

**Comment by russjones** [comment] 2020-06-23 17:38
@stevenGravy Can you try and reproduce this in 4.3.0-alpha.1, this should be fixed.

**Comment by stevenGravy** [comment] 2020-06-24 11:59
@russjones  Yes, that's working great.  You can see the scroll and copy/select multiple pages.Should we tag this with 4.3?

**Comment by russjones** [comment] 2020-06-24 17:13
@stevenGravy Let's just close it, since it looks like solved.

**Closed by russjones** 2020-06-24 17:13 UTC
Labels: sales-onboarding, ui, ux
