### ISSUE TITLE
Update Access Request when locked

### ISSUE THREAD

**Issue by scottpgallagher** [gravitational/teleport#43509] opened 2024-06-25 18:49 UTC
What would you like Teleport to do?
Currently when a lock is placed on an Access Request it still shows as available. Updating the "Available" field to show a lock is in place. 

<img width="1095" alt="Screenshot 2024-06-25 at 2 45 44 PM" src="https://github.com/gravitational/teleport/assets/51385814/96134b69-1864-4633-b422-f387a9ec4bfa">

What problem does this solve?
Shows when an Access Request has a lock on it. Can be useful for troubleshooting Access Requests or seeing which ones have a lock on them. 

If a workaround exists, please include it.

**Comment by zmb3** [comment] 2024-06-25 20:36
Duplicate of #43355

**Closed** 2024-06-25 20:36 UTC
Labels: feature-request, access-requests
