### ISSUE TITLE
Database access for Microsoft SQL with non-AWS managed AD authentication

### ISSUE THREAD

**Issue by WilliamLoy** [gravitational/teleport#15301] opened 2022-08-08 13:09 UTC
What would you like Teleport to do?
Enable database access for Microsoft SQL with non-AWS managed AD authentication

What problem does this solve?
The customer needs access to this protocol. 

If a workaround exists, please include it.

**Comment by zmb3** [comment] 2022-08-08 14:23
Closing as a duplicate of #14285 and #10485

**Closed by zmb3** 2022-08-08 14:23 UTC
Labels: feature-request, c-md
