### ISSUE TITLE
Command history not working.

### ISSUE THREAD

**Issue by noriuky** [gravitational/teleport#855] opened 2017-03-22 00:38 UTC
Did someone had same problem?
i press up but it doesnt behave like ssh terminal.
any solution?
i really need it is very useful.
I also wonder how to move backward / forward along the actual command line.
left and right arrows keys not working too.
this force me to keep open a notepad and elaborate my command string there then copy paste into the shell. This is so frustrating and slow down the work a lot.
you should consider to insert these cursor functions ASAP plz.

**Comment by alex-kovoy** [comment] 2017-03-22 04:23
Could you tell more about your environment? What OS/Browser do you use on the client? What OS do you use on the node/server?

**Comment by alex-kovoy** [comment] 2017-03-22 04:29
In issue #833 you mentioned that this behavior was observed in Firefox. While we are looking into this issue, could you tell if it works fine in Chrome or other browser for the same environment?

**Comment by kontsevoy** [comment] 2017-04-13 20:57
tested on all supported browsers and could not reproduce. @noriuky we're going to close this for now but feel free to send a better instructions for how to reproduce this. Thanks!

**Closed by kontsevoy** 2017-04-13 20:57 UTC
