### ISSUE TITLE
TOTP Resynchronization

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#2667] opened 2019-04-22 20:08 UTC
Teleport uses the Time-based One-time Password (TOTP) algorithm to generate second factor tokens for local accounts. TOTP tokens are typically are only valid within a 30 second window and require time synchronization between the server and client. If time drift occurs on either server or client, the server will consider the token invalid because the token appeared to be generated outside the 30 second validity window.

To accommodate servers and clients where time drift has occurred, the below document proposes adding resynchronization ability to Teleport to allow Teleport to discover the time drift between a server and client, and include the drift when calculating the TOTP token during future authentication events.

[TOTP Resynchronization](https://docs.google.com/document/d/1ow7Acib1XoZ3duMwzAXPca8FrcUnwKG-FU8ldmt0Vtk/edit?usp=sharing)

**Comment by russjones** [comment] 2021-11-23 18:09
@knisbet You may be interested in this.

**Comment by zmb3** [comment] 2022-06-09 21:30
Closing as duplicate of #1727

**Closed by zmb3** 2022-06-09 21:30 UTC
Labels: ux, mfa
