### ISSUE TITLE
Trusted cluster : remote error: tls: bad certificate

### ISSUE THREAD

**Issue by samouds** [gravitational/teleport#1941] opened 2018-05-06 20:05 UTC
**What happened**:
When I start my teleport instance with a trsuted cluster I get this error when I go to the truster cluster page (by the way I don't see the node instance in my list) : 
```
[NODE]    Service is starting on 0.0.0.0:3022.
[PROXY]   Reverse tunnel service is starting on 0.0.0.0:3024.
[PROXY]   Web proxy service is starting on 0.0.0.0:3080.
[PROXY]   SSH proxy service is starting on 0.0.0.0:3023.
2018/05/06 20:06:16 http: TLS handshake error from 192.168.1.10:55406: remote error: tls: bad certificate
2018/05/06 20:06:20 http: TLS handshake error from 192.168.1.10:55410: remote error: tls: bad certificate
2018/05/06 20:06:22 http: TLS handshake error from 192.168.1.10:55412: remote error: tls: bad certificate
```

**What you expected to happen**:
That my instance connect to my main remote teleport instance.

**How to reproduce it (as minimally and precisely as possible)**:
teleport config : 
```
teleport:
  nodename: "nodename"
auth_service:
  enabled: yes
  session_recording: "off"
ssh_service:
  enabled: yes
proxy_service:
  enabled: yes
```

trusted cluster config
```
kind: trusted_cluster
version: v2
metadata:
  name: tpt.example.com
spec:
  enabled: true
  token: "tokeeeeeen"
  tunnel_addr: tpt.example.com:3024
  web_proxy_addr: tpt.example.com
```

**Environment**:
- Teleport version (use `teleport version`): 2.5.6
- OS (e.g. from /etc/os-release): Raspbian stretch

**Comment by samouds** [comment] 2018-05-07 08:42
@klizhentas my main auth runs with --insecure and the main proxy with --insecure --insecure-no-tls. And the proxy is behind a reverse proxy (traefik) that generates the certificate for tpt.example.com (web proxy only) and not other ports (3024).

On the other hand, my raspberry trusted cluster (auth, proxy, node and cluster) runs with the configuration below.

One thing I noticed, if I restart the main proxy and retry, the trusted cluster connects to the main server successfully. but most of times I get the error : **tls: bad certificate** and get this one in my main proxy : **ERRO             access denied to perform action 'read' on session web/stream.go:98**

**Comment by iGeekuPlay** [comment] 2018-08-14 01:14
@klizhentas I am also getting this issue with the --insecure-no-tls flag. I can provide any details needed.

**Comment by kontsevoy** [comment] 2018-10-10 17:14
@klizhentas can this be related to #1816 ?

**Comment by kontsevoy** [comment] 2018-10-10 17:16
Seems to be a common issue, adding to 3.1
@klizhentas lets discus.

**Comment by sebakerckhof** [comment] 2018-11-06 14:34
I'm also seeing this. Could it be related to clusters that had been joined before but have changed their certificates?

**Comment by klizhentas** [comment] 2018-11-06 16:36
from main cluster's perspective, some unknown cluster connects to it and presents non-trusted certificate. The right way is to remove the cluster from the main cluster side using `tctl rm rc <cluster-name>` and then rejoin the new cluster using security join token.

**Comment by kontsevoy** [comment] 2018-11-15 22:01
@klizhentas so this one appears to work as expected. shall we close this?

**Comment by klizhentas** [comment] 2019-04-24 16:19
UX could be improved, closing as a dupe of #2179

**Closed** 2019-04-24 16:19 UTC
