### ISSUE TITLE
Feature Request: labels/aliases for clusters

### ISSUE THREAD

**Issue by knisbet** [gravitational/teleport#2317] opened 2018-10-26 18:35 UTC
Problem Statement:
In discussions with a customer, they would like a feature similar to node labels, but at a cluster level. Their use case, is they are running multiple kubernetes clusters, in an active/standby setup, and they would like to expose logging into the kubernetes clusters to internal users, without the internal users needing to know which cluster is active.

Something along the lines of:
cluster1 = active
cluster2 = standby

And then being able to login to cluster active, regardless of whether cluster1 or cluster2 are currently the active cluster.

**Comment by benarent** [comment] 2020-04-20 18:45
Duplicate of https://github.com/gravitational/teleport/issues/3604

**Closed by benarent** 2020-04-20 18:45 UTC
Labels: cluster, ux
