### ISSUE TITLE
Accept error: accept tcp / Too many open files

### ISSUE THREAD

**Issue by vad** [gravitational/teleport#1551] opened 2018-01-05 09:24 UTC
We're running Teleport v2.3.5 on Ubuntu 14.04 LTS.
Yesterday Teleport wasn't accepting connections anymore. We found this in the logs:

```
2018/01/04 14:43:30 http: Accept error: accept tcp [::]:3080: accept4: too many open files; retrying in 1s
2018/01/04 14:43:31 http: Accept error: accept tcp [::]:3080: accept4: too many open files; retrying in 1s
2018/01/04 14:43:32 http: Accept error: accept tcp [::]:3080: accept4: too many open files; retrying in 1s
2018/01/04 14:43:33 http: Accept error: accept tcp [::]:3080: accept4: too many open files; retrying in 1s
```
A restart of teleport daemon solved the issue.

Is there a leak? Please tell me if I can help you with some other information or monitoring of the teleport process.

**Comment by klizhentas** [comment] 2018-01-05 21:28
I think this is a dupe of #1433 . Please try 2.4.0 that comes out next week and let me know if that fixed the issue.

**Comment by kontsevoy** [comment] 2018-01-11 21:23
@vad can you please confirm that 2.4 fixes the issue?

**Comment by vad** [comment] 2018-01-11 21:45
@kontsevoy I'll try ASAP, thank you

**Comment by kontsevoy** [comment] 2018-02-05 21:25
@vad I am doing a regular issue maintenance and as far as we're aware, this has been fixed. Feel free to comment/reopen.

**Closed by kontsevoy** 2018-02-05 21:25 UTC
