### ISSUE TITLE
Allow session recordings inherit labels from resources like nodes/db

### ISSUE THREAD

**Issue by j-teleport** [gravitational/teleport#16576] opened 2022-09-20 22:05 UTC
**What would you like Teleport to do?**
Now session recordings only can be filtered by session.participants,
Please allow session recordings inherit labels from resources like nodes/db, and the filter can be more flexible.

**What problem does this solve?**
Hard to find session recordings what resource it was from.

**If a workaround exists, please include it.**
NA

**Comment by zmb3** [comment] 2022-09-21 16:15
Duplicate of #13482?

**Comment by jingsun-teleport** [comment] 2022-09-22 08:15
> Duplicate of #13482?

Looks like yes, please close it if need. Thanks,

**Closed** 2022-12-21 19:29 UTC
Labels: feature-request, audit-log, c-fwh, c-g2
