### ISSUE TITLE
Manage role creation with a user interface that converts output to yaml

### ISSUE THREAD

**Issue by yjperez** [gravitational/teleport#25203] opened 2023-04-26 15:53 UTC
What would you like Teleport to do?
Similar to how AWS has a UI that allows one to click on which roles and resources to add and it gets converted to IAM JSON file, Teleport should do the same for roles. Users should be able to click on resources or labels and it would auto-populate the Teleport role yaml. This could also be a form type experience where they can just select options from a dropdown

What problem does this solve?
For some folks it would make it easier to just click on the labels/resources they want rather than have to write out a YAML file. Many customers we come across have not worked with YAML files and may find it challenging. Additionally, this could make it easier for non-technical auditors to evaluate what access a role grants.

If a workaround exists, please include it.
Write out the role in YAML.

**Comment by zmb3** [comment] 2024-09-30 22:47
Closing as a duplicate of #46612

**Closed by zmb3** 2024-09-30 22:47 UTC
Labels: feature-request, ux, rbac, IICD
