### ISSUE TITLE
Readyz endpoint not returning accurate state.

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#3700] opened 2020-05-12 01:08 UTC
From https://github.com/gravitational/teleport/issues/3686.

Disconnect the node from the auth server or proxy (shut down the auth server and proxy). Folks are reporting that /readyz endpoint is not going to degraded state. In addition to that they would want to have Prometheus gauge that mirrors readyz status.

**Comment by awly** [comment] 2020-05-12 22:34
For my simple local setup, `/readyz` does go into degraded state correctly when auth server disappears. However, it's tied to the rotation state sync for some reason, which is on a 10min poll cycle. The node notices missing auth server almost immediately, but takes >10min to get back to "ok" state, due to https://github.com/gravitational/teleport/blob/master/lib/service/state.go#L65-L69
Could we get more info from the user? Teleport version, network setup, configs, logs, etc.

Prometheus gauge definitely makes sense, will add.

**Comment by webvictim** [comment] 2020-05-13 12:29
I have seen a considerable amount of time taken to go from degraded back to healthy again after a node reconnects, too.

**Comment by benarent** [comment] 2020-05-14 19:39
I had another report today that if a node starts but has an invalid token it still reports  Ok on readyz endpoint.

**Comment by awly** [comment] 2020-05-19 23:47
Summary:
- incorrect `/readyz` state at startup (when initial join fails) is fixed
- prometheus metric to mirror `/readyz` is added
- can't reproduce the original issue of nodes not going into degraded state when auth server and proxy are down
- filed https://github.com/gravitational/teleport/issues/3743 to improve `/readyz` recovery speed

Closing this issue, unless there's more info or a repro case.

**Closed by awly** 2020-05-19 23:47 UTC
