### ISSUE TITLE
Configurable `ttl` for access requests left unattended

### ISSUE THREAD

**Issue by oshati** [gravitational/teleport#17277] opened 2022-10-11 15:48 UTC
What would you like Teleport to do?
There appears to be a `ttl` hard limit  of `1h`  for  access requests left unattended by the approver. Customer has requested that `ttl` for such requests is made configurable. 

What problem does this solve?
This allows an approver that is super busy and isn't able to get to the request before it expires be able to review and approve the request. 

If a workaround exists, please include it.
There is not really a good workaround

**Comment by zmb3** [comment] 2022-10-11 16:17
Duplicate of https://github.com/gravitational/teleport/issues/10147 ?

**Comment by russjones** [comment] 2022-10-12 00:33
This one has a better description, let's keep this one.

**Closed** 2022-12-14 23:18 UTC
Labels: feature-request, access-requests, c-ny, c-cro, c-pc
