### ISSUE TITLE
`TestHSMRotation` flakiness

### ISSUE THREAD

**Issue by ibeckermayer** [gravitational/teleport#13845] opened 2022-06-24 16:57 UTC
#### Link(s) to logs

- https://console.cloud.google.com/cloud-build/builds/2e331f94-0ac7-45dd-b102-13d8e0d25794?project=ci-account

#### Relevant snippet

```
    hsm_test.go:379: 
        	Error Trace:	hsm_test.go:379
        	Error:      	Received unexpected error:
        	            	timed out waiting for proxy to be ready
        	            		context deadline exceeded
        	Test:       	TestHSMRotation
```

**Comment by zmb3** [comment] 2022-06-25 03:07
Closing as duplicate of #13599

**Closed by zmb3** 2022-06-25 03:07 UTC
Labels: flaky tests
