### ISSUE TITLE
Ubuntu Kinetic (22.10) does not have a release

### ISSUE THREAD

**Issue by srelf-eschercloud** [gravitational/teleport#18679] opened 2022-11-22 14:30 UTC
Expected behavior:
When following https://goteleport.com/docs/server-access/guides/bpf-session-recording/#install-teleport-on-your-node you should be able to install teleport on your ubuntu kinetic node.

Current behavior:

When following https://goteleport.com/docs/server-access/guides/bpf-session-recording/#install-teleport-on-your-node you are met with the following error message when running apt-update on your node if your running ubuntu kinetic.
To be fair kinetic is not listed as supported (https://github.com/gravitational/teleport/blob/master/build.assets/tooling/cmd/build-os-package-repos/runners.go#L42-L67)

Bug details:
- Teleport version: V/11
- Recreation steps: follow the install steps above when running ubuntu kinetic.
- Debug logs

**Comment by GuyKh** [comment] 2023-02-10 10:45
As mentioned -- this is a workaround (using `jammy` instead of `kinetic`) - as @webvictim described:
```
sudo sed -i 's/kinetic/jammy/g' /etc/apt/sources.list.d/teleport.list && apt -y update
```

**Comment by pimvanderheijden-cpi** [comment] 2023-02-10 13:27
``` ... && sudo apt install teleport```  ?

**Comment by webvictim** [comment] 2023-02-10 16:24
Yes, installing Teleport at the end is important too 😁

**Comment by alexeytashmatov** [comment] 2023-04-25 09:34
I have the same problem with Pop OS 22.04 LTS. Error:
```
Err:8 https://apt.releases.teleport.dev/pop jammy Release
  404  Not Found [IP: 13.33.243.20 443]
Get:9 http://apt.pop-os.org/ubuntu jammy-security InRelease [110 kB]
Get:10 http://apt.pop-os.org/ubuntu jammy-updates InRelease [119 kB]
Get:11 http://apt.pop-os.org/ubuntu jammy-backports InRelease [108 kB]
Get:12 http://apt.pop-os.org/ubuntu jammy-security/main amd64 DEP-11 Metadata [41.5 kB]
Get:13 http://apt.pop-os.org/ubuntu jammy-security/universe amd64 DEP-11 Metadata [18.5 kB]
Get:14 http://apt.pop-os.org/ubuntu jammy-updates/main amd64 DEP-11 Metadata [101 kB]
Get:15 http://apt.pop-os.org/ubuntu jammy-updates/universe amd64 DEP-11 Metadata [269 kB]
Get:16 http://apt.pop-os.org/ubuntu jammy-updates/multiverse amd64 DEP-11 Metadata [940 B]
Get:17 http://apt.pop-os.org/ubuntu jammy-backports/main amd64 DEP-11 Metadata [8,000 B]
Get:18 http://apt.pop-os.org/ubuntu jammy-backports/universe amd64 DEP-11 Metadata [12.9 kB]
Reading package lists... Done                  
E: The repository 'https://apt.releases.teleport.dev/pop jammy Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by walshg3** [comment] 2023-08-17 05:54
For those coming from Ubuntu Lunar and this is your first time interacting with Teleport make sure you don't have version 14 of the "Get Started With Teleport" Guide and instead select 13.x 
Basically you need to make sure the install.sh is getting 13.2.2 because there is no stable 14 version available for jammy if i'm understanding correctly?

`curl https://goteleport.com/static/install.sh | bash -s 13.3.2`

Also change the sed command above to:

`sudo sed -i 's/lunar/jammy/g' /etc/apt/sources.list.d/teleport.list && apt -y update && sudo apt install teleport`

I was able to install teleport on Ubuntu Lunar after those changes. It would be helpful if in the install.sh you checked the version of ubuntu / linux and if you have a compatible version of the installer as a release as a QOL change. This is also getting close to a year old is there a roadmap to offer support for Lunar? 

Thanks for working on such a great project. Seriously its a game changer.

**Comment by ThomasRieutord** [comment] 2023-09-16 11:20
I had a similar issue with Linux Mint 21.2 "Victoria". With the recommended installation (namely `curl https://goteleport.com/static/install.sh | bash -s 13.3.8`), here is the message I get:
```
Hit :1 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit :2 http://archive.ubuntu.com/ubuntu jammy-updates InRelease                                
Ign :3 https://ftp.heanet.ie/pub/packages.linuxmint.com victoria InRelease                         
Hit :4 https://ftp.heanet.ie/pub/packages.linuxmint.com victoria Release                       
Hit :5 http://archive.ubuntu.com/ubuntu jammy-backports InRelease                              
Hit :6 http://security.ubuntu.com/ubuntu jammy-security InRelease                              
Ign :7 https://apt.releases.teleport.dev/ubuntu debian InRelease      
Err :9 https://apt.releases.teleport.dev/ubuntu debian Release
  404  Not Found [IP : 18.165.201.70 443]
Reading package lists... Done
E: The repository 'https://apt.releases.teleport.dev/ubuntu debian Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```
The workaround that was successful for me was to download the `.deb` and install it with dpkg:
```
curl https://cdn.teleport.dev/teleport_13.3.8_amd64.deb --output teleport_13.3.8_amd64.deb
sudo dpkg -i teleport_13.3.8_amd64.deb
```

**Comment by webvictim** [comment] 2023-09-18 13:29
This should be possible to fix by changing the use of `VERSION_CODENAME` in the APT install docs to `UBUNTU_CODENAME` instead, i.e.

```
echo "deb [signed-by=/usr/share/keyrings/teleport-archive-keyring.asc] \
https://apt.releases.teleport.dev/${ID?} ${UBUNTU_CODENAME?} stable/v13" \
| sudo tee /etc/apt/sources.list.d/teleport.list > /dev/null
```

**Comment by haseebahmed-deutics** [comment] 2023-12-07 10:55
more than one suite specified for show_static (focal focal-updates focal-backports jammy jammy-updates jammy-backports lunar lunar-updates lunar-backports mantic mantic-updates mantic-backports noble) this is the error on ubuntu packages link. I'm new to ubuntu just ran sudo ap-get update now I'm receiving to download latest packages 
Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by fsoyer** [comment] 2024-02-28 12:03
Hi there,
I try to install teleport on Min 21.1, I have the same problem. The workaround give by webvictim doesn't work : it's already UBUNTU_CODENAME in the apt file.

```
$ cat /etc/os-release
NAME="Linux Mint"
VERSION="21.1 (Vera)"
ID=linuxmint
ID_LIKE="ubuntu debian"
PRETTY_NAME="Linux Mint 21.1"
VERSION_ID="21.1"
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.linuxmint.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
VERSION_CODENAME=vera
UBUNTU_CODENAME=jammy
```
I find this error in install.sh :
```
$ curl https://goteleport.com/static/install.sh | bash -s 15.0.2
[...]
Installing Teleport v15.0.2 via apt-get
main: line 63: [: 21.1: integer expression expected
[...]
```
Temporary modifying 21.1 in 21 doesn't help :(

Here is the apt file :
```
$ cat /etc/apt/sources.list.d/teleport.list 
deb [signed-by=/usr/share/keyrings/teleport-archive-keyring.asc]  https://apt.releases.teleport.dev/ubuntu debian jammy stable/v15
```

So, I can install Teleport manually by downloading the .deb file, but if anyone has an idea to solve this issue with install.sh ?

**Comment by webvictim** [comment] 2024-02-28 14:07
Although annoying, that's not the actual error that's causing the problem.

The issue is this:
```
+ echo 'deb [signed-by=/usr/share/keyrings/teleport-archive-keyring.asc]  https://apt.releases.teleport.dev/ubuntu debian jammy stable/v15'
+ tee /etc/apt/sources.list.d/teleport.list
+ set +x
+ apt-get update
Ign:1 http://packages.linuxmint.com victoria InRelease
Hit:2 http://packages.linuxmint.com victoria Release
Ign:3 https://apt.releases.teleport.dev/ubuntu debian InRelease
Err:4 https://apt.releases.teleport.dev/ubuntu debian Release
  404  Not Found [IP: 3.162.3.29 443]
Hit:6 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:7 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:8 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:9 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Reading package lists... Done
E: The repository 'https://apt.releases.teleport.dev/ubuntu debian Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

When using Linux Mint, it seems that the APT_REPO_ID is being set to `ubuntu debian` and not `ubuntu` as it should be.

Running this will fix the `teleport.list` file:
```
sed -i 's/debian jammy/jammy/g' /etc/apt/sources.list.d/teleport.list
```

After that `apt-get -y update && apt-get -y install teleport` will install Teleport.

I'll see whether I can get the install script fixed.

**Comment by fsoyer** [comment] 2024-02-28 15:32
Ah, I see. Just tried it, it works. Thank you for the tip.

**Comment by zmb3** [comment] 2024-06-18 18:10
@marcoandredinis is this still an issue?

**Comment by marcoandredinis** [comment] 2024-06-18 20:59
Closing because it reached EOL
https://endoflife.date/ubuntu
https://discourse.ubuntu.com/t/kinetic-kudu-release-notes/27976#support-lifespan-3

(I'm pretty sure we added a release track for this version, but it doesn't really matter anymore).

**Closed by marcoandredinis** 2024-06-18 20:59 UTC
Labels: bug, release-engineering, c-nt
