### ISSUE TITLE
Web terminal sessions kick users out

### ISSUE THREAD

**Issue by kontsevoy** [gravitational/teleport#2463] opened 2018-12-27 23:07 UTC
## Problem

This has been reported by Samsung. Users, while using a web-based terminal, will get an error saying "server disconnected". 

## How to Reproduce

I was able to reproduce it using my [personal cluster](https://kontsevoy.com:3080) configured with Github authentication.

## To reproduce

* Login with Github SSO
* Open a web terminal
* Keep typnig `date` in it (the output is below)
* After about an hour I got kicked out (at 14:17:58) - see below
* NOTE: doing the same in CLI i.e. via `tsh` does not result in this behavior, i.e. a user does not get kicked out.

## Terminal output

```
bbox ~: ls
go  tmp
bbox ~: htop
bbox ~: uname -a
Linux bbox 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64 GNU/Linux
bbox ~: date
Thu Dec 27 13:18:43 PST 2018
bbox ~: date
Thu Dec 27 13:24:37 PST 2018
bbox ~: date
Thu Dec 27 14:13:58 PST 2018
bbox ~:
(disconnected)
```

## Proxy Servers Log

Dump of the relevant date range of `journalctl -u teleport`:

```
Dec 27 14:17:58 dmz teleport[452]: INFO             [WEB] removed 2 expired sessions web/sessions.go:428
Dec 27 14:17:58 dmz teleport[452]: INFO             [WEB] closing context kontsevoy7fb207ffa02bc5dc3c49b242077b114a web/sessions.go:397
Dec 27 14:17:58 dmz teleport[452]: INFO             [WEB] closing context kontsevoy67374db751f484d1e02a5592f251e59e web/sessions.go:397
Dec 27 14:17:58 dmz teleport[452]: DEBU             Closing &{0xc420888240 {53137e82-30ed-4fe5-836b-b03473b6cfab ekontsevoy {128 46} f18af1e4-0a1c-11e9-9828-525400431001 
Dec 27 14:17:58 dmz teleport[452]: DEBU [WEBSOCKET] Closing websocket stream for f18af1e4-0a1c-11e9-9828-525400431001. web/terminal.go:236
Dec 27 14:17:58 dmz teleport[452]: ERRO [WEBSOCKET] Unable to send close event to web client. web/terminal.go:317
Dec 27 14:17:58 dmz teleport[452]: DEBU [SSH:PROXY] closed connection 127.0.0.1:56490 sshutils/server.go:390
Dec 27 14:17:58 dmz teleport[452]: DEBU [NODE]      Subsystem proxySubsys(cluster=default/dmz, host=bbox, port=0) finished with result: <nil>. regular/sshserver.go:1088
Dec 27 14:17:58 dmz teleport[452]: DEBU [PROXY]     Client 127.0.0.1:56490 disconnected. id:7 local:127.0.0.1:3023 login:ekontsevoy remote:127.0.0.1:56490 teleportUser:ko
Dec 27 14:17:59 dmz teleport[452]: WARN             invalid session: session is invalid or has expired request:POST /webapi/sessions/renew web/apiserver.go:1904
Dec 27 14:17:59 dmz teleport[452]: DEBU             [web] GET zip:/app/assets/img/img-54ca7c.png web/static.go:196
Dec 27 14:17:59 dmz teleport[452]: DEBU             [web] zip::Close(img-54ca7c.png) web/static.go:189
```

## Auth Server Log

Dump of the relevant date range of `journalctl -u teleport`:

```
Dec 27 14:17:58 bbox teleport[412]: DEBU             AgentServer(/tmp/teleport-161678402/teleport-412.socket) is closing teleagent/agent.go:104
Dec 27 14:17:58 bbox teleport[412]: INFO [SESSION:N] Closing party f1bde616-0a1c-11e9-9fa0-5254004320d1 srv/sess.go:1014
Dec 27 14:17:58 bbox teleport[412]: INFO [SESSION:N] Party member f1bde616-0a1c-11e9-9fa0-5254004320d1 left session f18af1e4-0a1c-11e9-9828-525400431001. srv/sess.go:863
Dec 27 14:17:58 bbox teleport[412]: DEBU [SSH:NODE]  closed connection 69.181.185.6:40034 sshutils/server.go:390
Dec 27 14:17:58 bbox teleport[412]: WARN [SESSION:N] Unable to send session.join to 69.181.185.6:40034: write tcp 10.5.100.2:3022->10.5.100.1:40124: write: connection res
Dec 27 14:17:58 bbox teleport[412]: INFO [NODE]      Removing party ServerContext(69.181.185.6:40034->10.5.100.2:3022, user=ekontsevoy, id=1) party(id=f1bde616-0a1c-11e9-
Dec 27 14:18:18 bbox teleport[412]: INFO [SESSION:N] Session f18af1e4-0a1c-11e9-9828-525400431001 will be garbage collected. srv/sess.go:247
Dec 27 14:18:18 bbox teleport[412]: INFO [SESSION:N] Closing session f18af1e4-0a1c-11e9-9828-525400431001 srv/sess.go:510
```

Total session length: **59:54** (suspiciously close to one hour)

## Questions

* The total session length is almost exactly an hour. Coincidence?
* The proxy log says "[WEB] removed 2 expired sessions". Why two? Also, why removed?

**Comment by alex-kovoy** [comment] 2018-12-28 21:31
> The total session length is almost exactly an hour. Coincidence?

 This is because we limit web session TTL for github connectors to 1h max. That needs to be fixed and this is specific to github connector issue.

> The proxy log says "[WEB] removed 2 expired sessions". Why two? Also, why removed?

This is from the session cache, might be related to websocket connection. Will check.

**Comment by wllenyj** [comment] 2019-01-09 03:46
This is not only be disconnected for idle. When I 'm inputing, also disconnected. 
Proxy log is the same, there are three logs is important:
DEBU             Closing  .....               web/sessions.go:343
DEBU [WEBSOCKET] Closing websocket stream for ...... web/terminal.go:236
.....
ERRO [WEBSOCKET] Unable to send close event to web client. web/terminal.go:317

**In normal:**
DEBU [WEBSOCKET] Sent close event to web client. web/terminal.go:320
......
DEBU [WEBSOCKET] Closing websocket stream for .... web/terminal.go:236

**Comment by klizhentas** [comment] 2019-04-24 16:18
this particular issue was caused by the time drift in the auth/proxy servers AFAIK and was resolved

**Closed by klizhentas** 2019-04-24 16:18 UTC
