### ISSUE TITLE
Support Desktop Access Protocol in Kube Agent

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#22402] opened 2023-02-28 15:44 UTC
What would you like Teleport to do?

Provide the ability to configure a Windows desktop service in the Teleport kube agent helm chart.

What problem does this solve?

Provides the ability for  Windows desktop service to connect from k8s, currently available for k8s, db and app services.

If a workaround exists, please include it.

Customize helm chart to have a Windows desktop service.

**Comment by zmb3** [comment] 2023-09-22 23:16
Closing as duplicate of #15956

**Closed by zmb3** 2023-09-22 23:16 UTC
Labels: feature-request, helm, desktop-access
