### ISSUE TITLE
`TestHandlerConnectionUpgrade` flakiness

### ISSUE THREAD

**Issue by GavinFrazar** [gravitational/teleport#16128] opened 2022-09-03 10:41 UTC
### Link(s) to logs

https://console.cloud.google.com/cloud-build/builds/cb6320f4-80fe-4042-946b-315d490ec74b?project=ci-account

### Relevant snippet

Lots of tests failed due to a race detected during parallel execution of tests:

```
WARNING: DATA RACE
Write at 0x00c00115b600 by goroutine 519:
  github.com/gravitational/teleport/lib/web.TestHandlerConnectionUpgrade.func3()
      /workspace/lib/web/conn_upgrade_test.go:101 +0x864
  testing.tRunner()
      /opt/go/src/testing/testing.go:1439 +0x213
  testing.(*T).Run.func1()
      /opt/go/src/testing/testing.go:1486 +0x47

Previous write at 0x00c00115b600 by goroutine 309:
  github.com/gravitational/teleport/lib/web.TestHandlerConnectionUpgrade.func3.1()
      /workspace/lib/web/conn_upgrade_test.go:90 +0x244

Goroutine 519 (running) created at:
  testing.(*T).Run()
      /opt/go/src/testing/testing.go:1486 +0x724
  github.com/gravitational/teleport/lib/web.TestHandlerConnectionUpgrade()
      /workspace/lib/web/conn_upgrade_test.go:78 +0x377
  testing.tRunner()
      /opt/go/src/testing/testing.go:1439 +0x213
  testing.(*T).Run.func1()
      /opt/go/src/testing/testing.go:1486 +0x47

Goroutine 309 (finished) created at:
  github.com/gravitational/teleport/lib/web.TestHandlerConnectionUpgrade.func3()
      /workspace/lib/web/conn_upgrade_test.go:87 +0x585
  testing.tRunner()
      /opt/go/src/testing/testing.go:1439 +0x213
  testing.(*T).Run.func1()
      /opt/go/src/testing/testing.go:1486 +0x47
```

Edit: I reproduced locally on master branch, checked out at this commit: e6d86299a855687b21970504fbf06f52a8f80c74

Just run `go test -v -count=1 -race -run "TestHandlerConnectionUpgrade" ./lib/web`

**Comment by greedy52** [comment] 2022-09-03 15:44
Duplicate of #16064

**Comment by greedy52** [comment] 2022-09-03 15:45
Hmm. not the same one. will fix

**Closed** 2022-09-05 14:56 UTC
Labels: flaky tests
