### ISSUE TITLE
`Public IP not in the set of valid principals for given certificate` when using openssh client

### ISSUE THREAD

**Issue by vincentonderwaater** [gravitational/teleport#14743] opened 2022-07-21 10:33 UTC
Expected behavior:
``` 
ssh config
...
ssh root@<REDACTED>
<an ssh session>
```

Current behavior:
```
ERROR: ssh: handshake failed: ssh: principal "<REDACTED: proxy public ip>" not in the set of valid principals for given certificate: ["4945a81a-8afb-4b41-b573-df2153f38ed4.azure_root" "4945a81a-8afb-4b41-b573-df2153f38ed4" "REDACTED.azure_root" "REDACTED" "localhost" "127.0.0.1" "::1" "teleport.REDACTED.net" "REDACTED" "remote.kube.proxy.teleport.cluster.local"]
```

Bug details:
```
Teleport v10.0.2 git:v10.0.2-0-g47e0914 go1.18.3
Proxy version: 10.0.2
```
Reproduce:
- Nuke teleport ssh config and regenerate with `tsh config > config.teleport`
- Nuke ~/.tsh/known_hosts
- `tsh login`

**Comment by zmb3** [comment] 2022-07-21 16:03
Looks like a duplicate of https://github.com/gravitational/teleport/issues/2770 and https://github.com/gravitational/teleport/issues/13012.

Did you set the proxy's `public_addr` in your configuration?

**Comment by vincentonderwaater** [comment] 2022-07-21 16:35
> Looks like a duplicate of #2770 and #13012.
> 
> Did you set the proxy's `public_addr` in your configuration?

We did!

**Comment by somethingnew2-0** [comment] 2022-07-21 20:13
We’re seeing this same issue with client version 10.02 and proxy version 9.3.6 with TLS multiplexing enabled. However, we cannot reproduce it with a 10.01 or 9.3.6 client.

**Closed** 2022-07-28 17:59 UTC
Labels: bug, regression, c-di, server-access
