### ISSUE TITLE
Include Audit Log with JIT Access Request

### ISSUE THREAD

**Issue by djohns7** [gravitational/teleport#33021] opened 2023-10-05 15:35 UTC
What would you like Teleport to do?
Compile or link to the audit log associated with a JIT access requests, so JIT requests can include a review of all actions taken.

What problem does this solve?
Customer requires reviews of access requests to ensure what was stated is what was accomplished. Using audit log filters, we could include a link or report of the actions taken during an access request.

If a workaround exists, please include it.
Customer can manually retrieve the request ID and then using a SEIM query the audit logs for associated actions.

**Comment by zmb3** [comment] 2023-10-05 17:54
Duplicate of #29533

**Closed by zmb3** 2023-10-05 17:54 UTC
Labels: feature-request, audit-log, access-requests, c-nt
