### ISSUE TITLE
docker image out of date repos?

### ISSUE THREAD

**Issue by bhartm3** [gravitational/teleport#2274] opened 2018-10-08 16:22 UTC
**What happened**:
Hello my build was failing because some of the repo dependencies were out of date and I added 
```RUN apt-get update```
in [https://github.com/gravitational/teleport/blob/master/docker/Dockerfile](https://github.com/gravitational/teleport/blob/master/docker/Dockerfile)

Although there might be another way?

**What you expected to happen**:
successful build

**How to reproduce it (as minimally and precisely as possible)**:
Follow instructions in [https://github.com/gravitational/teleport/blob/master/docker/README.md](https://github.com/gravitational/teleport/blob/master/docker/README.md)

**Comment by klizhentas** [comment] 2018-10-08 17:18
can you please post the error that you got and the command that you tried to run, it is not clear what the problem is otherwise.

**Comment by bhartm3** [comment] 2018-10-08 17:52
sorry, I did the ```make -C build.assets``` and then ```make build``` from the ```teleport/docker``` directory and get:
```
Step 4/10 : RUN apt-get install -y ansible ssh inetutils-syslogd
 ---> Running in e68b717d2080
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  bzip2 cgmanager dbus dmsetup file ieee-data libapparmor1 libcap2
  libcgmanager0 libcryptsetup4 libdbus-1-3 libdevmapper1.02.1 libglib2.0-0
  libglib2.0-data libicu57 libip4tc0 libkmod2 libmagic-mgc libmagic1
  libnih-dbus1 libnih1 libpam-systemd libprocps6 libpython-stdlib
  libpython2.7-minimal libpython2.7-stdlib libreadline7 libseccomp2 libwrap0
  libxml2 libyaml-0-2 mime-support ncurses-term openssh-server
  openssh-sftp-server procps psmisc python python-cffi-backend python-crypto
  python-cryptography python-enum34 python-httplib2 python-idna
  python-ipaddress python-jinja2 python-kerberos python-markupsafe
  python-minimal python-netaddr python-paramiko python-pkg-resources
  python-pyasn1 python-selinux python-setuptools python-six python-xmltodict
  python-yaml python2.7 python2.7-minimal readline-common sgml-base
  shared-mime-info systemd systemd-shim tcpd ucf xdg-user-dirs xml-core
  xz-utils
Suggested packages:
  cowsay sshpass bzip2-doc default-dbus-session-bus | dbus-session-bus
  molly-guard monkeysphere rssh ssh-askpass ufw python-doc python-tk
  python-crypto-dbg python-crypto-doc python-cryptography-doc
  python-cryptography-vectors python-enum34-doc python-jinja2-doc ipython
  python-netaddr-docs python-gssapi doc-base python-setuptools-doc
  python2.7-doc binfmt-support readline-doc sgml-base-doc systemd-ui
  systemd-container policykit-1 pm-utils debhelper
Recommended packages:
  python-winrm
The following NEW packages will be installed:
  ansible bzip2 cgmanager dbus dmsetup file ieee-data inetutils-syslogd
  libapparmor1 libcap2 libcgmanager0 libcryptsetup4 libdbus-1-3
  libdevmapper1.02.1 libglib2.0-0 libglib2.0-data libicu57 libip4tc0 libkmod2
  libmagic-mgc libmagic1 libnih-dbus1 libnih1 libpam-systemd libprocps6
  libpython-stdlib libpython2.7-minimal libpython2.7-stdlib libreadline7
  libseccomp2 libwrap0 libxml2 libyaml-0-2 mime-support ncurses-term
  openssh-server openssh-sftp-server procps psmisc python python-cffi-backend
  python-crypto python-cryptography python-enum34 python-httplib2 python-idna
  python-ipaddress python-jinja2 python-kerberos python-markupsafe
  python-minimal python-netaddr python-paramiko python-pkg-resources
  python-pyasn1 python-selinux python-setuptools python-six python-xmltodict
  python-yaml python2.7 python2.7-minimal readline-common sgml-base
  shared-mime-info ssh systemd systemd-shim tcpd ucf xdg-user-dirs xml-core
  xz-utils
0 upgraded, 73 newly installed, 0 to remove and 0 not upgraded.
Need to get 30.3 MB of archives.
After this operation, 126 MB of additional disk space will be used.
Get:1 http://deb.debian.org/debian stretch/main amd64 libapparmor1 amd64 2.11.0-3+deb9u2 [78.9 kB]
Get:2 http://security.debian.org stretch/updates/main amd64 libicu57 amd64 57.1-6+deb9u2 [7,700 kB]
Get:3 http://deb.debian.org/debian stretch/main amd64 libcap2 amd64 1:2.25-1 [16.8 kB]
Get:4 http://deb.debian.org/debian stretch/main amd64 dmsetup amd64 2:1.02.137-2 [107 kB]
Get:5 http://deb.debian.org/debian stretch/main amd64 libdevmapper1.02.1 amd64 2:1.02.137-2 [170 kB]
Get:6 http://deb.debian.org/debian stretch/main amd64 libcryptsetup4 amd64 2:1.7.3-4 [109 kB]
Get:7 http://deb.debian.org/debian stretch/main amd64 libip4tc0 amd64 1.6.0+snapshot20161117-6 [67.8 kB]
Get:8 http://deb.debian.org/debian stretch/main amd64 libkmod2 amd64 23-2 [48.1 kB]
Get:9 http://deb.debian.org/debian stretch/main amd64 libseccomp2 amd64 2.3.1-2.1 [39.5 kB]
Err:10 http://deb.debian.org/debian stretch/main amd64 libprocps6 amd64 2:3.3.12-3
  404  Not Found
Err:11 http://deb.debian.org/debian stretch/main amd64 procps amd64 2:3.3.12-3
  404  Not Found
Err:12 http://deb.debian.org/debian stretch-updates/main amd64 systemd amd64 232-25+deb9u3
  404  Not Found
Get:13 http://deb.debian.org/debian stretch/main amd64 libpython2.7-minimal amd64 2.7.13-2+deb9u2 [389 kB]
Get:14 http://deb.debian.org/debian stretch/main amd64 python2.7-minimal amd64 2.7.13-2+deb9u2 [1,382 kB]
Get:15 http://deb.debian.org/debian stretch/main amd64 python-minimal amd64 2.7.13-2 [40.5 kB]
Get:16 http://deb.debian.org/debian stretch/main amd64 mime-support all 3.60 [36.7 kB]
Get:17 http://deb.debian.org/debian stretch/main amd64 readline-common all 7.0-3 [70.4 kB]
Get:18 http://deb.debian.org/debian stretch/main amd64 libreadline7 amd64 7.0-3 [151 kB]
Get:19 http://deb.debian.org/debian stretch/main amd64 libpython2.7-stdlib amd64 2.7.13-2+deb9u2 [1,896 kB]
Get:20 http://deb.debian.org/debian stretch/main amd64 python2.7 amd64 2.7.13-2+deb9u2 [285 kB]
Get:21 http://deb.debian.org/debian stretch/main amd64 libpython-stdlib amd64 2.7.13-2 [20.0 kB]
Get:22 http://deb.debian.org/debian stretch/main amd64 python amd64 2.7.13-2 [154 kB]
Get:23 http://deb.debian.org/debian stretch/main amd64 sgml-base all 1.29 [14.8 kB]
Get:24 http://deb.debian.org/debian stretch/main amd64 openssh-sftp-server amd64 1:7.4p1-10+deb9u3 [39.5 kB]
Get:25 http://deb.debian.org/debian stretch/main amd64 ucf all 3.0036 [70.2 kB]
Get:26 http://deb.debian.org/debian stretch/main amd64 libwrap0 amd64 7.6.q-26 [58.2 kB]
Get:27 http://deb.debian.org/debian stretch/main amd64 openssh-server amd64 1:7.4p1-10+deb9u3 [332 kB]
Get:28 http://deb.debian.org/debian stretch/main amd64 ssh all 1:7.4p1-10+deb9u3 [189 kB]
Get:29 http://deb.debian.org/debian stretch/main amd64 bzip2 amd64 1.0.6-8.1 [47.5 kB]
Get:30 http://deb.debian.org/debian stretch/main amd64 libdbus-1-3 amd64 1.10.26-0+deb9u1 [194 kB]
Get:31 http://deb.debian.org/debian stretch/main amd64 dbus amd64 1.10.26-0+deb9u1 [210 kB]
Err:32 http://deb.debian.org/debian stretch/main amd64 libmagic-mgc amd64 1:5.30-1+deb9u1
  404  Not Found
Get:32 http://security.debian.org stretch/updates/main amd64 libmagic-mgc amd64 1:5.30-1+deb9u1 [222 kB]
Err:33 http://deb.debian.org/debian stretch/main amd64 libmagic1 amd64 1:5.30-1+deb9u1
  404  Not Found
Get:33 http://security.debian.org stretch/updates/main amd64 libmagic1 amd64 1:5.30-1+deb9u1 [111 kB]
Err:34 http://deb.debian.org/debian stretch/main amd64 file amd64 1:5.30-1+deb9u1
  404  Not Found
Get:35 http://deb.debian.org/debian stretch/main amd64 libglib2.0-0 amd64 2.50.3-2 [2,691 kB]
Get:34 http://security.debian.org stretch/updates/main amd64 file amd64 1:5.30-1+deb9u1 [64.1 kB]
Get:36 http://deb.debian.org/debian stretch/main amd64 libnih1 amd64 1.0.3-8 [125 kB]
Get:37 http://deb.debian.org/debian stretch/main amd64 libnih-dbus1 amd64 1.0.3-8 [96.8 kB]
Get:38 http://deb.debian.org/debian stretch/main amd64 libcgmanager0 amd64 0.41-2 [41.1 kB]
Get:39 http://deb.debian.org/debian stretch/main amd64 cgmanager amd64 0.41-2 [84.0 kB]
Get:40 http://deb.debian.org/debian stretch/main amd64 systemd-shim amd64 10-3 [20.0 kB]
Err:41 http://deb.debian.org/debian stretch-updates/main amd64 libpam-systemd amd64 232-25+deb9u3
  404  Not Found
Get:42 http://deb.debian.org/debian stretch/main amd64 libxml2 amd64 2.9.4+dfsg1-2.2+deb9u2 [920 kB]
Get:43 http://deb.debian.org/debian stretch/main amd64 ncurses-term all 6.0+20161126-1+deb9u2 [469 kB]
Get:44 http://deb.debian.org/debian stretch/main amd64 xz-utils amd64 5.2.2-1.2+b1 [266 kB]
Get:45 http://deb.debian.org/debian stretch/main amd64 python-crypto amd64 2.6.1-7 [259 kB]
Get:46 http://deb.debian.org/debian stretch/main amd64 python-markupsafe amd64 0.23-3 [14.4 kB]
Get:47 http://deb.debian.org/debian stretch/main amd64 python-jinja2 all 2.8-1 [111 kB]
Get:48 http://deb.debian.org/debian stretch/main amd64 python-cffi-backend amd64 1.9.1-2 [69.0 kB]
Get:49 http://deb.debian.org/debian stretch/main amd64 python-enum34 all 1.1.6-1 [35.0 kB]
Get:50 http://deb.debian.org/debian stretch/main amd64 python-idna all 2.2-1 [32.6 kB]
Get:51 http://deb.debian.org/debian stretch/main amd64 python-ipaddress all 1.0.17-1 [18.1 kB]
Get:52 http://deb.debian.org/debian stretch/main amd64 python-pyasn1 all 0.1.9-2 [51.8 kB]
Get:53 http://deb.debian.org/debian stretch/main amd64 python-pkg-resources all 33.1.1-1 [166 kB]
Get:54 http://deb.debian.org/debian stretch/main amd64 python-setuptools all 33.1.1-1 [297 kB]
Get:55 http://deb.debian.org/debian stretch/main amd64 python-six all 1.10.0-3 [14.4 kB]
Get:56 http://deb.debian.org/debian stretch/main amd64 python-cryptography amd64 1.7.1-3 [211 kB]
Get:57 http://deb.debian.org/debian stretch/main amd64 python-paramiko all 2.0.0-1 [111 kB]
Get:58 http://deb.debian.org/debian stretch/main amd64 libyaml-0-2 amd64 0.1.7-2 [47.6 kB]
Get:59 http://deb.debian.org/debian stretch/main amd64 python-yaml amd64 3.12-1 [119 kB]
Get:60 http://deb.debian.org/debian stretch/main amd64 python-httplib2 all 0.9.2+dfsg-1 [39.7 kB]
Get:61 http://deb.debian.org/debian stretch/main amd64 ieee-data all 20160613.1 [952 kB]
Get:62 http://deb.debian.org/debian stretch/main amd64 python-netaddr all 0.7.18-2 [227 kB]
Get:63 http://deb.debian.org/debian stretch/main amd64 ansible all 2.2.1.0-2 [1,675 kB]
Get:64 http://deb.debian.org/debian stretch/main amd64 libglib2.0-data all 2.50.3-2 [2,517 kB]
Get:65 http://deb.debian.org/debian stretch/main amd64 psmisc amd64 22.21-2.1+b2 [123 kB]
Get:66 http://deb.debian.org/debian stretch/main amd64 python-kerberos amd64 1.1.5-2+b2 [22.5 kB]
Get:67 http://deb.debian.org/debian stretch/main amd64 python-selinux amd64 2.6-3+b3 [171 kB]
Get:68 http://deb.debian.org/debian stretch/main amd64 python-xmltodict all 0.10.2-1 [11.8 kB]
Err:69 http://deb.debian.org/debian stretch/main amd64 shared-mime-info amd64 1.8-1
  404  Not Found
Get:70 http://deb.debian.org/debian stretch/main amd64 tcpd amd64 7.6.q-26 [23.3 kB]
Get:71 http://deb.debian.org/debian stretch/main amd64 xdg-user-dirs amd64 0.15-2+b1 [52.2 kB]
Get:72 http://deb.debian.org/debian stretch/main amd64 xml-core all 0.17 [23.2 kB]
Get:73 http://deb.debian.org/debian stretch/main amd64 inetutils-syslogd amd64 2:1.9.4-2+b1 [222 kB]
Fetched 26.6 MB in 0s (28.3 MB/s)
E: Failed to fetch http://deb.debian.org/debian/pool/main/p/procps/libprocps6_3.3.12-3_amd64.deb  404  Not Found
E: Failed to fetch http://deb.debian.org/debian/pool/main/p/procps/procps_3.3.12-3_amd64.deb  404  Not Found
E: Failed to fetch http://deb.debian.org/debian/pool/main/s/systemd/systemd_232-25+deb9u3_amd64.deb  404  Not Found
E: Failed to fetch http://deb.debian.org/debian/pool/main/s/systemd/libpam-systemd_232-25+deb9u3_amd64.deb  404  Not Found
E: Failed to fetch http://deb.debian.org/debian/pool/main/s/shared-mime-info/shared-mime-info_1.8-1_amd64.deb  404  Not Found
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
The command '/bin/sh -c apt-get install -y ansible ssh inetutils-syslogd' returned a non-zero code: 100
Makefile:85: recipe for target 'build' failed
make: *** [build] Error 100
```

**Comment by bhartm3** [comment] 2018-10-08 18:18
https://github.com/gravitational/teleport/pull/2275

**Comment by kontsevoy** [comment] 2018-12-27 01:44
Note to G: we need to update the buildbox image on `quay.io` to work out of the box.

**Comment by kontsevoy** [comment] 2018-12-27 17:42
@bhartm3 we've merged your patch. Thanks for fixing this.

**Closed by kontsevoy** 2018-12-27 17:42 UTC
